// Appetizer Recipes for WhatAboutDinner App
// 20 detailed appetizer recipes with all required fields

const appetizerRecipes = [
  {
    title: "Spinach and Artichoke Stuffed Mushrooms",
    description: "Tender mushroom caps filled with a creamy spinach and artichoke mixture, topped with melted cheese for an elegant and flavorful bite-sized appetizer.",
    ingredients: [
      { name: "cremini mushrooms", quantity: "24", unit: "large", notes: "stems removed and chopped" },
      { name: "olive oil", quantity: "2", unit: "tablespoons", notes: "divided" },
      { name: "garlic", quantity: "3", unit: "cloves", notes: "minced" },
      { name: "shallot", quantity: "1", unit: "medium", notes: "finely diced" },
      { name: "frozen spinach", quantity: "10", unit: "ounces", notes: "thawed and squeezed dry" },
      { name: "artichoke hearts", quantity: "1", unit: "14-ounce can", notes: "drained and chopped" },
      { name: "cream cheese", quantity: "4", unit: "ounces", notes: "softened" },
      { name: "sour cream", quantity: "1/4", unit: "cup" },
      { name: "parmesan cheese", quantity: "1/2", unit: "cup", notes: "grated, divided" },
      { name: "mozzarella cheese", quantity: "1/2", unit: "cup", notes: "shredded" },
      { name: "red pepper flakes", quantity: "1/4", unit: "teaspoon", notes: "optional" },
      { name: "salt", quantity: "1/2", unit: "teaspoon" },
      { name: "black pepper", quantity: "1/4", unit: "teaspoon" },
      { name: "panko breadcrumbs", quantity: "1/4", unit: "cup" },
      { name: "fresh parsley", quantity: "2", unit: "tablespoons", notes: "chopped, for garnish" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 375°F (190°C). Line a baking sheet with parchment paper." },
      { order: 2, instruction: "Clean mushrooms with a damp paper towel. Remove stems, chop them finely, and set aside." },
      { order: 3, instruction: "Brush mushroom caps with 1 tablespoon olive oil and place them gill-side up on the prepared baking sheet." },
      { order: 4, instruction: "In a large skillet, heat the remaining 1 tablespoon olive oil over medium heat. Add chopped mushroom stems, garlic, and shallot. Cook until softened, about 3-4 minutes." },
      { order: 5, instruction: "Add spinach and artichoke hearts to the skillet. Cook for 2-3 minutes to combine flavors and evaporate excess moisture." },
      { order: 6, instruction: "Reduce heat to low. Add cream cheese and sour cream, stirring until melted and combined." },
      { order: 7, instruction: "Remove from heat. Stir in 1/4 cup parmesan cheese, mozzarella cheese, red pepper flakes (if using), salt, and pepper." },
      { order: 8, instruction: "In a small bowl, combine panko breadcrumbs with the remaining 1/4 cup parmesan cheese." },
      { order: 9, instruction: "Fill each mushroom cap with the spinach-artichoke mixture, slightly mounding the filling." },
      { order: 10, instruction: "Sprinkle the breadcrumb-cheese mixture over the filled mushrooms." },
      { order: 11, instruction: "Bake for 20-25 minutes, until mushrooms are tender and topping is golden brown." },
      { order: 12, instruction: "Garnish with chopped parsley before serving." }
    ],
    cookingVessel: "Baking Sheet",
    prepTime: 20,
    cookTime: 25,
    servings: 8,
    difficulty: "Medium",
    mealType: "Appetizer",
    cuisine: "American",
    categories: ["Stuffed Mushrooms", "Hot Appetizers"],
    dietaryCategories: ["Vegetarian", "Gluten-Free (without breadcrumbs)"],
    tags: ["mushrooms", "spinach", "artichoke", "cheese", "party food"],
    imageUrl: "https://images.unsplash.com/photo-1608039755401-742074f0548d"
  },
  {
    title: "Crispy Coconut Shrimp with Sweet Chili Sauce",
    description: "Succulent shrimp coated in a crispy coconut crust, fried to golden perfection and served with a tangy sweet chili dipping sauce for an irresistible tropical-inspired appetizer.",
    ingredients: [
      { name: "large shrimp", quantity: "1", unit: "pound", notes: "peeled and deveined, tails on" },
      { name: "all-purpose flour", quantity: "1/2", unit: "cup" },
      { name: "salt", quantity: "1/2", unit: "teaspoon" },
      { name: "black pepper", quantity: "1/4", unit: "teaspoon" },
      { name: "garlic powder", quantity: "1/2", unit: "teaspoon" },
      { name: "eggs", quantity: "2", unit: "large", notes: "beaten" },
      { name: "shredded sweetened coconut", quantity: "1", unit: "cup" },
      { name: "panko breadcrumbs", quantity: "1", unit: "cup" },
      { name: "vegetable oil", quantity: "3", unit: "cups", notes: "for frying" },
      { name: "sweet chili sauce", quantity: "1/2", unit: "cup", notes: "for dipping" },
      { name: "lime", quantity: "1", unit: "medium", notes: "cut into wedges" },
      { name: "cilantro", quantity: "2", unit: "tablespoons", notes: "chopped, for garnish" }
    ],
    steps: [
      { order: 1, instruction: "Pat shrimp dry with paper towels. Make sure they are completely dry to ensure the coating adheres properly." },
      { order: 2, instruction: "Set up a breading station with three shallow dishes: In the first dish, combine flour, salt, pepper, and garlic powder. In the second dish, place beaten eggs. In the third dish, mix together shredded coconut and panko breadcrumbs." },
      { order: 3, instruction: "Dredge each shrimp in the flour mixture, shaking off excess, then dip in beaten eggs, and finally coat thoroughly with the coconut-panko mixture, pressing gently to adhere." },
      { order: 4, instruction: "Place breaded shrimp on a baking sheet lined with parchment paper. Refrigerate for 15-30 minutes to help the coating set." },
      { order: 5, instruction: "In a large, heavy-bottomed skillet or Dutch oven, heat oil to 350°F (175°C). Use a thermometer to monitor temperature." },
      { order: 6, instruction: "Working in batches to avoid overcrowding, fry shrimp for 2-3 minutes, turning once, until golden brown and crispy." },
      { order: 7, instruction: "Using a slotted spoon, transfer fried shrimp to a paper towel-lined plate to drain excess oil." },
      { order: 8, instruction: "Serve immediately with sweet chili sauce for dipping, lime wedges, and a sprinkle of chopped cilantro." }
    ],
    cookingVessel: "Dutch Oven or Deep Skillet",
    prepTime: 20,
    cookTime: 15,
    servings: 6,
    difficulty: "Medium",
    mealType: "Appetizer",
    cuisine: "Thai-Inspired",
    categories: ["Fried Appetizers", "Seafood Appetizers"],
    dietaryCategories: ["Dairy-Free"],
    tags: ["shrimp", "coconut", "fried", "sweet chili", "party food"],
    imageUrl: "https://images.unsplash.com/photo-1625943553852-781c6dd46faa"
  },
  {
    title: "Baked Brie with Honey, Walnuts, and Rosemary",
    description: "A wheel of creamy brie cheese baked until molten, topped with honey, toasted walnuts, and fresh rosemary for an elegant appetizer that's perfect for entertaining.",
    ingredients: [
      { name: "brie cheese", quantity: "1", unit: "8-ounce wheel" },
      { name: "honey", quantity: "3", unit: "tablespoons" },
      { name: "walnuts", quantity: "1/3", unit: "cup", notes: "roughly chopped" },
      { name: "fresh rosemary", quantity: "1", unit: "tablespoon", notes: "chopped, plus sprigs for garnish" },
      { name: "baguette", quantity: "1", unit: "small", notes: "sliced" },
      { name: "apple", quantity: "1", unit: "medium", notes: "sliced" },
      { name: "pear", quantity: "1", unit: "medium", notes: "sliced" },
      { name: "sea salt", quantity: "1/4", unit: "teaspoon", notes: "flaky, optional" },
      { name: "black pepper", quantity: "1/8", unit: "teaspoon", notes: "freshly ground, optional" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 350°F (175°C)." },
      { order: 2, instruction: "Place the brie wheel in a small oven-safe dish or on a parchment-lined baking sheet." },
      { order: 3, instruction: "Score the top of the brie in a crosshatch pattern, being careful not to cut all the way through." },
      { order: 4, instruction: "Bake for 12-15 minutes, until the cheese is soft and beginning to ooze but not completely melted." },
      { order: 5, instruction: "While the brie is baking, toast the walnuts in a dry skillet over medium heat for 3-5 minutes, stirring frequently, until fragrant. Remove from heat." },
      { order: 6, instruction: "Remove the brie from the oven and immediately drizzle with honey." },
      { order: 7, instruction: "Sprinkle with toasted walnuts and chopped rosemary." },
      { order: 8, instruction: "If desired, add a light sprinkle of flaky sea salt and freshly ground black pepper." },
      { order: 9, instruction: "Garnish with small rosemary sprigs." },
      { order: 10, instruction: "Serve immediately with sliced baguette, apple, and pear." }
    ],
    cookingVessel: "Oven-Safe Dish",
    prepTime: 10,
    cookTime: 15,
    servings: 6,
    difficulty: "Easy",
    mealType: "Appetizer",
    cuisine: "French",
    categories: ["Cheese Appetizers", "Hot Appetizers"],
    dietaryCategories: ["Vegetarian"],
    tags: ["brie", "honey", "walnuts", "elegant", "entertaining"],
    imageUrl: "https://images.unsplash.com/photo-1646566822483-d9b6bae124ab"
  },
  {
    title: "Bacon-Wrapped Dates Stuffed with Goat Cheese",
    description: "Sweet, tender dates stuffed with tangy goat cheese and wrapped in crispy bacon for an irresistible sweet-savory appetizer that's always a crowd-pleaser.",
    ingredients: [
      { name: "Medjool dates", quantity: "24", unit: "large" },
      { name: "goat cheese", quantity: "4", unit: "ounces", notes: "softened" },
      { name: "bacon", quantity: "12", unit: "slices", notes: "cut in half crosswise" },
      { name: "honey", quantity: "2", unit: "tablespoons", notes: "for drizzling" },
      { name: "fresh thyme leaves", quantity: "1", unit: "tablespoon", notes: "for garnish" },
      { name: "black pepper", quantity: "1/4", unit: "teaspoon", notes: "freshly ground" },
      { name: "toothpicks", quantity: "24", unit: "", notes: "soaked in water for 30 minutes" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 375°F (190°C). Line a baking sheet with parchment paper or aluminum foil." },
      { order: 2, instruction: "Using a small knife, make a lengthwise slit in each date and remove the pit." },
      { order: 3, instruction: "Fill each date with about 1 teaspoon of goat cheese." },
      { order: 4, instruction: "Wrap each stuffed date with a half slice of bacon and secure with a toothpick." },
      { order: 5, instruction: "Arrange the wrapped dates on the prepared baking sheet, seam-side down." },
      { order: 6, instruction: "Bake for 20-25 minutes, turning halfway through, until the bacon is crisp and golden brown." },
      { order: 7, instruction: "Transfer to a paper towel-lined plate to drain any excess bacon fat." },
      { order: 8, instruction: "Arrange on a serving platter, drizzle with honey, and sprinkle with fresh thyme leaves and freshly ground black pepper." },
      { order: 9, instruction: "Serve warm." }
    ],
    cookingVessel: "Baking Sheet",
    prepTime: 15,
    cookTime: 25,
    servings: 8,
    difficulty: "Easy",
    mealType: "Appetizer",
    cuisine: "Mediterranean-Inspired",
    categories: ["Bacon-Wrapped Appetizers", "Hot Appetizers"],
    dietaryCategories: ["Gluten-Free"],
    tags: ["dates", "bacon", "goat cheese", "sweet and savory", "party food"],
    imageUrl: "https://images.unsplash.com/photo-1541014741259-de529411b96a"
  },
  {
    title: "Bruschetta with Tomato and Basil",
    description: "Classic Italian appetizer featuring toasted baguette slices topped with a fresh mixture of diced tomatoes, basil, garlic, and balsamic glaze for a simple yet flavorful starter.",
    ingredients: [
      { name: "baguette", quantity: "1", unit: "French", notes: "sliced diagonally into 1/2-inch pieces" },
      { name: "olive oil", quantity: "1/4", unit: "cup", notes: "plus more for brushing bread" },
      { name: "garlic", quantity: "2", unit: "cloves", notes: "one minced, one halved" },
      { name: "tomatoes", quantity: "6", unit: "medium", notes: "Roma or plum, diced" },
      { name: "fresh basil", quantity: "1/4", unit: "cup", notes: "chopped, plus more for garnish" },
      { name: "balsamic vinegar", quantity: "2", unit: "tablespoons" },
      { name: "balsamic glaze", quantity: "2", unit: "tablespoons", notes: "for drizzling" },
      { name: "salt", quantity: "1/2", unit: "teaspoon" },
      { name: "black pepper", quantity: "1/4", unit: "teaspoon", notes: "freshly ground" },
      { name: "parmesan cheese", quantity: "1/4", unit: "cup", notes: "freshly grated, optional" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 400°F (200°C)." },
      { order: 2, instruction: "Place baguette slices on a large baking sheet. Brush both sides lightly with olive oil." },
      { order: 3, instruction: "Bake for 8-10 minutes, flipping halfway through, until bread is golden and crisp." },
      { order: 4, instruction: "While still hot, rub one side of each toast with the cut side of the halved garlic clove." },
      { order: 5, instruction: "In a medium bowl, combine diced tomatoes, minced garlic, chopped basil, 1/4 cup olive oil, and balsamic vinegar." },
      { order: 6, instruction: "Season with salt and pepper, then gently toss to combine. Let sit for at least 15 minutes to allow flavors to meld." },
      { order: 7, instruction: "Just before serving, spoon the tomato mixture onto the garlic-rubbed side of each toast." },
      { order: 8, instruction: "If using, sprinkle with freshly grated parmesan cheese." },
      { order: 9, instruction: "Drizzle with balsamic glaze and garnish with additional basil leaves." },
      { order: 10, instruction: "Serve immediately to prevent the bread from becoming soggy." }
    ],
    cookingVessel: "Baking Sheet",
    prepTime: 15,
    cookTime: 10,
    servings: 8,
    difficulty: "Easy",
    mealType: "Appetizer",
    cuisine: "Italian",
    categories: ["Bruschetta", "Vegetable Appetizers"],
    dietaryCategories: ["Vegetarian"],
    tags: ["tomato", "basil", "baguette", "Italian", "fresh"],
    imageUrl: "https://images.unsplash.com/photo-1572695157366-5e585ab2b69f"
  },
  {
    title: "Crispy Buffalo Cauliflower Bites",
    description: "Crispy battered cauliflower florets tossed in spicy buffalo sauce for a vegetarian twist on buffalo wings that's equally satisfying and perfect for game day snacking.",
    ingredients: [
      { name: "cauliflower", quantity: "1", unit: "large head", notes: "cut into florets" },
      { name: "all-purpose flour", quantity: "1", unit: "cup" },
      { name: "garlic powder", quantity: "2", unit: "teaspoons" },
      { name: "onion powder", quantity: "1", unit: "teaspoon" },
      { name: "paprika", quantity: "1", unit: "teaspoon" },
      { name: "salt", quantity: "1", unit: "teaspoon" },
      { name: "black pepper", quantity: "1/2", unit: "teaspoon" },
      { name: "milk", quantity: "1", unit: "cup", notes: "dairy or plant-based" },
      { name: "buffalo sauce", quantity: "1/2", unit: "cup", notes: "plus more for serving" },
      { name: "unsalted butter", quantity: "2", unit: "tablespoons", notes: "melted" },
      { name: "blue cheese dressing", quantity: "1/2", unit: "cup", notes: "for serving" },
      { name: "ranch dressing", quantity: "1/2", unit: "cup", notes: "for serving" },
      { name: "celery sticks", quantity: "4", unit: "", notes: "for serving" },
      { name: "carrot sticks", quantity: "4", unit: "", notes: "for serving" },
      { name: "green onions", quantity: "2", unit: "", notes: "sliced, for garnish" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 450°F (230°C). Line a large baking sheet with parchment paper and spray with cooking spray." },
      { order: 2, instruction: "In a large bowl, whisk together flour, garlic powder, onion powder, paprika, salt, and pepper." },
      { order: 3, instruction: "Gradually add milk to the dry ingredients, whisking until a smooth batter forms." },
      { order: 4, instruction: "Add cauliflower florets to the batter and toss until each piece is thoroughly coated." },
      { order: 5, instruction: "Using a slotted spoon, transfer the battered cauliflower to the prepared baking sheet, allowing excess batter to drip off. Arrange in a single layer." },
      { order: 6, instruction: "Bake for 20 minutes, flipping halfway through, until golden and crispy." },
      { order: 7, instruction: "While the cauliflower bakes, combine buffalo sauce and melted butter in a large bowl." },
      { order: 8, instruction: "When cauliflower is done, transfer the hot florets to the bowl with buffalo sauce and gently toss to coat." },
      { order: 9, instruction: "Return the coated cauliflower to the baking sheet and bake for an additional 5-7 minutes until the sauce is set and slightly caramelized." },
      { order: 10, instruction: "Serve hot with blue cheese dressing, ranch dressing, celery sticks, and carrot sticks." },
      { order: 11, instruction: "Garnish with sliced green onions and additional buffalo sauce if desired." }
    ],
    cookingVessel: "Baking Sheet",
    prepTime: 15,
    cookTime: 30,
    servings: 6,
    difficulty: "Medium",
    mealType: "Appetizer",
    cuisine: "American",
    categories: ["Vegetable Appetizers", "Spicy Appetizers"],
    dietaryCategories: ["Vegetarian"],
    tags: ["cauliflower", "buffalo", "spicy", "game day", "vegetarian wings"],
    imageUrl: "https://images.unsplash.com/photo-1562967916-eb82221dfb92"
  },
  {
    title: "Smoked Salmon and Cream Cheese Cucumber Rounds",
    description: "Elegant cucumber slices topped with herbed cream cheese and smoked salmon, garnished with fresh dill and capers for a refreshing, no-cook appetizer that's perfect for entertaining.",
    ingredients: [
      { name: "English cucumber", quantity: "2", unit: "large" },
      { name: "cream cheese", quantity: "8", unit: "ounces", notes: "softened" },
      { name: "fresh dill", quantity: "2", unit: "tablespoons", notes: "chopped, plus more for garnish" },
      { name: "lemon zest", quantity: "1", unit: "teaspoon" },
      { name: "lemon juice", quantity: "1", unit: "tablespoon" },
      { name: "smoked salmon", quantity: "8", unit: "ounces", notes: "thinly sliced" },
      { name: "capers", quantity: "2", unit: "tablespoons", notes: "drained" },
      { name: "red onion", quantity: "1/4", unit: "cup", notes: "finely diced" },
      { name: "black pepper", quantity: "1/4", unit: "teaspoon", notes: "freshly ground" },
      { name: "everything bagel seasoning", quantity: "1", unit: "tablespoon", notes: "optional" }
    ],
    steps: [
      { order: 1, instruction: "Wash and slice cucumbers into 1/4-inch thick rounds. Place on paper towels to remove excess moisture." },
      { order: 2, instruction: "In a small bowl, mix together softened cream cheese, chopped dill, lemon zest, and lemon juice until well combined." },
      { order: 3, instruction: "Spread or pipe about 1 teaspoon of the cream cheese mixture onto each cucumber round." },
      { order: 4, instruction: "Top each with a small piece of smoked salmon, folded or rolled for presentation." },
      { order: 5, instruction: "Sprinkle with capers and diced red onion." },
      { order: 6, instruction: "Season with freshly ground black pepper and everything bagel seasoning if using." },
      { order: 7, instruction: "Garnish with additional fresh dill sprigs." },
      { order: 8, instruction: "Arrange on a serving platter and refrigerate until ready to serve, up to 2 hours." }
    ],
    cookingVessel: "None",
    prepTime: 20,
    cookTime: 0,
    servings: 8,
    difficulty: "Easy",
    mealType: "Appetizer",
    cuisine: "Scandinavian",
    categories: ["No-Cook Appetizers", "Seafood Appetizers"],
    dietaryCategories: ["Gluten-Free", "Low-Carb"],
    tags: ["smoked salmon", "cucumber", "cream cheese", "elegant", "no-cook"],
    imageUrl: "https://images.unsplash.com/photo-1485963631004-f2f00b1d6606"
  },
  {
    title: "Jalapeño Poppers with Bacon and Cheddar",
    description: "Spicy jalapeño peppers halved and filled with a creamy cheese mixture, topped with crispy bacon and baked until golden for a crowd-pleasing appetizer with the perfect balance of heat and richness.",
    ingredients: [
      { name: "jalapeño peppers", quantity: "12", unit: "medium", notes: "halved lengthwise, seeds and membranes removed" },
      { name: "cream cheese", quantity: "8", unit: "ounces", notes: "softened" },
      { name: "sharp cheddar cheese", quantity: "1", unit: "cup", notes: "shredded" },
      { name: "bacon", quantity: "6", unit: "slices", notes: "cooked and crumbled" },
      { name: "green onions", quantity: "3", unit: "", notes: "finely chopped" },
      { name: "garlic powder", quantity: "1/2", unit: "teaspoon" },
      { name: "onion powder", quantity: "1/2", unit: "teaspoon" },
      { name: "smoked paprika", quantity: "1/4", unit: "teaspoon" },
      { name: "salt", quantity: "1/4", unit: "teaspoon" },
      { name: "black pepper", quantity: "1/4", unit: "teaspoon" },
      { name: "panko breadcrumbs", quantity: "1/2", unit: "cup" },
      { name: "parmesan cheese", quantity: "1/4", unit: "cup", notes: "grated" },
      { name: "olive oil", quantity: "1", unit: "tablespoon" },
      { name: "fresh cilantro", quantity: "2", unit: "tablespoons", notes: "chopped, for garnish" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 400°F (200°C). Line a baking sheet with parchment paper." },
      { order: 2, instruction: "In a medium bowl, combine cream cheese, cheddar cheese, half of the crumbled bacon, green onions, garlic powder, onion powder, smoked paprika, salt, and pepper. Mix until well combined." },
      { order: 3, instruction: "Fill each jalapeño half with the cheese mixture, mounding slightly." },
      { order: 4, instruction: "In a small bowl, mix together panko breadcrumbs, parmesan cheese, and olive oil." },
      { order: 5, instruction: "Sprinkle the breadcrumb mixture over the filled jalapeños, then top with remaining crumbled bacon." },
      { order: 6, instruction: "Place the jalapeño poppers on the prepared baking sheet." },
      { order: 7, instruction: "Bake for 15-20 minutes, until the filling is bubbly and the tops are golden brown." },
      { order: 8, instruction: "Let cool for 5 minutes before serving." },
      { order: 9, instruction: "Garnish with chopped cilantro and serve warm." }
    ],
    cookingVessel: "Baking Sheet",
    prepTime: 20,
    cookTime: 20,
    servings: 6,
    difficulty: "Medium",
    mealType: "Appetizer",
    cuisine: "American",
    categories: ["Stuffed Peppers", "Spicy Appetizers"],
    dietaryCategories: ["Gluten-Free (without breadcrumbs)", "Low-Carb"],
    tags: ["jalapeño", "bacon", "cheese", "spicy", "game day"],
    imageUrl: "https://images.unsplash.com/photo-1608039755401-742074f0548d"
  },
  {
    title: "Mini Mediterranean Hummus Cups",
    description: "Crispy phyllo cups filled with creamy hummus and topped with a colorful Mediterranean salad for an elegant, bite-sized appetizer that's as beautiful as it is delicious.",
    ingredients: [
      { name: "mini phyllo shells", quantity: "30", unit: "", notes: "thawed if frozen" },
      { name: "hummus", quantity: "1 1/2", unit: "cups", notes: "store-bought or homemade" },
      { name: "cucumber", quantity: "1/2", unit: "medium", notes: "finely diced" },
      { name: "cherry tomatoes", quantity: "1/2", unit: "cup", notes: "quartered" },
      { name: "kalamata olives", quantity: "1/4", unit: "cup", notes: "pitted and finely chopped" },
      { name: "red onion", quantity: "2", unit: "tablespoons", notes: "finely diced" },
      { name: "feta cheese", quantity: "1/3", unit: "cup", notes: "crumbled" },
      { name: "fresh parsley", quantity: "2", unit: "tablespoons", notes: "chopped" },
      { name: "lemon juice", quantity: "1", unit: "tablespoon" },
      { name: "extra virgin olive oil", quantity: "1", unit: "tablespoon" },
      { name: "dried oregano", quantity: "1/2", unit: "teaspoon" },
      { name: "salt", quantity: "1/4", unit: "teaspoon" },
      { name: "black pepper", quantity: "1/4", unit: "teaspoon" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 350°F (175°C)." },
      { order: 2, instruction: "Place phyllo shells on a baking sheet and bake for 3-5 minutes until crisp. Let cool completely." },
      { order: 3, instruction: "In a medium bowl, combine cucumber, cherry tomatoes, olives, red onion, feta cheese, and parsley." },
      { order: 4, instruction: "In a small bowl, whisk together lemon juice, olive oil, oregano, salt, and pepper to make the dressing." },
      { order: 5, instruction: "Pour the dressing over the vegetable mixture and toss gently to combine." },
      { order: 6, instruction: "Fill each phyllo shell with about 1-2 teaspoons of hummus." },
      { order: 7, instruction: "Top each with a small spoonful of the Mediterranean salad mixture." },
      { order: 8, instruction: "Arrange on a serving platter and serve immediately, or refrigerate for up to 1 hour before serving." }
    ],
    cookingVessel: "Baking Sheet",
    prepTime: 20,
    cookTime: 5,
    servings: 10,
    difficulty: "Easy",
    mealType: "Appetizer",
    cuisine: "Mediterranean",
    categories: ["Phyllo Cup Appetizers", "Vegetable Appetizers"],
    dietaryCategories: ["Vegetarian"],
    tags: ["hummus", "phyllo", "Mediterranean", "bite-sized", "party food"],
    imageUrl: "https://images.unsplash.com/photo-1505253716362-afaea1d3d1af"
  },
  {
    title: "Loaded Potato Skins",
    description: "Crispy potato skins filled with melted cheese, crispy bacon, and green onions, served with sour cream for a classic, crowd-pleasing appetizer that's perfect for game day or casual entertaining.",
    ingredients: [
      { name: "russet potatoes", quantity: "6", unit: "medium", notes: "scrubbed clean" },
      { name: "olive oil", quantity: "2", unit: "tablespoons" },
      { name: "salt", quantity: "1", unit: "teaspoon", notes: "divided" },
      { name: "black pepper", quantity: "1/2", unit: "teaspoon", notes: "divided" },
      { name: "garlic powder", quantity: "1/2", unit: "teaspoon" },
      { name: "bacon", quantity: "8", unit: "slices", notes: "cooked and crumbled" },
      { name: "cheddar cheese", quantity: "2", unit: "cups", notes: "shredded" },
      { name: "green onions", quantity: "4", unit: "", notes: "sliced, divided" },
      { name: "sour cream", quantity: "1", unit: "cup", notes: "for serving" },
      { name: "hot sauce", quantity: "to taste", unit: "", notes: "optional" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 400°F (200°C). Line a baking sheet with parchment paper." },
      { order: 2, instruction: "Prick potatoes several times with a fork. Rub with 1 tablespoon olive oil and sprinkle with 1/2 teaspoon salt." },
      { order: 3, instruction: "Bake potatoes for 45-60 minutes, until tender when pierced with a fork. Remove from oven and let cool until easy to handle." },
      { order: 4, instruction: "Increase oven temperature to 450°F (230°C)." },
      { order: 5, instruction: "Cut potatoes in half lengthwise. Scoop out the flesh, leaving about 1/4-inch of potato attached to the skin. (Reserve the scooped potato for another use, such as mashed potatoes.)" },
      { order: 6, instruction: "Brush both sides of potato skins with remaining olive oil. Sprinkle the inside with remaining salt, pepper, and garlic powder." },
      { order: 7, instruction: "Place potato skins skin-side up on the baking sheet and bake for 10 minutes." },
      { order: 8, instruction: "Flip skins over and bake for another 10 minutes until the edges are crisp and golden." },
      { order: 9, instruction: "Remove from oven and fill each skin with shredded cheese and crumbled bacon." },
      { order: 10, instruction: "Return to oven and bake for 2-3 minutes, until cheese is melted and bubbly." },
      { order: 11, instruction: "Top with most of the sliced green onions, reserving some for garnish." },
      { order: 12, instruction: "Serve hot with sour cream, remaining green onions, and hot sauce if desired." }
    ],
    cookingVessel: "Baking Sheet",
    prepTime: 15,
    cookTime: 85,
    servings: 12,
    difficulty: "Medium",
    mealType: "Appetizer",
    cuisine: "American",
    categories: ["Potato Appetizers", "Game Day Food"],
    dietaryCategories: ["Gluten-Free"],
    tags: ["potato skins", "bacon", "cheese", "game day", "classic"],
    imageUrl: "https://images.unsplash.com/photo-1576021182211-9ea8dced3690"
  },
  {
    title: "Spanakopita Triangles",
    description: "Flaky phyllo pastry triangles filled with a savory mixture of spinach, feta cheese, and herbs for a classic Greek appetizer that's both elegant and satisfying.",
    ingredients: [
      { name: "frozen chopped spinach", quantity: "16", unit: "ounces", notes: "thawed and squeezed dry" },
      { name: "feta cheese", quantity: "8", unit: "ounces", notes: "crumbled" },
      { name: "ricotta cheese", quantity: "1/2", unit: "cup" },
      { name: "eggs", quantity: "2", unit: "large", notes: "beaten" },
      { name: "green onions", quantity: "4", unit: "", notes: "finely chopped" },
      { name: "fresh dill", quantity: "2", unit: "tablespoons", notes: "chopped" },
      { name: "fresh parsley", quantity: "2", unit: "tablespoons", notes: "chopped" },
      { name: "garlic", quantity: "2", unit: "cloves", notes: "minced" },
      { name: "nutmeg", quantity: "1/4", unit: "teaspoon", notes: "freshly grated" },
      { name: "salt", quantity: "1/2", unit: "teaspoon" },
      { name: "black pepper", quantity: "1/4", unit: "teaspoon" },
      { name: "phyllo dough", quantity: "1", unit: "package", notes: "thawed according to package instructions" },
      { name: "unsalted butter", quantity: "1/2", unit: "cup", notes: "melted" },
      { name: "olive oil", quantity: "1/4", unit: "cup" },
      { name: "sesame seeds", quantity: "1", unit: "tablespoon", notes: "for garnish, optional" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 375°F (190°C). Line two baking sheets with parchment paper." },
      { order: 2, instruction: "In a large bowl, combine spinach, feta cheese, ricotta cheese, eggs, green onions, dill, parsley, garlic, nutmeg, salt, and pepper. Mix well." },
      { order: 3, instruction: "In a small bowl, mix melted butter and olive oil." },
      { order: 4, instruction: "Unroll phyllo dough and cover with a damp kitchen towel to prevent it from drying out." },
      { order: 5, instruction: "Place one sheet of phyllo on a clean work surface and brush lightly with the butter-oil mixture. Place another sheet on top and brush again." },
      { order: 6, instruction: "Cut the stacked phyllo sheets lengthwise into 3-inch wide strips." },
      { order: 7, instruction: "Place a heaping tablespoon of the spinach-feta mixture at the bottom of each strip." },
      { order: 8, instruction: "Fold the bottom corner of the strip over the filling to form a triangle. Continue folding the triangle up the strip, like folding a flag, until you reach the end." },
      { order: 9, instruction: "Place the triangles on the prepared baking sheets. Brush the tops with the butter-oil mixture and sprinkle with sesame seeds if using." },
      { order: 10, instruction: "Bake for 20-25 minutes, until golden brown and crisp." },
      { order: 11, instruction: "Let cool for 5 minutes before serving." }
    ],
    cookingVessel: "Baking Sheet",
    prepTime: 30,
    cookTime: 25,
    servings: 12,
    difficulty: "Medium",
    mealType: "Appetizer",
    cuisine: "Greek",
    categories: ["Phyllo Appetizers", "Vegetable Appetizers"],
    dietaryCategories: ["Vegetarian"],
    tags: ["spanakopita", "spinach", "feta", "phyllo", "Greek"],
    imageUrl: "https://images.unsplash.com/photo-1599021456807-25db0f974333"
  },
  {
    title: "Shrimp Cocktail with Zesty Sauce",
    description: "Chilled, perfectly cooked shrimp served with a zesty, homemade cocktail sauce for a classic appetizer that's elegant, refreshing, and always impressive.",
    ingredients: [
      { name: "large shrimp", quantity: "2", unit: "pounds", notes: "shell-on, deveined" },
      { name: "water", quantity: "8", unit: "cups" },
      { name: "lemon", quantity: "1", unit: "medium", notes: "halved, plus wedges for serving" },
      { name: "bay leaves", quantity: "2", unit: "" },
      { name: "black peppercorns", quantity: "1", unit: "tablespoon" },
      { name: "salt", quantity: "2", unit: "tablespoons" },
      { name: "ketchup", quantity: "1", unit: "cup" },
      { name: "prepared horseradish", quantity: "3", unit: "tablespoons", notes: "drained" },
      { name: "Worcestershire sauce", quantity: "2", unit: "teaspoons" },
      { name: "hot sauce", quantity: "1", unit: "teaspoon", notes: "such as Tabasco" },
      { name: "lemon juice", quantity: "2", unit: "tablespoons", notes: "fresh" },
      { name: "fresh parsley", quantity: "2", unit: "tablespoons", notes: "chopped, for garnish" },
      { name: "ice", quantity: "4", unit: "cups", notes: "for ice bath" }
    ],
    steps: [
      { order: 1, instruction: "In a large pot, combine water, lemon halves (squeeze juice into water first), bay leaves, peppercorns, and salt. Bring to a boil." },
      { order: 2, instruction: "Add shrimp to the boiling water and cook just until they turn pink and opaque, about 2-3 minutes. Do not overcook." },
      { order: 3, instruction: "Using a slotted spoon, immediately transfer shrimp to a large bowl filled with ice water to stop the cooking process." },
      { order: 4, instruction: "Once cooled, peel the shrimp, leaving the tails intact for presentation." },
      { order: 5, instruction: "Pat shrimp dry with paper towels and refrigerate until ready to serve." },
      { order: 6, instruction: "For the cocktail sauce, in a medium bowl, combine ketchup, horseradish, Worcestershire sauce, hot sauce, and lemon juice. Stir well." },
      { order: 7, instruction: "Taste and adjust seasonings as needed. Cover and refrigerate until ready to serve." },
      { order: 8, instruction: "To serve, arrange chilled shrimp around the edge of a serving platter or in a martini glass, tails pointing outward." },
      { order: 9, instruction: "Place cocktail sauce in a small bowl in the center." },
      { order: 10, instruction: "Garnish with chopped parsley and serve with lemon wedges." }
    ],
    cookingVessel: "Large Pot",
    prepTime: 15,
    cookTime: 5,
    servings: 8,
    difficulty: "Easy",
    mealType: "Appetizer",
    cuisine: "American",
    categories: ["Seafood Appetizers", "Cold Appetizers"],
    dietaryCategories: ["Gluten-Free", "Dairy-Free"],
    tags: ["shrimp", "cocktail sauce", "classic", "elegant", "party food"],
    imageUrl: "https://images.unsplash.com/photo-1565802527863-1353e4e273e9"
  },
  {
    title: "Stuffed Mushroom Caps with Sausage and Herbs",
    description: "Savory mushroom caps filled with a flavorful mixture of Italian sausage, herbs, and cheese, baked until golden for an irresistible appetizer that's perfect for entertaining.",
    ingredients: [
      { name: "cremini mushrooms", quantity: "24", unit: "large", notes: "stems removed and chopped" },
      { name: "Italian sausage", quantity: "1/2", unit: "pound", notes: "casings removed" },
      { name: "olive oil", quantity: "2", unit: "tablespoons", notes: "divided" },
      { name: "shallot", quantity: "1", unit: "medium", notes: "finely diced" },
      { name: "garlic", quantity: "3", unit: "cloves", notes: "minced" },
      { name: "fresh thyme", quantity: "1", unit: "tablespoon", notes: "chopped" },
      { name: "fresh rosemary", quantity: "1", unit: "teaspoon", notes: "chopped" },
      { name: "fresh parsley", quantity: "2", unit: "tablespoons", notes: "chopped, divided" },
      { name: "breadcrumbs", quantity: "1/2", unit: "cup", notes: "plain or Italian-seasoned" },
      { name: "parmesan cheese", quantity: "1/2", unit: "cup", notes: "grated, divided" },
      { name: "cream cheese", quantity: "2", unit: "ounces", notes: "softened" },
      { name: "salt", quantity: "1/2", unit: "teaspoon" },
      { name: "black pepper", quantity: "1/4", unit: "teaspoon" },
      { name: "red pepper flakes", quantity: "1/8", unit: "teaspoon", notes: "optional" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 375°F (190°C). Line a baking sheet with parchment paper." },
      { order: 2, instruction: "Clean mushroom caps with a damp paper towel. Brush the outside of caps with 1 tablespoon olive oil and place them gill-side up on the prepared baking sheet." },
      { order: 3, instruction: "In a large skillet over medium heat, cook Italian sausage, breaking it into small pieces, until browned and cooked through, about 5-7 minutes. Transfer to a paper towel-lined plate to drain excess fat." },
      { order: 4, instruction: "In the same skillet, heat remaining 1 tablespoon olive oil. Add chopped mushroom stems, shallot, and garlic. Cook until softened, about 3-4 minutes." },
      { order: 5, instruction: "Add thyme, rosemary, and half of the parsley. Cook for another minute until fragrant." },
      { order: 6, instruction: "In a large bowl, combine cooked sausage, mushroom stem mixture, breadcrumbs, 1/4 cup parmesan cheese, cream cheese, salt, pepper, and red pepper flakes if using. Mix well." },
      { order: 7, instruction: "Fill each mushroom cap with the sausage mixture, mounding slightly." },
      { order: 8, instruction: "Sprinkle the tops with remaining parmesan cheese." },
      { order: 9, instruction: "Bake for 20-25 minutes, until mushrooms are tender and tops are golden brown." },
      { order: 10, instruction: "Garnish with remaining chopped parsley before serving." }
    ],
    cookingVessel: "Baking Sheet",
    prepTime: 20,
    cookTime: 25,
    servings: 8,
    difficulty: "Medium",
    mealType: "Appetizer",
    cuisine: "Italian-American",
    categories: ["Stuffed Mushrooms", "Hot Appetizers"],
    dietaryCategories: ["Gluten-Free (with GF breadcrumbs)"],
    tags: ["mushrooms", "sausage", "stuffed", "herbs", "party food"],
    imageUrl: "https://images.unsplash.com/photo-1608039755401-742074f0548d"
  },
  {
    title: "Crispy Vegetable Spring Rolls",
    description: "Crispy, golden spring rolls filled with a flavorful mixture of vegetables and served with a sweet chili dipping sauce for an irresistible Asian-inspired appetizer.",
    ingredients: [
      { name: "spring roll wrappers", quantity: "20", unit: "", notes: "thawed if frozen" },
      { name: "cabbage", quantity: "2", unit: "cups", notes: "finely shredded" },
      { name: "carrots", quantity: "2", unit: "medium", notes: "julienned" },
      { name: "shiitake mushrooms", quantity: "1", unit: "cup", notes: "stems removed, finely chopped" },
      { name: "bean sprouts", quantity: "1", unit: "cup" },
      { name: "green onions", quantity: "4", unit: "", notes: "thinly sliced" },
      { name: "garlic", quantity: "3", unit: "cloves", notes: "minced" },
      { name: "ginger", quantity: "1", unit: "tablespoon", notes: "freshly grated" },
      { name: "soy sauce", quantity: "2", unit: "tablespoons", notes: "low-sodium" },
      { name: "sesame oil", quantity: "1", unit: "tablespoon" },
      { name: "rice vinegar", quantity: "1", unit: "teaspoon" },
      { name: "vegetable oil", quantity: "2", unit: "tablespoons", notes: "plus more for frying" },
      { name: "cornstarch", quantity: "1", unit: "tablespoon", notes: "mixed with 2 tablespoons water" },
      { name: "salt", quantity: "1/2", unit: "teaspoon" },
      { name: "black pepper", quantity: "1/4", unit: "teaspoon" },
      { name: "sweet chili sauce", quantity: "1", unit: "cup", notes: "for dipping" }
    ],
    steps: [
      { order: 1, instruction: "In a large skillet or wok, heat 2 tablespoons vegetable oil over medium-high heat." },
      { order: 2, instruction: "Add garlic and ginger, stir-fry for 30 seconds until fragrant." },
      { order: 3, instruction: "Add mushrooms and stir-fry for 2 minutes until softened." },
      { order: 4, instruction: "Add cabbage and carrots, stir-fry for 3-4 minutes until vegetables begin to soften." },
      { order: 5, instruction: "Add bean sprouts and green onions, stir-fry for 1 minute." },
      { order: 6, instruction: "Stir in soy sauce, sesame oil, rice vinegar, salt, and pepper. Cook for 1 minute." },
      { order: 7, instruction: "Remove from heat and let the filling cool completely." },
      { order: 8, instruction: "Once cooled, drain any excess liquid from the vegetable mixture to prevent soggy spring rolls." },
      { order: 9, instruction: "Place a spring roll wrapper on a clean work surface with one corner pointing toward you (like a diamond)." },
      { order: 10, instruction: "Place about 2 tablespoons of filling near the bottom corner, leaving about 1 inch of space from the edges." },
      { order: 11, instruction: "Fold the bottom corner over the filling, then fold in the left and right corners. Roll tightly toward the top corner." },
      { order: 12, instruction: "Seal the edge with the cornstarch-water mixture." },
      { order: 13, instruction: "Repeat with remaining wrappers and filling." },
      { order: 14, instruction: "In a large, heavy-bottomed pot or deep fryer, heat oil to 350°F (175°C)." },
      { order: 15, instruction: "Fry spring rolls in batches for 2-3 minutes, turning occasionally, until golden brown and crispy." },
      { order: 16, instruction: "Drain on paper towels." },
      { order: 17, instruction: "Serve hot with sweet chili sauce for dipping." }
    ],
    cookingVessel: "Deep Fryer or Heavy Pot",
    prepTime: 30,
    cookTime: 20,
    servings: 10,
    difficulty: "Medium",
    mealType: "Appetizer",
    cuisine: "Asian",
    categories: ["Fried Appetizers", "Vegetable Appetizers"],
    dietaryCategories: ["Vegetarian", "Vegan", "Dairy-Free"],
    tags: ["spring rolls", "vegetables", "fried", "Asian", "party food"],
    imageUrl: "https://images.unsplash.com/photo-1548811256-1627d99e7a57"
  },
  {
    title: "Baked Brie en Croûte with Cranberry and Walnuts",
    description: "A wheel of creamy brie cheese topped with cranberry sauce and walnuts, wrapped in flaky puff pastry and baked until golden for an elegant, crowd-pleasing appetizer.",
    ingredients: [
      { name: "brie cheese", quantity: "1", unit: "8-ounce wheel" },
      { name: "puff pastry", quantity: "1", unit: "sheet", notes: "thawed" },
      { name: "cranberry sauce", quantity: "1/3", unit: "cup", notes: "whole berry or jellied" },
      { name: "walnuts", quantity: "1/4", unit: "cup", notes: "chopped" },
      { name: "honey", quantity: "1", unit: "tablespoon" },
      { name: "fresh thyme leaves", quantity: "1", unit: "teaspoon", notes: "plus sprigs for garnish" },
      { name: "egg", quantity: "1", unit: "large", notes: "beaten with 1 tablespoon water" },
      { name: "crackers", quantity: "for serving", unit: "" },
      { name: "sliced apples", quantity: "for serving", unit: "" },
      { name: "sliced pears", quantity: "for serving", unit: "" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 400°F (200°C). Line a baking sheet with parchment paper." },
      { order: 2, instruction: "Roll out the puff pastry sheet on a lightly floured surface to about 1/8-inch thickness." },
      { order: 3, instruction: "Cut the puff pastry into a circle about 2 inches larger than the brie wheel." },
      { order: 4, instruction: "In a small bowl, mix together cranberry sauce, chopped walnuts, honey, and thyme leaves." },
      { order: 5, instruction: "Place the brie wheel in the center of the puff pastry circle." },
      { order: 6, instruction: "Spoon the cranberry-walnut mixture on top of the brie." },
      { order: 7, instruction: "Fold the puff pastry up and over the brie, pleating as necessary to enclose the cheese completely. Press the edges together to seal." },
      { order: 8, instruction: "Transfer the wrapped brie to the prepared baking sheet, seam-side down." },
      { order: 9, instruction: "Brush the pastry all over with the egg wash." },
      { order: 10, instruction: "Bake for 25-30 minutes, until the pastry is golden brown and puffed." },
      { order: 11, instruction: "Let rest for 5-10 minutes before serving." },
      { order: 12, instruction: "Garnish with fresh thyme sprigs and serve warm with crackers, sliced apples, and pears." }
    ],
    cookingVessel: "Baking Sheet",
    prepTime: 15,
    cookTime: 30,
    servings: 8,
    difficulty: "Medium",
    mealType: "Appetizer",
    cuisine: "French-Inspired",
    categories: ["Cheese Appetizers", "Pastry Appetizers"],
    dietaryCategories: ["Vegetarian"],
    tags: ["brie", "puff pastry", "cranberry", "elegant", "holiday"],
    imageUrl: "https://images.unsplash.com/photo-1608164042537-d1c0a6e7d70d"
  },
  {
    title: "Spicy Tuna Tartare on Wonton Crisps",
    description: "Fresh, diced sushi-grade tuna mixed with Asian-inspired flavors, served on crispy wonton chips for an elegant, restaurant-quality appetizer that's sure to impress.",
    ingredients: [
      { name: "sushi-grade tuna", quantity: "1/2", unit: "pound", notes: "diced into 1/4-inch cubes" },
      { name: "avocado", quantity: "1", unit: "ripe", notes: "diced into 1/4-inch cubes" },
      { name: "green onions", quantity: "3", unit: "", notes: "thinly sliced" },
      { name: "sesame oil", quantity: "2", unit: "teaspoons" },
      { name: "soy sauce", quantity: "1", unit: "tablespoon", notes: "low-sodium" },
      { name: "rice vinegar", quantity: "1", unit: "teaspoon" },
      { name: "sriracha sauce", quantity: "1", unit: "teaspoon", notes: "adjust to taste" },
      { name: "fresh lime juice", quantity: "1", unit: "tablespoon" },
      { name: "fresh ginger", quantity: "1", unit: "teaspoon", notes: "grated" },
      { name: "sesame seeds", quantity: "1", unit: "tablespoon", notes: "toasted" },
      { name: "wonton wrappers", quantity: "24", unit: "" },
      { name: "vegetable oil", quantity: "for frying", unit: "" },
      { name: "microgreens", quantity: "for garnish", unit: "", notes: "optional" },
      { name: "tobiko or masago", quantity: "2", unit: "tablespoons", notes: "flying fish roe, optional" }
    ],
    steps: [
      { order: 1, instruction: "For the wonton crisps: Cut wonton wrappers in half diagonally to form triangles." },
      { order: 2, instruction: "Heat vegetable oil in a large, heavy-bottomed pot to 350°F (175°C)." },
      { order: 3, instruction: "Fry wonton triangles in batches for 30-45 seconds, until golden and crisp." },
      { order: 4, instruction: "Drain on paper towels and sprinkle lightly with salt while still hot. Set aside to cool." },
      { order: 5, instruction: "For the tuna tartare: In a medium bowl, gently combine diced tuna, avocado, and green onions." },
      { order: 6, instruction: "In a small bowl, whisk together sesame oil, soy sauce, rice vinegar, sriracha, lime juice, and grated ginger." },
      { order: 7, instruction: "Pour the dressing over the tuna mixture and fold gently to combine, being careful not to mash the avocado." },
      { order: 8, instruction: "Cover and refrigerate for 15-30 minutes to allow flavors to meld." },
      { order: 9, instruction: "Just before serving, stir in half of the toasted sesame seeds." },
      { order: 10, instruction: "To serve, place a small spoonful of tuna tartare on each wonton crisp." },
      { order: 11, instruction: "Garnish with remaining sesame seeds, microgreens, and tobiko or masago if using." },
      { order: 12, instruction: "Arrange on a serving platter and serve immediately." }
    ],
    cookingVessel: "Heavy-Bottomed Pot",
    prepTime: 25,
    cookTime: 10,
    servings: 8,
    difficulty: "Medium",
    mealType: "Appetizer",
    cuisine: "Asian-Fusion",
    categories: ["Seafood Appetizers", "Raw Appetizers"],
    dietaryCategories: ["Dairy-Free"],
    tags: ["tuna", "tartare", "wonton", "elegant", "raw"],
    imageUrl: "https://images.unsplash.com/photo-1579584425555-c3ce17fd4351"
  },
  {
    title: "Prosciutto-Wrapped Asparagus with Balsamic Glaze",
    description: "Tender asparagus spears wrapped in thin slices of prosciutto, roasted until crisp and drizzled with balsamic glaze for an elegant, simple appetizer that's both impressive and delicious.",
    ingredients: [
      { name: "asparagus spears", quantity: "24", unit: "", notes: "woody ends trimmed" },
      { name: "prosciutto", quantity: "12", unit: "slices", notes: "cut in half lengthwise" },
      { name: "olive oil", quantity: "2", unit: "tablespoons" },
      { name: "black pepper", quantity: "1/4", unit: "teaspoon", notes: "freshly ground" },
      { name: "balsamic glaze", quantity: "1/4", unit: "cup", notes: "store-bought or homemade" },
      { name: "parmesan cheese", quantity: "1/4", unit: "cup", notes: "shaved, optional" },
      { name: "lemon zest", quantity: "1", unit: "teaspoon", notes: "optional" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 425°F (220°C). Line a baking sheet with parchment paper." },
      { order: 2, instruction: "Bring a large pot of salted water to a boil. Prepare an ice bath in a large bowl." },
      { order: 3, instruction: "Blanch asparagus in boiling water for 2 minutes, then immediately transfer to the ice bath to stop the cooking process." },
      { order: 4, instruction: "Once cooled, drain asparagus and pat dry with paper towels." },
      { order: 5, instruction: "Wrap each asparagus spear with a half slice of prosciutto, starting at the bottom and wrapping diagonally to cover most of the spear but leaving the tip exposed." },
      { order: 6, instruction: "Arrange wrapped asparagus on the prepared baking sheet, making sure they're not touching." },
      { order: 7, instruction: "Brush lightly with olive oil and sprinkle with freshly ground black pepper." },
      { order: 8, instruction: "Roast for 8-10 minutes, until the prosciutto is crisp and the asparagus is tender." },
      { order: 9, instruction: "Transfer to a serving platter and drizzle with balsamic glaze." },
      { order: 10, instruction: "If using, sprinkle with shaved parmesan cheese and lemon zest." },
      { order: 11, instruction: "Serve warm or at room temperature." }
    ],
    cookingVessel: "Baking Sheet",
    prepTime: 15,
    cookTime: 10,
    servings: 6,
    difficulty: "Easy",
    mealType: "Appetizer",
    cuisine: "Italian",
    categories: ["Vegetable Appetizers", "Meat Appetizers"],
    dietaryCategories: ["Gluten-Free", "Low-Carb"],
    tags: ["asparagus", "prosciutto", "balsamic", "elegant", "simple"],
    imageUrl: "https://images.unsplash.com/photo-1622973536968-3ead9e780960"
  },
  {
    title: "Mini Crab Cakes with Lemon Aioli",
    description: "Delicate, bite-sized crab cakes made with lump crab meat and minimal fillers, pan-fried until golden and served with a zesty lemon aioli for an elegant seafood appetizer.",
    ingredients: [
      { name: "lump crab meat", quantity: "1", unit: "pound", notes: "picked over for shells" },
      { name: "panko breadcrumbs", quantity: "1/2", unit: "cup", notes: "plus more for coating" },
      { name: "mayonnaise", quantity: "1/4", unit: "cup" },
      { name: "egg", quantity: "1", unit: "large", notes: "beaten" },
      { name: "Dijon mustard", quantity: "1", unit: "tablespoon" },
      { name: "Worcestershire sauce", quantity: "1", unit: "teaspoon" },
      { name: "Old Bay seasoning", quantity: "1", unit: "tablespoon" },
      { name: "lemon zest", quantity: "1", unit: "teaspoon" },
      { name: "fresh parsley", quantity: "2", unit: "tablespoons", notes: "chopped" },
      { name: "green onions", quantity: "2", unit: "", notes: "finely chopped" },
      { name: "salt", quantity: "1/4", unit: "teaspoon" },
      { name: "black pepper", quantity: "1/4", unit: "teaspoon" },
      { name: "vegetable oil", quantity: "3", unit: "tablespoons", notes: "for frying" },
      { name: "mayonnaise", quantity: "1/2", unit: "cup", notes: "for aioli" },
      { name: "garlic", quantity: "1", unit: "clove", notes: "minced, for aioli" },
      { name: "lemon juice", quantity: "1", unit: "tablespoon", notes: "for aioli" },
      { name: "lemon zest", quantity: "1/2", unit: "teaspoon", notes: "for aioli" },
      { name: "fresh dill", quantity: "1", unit: "tablespoon", notes: "chopped, for aioli" },
      { name: "lemon wedges", quantity: "for serving", unit: "" }
    ],
    steps: [
      { order: 1, instruction: "For the lemon aioli: In a small bowl, combine 1/2 cup mayonnaise, minced garlic, lemon juice, lemon zest, and chopped dill. Season with salt and pepper to taste. Cover and refrigerate until ready to serve." },
      { order: 2, instruction: "For the crab cakes: In a large bowl, gently combine crab meat, 1/2 cup panko breadcrumbs, 1/4 cup mayonnaise, beaten egg, Dijon mustard, Worcestershire sauce, Old Bay seasoning, lemon zest, parsley, green onions, salt, and pepper. Be careful not to break up the crab meat too much." },
      { order: 3, instruction: "Cover and refrigerate for 30 minutes to allow the mixture to firm up." },
      { order: 4, instruction: "Place additional panko breadcrumbs in a shallow dish." },
      { order: 5, instruction: "Using a tablespoon or small ice cream scoop, form the crab mixture into 24 small patties, about 1 1/2 inches in diameter." },
      { order: 6, instruction: "Gently coat each crab cake in panko breadcrumbs, pressing lightly to adhere." },
      { order: 7, instruction: "In a large skillet, heat vegetable oil over medium heat." },
      { order: 8, instruction: "Working in batches, cook crab cakes for 2-3 minutes per side, until golden brown and heated through." },
      { order: 9, instruction: "Transfer to a paper towel-lined plate to drain excess oil." },
      { order: 10, instruction: "Arrange crab cakes on a serving platter and top each with a small dollop of lemon aioli." },
      { order: 11, instruction: "Garnish with additional chopped parsley and serve with lemon wedges." }
    ],
    cookingVessel: "Skillet",
    prepTime: 20,
    cookTime: 15,
    servings: 8,
    difficulty: "Medium",
    mealType: "Appetizer",
    cuisine: "American",
    categories: ["Seafood Appetizers", "Fried Appetizers"],
    dietaryCategories: ["Dairy-Free"],
    tags: ["crab cakes", "seafood", "aioli", "elegant", "party food"],
    imageUrl: "https://images.unsplash.com/photo-1599021456807-25db0f974333"
  },
  {
    title: "Stuffed Mini Bell Peppers",
    description: "Colorful mini bell peppers filled with a creamy mixture of cheese, herbs, and spices, then baked until tender for a vibrant, flavorful appetizer that's as beautiful as it is delicious.",
    ingredients: [
      { name: "mini bell peppers", quantity: "24", unit: "", notes: "assorted colors" },
      { name: "cream cheese", quantity: "8", unit: "ounces", notes: "softened" },
      { name: "feta cheese", quantity: "1/2", unit: "cup", notes: "crumbled" },
      { name: "shredded cheddar cheese", quantity: "1/2", unit: "cup" },
      { name: "garlic", quantity: "2", unit: "cloves", notes: "minced" },
      { name: "green onions", quantity: "3", unit: "", notes: "finely chopped" },
      { name: "fresh parsley", quantity: "2", unit: "tablespoons", notes: "chopped" },
      { name: "fresh dill", quantity: "1", unit: "tablespoon", notes: "chopped" },
      { name: "smoked paprika", quantity: "1/2", unit: "teaspoon", notes: "plus more for garnish" },
      { name: "red pepper flakes", quantity: "1/4", unit: "teaspoon", notes: "optional" },
      { name: "salt", quantity: "1/4", unit: "teaspoon" },
      { name: "black pepper", quantity: "1/4", unit: "teaspoon" },
      { name: "olive oil", quantity: "1", unit: "tablespoon" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 375°F (190°C). Line a baking sheet with parchment paper." },
      { order: 2, instruction: "Cut the tops off the mini bell peppers and remove seeds and membranes. Leave stems intact for presentation if desired." },
      { order: 3, instruction: "In a medium bowl, combine cream cheese, feta cheese, cheddar cheese, minced garlic, green onions, parsley, dill, smoked paprika, red pepper flakes (if using), salt, and pepper. Mix until well combined." },
      { order: 4, instruction: "Transfer the cheese mixture to a piping bag or use a small spoon to fill each pepper cavity." },
      { order: 5, instruction: "Arrange stuffed peppers on the prepared baking sheet." },
      { order: 6, instruction: "Brush the outside of each pepper lightly with olive oil." },
      { order: 7, instruction: "Bake for 15-20 minutes, until peppers are tender and filling is heated through." },
      { order: 8, instruction: "Let cool for 5 minutes before serving." },
      { order: 9, instruction: "Sprinkle with additional smoked paprika for garnish." },
      { order: 10, instruction: "Serve warm or at room temperature." }
    ],
    cookingVessel: "Baking Sheet",
    prepTime: 20,
    cookTime: 20,
    servings: 8,
    difficulty: "Easy",
    mealType: "Appetizer",
    cuisine: "Mediterranean-Inspired",
    categories: ["Stuffed Peppers", "Vegetable Appetizers"],
    dietaryCategories: ["Vegetarian", "Gluten-Free"],
    tags: ["bell peppers", "cheese", "stuffed", "colorful", "party food"],
    imageUrl: "https://images.unsplash.com/photo-1603903631918-a6a92fb6ac49"
  },
  {
    title: "Garlic Parmesan Chicken Wings",
    description: "Crispy baked chicken wings tossed in a savory garlic parmesan sauce for a flavorful, crowd-pleasing appetizer that's perfect for game day or casual entertaining.",
    ingredients: [
      { name: "chicken wings", quantity: "3", unit: "pounds", notes: "split into flats and drumettes" },
      { name: "baking powder", quantity: "2", unit: "tablespoons", notes: "not baking soda" },
      { name: "salt", quantity: "1", unit: "teaspoon" },
      { name: "black pepper", quantity: "1/2", unit: "teaspoon" },
      { name: "garlic powder", quantity: "1", unit: "teaspoon" },
      { name: "unsalted butter", quantity: "1/2", unit: "cup", notes: "melted" },
      { name: "garlic", quantity: "6", unit: "cloves", notes: "minced" },
      { name: "parmesan cheese", quantity: "1", unit: "cup", notes: "finely grated" },
      { name: "fresh parsley", quantity: "2", unit: "tablespoons", notes: "chopped" },
      { name: "red pepper flakes", quantity: "1/4", unit: "teaspoon", notes: "optional" },
      { name: "lemon zest", quantity: "1", unit: "teaspoon", notes: "optional" },
      { name: "ranch or blue cheese dressing", quantity: "for serving", unit: "" },
      { name: "celery sticks", quantity: "for serving", unit: "" }
    ],
    steps: [
      { order: 1, instruction: "Pat chicken wings dry with paper towels. This is crucial for achieving crispy skin." },
      { order: 2, instruction: "In a large bowl, toss wings with baking powder, salt, pepper, and garlic powder until evenly coated." },
      { order: 3, instruction: "Arrange wings on a wire rack set over a baking sheet, making sure they're not touching." },
      { order: 4, instruction: "Refrigerate, uncovered, for at least 1 hour or overnight to allow the skin to dry out." },
      { order: 5, instruction: "Preheat oven to 425°F (220°C)." },
      { order: 6, instruction: "Bake wings for 30 minutes, then flip and continue baking for another 20-25 minutes, until skin is crispy and golden brown." },
      { order: 7, instruction: "Meanwhile, prepare the garlic parmesan sauce: In a small saucepan over medium heat, melt butter. Add minced garlic and cook for 1-2 minutes until fragrant but not browned." },
      { order: 8, instruction: "Remove from heat and stir in 3/4 cup of the parmesan cheese, parsley, red pepper flakes (if using), and lemon zest (if using)." },
      { order: 9, instruction: "When wings are done, transfer them to a large bowl." },
      { order: 10, instruction: "Pour the garlic parmesan sauce over the wings and toss until evenly coated." },
      { order: 11, instruction: "Sprinkle with remaining 1/4 cup parmesan cheese and additional chopped parsley." },
      { order: 12, instruction: "Serve immediately with ranch or blue cheese dressing and celery sticks." }
    ],
    cookingVessel: "Baking Sheet with Wire Rack",
    prepTime: 15,
    cookTime: 55,
    servings: 6,
    difficulty: "Medium",
    mealType: "Appetizer",
    cuisine: "American",
    categories: ["Chicken Wings", "Game Day Food"],
    dietaryCategories: ["Gluten-Free", "Low-Carb"],
    tags: ["chicken wings", "garlic", "parmesan", "game day", "party food"],
    imageUrl: "https://images.unsplash.com/photo-1608039755401-742074f0548d"
  },
  {
    title: "Spinach and Feta Phyllo Triangles (Spanakopita)",
    description: "Flaky phyllo pastry triangles filled with a savory mixture of spinach, feta cheese, and herbs for a classic Greek appetizer that's both elegant and satisfying.",
    ingredients: [
      { name: "frozen chopped spinach", quantity: "16", unit: "ounces", notes: "thawed and squeezed dry" },
      { name: "feta cheese", quantity: "8", unit: "ounces", notes: "crumbled" },
      { name: "ricotta cheese", quantity: "1/2", unit: "cup" },
      { name: "eggs", quantity: "2", unit: "large", notes: "beaten" },
      { name: "green onions", quantity: "4", unit: "", notes: "finely chopped" },
      { name: "fresh dill", quantity: "2", unit: "tablespoons", notes: "chopped" },
      { name: "fresh parsley", quantity: "2", unit: "tablespoons", notes: "chopped" },
      { name: "garlic", quantity: "2", unit: "cloves", notes: "minced" },
      { name: "nutmeg", quantity: "1/4", unit: "teaspoon", notes: "freshly grated" },
      { name: "salt", quantity: "1/2", unit: "teaspoon" },
      { name: "black pepper", quantity: "1/4", unit: "teaspoon" },
      { name: "phyllo dough", quantity: "1", unit: "package", notes: "thawed according to package instructions" },
      { name: "unsalted butter", quantity: "1/2", unit: "cup", notes: "melted" },
      { name: "olive oil", quantity: "1/4", unit: "cup" },
      { name: "sesame seeds", quantity: "1", unit: "tablespoon", notes: "for garnish, optional" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 375°F (190°C). Line two baking sheets with parchment paper." },
      { order: 2, instruction: "In a large bowl, combine spinach, feta cheese, ricotta cheese, eggs, green onions, dill, parsley, garlic, nutmeg, salt, and pepper. Mix well." },
      { order: 3, instruction: "In a small bowl, mix melted butter and olive oil." },
      { order: 4, instruction: "Unroll phyllo dough and cover with a damp kitchen towel to prevent it from drying out." },
      { order: 5, instruction: "Place one sheet of phyllo on a clean work surface and brush lightly with the butter-oil mixture. Place another sheet on top and brush again." },
      { order: 6, instruction: "Cut the stacked phyllo sheets lengthwise into 3-inch wide strips." },
      { order: 7, instruction: "Place a heaping tablespoon of the spinach-feta mixture at the bottom of each strip." },
      { order: 8, instruction: "Fold the bottom corner of the strip over the filling to form a triangle. Continue folding the triangle up the strip, like folding a flag, until you reach the end." },
      { order: 9, instruction: "Place the triangles on the prepared baking sheets. Brush the tops with the butter-oil mixture and sprinkle with sesame seeds if using." },
      { order: 10, instruction: "Bake for 20-25 minutes, until golden brown and crisp." },
      { order: 11, instruction: "Let cool for 5 minutes before serving." }
    ],
    cookingVessel: "Baking Sheet",
    prepTime: 30,
    cookTime: 25,
    servings: 12,
    difficulty: "Medium",
    mealType: "Appetizer",
    cuisine: "Greek",
    categories: ["Phyllo Appetizers", "Vegetable Appetizers"],
    dietaryCategories: ["Vegetarian"],
    tags: ["spanakopita", "spinach", "feta", "phyllo", "Greek"],
    imageUrl: "https://images.unsplash.com/photo-1599021456807-25db0f974333"
  }
];

export default appetizerRecipes;
