// Breakfast Recipes for WhatAboutDinner App
// 20 detailed breakfast recipes with all required fields

const breakfastRecipes = [
  {
    title: "Classic Avocado Toast",
    description: "A simple, nutritious breakfast that's quick to prepare and infinitely customizable with creamy avocado on crispy whole grain toast.",
    ingredients: [
      { name: "bread", quantity: "2", unit: "slices", notes: "whole grain or sourdough" },
      { name: "avocado", quantity: "1", unit: "medium", notes: "ripe" },
      { name: "lemon juice", quantity: "1", unit: "teaspoon" },
      { name: "salt", quantity: "1/4", unit: "teaspoon" },
      { name: "black pepper", quantity: "1/8", unit: "teaspoon", notes: "freshly ground" },
      { name: "red pepper flakes", quantity: "1/8", unit: "teaspoon", notes: "optional" }
    ],
    steps: [
      { order: 1, instruction: "Toast the bread slices until golden and crisp." },
      { order: 2, instruction: "Cut the avocado in half, remove the pit, and scoop the flesh into a bowl." },
      { order: 3, instruction: "Add lemon juice, salt, and pepper to the avocado and mash with a fork to desired consistency." },
      { order: 4, instruction: "Spread the avocado mixture evenly on the toast slices." },
      { order: 5, instruction: "Sprinkle with red pepper flakes if desired and serve immediately." }
    ],
    cookingVessel: "Toaster",
    prepTime: 5,
    cookTime: 3,
    servings: 1,
    difficulty: "Easy",
    mealType: "Breakfast",
    cuisine: "American",
    categories: ["Quick & Easy", "Healthy", "Vegetarian"],
    dietaryCategories: ["Vegetarian", "Vegan", "Dairy-Free"],
    tags: ["avocado", "toast", "healthy", "quick breakfast"],
    imageUrl: "https://images.unsplash.com/photo-1588137378633-dea1336ce1e2"
  },
  {
    title: "Fluffy Blueberry Pancakes",
    description: "Light and fluffy pancakes studded with fresh blueberries, perfect for a weekend breakfast that the whole family will love.",
    ingredients: [
      { name: "all-purpose flour", quantity: "1", unit: "cup" },
      { name: "sugar", quantity: "2", unit: "tablespoons" },
      { name: "baking powder", quantity: "2", unit: "teaspoons" },
      { name: "salt", quantity: "1/4", unit: "teaspoon" },
      { name: "milk", quantity: "3/4", unit: "cup" },
      { name: "egg", quantity: "1", unit: "large" },
      { name: "butter", quantity: "2", unit: "tablespoons", notes: "melted" },
      { name: "vanilla extract", quantity: "1", unit: "teaspoon" },
      { name: "blueberries", quantity: "1", unit: "cup", notes: "fresh or frozen" },
      { name: "maple syrup", quantity: "1/4", unit: "cup", notes: "for serving" }
    ],
    steps: [
      { order: 1, instruction: "In a large bowl, whisk together flour, sugar, baking powder, and salt." },
      { order: 2, instruction: "In another bowl, whisk together milk, egg, melted butter, and vanilla extract." },
      { order: 3, instruction: "Pour the wet ingredients into the dry ingredients and stir just until combined. Do not overmix." },
      { order: 4, instruction: "Gently fold in the blueberries." },
      { order: 5, instruction: "Heat a griddle or non-stick pan over medium heat. Lightly grease with butter or cooking spray." },
      { order: 6, instruction: "Pour 1/4 cup of batter onto the griddle for each pancake." },
      { order: 7, instruction: "Cook until bubbles form on the surface, then flip and cook until golden brown on the other side." },
      { order: 8, instruction: "Serve warm with maple syrup." }
    ],
    cookingVessel: "Griddle",
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    difficulty: "Easy",
    mealType: "Breakfast",
    cuisine: "American",
    categories: ["Weekend Breakfast", "Family Favorite"],
    dietaryCategories: ["Vegetarian"],
    tags: ["pancakes", "blueberry", "breakfast", "brunch"],
    imageUrl: "https://images.unsplash.com/photo-1528207776546-365bb710ee93"
  },
  {
    title: "Mediterranean Breakfast Bowl",
    description: "A protein-packed breakfast bowl with Mediterranean flavors featuring eggs, hummus, and fresh vegetables for a nutritious start to your day.",
    ingredients: [
      { name: "eggs", quantity: "2", unit: "large" },
      { name: "hummus", quantity: "1/4", unit: "cup" },
      { name: "cherry tomatoes", quantity: "1/2", unit: "cup", notes: "halved" },
      { name: "cucumber", quantity: "1/4", unit: "medium", notes: "diced" },
      { name: "kalamata olives", quantity: "10", unit: "", notes: "pitted and halved" },
      { name: "feta cheese", quantity: "2", unit: "tablespoons", notes: "crumbled" },
      { name: "olive oil", quantity: "1", unit: "teaspoon" },
      { name: "za'atar spice blend", quantity: "1/2", unit: "teaspoon", notes: "optional" },
      { name: "salt", quantity: "1/4", unit: "teaspoon" },
      { name: "black pepper", quantity: "1/8", unit: "teaspoon" }
    ],
    steps: [
      { order: 1, instruction: "Heat a non-stick pan over medium heat and add a small amount of olive oil." },
      { order: 2, instruction: "Crack eggs into the pan and cook to your preference (poached, fried, or soft-boiled)." },
      { order: 3, instruction: "Spread hummus on the bottom of a serving bowl." },
      { order: 4, instruction: "Arrange tomatoes, cucumber, and olives around the edge of the bowl." },
      { order: 5, instruction: "Place the cooked eggs in the center of the bowl." },
      { order: 6, instruction: "Sprinkle with feta cheese, za'atar (if using), salt, and pepper." },
      { order: 7, instruction: "Drizzle with olive oil and serve immediately." }
    ],
    cookingVessel: "Non-stick Pan",
    prepTime: 10,
    cookTime: 5,
    servings: 1,
    difficulty: "Easy",
    mealType: "Breakfast",
    cuisine: "Mediterranean",
    categories: ["Protein-Rich", "Healthy"],
    dietaryCategories: ["Gluten-Free", "Vegetarian"],
    tags: ["breakfast bowl", "mediterranean", "protein", "healthy"],
    imageUrl: "https://images.unsplash.com/photo-1511690743698-d9d85f2fbf38"
  },
  {
    title: "Overnight Oats with Berries and Nuts",
    description: "A make-ahead breakfast that combines rolled oats, milk, yogurt, and your favorite toppings for a convenient and nutritious morning meal.",
    ingredients: [
      { name: "rolled oats", quantity: "1/2", unit: "cup" },
      { name: "milk", quantity: "1/2", unit: "cup", notes: "dairy or plant-based" },
      { name: "Greek yogurt", quantity: "1/4", unit: "cup", notes: "plain or vanilla" },
      { name: "chia seeds", quantity: "1", unit: "tablespoon" },
      { name: "honey or maple syrup", quantity: "1", unit: "tablespoon" },
      { name: "vanilla extract", quantity: "1/4", unit: "teaspoon" },
      { name: "mixed berries", quantity: "1/4", unit: "cup", notes: "fresh or frozen" },
      { name: "almonds", quantity: "1", unit: "tablespoon", notes: "sliced or chopped" },
      { name: "cinnamon", quantity: "1/8", unit: "teaspoon", notes: "optional" }
    ],
    steps: [
      { order: 1, instruction: "In a mason jar or container with a lid, combine oats, milk, yogurt, chia seeds, honey or maple syrup, and vanilla extract." },
      { order: 2, instruction: "Stir well to combine all ingredients." },
      { order: 3, instruction: "Seal the container and refrigerate overnight or for at least 4 hours." },
      { order: 4, instruction: "In the morning, stir the oat mixture and add more milk if needed to achieve desired consistency." },
      { order: 5, instruction: "Top with mixed berries, almonds, and a sprinkle of cinnamon if desired." },
      { order: 6, instruction: "Enjoy cold or warm briefly in the microwave if preferred." }
    ],
    cookingVessel: "Mixing Bowl",
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    difficulty: "Easy",
    mealType: "Breakfast",
    cuisine: "American",
    categories: ["Make-Ahead", "No-Cook", "Healthy"],
    dietaryCategories: ["Vegetarian"],
    tags: ["oats", "overnight", "meal prep", "healthy breakfast"],
    imageUrl: "https://images.unsplash.com/photo-1456935190777-ae8e018b85b0"
  },
  {
    title: "Spanish Tortilla with Potatoes and Onions",
    description: "A classic Spanish egg dish similar to a frittata, featuring thinly sliced potatoes and onions cooked in olive oil until tender, then combined with beaten eggs and cooked until set.",
    ingredients: [
      { name: "potatoes", quantity: "1", unit: "pound", notes: "waxy variety, peeled and thinly sliced" },
      { name: "onion", quantity: "1", unit: "medium", notes: "thinly sliced" },
      { name: "eggs", quantity: "6", unit: "large" },
      { name: "olive oil", quantity: "1/2", unit: "cup" },
      { name: "salt", quantity: "1", unit: "teaspoon" },
      { name: "black pepper", quantity: "1/4", unit: "teaspoon" },
      { name: "fresh parsley", quantity: "2", unit: "tablespoons", notes: "chopped, for garnish (optional)" }
    ],
    steps: [
      { order: 1, instruction: "Heat olive oil in a large cast iron skillet over medium-low heat." },
      { order: 2, instruction: "Add the sliced potatoes and onions to the skillet, season with half the salt." },
      { order: 3, instruction: "Cook, stirring occasionally, until the potatoes and onions are tender but not browned, about 20 minutes." },
      { order: 4, instruction: "Meanwhile, beat the eggs in a large bowl with the remaining salt and pepper." },
      { order: 5, instruction: "Using a slotted spoon, transfer the cooked potatoes and onions to the bowl with the beaten eggs, leaving most of the oil in the skillet." },
      { order: 6, instruction: "Gently mix the potatoes and onions with the eggs." },
      { order: 7, instruction: "Heat the skillet with the remaining oil over medium heat." },
      { order: 8, instruction: "Pour the egg and potato mixture back into the skillet, spreading it evenly." },
      { order: 9, instruction: "Cook until the bottom is set and golden, about 5-7 minutes." },
      { order: 10, instruction: "Place a large plate over the skillet and carefully flip the tortilla onto the plate." },
      { order: 11, instruction: "Slide the tortilla back into the skillet with the uncooked side down." },
      { order: 12, instruction: "Cook until the bottom is set and golden, about 3-5 minutes more." },
      { order: 13, instruction: "Slide the tortilla onto a serving plate and let it cool slightly." },
      { order: 14, instruction: "Cut into wedges, garnish with parsley if desired, and serve warm or at room temperature." }
    ],
    cookingVessel: "Cast Iron Skillet",
    prepTime: 15,
    cookTime: 35,
    servings: 6,
    difficulty: "Medium",
    mealType: "Breakfast",
    cuisine: "Spanish",
    categories: ["Egg Dishes", "Traditional"],
    dietaryCategories: ["Vegetarian", "Gluten-Free"],
    tags: ["tortilla", "spanish", "potatoes", "eggs"],
    imageUrl: "https://images.unsplash.com/photo-1607118750694-1469a22ef45d"
  },
  {
    title: "Shakshuka with Feta",
    description: "A Middle Eastern breakfast dish featuring eggs poached in a flavorful sauce of tomatoes, peppers, onions, and spices, topped with crumbled feta cheese.",
    ingredients: [
      { name: "olive oil", quantity: "2", unit: "tablespoons" },
      { name: "onion", quantity: "1", unit: "medium", notes: "diced" },
      { name: "red bell pepper", quantity: "1", unit: "medium", notes: "diced" },
      { name: "garlic", quantity: "3", unit: "cloves", notes: "minced" },
      { name: "cumin", quantity: "1", unit: "teaspoon", notes: "ground" },
      { name: "paprika", quantity: "1", unit: "teaspoon" },
      { name: "cayenne pepper", quantity: "1/4", unit: "teaspoon", notes: "adjust to taste" },
      { name: "crushed tomatoes", quantity: "1", unit: "28-ounce can" },
      { name: "salt", quantity: "1", unit: "teaspoon" },
      { name: "black pepper", quantity: "1/2", unit: "teaspoon" },
      { name: "eggs", quantity: "6", unit: "large" },
      { name: "feta cheese", quantity: "1/2", unit: "cup", notes: "crumbled" },
      { name: "fresh parsley", quantity: "2", unit: "tablespoons", notes: "chopped" },
      { name: "fresh cilantro", quantity: "2", unit: "tablespoons", notes: "chopped" },
      { name: "bread", quantity: "4", unit: "slices", notes: "for serving" }
    ],
    steps: [
      { order: 1, instruction: "Heat olive oil in a large cast iron skillet over medium heat." },
      { order: 2, instruction: "Add onion and bell pepper, cook until softened, about 5 minutes." },
      { order: 3, instruction: "Add garlic, cumin, paprika, and cayenne pepper, cook for 1 minute until fragrant." },
      { order: 4, instruction: "Pour in crushed tomatoes, season with salt and pepper, and simmer for 10 minutes until slightly thickened." },
      { order: 5, instruction: "Using a spoon, make 6 indentations in the sauce for the eggs." },
      { order: 6, instruction: "Crack an egg into each indentation." },
      { order: 7, instruction: "Cover the skillet and cook for 5-8 minutes, until egg whites are set but yolks are still runny (or longer if you prefer firmer yolks)." },
      { order: 8, instruction: "Sprinkle crumbled feta cheese over the top." },
      { order: 9, instruction: "Garnish with chopped parsley and cilantro." },
      { order: 10, instruction: "Serve hot directly from the skillet with bread for dipping." }
    ],
    cookingVessel: "Cast Iron Skillet",
    prepTime: 10,
    cookTime: 25,
    servings: 4,
    difficulty: "Medium",
    mealType: "Breakfast",
    cuisine: "Middle Eastern",
    categories: ["Egg Dishes", "One-Pan Meals"],
    dietaryCategories: ["Vegetarian", "Gluten-Free"],
    tags: ["shakshuka", "eggs", "tomato sauce", "middle eastern"],
    imageUrl: "https://images.unsplash.com/photo-1590412200988-a436970781fa"
  },
  {
    title: "Homemade Granola with Nuts and Dried Fruit",
    description: "A crunchy, customizable breakfast staple made with rolled oats, nuts, seeds, and dried fruits, sweetened with honey and maple syrup.",
    ingredients: [
      { name: "rolled oats", quantity: "3", unit: "cups" },
      { name: "almonds", quantity: "1", unit: "cup", notes: "roughly chopped" },
      { name: "pecans", quantity: "1/2", unit: "cup", notes: "roughly chopped" },
      { name: "sunflower seeds", quantity: "1/2", unit: "cup" },
      { name: "pumpkin seeds", quantity: "1/4", unit: "cup" },
      { name: "shredded coconut", quantity: "1/2", unit: "cup", notes: "unsweetened" },
      { name: "cinnamon", quantity: "1", unit: "teaspoon" },
      { name: "salt", quantity: "1/2", unit: "teaspoon" },
      { name: "coconut oil", quantity: "1/3", unit: "cup", notes: "melted" },
      { name: "honey", quantity: "1/4", unit: "cup" },
      { name: "maple syrup", quantity: "1/4", unit: "cup" },
      { name: "vanilla extract", quantity: "1", unit: "teaspoon" },
      { name: "dried cranberries", quantity: "1/2", unit: "cup" },
      { name: "dried apricots", quantity: "1/2", unit: "cup", notes: "chopped" },
      { name: "dried cherries", quantity: "1/4", unit: "cup" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 300°F (150°C) and line a large baking sheet with parchment paper." },
      { order: 2, instruction: "In a large bowl, combine rolled oats, almonds, pecans, sunflower seeds, pumpkin seeds, coconut, cinnamon, and salt." },
      { order: 3, instruction: "In a separate bowl, whisk together melted coconut oil, honey, maple syrup, and vanilla extract." },
      { order: 4, instruction: "Pour the wet ingredients over the dry ingredients and stir until everything is well coated." },
      { order: 5, instruction: "Spread the mixture evenly on the prepared baking sheet." },
      { order: 6, instruction: "Bake for 40-45 minutes, stirring every 15 minutes, until the granola is golden brown." },
      { order: 7, instruction: "Remove from the oven and let cool completely without stirring (this helps form clusters)." },
      { order: 8, instruction: "Once cooled, add the dried cranberries, apricots, and cherries, and mix gently." },
      { order: 9, instruction: "Store in an airtight container at room temperature for up to 2 weeks." }
    ],
    cookingVessel: "Baking Sheet",
    prepTime: 15,
    cookTime: 45,
    servings: 12,
    difficulty: "Easy",
    mealType: "Breakfast",
    cuisine: "American",
    categories: ["Make-Ahead", "Batch Cooking"],
    dietaryCategories: ["Vegetarian", "Dairy-Free"],
    tags: ["granola", "oats", "nuts", "dried fruit", "homemade"],
    imageUrl: "https://images.unsplash.com/photo-1517093157656-b9eccef91cb1"
  },
  {
    title: "Breakfast Burrito with Scrambled Eggs and Avocado",
    description: "A hearty, portable breakfast featuring scrambled eggs, black beans, cheese, and avocado wrapped in a warm tortilla, perfect for busy mornings.",
    ingredients: [
      { name: "large flour tortillas", quantity: "4", unit: "10-inch" },
      { name: "eggs", quantity: "8", unit: "large" },
      { name: "milk", quantity: "2", unit: "tablespoons" },
      { name: "salt", quantity: "1/2", unit: "teaspoon" },
      { name: "black pepper", quantity: "1/4", unit: "teaspoon" },
      { name: "olive oil", quantity: "1", unit: "tablespoon" },
      { name: "black beans", quantity: "1", unit: "15-ounce can", notes: "drained and rinsed" },
      { name: "cheddar cheese", quantity: "1", unit: "cup", notes: "shredded" },
      { name: "avocado", quantity: "1", unit: "large", notes: "sliced" },
      { name: "salsa", quantity: "1/2", unit: "cup" },
      { name: "green onions", quantity: "4", unit: "", notes: "sliced" },
      { name: "fresh cilantro", quantity: "1/4", unit: "cup", notes: "chopped" },
      { name: "hot sauce", quantity: "to taste", unit: "", notes: "optional" }
    ],
    steps: [
      { order: 1, instruction: "In a bowl, whisk together eggs, milk, salt, and pepper until well combined." },
      { order: 2, instruction: "Heat olive oil in a non-stick skillet over medium heat." },
      { order: 3, instruction: "Pour in the egg mixture and cook, stirring occasionally, until eggs are scrambled and just set, about 3-4 minutes." },
      { order: 4, instruction: "Warm the black beans in a small saucepan over low heat or in the microwave." },
      { order: 5, instruction: "Warm the tortillas in a dry skillet or in the microwave for 10-15 seconds each." },
      { order: 6, instruction: "To assemble each burrito, place a tortilla on a flat surface and layer with 1/4 of the scrambled eggs, black beans, cheese, avocado slices, salsa, green onions, and cilantro." },
      { order: 7, instruction: "Add hot sauce if desired." },
      { order: 8, instruction: "Fold in the sides of the tortilla, then roll up tightly from the bottom." },
      { order: 9, instruction: "If desired, return the assembled burrito to the skillet and cook for 1-2 minutes per side until golden and crisp." },
      { order: 10, instruction: "Serve immediately or wrap in foil to take on the go." }
    ],
    cookingVessel: "Non-stick Pan",
    prepTime: 15,
    cookTime: 10,
    servings: 4,
    difficulty: "Easy",
    mealType: "Breakfast",
    cuisine: "Mexican",
    categories: ["Portable", "Protein-Rich"],
    dietaryCategories: ["Vegetarian"],
    tags: ["burrito", "eggs", "avocado", "breakfast", "mexican"],
    imageUrl: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f"
  },
  {
    title: "Belgian Waffles with Fresh Berries",
    description: "Light and crispy on the outside, tender on the inside Belgian waffles topped with fresh berries and a dusting of powdered sugar.",
    ingredients: [
      { name: "all-purpose flour", quantity: "2", unit: "cups" },
      { name: "sugar", quantity: "3", unit: "tablespoons" },
      { name: "baking powder", quantity: "1", unit: "tablespoon" },
      { name: "baking soda", quantity: "1/2", unit: "teaspoon" },
      { name: "salt", quantity: "1/4", unit: "teaspoon" },
      { name: "eggs", quantity: "2", unit: "large", notes: "separated" },
      { name: "buttermilk", quantity: "2", unit: "cups" },
      { name: "unsalted butter", quantity: "1/3", unit: "cup", notes: "melted" },
      { name: "vanilla extract", quantity: "1", unit: "teaspoon" },
      { name: "mixed berries", quantity: "2", unit: "cups", notes: "strawberries, blueberries, raspberries" },
      { name: "maple syrup", quantity: "1/2", unit: "cup", notes: "for serving" },
      { name: "powdered sugar", quantity: "2", unit: "tablespoons", notes: "for dusting" },
      { name: "whipped cream", quantity: "1/2", unit: "cup", notes: "optional, for serving" }
    ],
    steps: [
      { order: 1, instruction: "Preheat your waffle iron according to manufacturer's instructions." },
      { order: 2, instruction: "In a large bowl, whisk together flour, sugar, baking powder, baking soda, and salt." },
      { order: 3, instruction: "In another bowl, whisk egg yolks, then add buttermilk, melted butter, and vanilla extract." },
      { order: 4, instruction: "Pour the wet ingredients into the dry ingredients and mix just until combined." },
      { order: 5, instruction: "In a separate bowl, beat egg whites until stiff peaks form." },
      { order: 6, instruction: "Gently fold the beaten egg whites into the batter." },
      { order: 7, instruction: "Lightly grease the waffle iron with cooking spray." },
      { order: 8, instruction: "Pour the appropriate amount of batter onto the hot waffle iron (usually about 1/2 to 3/4 cup, depending on your waffle iron size)." },
      { order: 9, instruction: "Close the lid and cook until the waffle is golden brown and crisp, about 3-5 minutes." },
      { order: 10, instruction: "Remove waffle and repeat with remaining batter." },
      { order: 11, instruction: "Serve waffles topped with fresh berries, a dusting of powdered sugar, and maple syrup." },
      { order: 12, instruction: "Add a dollop of whipped cream if desired." }
    ],
    cookingVessel: "Waffle Iron",
    prepTime: 15,
    cookTime: 20,
    servings: 6,
    difficulty: "Medium",
    mealType: "Breakfast",
    cuisine: "Belgian",
    categories: ["Weekend Breakfast", "Special Occasion"],
    dietaryCategories: ["Vegetarian"],
    tags: ["waffles", "berries", "belgian", "breakfast", "brunch"],
    imageUrl: "https://images.unsplash.com/photo-1562376552-0d160a2f35b6"
  },
  {
    title: "Savory Breakfast Quinoa Bowl",
    description: "A protein-packed alternative to oatmeal, this savory quinoa bowl is topped with a fried egg, avocado, and roasted vegetables for a nutritious start to your day.",
    ingredients: [
      { name: "quinoa", quantity: "1", unit: "cup", notes: "rinsed" },
      { name: "water", quantity: "2", unit: "cups" },
      { name: "salt", quantity: "1/2", unit: "teaspoon", notes: "divided" },
      { name: "olive oil", quantity: "2", unit: "tablespoons", notes: "divided" },
      { name: "cherry tomatoes", quantity: "1", unit: "cup", notes: "halved" },
      { name: "bell pepper", quantity: "1", unit: "medium", notes: "diced" },
      { name: "eggs", quantity: "4", unit: "large" },
      { name: "avocado", quantity: "1", unit: "medium", notes: "sliced" },
      { name: "green onions", quantity: "3", unit: "", notes: "sliced" },
      { name: "feta cheese", quantity: "1/4", unit: "cup", notes: "crumbled" },
      { name: "black pepper", quantity: "1/4", unit: "teaspoon" },
      { name: "hot sauce", quantity: "to taste", unit: "", notes: "optional" }
    ],
    steps: [
      { order: 1, instruction: "In a medium saucepan, combine quinoa, water, and 1/4 teaspoon salt. Bring to a boil, then reduce heat to low, cover, and simmer for 15 minutes until water is absorbed." },
      { order: 2, instruction: "Remove from heat and let stand, covered, for 5 minutes, then fluff with a fork." },
      { order: 3, instruction: "While quinoa is cooking, heat 1 tablespoon olive oil in a skillet over medium-high heat." },
      { order: 4, instruction: "Add cherry tomatoes and bell pepper, season with a pinch of salt, and cook until slightly softened, about 5 minutes. Remove to a plate." },
      { order: 5, instruction: "In the same skillet, heat the remaining 1 tablespoon olive oil over medium heat." },
      { order: 6, instruction: "Crack eggs into the skillet and cook to your preference (sunny-side up, over easy, etc.)." },
      { order: 7, instruction: "To assemble each bowl, place 1/4 of the cooked quinoa in a bowl." },
      { order: 8, instruction: "Top with 1/4 of the roasted vegetables, a fried egg, avocado slices, green onions, and crumbled feta." },
      { order: 9, instruction: "Season with remaining salt, black pepper, and hot sauce if desired." },
      { order: 10, instruction: "Serve immediately while warm." }
    ],
    cookingVessel: "Skillet",
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    difficulty: "Easy",
    mealType: "Breakfast",
    cuisine: "American",
    categories: ["Grain Bowls", "Healthy", "Protein-Rich"],
    dietaryCategories: ["Vegetarian", "Gluten-Free"],
    tags: ["quinoa", "breakfast bowl", "savory breakfast", "healthy"],
    imageUrl: "https://images.unsplash.com/photo-1546548970-71785318a17b"
  },
  {
    title: "Slow Cooker Apple Cinnamon Oatmeal",
    description: "Wake up to the comforting aroma of this overnight apple cinnamon oatmeal that cooks while you sleep, featuring tender steel-cut oats, sweet apples, and warm spices.",
    ingredients: [
      { name: "steel-cut oats", quantity: "1 1/2", unit: "cups" },
      { name: "apples", quantity: "2", unit: "medium", notes: "peeled, cored, and diced" },
      { name: "water", quantity: "4", unit: "cups" },
      { name: "milk", quantity: "2", unit: "cups", notes: "dairy or plant-based" },
      { name: "brown sugar", quantity: "1/4", unit: "cup", notes: "packed" },
      { name: "cinnamon", quantity: "2", unit: "teaspoons" },
      { name: "nutmeg", quantity: "1/4", unit: "teaspoon" },
      { name: "salt", quantity: "1/2", unit: "teaspoon" },
      { name: "vanilla extract", quantity: "1", unit: "tablespoon" },
      { name: "butter", quantity: "2", unit: "tablespoons", notes: "cut into small pieces" },
      { name: "chopped nuts", quantity: "1/2", unit: "cup", notes: "walnuts or pecans, for serving" },
      { name: "maple syrup", quantity: "to taste", unit: "", notes: "for serving" }
    ],
    steps: [
      { order: 1, instruction: "Grease the inside of a 4-6 quart slow cooker with butter or cooking spray." },
      { order: 2, instruction: "Add steel-cut oats, diced apples, water, milk, brown sugar, cinnamon, nutmeg, and salt to the slow cooker and stir to combine." },
      { order: 3, instruction: "Dot the top with small pieces of butter." },
      { order: 4, instruction: "Cover and cook on low for 7-8 hours (overnight)." },
      { order: 5, instruction: "In the morning, stir in vanilla extract." },
      { order: 6, instruction: "Serve hot, topped with chopped nuts and a drizzle of maple syrup if desired." },
      { order: 7, instruction: "Store leftovers in the refrigerator for up to 5 days. Add a splash of milk when reheating." }
    ],
    cookingVessel: "Slow Cooker",
    prepTime: 10,
    cookTime: 480,
    servings: 6,
    difficulty: "Easy",
    mealType: "Breakfast",
    cuisine: "American",
    categories: ["Overnight", "Make-Ahead"],
    dietaryCategories: ["Vegetarian"],
    tags: ["oatmeal", "slow cooker", "apple", "cinnamon", "overnight"],
    imageUrl: "https://images.unsplash.com/photo-1517673132405-a56a62b18caf"
  },
  {
    title: "Smoked Salmon and Cream Cheese Bagels",
    description: "A classic breakfast or brunch option featuring toasted bagels topped with cream cheese, smoked salmon, capers, and red onion for a delicious savory meal.",
    ingredients: [
      { name: "bagels", quantity: "4", unit: "", notes: "plain, everything, or sesame" },
      { name: "cream cheese", quantity: "8", unit: "ounces", notes: "softened" },
      { name: "smoked salmon", quantity: "8", unit: "ounces", notes: "thinly sliced" },
      { name: "red onion", quantity: "1/2", unit: "small", notes: "thinly sliced" },
      { name: "capers", quantity: "2", unit: "tablespoons", notes: "drained" },
      { name: "fresh dill", quantity: "2", unit: "tablespoons", notes: "chopped" },
      { name: "lemon", quantity: "1", unit: "", notes: "cut into wedges" },
      { name: "black pepper", quantity: "to taste", unit: "" },
      { name: "cucumber", quantity: "1/2", unit: "medium", notes: "thinly sliced, optional" },
      { name: "tomato", quantity: "1", unit: "medium", notes: "thinly sliced, optional" }
    ],
    steps: [
      { order: 1, instruction: "Slice the bagels in half horizontally and toast them to desired doneness." },
      { order: 2, instruction: "Spread a generous layer of cream cheese on each bagel half." },
      { order: 3, instruction: "Arrange smoked salmon slices over the cream cheese." },
      { order: 4, instruction: "Top with thinly sliced red onion, cucumber, and tomato (if using)." },
      { order: 5, instruction: "Sprinkle with capers and fresh dill." },
      { order: 6, instruction: "Season with freshly ground black pepper to taste." },
      { order: 7, instruction: "Serve with lemon wedges on the side for squeezing over the top." }
    ],
    cookingVessel: "Toaster",
    prepTime: 10,
    cookTime: 2,
    servings: 4,
    difficulty: "Easy",
    mealType: "Breakfast",
    cuisine: "American",
    categories: ["Quick & Easy", "Brunch"],
    dietaryCategories: [],
    tags: ["bagel", "smoked salmon", "cream cheese", "brunch"],
    imageUrl: "https://images.unsplash.com/photo-1485963631004-f2f00b1d6606"
  },
  {
    title: "Sweet Potato and Black Bean Breakfast Hash",
    description: "A hearty, savory breakfast hash featuring sweet potatoes, black beans, peppers, and eggs for a nutritious and filling start to your day.",
    ingredients: [
      { name: "sweet potatoes", quantity: "2", unit: "medium", notes: "peeled and diced into 1/2-inch cubes" },
      { name: "olive oil", quantity: "3", unit: "tablespoons", notes: "divided" },
      { name: "onion", quantity: "1", unit: "medium", notes: "diced" },
      { name: "red bell pepper", quantity: "1", unit: "medium", notes: "diced" },
      { name: "garlic", quantity: "3", unit: "cloves", notes: "minced" },
      { name: "black beans", quantity: "1", unit: "15-ounce can", notes: "drained and rinsed" },
      { name: "cumin", quantity: "1", unit: "teaspoon" },
      { name: "smoked paprika", quantity: "1", unit: "teaspoon" },
      { name: "chili powder", quantity: "1/2", unit: "teaspoon" },
      { name: "salt", quantity: "1", unit: "teaspoon", notes: "divided" },
      { name: "black pepper", quantity: "1/2", unit: "teaspoon" },
      { name: "eggs", quantity: "4", unit: "large" },
      { name: "avocado", quantity: "1", unit: "medium", notes: "sliced" },
      { name: "fresh cilantro", quantity: "1/4", unit: "cup", notes: "chopped" },
      { name: "hot sauce", quantity: "to taste", unit: "", notes: "optional" }
    ],
    steps: [
      { order: 1, instruction: "Heat 2 tablespoons olive oil in a large cast iron skillet over medium-high heat." },
      { order: 2, instruction: "Add diced sweet potatoes and 1/2 teaspoon salt. Cook, stirring occasionally, until they begin to soften, about 5-7 minutes." },
      { order: 3, instruction: "Add onion and bell pepper to the skillet. Cook for another 5 minutes until vegetables are softened." },
      { order: 4, instruction: "Add garlic, cumin, smoked paprika, and chili powder. Cook for 1 minute until fragrant." },
      { order: 5, instruction: "Stir in black beans and cook until heated through, about 2 minutes." },
      { order: 6, instruction: "Season with remaining salt and black pepper." },
      { order: 7, instruction: "Using a spoon, create 4 wells in the hash mixture." },
      { order: 8, instruction: "Drizzle the remaining 1 tablespoon olive oil into the wells." },
      { order: 9, instruction: "Crack an egg into each well." },
      { order: 10, instruction: "Cover the skillet and cook until egg whites are set but yolks are still runny, about 4-5 minutes." },
      { order: 11, instruction: "Remove from heat and top with sliced avocado and chopped cilantro." },
      { order: 12, instruction: "Serve hot with hot sauce on the side if desired." }
    ],
    cookingVessel: "Cast Iron Skillet",
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    difficulty: "Medium",
    mealType: "Breakfast",
    cuisine: "Mexican",
    categories: ["One-Pan Meals", "Protein-Rich"],
    dietaryCategories: ["Vegetarian", "Gluten-Free"],
    tags: ["hash", "sweet potato", "black beans", "eggs", "breakfast"],
    imageUrl: "https://images.unsplash.com/photo-1525351484163-7529414344d8"
  },
  {
    title: "Coconut Chia Seed Pudding",
    description: "A creamy, dairy-free breakfast pudding made with chia seeds, coconut milk, and maple syrup, topped with fresh fruit and toasted coconut flakes.",
    ingredients: [
      { name: "chia seeds", quantity: "1/2", unit: "cup" },
      { name: "coconut milk", quantity: "1 1/2", unit: "cups", notes: "canned, full-fat" },
      { name: "maple syrup", quantity: "2", unit: "tablespoons" },
      { name: "vanilla extract", quantity: "1", unit: "teaspoon" },
      { name: "salt", quantity: "1/8", unit: "teaspoon" },
      { name: "mango", quantity: "1", unit: "medium", notes: "diced" },
      { name: "kiwi", quantity: "2", unit: "", notes: "peeled and sliced" },
      { name: "coconut flakes", quantity: "1/4", unit: "cup", notes: "toasted" },
      { name: "fresh mint leaves", quantity: "for garnish", unit: "", notes: "optional" }
    ],
    steps: [
      { order: 1, instruction: "In a medium bowl, whisk together chia seeds, coconut milk, maple syrup, vanilla extract, and salt." },
      { order: 2, instruction: "Cover and refrigerate for at least 4 hours or overnight, stirring once after about 30 minutes to prevent clumping." },
      { order: 3, instruction: "To toast coconut flakes, spread them on a baking sheet and bake at 325°F (165°C) for 5-7 minutes until golden, watching carefully to prevent burning." },
      { order: 4, instruction: "When ready to serve, stir the pudding well. If it's too thick, add a splash more coconut milk." },
      { order: 5, instruction: "Divide the pudding between serving bowls." },
      { order: 6, instruction: "Top with diced mango, sliced kiwi, and toasted coconut flakes." },
      { order: 7, instruction: "Garnish with fresh mint leaves if desired." },
      { order: 8, instruction: "Serve chilled." }
    ],
    cookingVessel: "Mixing Bowl",
    prepTime: 10,
    cookTime: 0,
    servings: 4,
    difficulty: "Easy",
    mealType: "Breakfast",
    cuisine: "American",
    categories: ["Make-Ahead", "No-Cook"],
    dietaryCategories: ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free"],
    tags: ["chia pudding", "coconut", "make-ahead", "healthy breakfast"],
    imageUrl: "https://images.unsplash.com/photo-1490323948794-cc6dde6e8f5b"
  },
  {
    title: "Breakfast Frittata with Spinach and Feta",
    description: "A versatile egg dish packed with spinach, feta cheese, and herbs that can be served hot or at room temperature for a protein-rich breakfast.",
    ingredients: [
      { name: "eggs", quantity: "10", unit: "large" },
      { name: "milk", quantity: "1/4", unit: "cup" },
      { name: "salt", quantity: "1", unit: "teaspoon" },
      { name: "black pepper", quantity: "1/2", unit: "teaspoon" },
      { name: "olive oil", quantity: "2", unit: "tablespoons" },
      { name: "onion", quantity: "1", unit: "medium", notes: "diced" },
      { name: "garlic", quantity: "2", unit: "cloves", notes: "minced" },
      { name: "fresh spinach", quantity: "6", unit: "cups", notes: "roughly chopped" },
      { name: "cherry tomatoes", quantity: "1", unit: "cup", notes: "halved" },
      { name: "feta cheese", quantity: "1", unit: "cup", notes: "crumbled" },
      { name: "fresh dill", quantity: "2", unit: "tablespoons", notes: "chopped" },
      { name: "fresh parsley", quantity: "2", unit: "tablespoons", notes: "chopped" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 375°F (190°C)." },
      { order: 2, instruction: "In a large bowl, whisk together eggs, milk, 1/2 teaspoon salt, and 1/4 teaspoon pepper until well combined." },
      { order: 3, instruction: "Heat olive oil in a 10-inch oven-safe skillet over medium heat." },
      { order: 4, instruction: "Add onion and cook until softened, about 5 minutes." },
      { order: 5, instruction: "Add garlic and cook for 30 seconds until fragrant." },
      { order: 6, instruction: "Add spinach in batches, stirring until wilted, about 2-3 minutes." },
      { order: 7, instruction: "Season with remaining salt and pepper." },
      { order: 8, instruction: "Spread the vegetables evenly in the skillet and sprinkle with halved cherry tomatoes." },
      { order: 9, instruction: "Pour the egg mixture over the vegetables." },
      { order: 10, instruction: "Sprinkle crumbled feta cheese, dill, and parsley over the top." },
      { order: 11, instruction: "Cook on the stovetop for 2-3 minutes until the edges start to set." },
      { order: 12, instruction: "Transfer the skillet to the preheated oven and bake for 15-20 minutes until the eggs are set and the top is lightly golden." },
      { order: 13, instruction: "Let cool for 5 minutes before slicing into wedges." },
      { order: 14, instruction: "Serve warm or at room temperature." }
    ],
    cookingVessel: "Oven-Safe Skillet",
    prepTime: 15,
    cookTime: 25,
    servings: 6,
    difficulty: "Medium",
    mealType: "Breakfast",
    cuisine: "Mediterranean",
    categories: ["Egg Dishes", "Make-Ahead"],
    dietaryCategories: ["Vegetarian", "Gluten-Free", "Low-Carb"],
    tags: ["frittata", "eggs", "spinach", "feta", "breakfast"],
    imageUrl: "https://images.unsplash.com/photo-1623428187969-5da2dcea5ebf"
  },
  {
    title: "Breakfast Smoothie Bowl with Granola and Berries",
    description: "A thick, creamy smoothie served in a bowl and topped with granola, fresh fruit, and other nutritious toppings for a refreshing breakfast.",
    ingredients: [
      { name: "frozen banana", quantity: "1", unit: "large", notes: "sliced" },
      { name: "frozen mixed berries", quantity: "1", unit: "cup" },
      { name: "Greek yogurt", quantity: "1/2", unit: "cup", notes: "plain or vanilla" },
      { name: "milk", quantity: "1/4", unit: "cup", notes: "dairy or plant-based" },
      { name: "honey", quantity: "1", unit: "tablespoon", notes: "or maple syrup" },
      { name: "granola", quantity: "1/4", unit: "cup" },
      { name: "fresh strawberries", quantity: "1/4", unit: "cup", notes: "sliced" },
      { name: "fresh blueberries", quantity: "1/4", unit: "cup" },
      { name: "banana", quantity: "1/2", unit: "", notes: "sliced" },
      { name: "chia seeds", quantity: "1", unit: "teaspoon" },
      { name: "hemp seeds", quantity: "1", unit: "teaspoon" },
      { name: "almond butter", quantity: "1", unit: "tablespoon", notes: "optional" }
    ],
    steps: [
      { order: 1, instruction: "In a blender, combine frozen banana, frozen mixed berries, Greek yogurt, milk, and honey or maple syrup." },
      { order: 2, instruction: "Blend until smooth and creamy. The mixture should be thicker than a regular smoothie." },
      { order: 3, instruction: "If the mixture is too thick, add a little more milk. If it's too thin, add more frozen fruit." },
      { order: 4, instruction: "Pour the smoothie into a bowl." },
      { order: 5, instruction: "Top with granola, fresh strawberries, blueberries, and banana slices." },
      { order: 6, instruction: "Sprinkle with chia seeds and hemp seeds." },
      { order: 7, instruction: "Drizzle with almond butter if using." },
      { order: 8, instruction: "Serve immediately with a spoon." }
    ],
    cookingVessel: "Blender",
    prepTime: 10,
    cookTime: 0,
    servings: 1,
    difficulty: "Easy",
    mealType: "Breakfast",
    cuisine: "American",
    categories: ["Smoothie Bowls", "Healthy", "Quick & Easy"],
    dietaryCategories: ["Vegetarian", "Gluten-Free"],
    tags: ["smoothie bowl", "berries", "healthy breakfast", "fruit"],
    imageUrl: "https://images.unsplash.com/photo-1511690656952-34342bb7c2f2"
  },
  {
    title: "Breakfast Quesadillas with Scrambled Eggs and Cheese",
    description: "A quick and satisfying breakfast featuring flour tortillas filled with scrambled eggs, cheese, and your choice of fillings, then pan-fried until crispy and golden.",
    ingredients: [
      { name: "large flour tortillas", quantity: "4", unit: "8-inch" },
      { name: "eggs", quantity: "6", unit: "large" },
      { name: "milk", quantity: "2", unit: "tablespoons" },
      { name: "salt", quantity: "1/2", unit: "teaspoon" },
      { name: "black pepper", quantity: "1/4", unit: "teaspoon" },
      { name: "butter", quantity: "2", unit: "tablespoons", notes: "divided" },
      { name: "cheddar cheese", quantity: "1", unit: "cup", notes: "shredded" },
      { name: "monterey jack cheese", quantity: "1", unit: "cup", notes: "shredded" },
      { name: "green onions", quantity: "3", unit: "", notes: "sliced" },
      { name: "bell pepper", quantity: "1/2", unit: "medium", notes: "diced" },
      { name: "salsa", quantity: "1/2", unit: "cup", notes: "for serving" },
      { name: "sour cream", quantity: "1/4", unit: "cup", notes: "for serving" },
      { name: "avocado", quantity: "1", unit: "medium", notes: "sliced, for serving" }
    ],
    steps: [
      { order: 1, instruction: "In a bowl, whisk together eggs, milk, salt, and pepper until well combined." },
      { order: 2, instruction: "Heat 1 tablespoon butter in a non-stick skillet over medium heat." },
      { order: 3, instruction: "Add diced bell pepper and cook for 2-3 minutes until slightly softened." },
      { order: 4, instruction: "Pour in the egg mixture and cook, stirring occasionally, until eggs are scrambled and just set, about 3-4 minutes." },
      { order: 5, instruction: "Remove eggs from skillet and set aside." },
      { order: 6, instruction: "Wipe the skillet clean and return to medium heat." },
      { order: 7, instruction: "To assemble each quesadilla, place a tortilla on a flat surface." },
      { order: 8, instruction: "Sprinkle 1/4 of the cheddar cheese on half of the tortilla." },
      { order: 9, instruction: "Top with 1/4 of the scrambled eggs, green onions, and 1/4 of the monterey jack cheese." },
      { order: 10, instruction: "Fold the tortilla in half to cover the filling." },
      { order: 11, instruction: "Melt 1/4 tablespoon butter in the skillet." },
      { order: 12, instruction: "Place the assembled quesadilla in the skillet and cook for 2-3 minutes per side until golden brown and crispy, and the cheese is melted." },
      { order: 13, instruction: "Repeat with remaining tortillas and fillings, adding more butter to the skillet as needed." },
      { order: 14, instruction: "Cut each quesadilla into wedges and serve with salsa, sour cream, and avocado slices." }
    ],
    cookingVessel: "Non-stick Pan",
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    difficulty: "Easy",
    mealType: "Breakfast",
    cuisine: "Mexican",
    categories: ["Quick & Easy", "Kid-Friendly"],
    dietaryCategories: ["Vegetarian"],
    tags: ["quesadilla", "eggs", "cheese", "breakfast", "mexican"],
    imageUrl: "https://images.unsplash.com/photo-1525351326368-efbb5cb6814d"
  },
  {
    title: "Breakfast Stuffed Bell Peppers",
    description: "Colorful bell peppers stuffed with a savory mixture of eggs, cheese, and breakfast sausage, then baked until tender for a protein-packed morning meal.",
    ingredients: [
      { name: "bell peppers", quantity: "4", unit: "large", notes: "any color" },
      { name: "breakfast sausage", quantity: "1/2", unit: "pound", notes: "casings removed" },
      { name: "onion", quantity: "1/2", unit: "medium", notes: "diced" },
      { name: "mushrooms", quantity: "1", unit: "cup", notes: "sliced" },
      { name: "spinach", quantity: "2", unit: "cups", notes: "fresh, roughly chopped" },
      { name: "eggs", quantity: "8", unit: "large" },
      { name: "milk", quantity: "1/4", unit: "cup" },
      { name: "cheddar cheese", quantity: "1", unit: "cup", notes: "shredded, divided" },
      { name: "salt", quantity: "1", unit: "teaspoon" },
      { name: "black pepper", quantity: "1/2", unit: "teaspoon" },
      { name: "garlic powder", quantity: "1/2", unit: "teaspoon" },
      { name: "fresh chives", quantity: "2", unit: "tablespoons", notes: "chopped, for garnish" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 375°F (190°C)." },
      { order: 2, instruction: "Cut the tops off the bell peppers and remove the seeds and membranes." },
      { order: 3, instruction: "Place the peppers cut-side up in a baking dish. If they don't stand upright, slice a small piece off the bottom to create a flat surface." },
      { order: 4, instruction: "In a large skillet over medium heat, cook the breakfast sausage, breaking it up with a spoon, until browned, about 5 minutes." },
      { order: 5, instruction: "Add diced onion and mushrooms to the skillet and cook until softened, about 3-4 minutes." },
      { order: 6, instruction: "Add spinach and cook until wilted, about 1-2 minutes." },
      { order: 7, instruction: "Remove from heat and let cool slightly." },
      { order: 8, instruction: "In a large bowl, whisk together eggs, milk, 1/2 cup of cheddar cheese, salt, pepper, and garlic powder." },
      { order: 9, instruction: "Stir in the sausage and vegetable mixture." },
      { order: 10, instruction: "Divide the egg mixture evenly among the bell peppers." },
      { order: 11, instruction: "Sprinkle the remaining 1/2 cup of cheddar cheese on top of the filled peppers." },
      { order: 12, instruction: "Cover the baking dish with foil and bake for 35 minutes." },
      { order: 13, instruction: "Remove foil and bake for an additional 10-15 minutes until the eggs are set and the cheese is golden." },
      { order: 14, instruction: "Garnish with chopped chives before serving." }
    ],
    cookingVessel: "Baking Dish",
    prepTime: 20,
    cookTime: 50,
    servings: 4,
    difficulty: "Medium",
    mealType: "Breakfast",
    cuisine: "American",
    categories: ["Protein-Rich", "Make-Ahead"],
    dietaryCategories: ["Gluten-Free", "Low-Carb"],
    tags: ["stuffed peppers", "eggs", "breakfast", "protein"],
    imageUrl: "https://images.unsplash.com/photo-1606756790138-261d2b21cd75"
  },
  {
    title: "Breakfast Tacos with Chorizo and Potatoes",
    description: "Flavorful breakfast tacos featuring spicy chorizo, crispy potatoes, scrambled eggs, and fresh toppings wrapped in warm corn tortillas.",
    ingredients: [
      { name: "chorizo", quantity: "1/2", unit: "pound", notes: "casings removed" },
      { name: "russet potatoes", quantity: "2", unit: "medium", notes: "peeled and diced into 1/2-inch cubes" },
      { name: "onion", quantity: "1/2", unit: "medium", notes: "diced" },
      { name: "jalapeño", quantity: "1", unit: "small", notes: "seeded and minced" },
      { name: "garlic", quantity: "2", unit: "cloves", notes: "minced" },
      { name: "eggs", quantity: "6", unit: "large" },
      { name: "milk", quantity: "2", unit: "tablespoons" },
      { name: "salt", quantity: "1/2", unit: "teaspoon" },
      { name: "black pepper", quantity: "1/4", unit: "teaspoon" },
      { name: "corn tortillas", quantity: "8", unit: "6-inch" },
      { name: "cilantro", quantity: "1/4", unit: "cup", notes: "chopped" },
      { name: "avocado", quantity: "1", unit: "medium", notes: "sliced" },
      { name: "lime", quantity: "1", unit: "", notes: "cut into wedges" },
      { name: "salsa", quantity: "1/2", unit: "cup", notes: "for serving" },
      { name: "queso fresco", quantity: "1/2", unit: "cup", notes: "crumbled, for serving" }
    ],
    steps: [
      { order: 1, instruction: "Heat a large skillet over medium-high heat." },
      { order: 2, instruction: "Add chorizo and cook, breaking it up with a spoon, until browned, about 5 minutes." },
      { order: 3, instruction: "Remove chorizo to a plate, leaving the rendered fat in the skillet." },
      { order: 4, instruction: "Add diced potatoes to the skillet and cook, stirring occasionally, until crispy and golden, about 10-12 minutes." },
      { order: 5, instruction: "Add onion and jalapeño to the potatoes and cook for 3-4 minutes until softened." },
      { order: 6, instruction: "Add garlic and cook for 30 seconds until fragrant." },
      { order: 7, instruction: "Return chorizo to the skillet and mix with the potato mixture." },
      { order: 8, instruction: "In a bowl, whisk together eggs, milk, salt, and pepper." },
      { order: 9, instruction: "Reduce heat to medium-low and pour the egg mixture into the skillet." },
      { order: 10, instruction: "Cook, stirring gently, until eggs are just set, about 2-3 minutes." },
      { order: 11, instruction: "Warm the corn tortillas in a dry skillet or directly over a gas flame for about 10-15 seconds per side." },
      { order: 12, instruction: "To assemble, place a spoonful of the chorizo-potato-egg mixture on each tortilla." },
      { order: 13, instruction: "Top with cilantro, avocado slices, a squeeze of lime, salsa, and crumbled queso fresco." },
      { order: 14, instruction: "Serve immediately with additional lime wedges on the side." }
    ],
    cookingVessel: "Skillet",
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    difficulty: "Medium",
    mealType: "Breakfast",
    cuisine: "Mexican",
    categories: ["Tacos", "Protein-Rich"],
    dietaryCategories: ["Gluten-Free"],
    tags: ["tacos", "chorizo", "potatoes", "breakfast", "mexican"],
    imageUrl: "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b"
  },
  {
    title: "Breakfast Grain Bowl with Soft-Boiled Egg",
    description: "A nutritious breakfast bowl featuring a base of cooked grains topped with a soft-boiled egg, roasted vegetables, avocado, and a flavorful sauce.",
    ingredients: [
      { name: "farro", quantity: "1", unit: "cup", notes: "or quinoa, brown rice, or other grain" },
      { name: "water", quantity: "2 1/2", unit: "cups", notes: "or as needed for grain" },
      { name: "salt", quantity: "1", unit: "teaspoon", notes: "divided" },
      { name: "sweet potato", quantity: "1", unit: "medium", notes: "peeled and diced" },
      { name: "broccoli florets", quantity: "2", unit: "cups" },
      { name: "olive oil", quantity: "2", unit: "tablespoons", notes: "divided" },
      { name: "eggs", quantity: "4", unit: "large" },
      { name: "avocado", quantity: "1", unit: "medium", notes: "sliced" },
      { name: "tahini", quantity: "2", unit: "tablespoons" },
      { name: "lemon juice", quantity: "1", unit: "tablespoon" },
      { name: "water", quantity: "1", unit: "tablespoon", notes: "for sauce" },
      { name: "garlic", quantity: "1", unit: "clove", notes: "minced" },
      { name: "microgreens", quantity: "1", unit: "cup", notes: "optional" },
      { name: "sesame seeds", quantity: "1", unit: "tablespoon", notes: "for garnish" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 425°F (220°C)." },
      { order: 2, instruction: "Cook farro (or chosen grain) according to package instructions with 1/2 teaspoon salt. Once cooked, fluff with a fork and set aside." },
      { order: 3, instruction: "On a baking sheet, toss sweet potato and broccoli with 1 tablespoon olive oil and 1/4 teaspoon salt." },
      { order: 4, instruction: "Roast vegetables for 20-25 minutes, stirring halfway through, until tender and lightly browned." },
      { order: 5, instruction: "While vegetables are roasting, bring a small pot of water to a boil." },
      { order: 6, instruction: "Carefully add eggs to the boiling water and cook for exactly 6 minutes for soft-boiled eggs." },
      { order: 7, instruction: "Immediately transfer eggs to an ice bath to stop the cooking process." },
      { order: 8, instruction: "Once cooled, peel the eggs carefully." },
      { order: 9, instruction: "Make the tahini sauce by whisking together tahini, lemon juice, water, minced garlic, and remaining 1/4 teaspoon salt until smooth." },
      { order: 10, instruction: "To assemble each bowl, place 1/4 of the cooked grain as the base." },
      { order: 11, instruction: "Top with 1/4 of the roasted vegetables and sliced avocado." },
      { order: 12, instruction: "Cut each soft-boiled egg in half and place on top." },
      { order: 13, instruction: "Drizzle with tahini sauce and remaining olive oil." },
      { order: 14, instruction: "Garnish with microgreens and sesame seeds if using." }
    ],
    cookingVessel: "Saucepan and Baking Sheet",
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    difficulty: "Medium",
    mealType: "Breakfast",
    cuisine: "Mediterranean",
    categories: ["Grain Bowls", "Healthy"],
    dietaryCategories: ["Vegetarian"],
    tags: ["grain bowl", "soft-boiled egg", "healthy breakfast", "vegetables"],
    imageUrl: "https://images.unsplash.com/photo-1540914124281-342587941389"
  },
  {
    title: "Breakfast Fried Rice with Bacon and Eggs",
    description: "A savory breakfast twist on classic fried rice, featuring leftover rice stir-fried with bacon, vegetables, and eggs for a hearty morning meal.",
    ingredients: [
      { name: "bacon", quantity: "6", unit: "slices", notes: "diced" },
      { name: "cooked rice", quantity: "3", unit: "cups", notes: "cold, leftover rice works best" },
      { name: "eggs", quantity: "4", unit: "large", notes: "divided" },
      { name: "vegetable oil", quantity: "1", unit: "tablespoon" },
      { name: "onion", quantity: "1", unit: "small", notes: "diced" },
      { name: "carrots", quantity: "2", unit: "medium", notes: "diced" },
      { name: "frozen peas", quantity: "1/2", unit: "cup", notes: "thawed" },
      { name: "garlic", quantity: "2", unit: "cloves", notes: "minced" },
      { name: "ginger", quantity: "1", unit: "teaspoon", notes: "minced" },
      { name: "soy sauce", quantity: "2", unit: "tablespoons" },
      { name: "sesame oil", quantity: "1", unit: "teaspoon" },
      { name: "green onions", quantity: "4", unit: "", notes: "sliced, divided" },
      { name: "salt", quantity: "to taste", unit: "" },
      { name: "black pepper", quantity: "to taste", unit: "" },
      { name: "sriracha sauce", quantity: "to taste", unit: "", notes: "optional, for serving" }
    ],
    steps: [
      { order: 1, instruction: "In a large wok or skillet, cook diced bacon over medium heat until crispy, about 5-7 minutes." },
      { order: 2, instruction: "Remove bacon with a slotted spoon and set aside, leaving the bacon fat in the wok." },
      { order: 3, instruction: "Crack 2 eggs into a small bowl and beat lightly." },
      { order: 4, instruction: "Pour the beaten eggs into the wok and scramble until just set, about 1 minute. Remove and set aside with the bacon." },
      { order: 5, instruction: "Add vegetable oil to the wok if needed (if there's not enough bacon fat left)." },
      { order: 6, instruction: "Add diced onion and carrots to the wok and stir-fry for 3-4 minutes until softened." },
      { order: 7, instruction: "Add minced garlic and ginger, and stir-fry for 30 seconds until fragrant." },
      { order: 8, instruction: "Add cold rice to the wok, breaking up any clumps, and stir-fry for 3-4 minutes until heated through." },
      { order: 9, instruction: "Add thawed peas, cooked bacon, scrambled eggs, soy sauce, sesame oil, and half of the sliced green onions." },
      { order: 10, instruction: "Stir-fry for another 2 minutes until everything is well combined and heated through." },
      { order: 11, instruction: "Season with salt and pepper to taste." },
      { order: 12, instruction: "Meanwhile, in a separate non-stick skillet, fry the remaining 2 eggs to your preference (sunny-side up or over-easy recommended)." },
      { order: 13, instruction: "Divide the fried rice among serving plates and top each portion with a fried egg." },
      { order: 14, instruction: "Garnish with remaining green onions and serve with sriracha sauce if desired." }
    ],
    cookingVessel: "Wok",
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    difficulty: "Medium",
    mealType: "Breakfast",
    cuisine: "Asian",
    categories: ["Leftover Makeover", "Savory Breakfast"],
    dietaryCategories: [],
    tags: ["fried rice", "bacon", "eggs", "breakfast", "asian"],
    imageUrl: "https://images.unsplash.com/photo-1512058564366-18510be2db19"
  },
  {
    title: "Breakfast Polenta Bowl with Roasted Tomatoes",
    description: "Creamy breakfast polenta topped with roasted cherry tomatoes, a poached egg, and fresh herbs for a comforting and satisfying morning meal.",
    ingredients: [
      { name: "cherry tomatoes", quantity: "2", unit: "cups", notes: "halved" },
      { name: "garlic", quantity: "3", unit: "cloves", notes: "thinly sliced" },
      { name: "olive oil", quantity: "3", unit: "tablespoons", notes: "divided" },
      { name: "balsamic vinegar", quantity: "1", unit: "tablespoon" },
      { name: "salt", quantity: "1", unit: "teaspoon", notes: "divided" },
      { name: "black pepper", quantity: "1/2", unit: "teaspoon", notes: "divided" },
      { name: "polenta", quantity: "1", unit: "cup", notes: "coarse ground" },
      { name: "water", quantity: "4", unit: "cups" },
      { name: "milk", quantity: "1", unit: "cup" },
      { name: "parmesan cheese", quantity: "1/2", unit: "cup", notes: "grated" },
      { name: "butter", quantity: "2", unit: "tablespoons" },
      { name: "eggs", quantity: "4", unit: "large" },
      { name: "white vinegar", quantity: "1", unit: "tablespoon", notes: "for poaching eggs" },
      { name: "fresh basil", quantity: "1/4", unit: "cup", notes: "torn" },
      { name: "red pepper flakes", quantity: "1/4", unit: "teaspoon", notes: "optional" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 400°F (200°C)." },
      { order: 2, instruction: "On a baking sheet, toss cherry tomatoes and sliced garlic with 2 tablespoons olive oil, balsamic vinegar, 1/4 teaspoon salt, and 1/4 teaspoon black pepper." },
      { order: 3, instruction: "Roast for 15-20 minutes until tomatoes are soft and slightly caramelized." },
      { order: 4, instruction: "Meanwhile, in a medium saucepan, bring water and milk to a gentle boil." },
      { order: 5, instruction: "Slowly whisk in polenta, reducing heat to low." },
      { order: 6, instruction: "Cook, stirring frequently, for 25-30 minutes until polenta is creamy and tender." },
      { order: 7, instruction: "Stir in parmesan cheese, butter, 1/2 teaspoon salt, and remaining black pepper. Keep warm." },
      { order: 8, instruction: "For the poached eggs, fill a large saucepan with about 3 inches of water and add white vinegar." },
      { order: 9, instruction: "Bring to a gentle simmer (small bubbles, not a rolling boil)." },
      { order: 10, instruction: "Crack each egg into a small cup or ramekin." },
      { order: 11, instruction: "Create a gentle whirlpool in the water with a spoon, then carefully slide each egg into the water." },
      { order: 12, instruction: "Cook for 3-4 minutes for a runny yolk, or longer if desired." },
      { order: 13, instruction: "Remove eggs with a slotted spoon and place on a paper towel to drain." },
      { order: 14, instruction: "To serve, divide polenta among four bowls, top with roasted tomatoes and garlic, a poached egg, torn basil, remaining olive oil, and red pepper flakes if using." }
    ],
    cookingVessel: "Saucepan",
    prepTime: 15,
    cookTime: 35,
    servings: 4,
    difficulty: "Medium",
    mealType: "Breakfast",
    cuisine: "Italian",
    categories: ["Grain Bowls", "Comfort Food"],
    dietaryCategories: ["Vegetarian", "Gluten-Free"],
    tags: ["polenta", "poached eggs", "roasted tomatoes", "breakfast bowl"],
    imageUrl: "https://images.unsplash.com/photo-1515942400420-2b98fed1f515"
  }
];

export default breakfastRecipes;
