// Dessert Recipes for WhatAboutDinner App
// 20 detailed dessert recipes with all required fields

const dessertRecipes = [
  {
    title: "Classic Chocolate Chip Cookies",
    description: "Soft and chewy chocolate chip cookies with crisp edges, melty chocolate chips, and a hint of vanilla - the perfect homemade treat that everyone loves.",
    ingredients: [
      { name: "all-purpose flour", quantity: "2 1/4", unit: "cups" },
      { name: "baking soda", quantity: "1", unit: "teaspoon" },
      { name: "salt", quantity: "1", unit: "teaspoon" },
      { name: "unsalted butter", quantity: "1", unit: "cup", notes: "softened" },
      { name: "granulated sugar", quantity: "3/4", unit: "cup" },
      { name: "brown sugar", quantity: "3/4", unit: "cup", notes: "packed" },
      { name: "vanilla extract", quantity: "2", unit: "teaspoons" },
      { name: "eggs", quantity: "2", unit: "large" },
      { name: "semi-sweet chocolate chips", quantity: "2", unit: "cups" },
      { name: "walnuts", quantity: "1", unit: "cup", notes: "chopped, optional" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 375°F (190°C). Line baking sheets with parchment paper." },
      { order: 2, instruction: "In a medium bowl, whisk together flour, baking soda, and salt. Set aside." },
      { order: 3, instruction: "In a large bowl or stand mixer, beat butter, granulated sugar, and brown sugar until creamy, about 2-3 minutes." },
      { order: 4, instruction: "Add vanilla extract and eggs, one at a time, beating well after each addition." },
      { order: 5, instruction: "Gradually add the flour mixture to the butter mixture, mixing until just combined." },
      { order: 6, instruction: "Stir in chocolate chips and walnuts (if using) by hand." },
      { order: 7, instruction: "Drop rounded tablespoons of dough onto prepared baking sheets, spacing them about 2 inches apart." },
      { order: 8, instruction: "Bake for 9-11 minutes or until edges are golden brown but centers still appear slightly soft." },
      { order: 9, instruction: "Allow cookies to cool on baking sheets for 2 minutes before transferring to wire racks to cool completely." }
    ],
    cookingVessel: "Baking Sheet",
    prepTime: 15,
    cookTime: 10,
    servings: 36,
    difficulty: "Easy",
    mealType: "Dessert",
    cuisine: "American",
    categories: ["Cookies", "Baked Goods"],
    dietaryCategories: ["Vegetarian"],
    tags: ["chocolate chip", "cookies", "baking", "dessert"],
    imageUrl: "https://images.unsplash.com/photo-1499636136210-6f4ee915583e"
  },
  {
    title: "New York Style Cheesecake",
    description: "A rich, creamy, and dense classic cheesecake with a buttery graham cracker crust and a smooth, tangy sour cream topping.",
    ingredients: [
      { name: "graham crackers", quantity: "2", unit: "cups", notes: "crushed into crumbs" },
      { name: "unsalted butter", quantity: "1/2", unit: "cup", notes: "melted" },
      { name: "granulated sugar", quantity: "1/4", unit: "cup", notes: "for crust" },
      { name: "cream cheese", quantity: "32", unit: "ounces", notes: "4 blocks, softened" },
      { name: "granulated sugar", quantity: "1 1/2", unit: "cups", notes: "for filling" },
      { name: "cornstarch", quantity: "3", unit: "tablespoons" },
      { name: "vanilla extract", quantity: "2", unit: "teaspoons" },
      { name: "lemon zest", quantity: "1", unit: "tablespoon" },
      { name: "eggs", quantity: "4", unit: "large" },
      { name: "egg yolk", quantity: "1", unit: "large" },
      { name: "heavy cream", quantity: "1/3", unit: "cup" },
      { name: "sour cream", quantity: "1", unit: "cup", notes: "divided" },
      { name: "powdered sugar", quantity: "2", unit: "tablespoons" },
      { name: "fresh berries", quantity: "2", unit: "cups", notes: "for serving, optional" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 350°F (175°C). Wrap the outside of a 9-inch springform pan with aluminum foil to prevent leaking." },
      { order: 2, instruction: "In a medium bowl, combine graham cracker crumbs, melted butter, and 1/4 cup sugar. Press mixture firmly into the bottom and about 1 inch up the sides of the springform pan." },
      { order: 3, instruction: "Bake crust for 10 minutes. Remove from oven and let cool. Reduce oven temperature to 325°F (165°C)." },
      { order: 4, instruction: "In a large bowl or stand mixer, beat cream cheese until smooth and creamy, about 2 minutes." },
      { order: 5, instruction: "Gradually add 1 1/2 cups sugar and cornstarch, beating until well combined." },
      { order: 6, instruction: "Add vanilla extract and lemon zest. Beat in eggs and egg yolk, one at a time, mixing just until each is incorporated." },
      { order: 7, instruction: "Mix in heavy cream and 1/2 cup sour cream until smooth. Be careful not to overmix." },
      { order: 8, instruction: "Pour filling into the prepared crust." },
      { order: 9, instruction: "Place the springform pan in a larger roasting pan. Fill the roasting pan with hot water to reach halfway up the sides of the springform pan (water bath)." },
      { order: 10, instruction: "Bake for 60-70 minutes, or until the edges are set but the center still has a slight jiggle." },
      { order: 11, instruction: "Turn off the oven, crack the door open, and let the cheesecake cool in the oven for 1 hour." },
      { order: 12, instruction: "Mix remaining 1/2 cup sour cream with powdered sugar. Spread over the top of the cheesecake." },
      { order: 13, instruction: "Remove from oven and water bath. Run a knife around the edge of the cheesecake to loosen from the pan." },
      { order: 14, instruction: "Refrigerate for at least 4 hours or overnight before serving." },
      { order: 15, instruction: "Serve with fresh berries if desired." }
    ],
    cookingVessel: "Springform Pan",
    prepTime: 30,
    cookTime: 80,
    servings: 12,
    difficulty: "Medium",
    mealType: "Dessert",
    cuisine: "American",
    categories: ["Cheesecake", "Baked Goods"],
    dietaryCategories: ["Vegetarian"],
    tags: ["cheesecake", "cream cheese", "graham cracker crust", "special occasion"],
    imageUrl: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad"
  },
  {
    title: "Warm Apple Crisp",
    description: "A comforting dessert featuring tender, spiced apples topped with a crispy, buttery oat crumble, best served warm with a scoop of vanilla ice cream.",
    ingredients: [
      { name: "apples", quantity: "6", unit: "large", notes: "peeled, cored, and sliced (Granny Smith or Honeycrisp)" },
      { name: "lemon juice", quantity: "1", unit: "tablespoon" },
      { name: "granulated sugar", quantity: "1/2", unit: "cup" },
      { name: "all-purpose flour", quantity: "2", unit: "tablespoons", notes: "for filling" },
      { name: "ground cinnamon", quantity: "1", unit: "teaspoon" },
      { name: "ground nutmeg", quantity: "1/4", unit: "teaspoon" },
      { name: "salt", quantity: "1/4", unit: "teaspoon", notes: "divided" },
      { name: "old-fashioned oats", quantity: "1", unit: "cup" },
      { name: "all-purpose flour", quantity: "3/4", unit: "cup", notes: "for topping" },
      { name: "brown sugar", quantity: "3/4", unit: "cup", notes: "packed" },
      { name: "unsalted butter", quantity: "1/2", unit: "cup", notes: "cold, cubed" },
      { name: "vanilla ice cream", quantity: "1", unit: "pint", notes: "for serving, optional" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 350°F (175°C). Butter a 9x9 inch baking dish." },
      { order: 2, instruction: "In a large bowl, toss sliced apples with lemon juice." },
      { order: 3, instruction: "In a small bowl, mix together granulated sugar, 2 tablespoons flour, cinnamon, nutmeg, and 1/8 teaspoon salt." },
      { order: 4, instruction: "Add the sugar mixture to the apples and toss to coat evenly. Transfer to the prepared baking dish." },
      { order: 5, instruction: "In a medium bowl, combine oats, 3/4 cup flour, brown sugar, and remaining 1/8 teaspoon salt." },
      { order: 6, instruction: "Using a pastry cutter or your fingers, cut in the cold butter until the mixture resembles coarse crumbs." },
      { order: 7, instruction: "Sprinkle the oat mixture evenly over the apples." },
      { order: 8, instruction: "Bake for 40-45 minutes, until the topping is golden brown and the filling is bubbly." },
      { order: 9, instruction: "Let cool for 10 minutes before serving." },
      { order: 10, instruction: "Serve warm with a scoop of vanilla ice cream if desired." }
    ],
    cookingVessel: "Baking Dish",
    prepTime: 20,
    cookTime: 45,
    servings: 8,
    difficulty: "Easy",
    mealType: "Dessert",
    cuisine: "American",
    categories: ["Fruit Desserts", "Baked Goods"],
    dietaryCategories: ["Vegetarian"],
    tags: ["apple crisp", "oat topping", "fall dessert", "comfort food"],
    imageUrl: "https://images.unsplash.com/photo-1568571780765-9276ac8b75a7"
  },
  {
    title: "Classic Tiramisu",
    description: "An elegant Italian dessert featuring layers of coffee-soaked ladyfingers and a rich, creamy mascarpone mixture, dusted with cocoa powder for a sophisticated finish.",
    ingredients: [
      { name: "egg yolks", quantity: "6", unit: "large" },
      { name: "granulated sugar", quantity: "3/4", unit: "cup" },
      { name: "mascarpone cheese", quantity: "16", unit: "ounces" },
      { name: "heavy cream", quantity: "1 1/2", unit: "cups" },
      { name: "vanilla extract", quantity: "2", unit: "teaspoons" },
      { name: "strong coffee", quantity: "1 1/2", unit: "cups", notes: "cooled" },
      { name: "coffee liqueur", quantity: "1/4", unit: "cup", notes: "such as Kahlúa, optional" },
      { name: "ladyfinger cookies", quantity: "24", unit: "" },
      { name: "unsweetened cocoa powder", quantity: "2", unit: "tablespoons" },
      { name: "dark chocolate", quantity: "2", unit: "ounces", notes: "grated, for garnish" }
    ],
    steps: [
      { order: 1, instruction: "In a heatproof bowl set over a pot of simmering water (double boiler), whisk egg yolks and sugar until pale and doubled in volume, about 5 minutes. The mixture should reach 160°F (71°C) to ensure eggs are safe to eat." },
      { order: 2, instruction: "Remove from heat and let cool for 5 minutes." },
      { order: 3, instruction: "Add mascarpone cheese to the egg mixture and whisk until smooth." },
      { order: 4, instruction: "In a separate bowl, whip heavy cream and vanilla extract until stiff peaks form." },
      { order: 5, instruction: "Gently fold the whipped cream into the mascarpone mixture until fully incorporated." },
      { order: 6, instruction: "In a shallow dish, combine cooled coffee and coffee liqueur (if using)." },
      { order: 7, instruction: "Quickly dip each ladyfinger into the coffee mixture (about 1 second per side) and arrange in a single layer in the bottom of an 8x8 inch dish or trifle bowl." },
      { order: 8, instruction: "Spread half of the mascarpone mixture over the ladyfingers." },
      { order: 9, instruction: "Repeat with another layer of dipped ladyfingers and the remaining mascarpone mixture." },
      { order: 10, instruction: "Cover and refrigerate for at least 4 hours or overnight." },
      { order: 11, instruction: "Just before serving, dust the top with cocoa powder and sprinkle with grated dark chocolate." }
    ],
    cookingVessel: "Trifle Dish",
    prepTime: 30,
    cookTime: 10,
    servings: 8,
    difficulty: "Medium",
    mealType: "Dessert",
    cuisine: "Italian",
    categories: ["No-Bake Desserts", "Custards"],
    dietaryCategories: ["Vegetarian"],
    tags: ["tiramisu", "coffee", "mascarpone", "italian dessert"],
    imageUrl: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9"
  },
  {
    title: "Lemon Bars",
    description: "Bright, tangy lemon bars with a buttery shortbread crust and a smooth, zesty lemon filling, dusted with powdered sugar for a classic sweet-tart dessert.",
    ingredients: [
      { name: "all-purpose flour", quantity: "2", unit: "cups", notes: "divided" },
      { name: "powdered sugar", quantity: "1/2", unit: "cup", notes: "plus more for dusting" },
      { name: "salt", quantity: "1/4", unit: "teaspoon" },
      { name: "unsalted butter", quantity: "1", unit: "cup", notes: "cold, cubed" },
      { name: "granulated sugar", quantity: "1 1/2", unit: "cups" },
      { name: "eggs", quantity: "4", unit: "large" },
      { name: "lemon zest", quantity: "2", unit: "tablespoons" },
      { name: "lemon juice", quantity: "2/3", unit: "cup", notes: "freshly squeezed (about 4-5 lemons)" },
      { name: "baking powder", quantity: "1/2", unit: "teaspoon" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 350°F (175°C). Line a 9x13 inch baking pan with parchment paper, leaving an overhang on the sides." },
      { order: 2, instruction: "For the crust: In a food processor, combine 1 3/4 cups flour, powdered sugar, and salt. Pulse a few times to mix." },
      { order: 3, instruction: "Add cold butter cubes and pulse until the mixture resembles coarse crumbs." },
      { order: 4, instruction: "Press the mixture evenly into the bottom of the prepared pan." },
      { order: 5, instruction: "Bake the crust for 15-18 minutes until lightly golden around the edges." },
      { order: 6, instruction: "While the crust is baking, prepare the filling: In a large bowl, whisk together granulated sugar and remaining 1/4 cup flour." },
      { order: 7, instruction: "Add eggs, lemon zest, lemon juice, and baking powder. Whisk until well combined." },
      { order: 8, instruction: "When the crust is done, reduce oven temperature to 325°F (165°C)." },
      { order: 9, instruction: "Pour the lemon filling over the hot crust." },
      { order: 10, instruction: "Return to the oven and bake for 20-25 minutes until the filling is set and no longer jiggles in the center." },
      { order: 11, instruction: "Allow to cool completely in the pan on a wire rack, then refrigerate for at least 2 hours." },
      { order: 12, instruction: "Using the parchment paper overhang, lift the bars out of the pan and place on a cutting board." },
      { order: 13, instruction: "Cut into squares and dust with powdered sugar just before serving." }
    ],
    cookingVessel: "Baking Pan",
    prepTime: 20,
    cookTime: 40,
    servings: 16,
    difficulty: "Medium",
    mealType: "Dessert",
    cuisine: "American",
    categories: ["Bars", "Baked Goods"],
    dietaryCategories: ["Vegetarian"],
    tags: ["lemon", "citrus", "bars", "shortbread crust"],
    imageUrl: "https://images.unsplash.com/photo-1628919817071-3b4d2b5b5b20"
  },
  {
    title: "Chocolate Lava Cakes",
    description: "Decadent individual chocolate cakes with a warm, molten chocolate center that flows out when cut into, served with a dusting of powdered sugar or a scoop of ice cream.",
    ingredients: [
      { name: "semi-sweet chocolate", quantity: "6", unit: "ounces", notes: "chopped" },
      { name: "unsalted butter", quantity: "1/2", unit: "cup" },
      { name: "eggs", quantity: "2", unit: "large" },
      { name: "egg yolks", quantity: "2", unit: "large" },
      { name: "granulated sugar", quantity: "1/4", unit: "cup" },
      { name: "vanilla extract", quantity: "1", unit: "teaspoon" },
      { name: "all-purpose flour", quantity: "1/4", unit: "cup" },
      { name: "salt", quantity: "1/8", unit: "teaspoon" },
      { name: "powdered sugar", quantity: "2", unit: "tablespoons", notes: "for dusting" },
      { name: "vanilla ice cream", quantity: "1", unit: "pint", notes: "for serving, optional" },
      { name: "fresh raspberries", quantity: "1", unit: "cup", notes: "for serving, optional" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 425°F (220°C). Butter and lightly flour four 6-ounce ramekins. Place on a baking sheet." },
      { order: 2, instruction: "In a microwave-safe bowl, combine chocolate and butter. Microwave in 30-second intervals, stirring between each, until melted and smooth." },
      { order: 3, instruction: "In a medium bowl, whisk together eggs, egg yolks, sugar, and vanilla until light and frothy." },
      { order: 4, instruction: "Gradually fold the melted chocolate mixture into the egg mixture until combined." },
      { order: 5, instruction: "Gently fold in flour and salt until just incorporated. Do not overmix." },
      { order: 6, instruction: "Divide the batter evenly among the prepared ramekins." },
      { order: 7, instruction: "Bake for 12-14 minutes until the edges are set but the centers are still soft (the tops should be firm but will spring back when lightly touched)." },
      { order: 8, instruction: "Remove from oven and let stand for 1 minute." },
      { order: 9, instruction: "Run a knife around the edges to loosen, then carefully invert each cake onto a serving plate." },
      { order: 10, instruction: "Dust with powdered sugar and serve immediately with vanilla ice cream and fresh raspberries if desired." }
    ],
    cookingVessel: "Ramekins",
    prepTime: 15,
    cookTime: 12,
    servings: 4,
    difficulty: "Medium",
    mealType: "Dessert",
    cuisine: "French",
    categories: ["Cakes", "Chocolate Desserts"],
    dietaryCategories: ["Vegetarian"],
    tags: ["lava cake", "molten chocolate", "individual desserts", "special occasion"],
    imageUrl: "https://images.unsplash.com/photo-1617305855058-336d24456869"
  },
  {
    title: "Homemade Vanilla Bean Ice Cream",
    description: "Rich, creamy vanilla ice cream made with real vanilla beans for an intense flavor, perfect on its own or as an accompaniment to other desserts.",
    ingredients: [
      { name: "heavy cream", quantity: "2", unit: "cups" },
      { name: "whole milk", quantity: "1", unit: "cup" },
      { name: "granulated sugar", quantity: "3/4", unit: "cup" },
      { name: "vanilla bean", quantity: "1", unit: "", notes: "split lengthwise and seeds scraped" },
      { name: "egg yolks", quantity: "6", unit: "large" },
      { name: "vanilla extract", quantity: "1", unit: "teaspoon" },
      { name: "salt", quantity: "1/4", unit: "teaspoon" }
    ],
    steps: [
      { order: 1, instruction: "In a medium saucepan, combine heavy cream, milk, half of the sugar, vanilla bean pod, and scraped seeds. Heat over medium until it begins to steam (do not boil)." },
      { order: 2, instruction: "Meanwhile, in a medium bowl, whisk together egg yolks, remaining sugar, and salt until pale and thick." },
      { order: 3, instruction: "Slowly pour about 1 cup of the hot cream mixture into the egg yolk mixture, whisking constantly to temper the eggs." },
      { order: 4, instruction: "Pour the tempered egg mixture back into the saucepan with the remaining cream mixture, whisking constantly." },
      { order: 5, instruction: "Cook over medium-low heat, stirring constantly with a wooden spoon, until the mixture thickens enough to coat the back of the spoon (about 170-175°F/77-80°C)." },
      { order: 6, instruction: "Strain the custard through a fine-mesh sieve into a clean bowl. Discard the vanilla bean pod or rinse and dry for another use." },
      { order: 7, instruction: "Stir in vanilla extract." },
      { order: 8, instruction: "Cover with plastic wrap, pressing it directly onto the surface of the custard to prevent a skin from forming." },
      { order: 9, instruction: "Refrigerate until completely chilled, at least 4 hours or overnight." },
      { order: 10, instruction: "Pour the chilled custard into an ice cream maker and churn according to manufacturer's instructions, usually 20-25 minutes." },
      { order: 11, instruction: "Transfer to an airtight container and freeze for at least 4 hours until firm." },
      { order: 12, instruction: "Let sit at room temperature for 5 minutes before scooping and serving." }
    ],
    cookingVessel: "Ice Cream Maker",
    prepTime: 30,
    cookTime: 15,
    servings: 8,
    difficulty: "Medium",
    mealType: "Dessert",
    cuisine: "American",
    categories: ["Frozen Desserts", "Ice Cream"],
    dietaryCategories: ["Vegetarian", "Gluten-Free"],
    tags: ["vanilla", "ice cream", "homemade", "custard base"],
    imageUrl: "https://images.unsplash.com/photo-1563805042-7684c019e1cb"
  },
  {
    title: "Classic Crème Brûlée",
    description: "An elegant French dessert featuring a rich vanilla custard base topped with a layer of caramelized sugar that cracks satisfyingly when tapped with a spoon.",
    ingredients: [
      { name: "heavy cream", quantity: "2", unit: "cups" },
      { name: "vanilla bean", quantity: "1", unit: "", notes: "split lengthwise and seeds scraped" },
      { name: "egg yolks", quantity: "5", unit: "large" },
      { name: "granulated sugar", quantity: "1/2", unit: "cup", notes: "divided" },
      { name: "salt", quantity: "1/8", unit: "teaspoon" },
      { name: "fresh berries", quantity: "1", unit: "cup", notes: "for serving, optional" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 325°F (165°C). Place 6 ramekins in a large baking dish." },
      { order: 2, instruction: "In a medium saucepan, combine heavy cream, vanilla bean pod, and scraped seeds. Heat over medium until it just begins to simmer. Remove from heat and let steep for 15 minutes." },
      { order: 3, instruction: "In a medium bowl, whisk together egg yolks, 1/4 cup sugar, and salt until light and pale." },
      { order: 4, instruction: "Remove vanilla bean pod from cream. Gradually whisk the warm cream into the egg yolk mixture until combined." },
      { order: 5, instruction: "Strain the custard through a fine-mesh sieve into a large measuring cup or bowl with a pouring spout." },
      { order: 6, instruction: "Divide the custard evenly among the ramekins." },
      { order: 7, instruction: "Pour hot water into the baking dish until it reaches halfway up the sides of the ramekins, creating a water bath." },
      { order: 8, instruction: "Carefully transfer to the oven and bake for 30-35 minutes, until the custards are set but still slightly jiggly in the center." },
      { order: 9, instruction: "Remove ramekins from the water bath and let cool to room temperature." },
      { order: 10, instruction: "Refrigerate for at least 4 hours or overnight." },
      { order: 11, instruction: "Just before serving, sprinkle about 1-2 teaspoons of the remaining sugar evenly over each custard." },
      { order: 12, instruction: "Using a kitchen torch, melt the sugar by moving the flame continuously over the surface until caramelized and golden brown." },
      { order: 13, instruction: "Let the caramelized sugar harden for 1-2 minutes before serving." },
      { order: 14, instruction: "Serve with fresh berries if desired." }
    ],
    cookingVessel: "Ramekins",
    prepTime: 20,
    cookTime: 35,
    servings: 6,
    difficulty: "Medium",
    mealType: "Dessert",
    cuisine: "French",
    categories: ["Custards", "Elegant Desserts"],
    dietaryCategories: ["Vegetarian", "Gluten-Free"],
    tags: ["crème brûlée", "custard", "caramelized sugar", "french dessert"],
    imageUrl: "https://images.unsplash.com/photo-1470124182917-cc6e71b22ecc"
  },
  {
    title: "Fresh Berry Pavlova",
    description: "A light and elegant dessert featuring a crisp meringue shell with a marshmallow-soft interior, topped with whipped cream and fresh seasonal berries.",
    ingredients: [
      { name: "egg whites", quantity: "4", unit: "large", notes: "at room temperature" },
      { name: "granulated sugar", quantity: "1", unit: "cup" },
      { name: "cornstarch", quantity: "1", unit: "tablespoon" },
      { name: "white vinegar", quantity: "1", unit: "teaspoon" },
      { name: "vanilla extract", quantity: "1", unit: "teaspoon" },
      { name: "heavy cream", quantity: "1 1/2", unit: "cups" },
      { name: "powdered sugar", quantity: "3", unit: "tablespoons" },
      { name: "strawberries", quantity: "1", unit: "cup", notes: "hulled and sliced" },
      { name: "blueberries", quantity: "1", unit: "cup" },
      { name: "raspberries", quantity: "1", unit: "cup" },
      { name: "blackberries", quantity: "1/2", unit: "cup" },
      { name: "fresh mint leaves", quantity: "2", unit: "tablespoons", notes: "for garnish" },
      { name: "lemon zest", quantity: "1", unit: "teaspoon", notes: "for garnish" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 300°F (150°C). Line a baking sheet with parchment paper and draw an 8-inch circle on the paper (flip the paper over so the pencil mark is on the bottom)." },
      { order: 2, instruction: "In a stand mixer fitted with the whisk attachment, beat egg whites on medium speed until soft peaks form." },
      { order: 3, instruction: "Gradually add sugar, 1 tablespoon at a time, while continuing to beat on high speed until stiff, glossy peaks form and sugar is dissolved (about 5-7 minutes)." },
      { order: 4, instruction: "Sprinkle cornstarch over the meringue, then add vinegar and vanilla. Gently fold in with a rubber spatula until just combined." },
      { order: 5, instruction: "Spoon the meringue onto the parchment paper, using the drawn circle as a guide. Shape into a disk with slightly higher edges and a slight depression in the center." },
      { order: 6, instruction: "Reduce oven temperature to 250°F (120°C) and place the meringue in the oven." },
      { order: 7, instruction: "Bake for 1 hour and 15 minutes, or until the outside is dry and crisp and very pale cream in color." },
      { order: 8, instruction: "Turn off the oven, crack the door open, and let the pavlova cool completely in the oven (about 1 hour)." },
      { order: 9, instruction: "Just before serving, whip heavy cream with powdered sugar until soft peaks form." },
      { order: 10, instruction: "Carefully transfer the cooled pavlova to a serving plate." },
      { order: 11, instruction: "Spread the whipped cream over the top of the pavlova." },
      { order: 12, instruction: "Arrange fresh berries on top of the whipped cream." },
      { order: 13, instruction: "Garnish with fresh mint leaves and lemon zest." },
      { order: 14, instruction: "Serve immediately." }
    ],
    cookingVessel: "Baking Sheet",
    prepTime: 25,
    cookTime: 75,
    servings: 8,
    difficulty: "Medium",
    mealType: "Dessert",
    cuisine: "Australian",
    categories: ["Meringue Desserts", "Fruit Desserts"],
    dietaryCategories: ["Vegetarian", "Gluten-Free"],
    tags: ["pavlova", "meringue", "berries", "elegant dessert"],
    imageUrl: "https://images.unsplash.com/photo-1464305795204-6f5bbfc7fb81"
  },
  {
    title: "Classic Bread Pudding with Vanilla Sauce",
    description: "A comforting dessert made with cubes of bread soaked in a rich custard, studded with raisins and cinnamon, baked until golden and served with a warm vanilla sauce.",
    ingredients: [
      { name: "day-old bread", quantity: "8", unit: "cups", notes: "cubed (French bread or brioche)" },
      { name: "raisins", quantity: "1", unit: "cup" },
      { name: "eggs", quantity: "4", unit: "large" },
      { name: "whole milk", quantity: "3", unit: "cups" },
      { name: "heavy cream", quantity: "1", unit: "cup" },
      { name: "granulated sugar", quantity: "1", unit: "cup" },
      { name: "brown sugar", quantity: "1/4", unit: "cup", notes: "packed" },
      { name: "vanilla extract", quantity: "2", unit: "teaspoons" },
      { name: "ground cinnamon", quantity: "1 1/2", unit: "teaspoons" },
      { name: "ground nutmeg", quantity: "1/4", unit: "teaspoon" },
      { name: "salt", quantity: "1/4", unit: "teaspoon" },
      { name: "unsalted butter", quantity: "1/4", unit: "cup", notes: "melted" },
      { name: "unsalted butter", quantity: "1/2", unit: "cup", notes: "for sauce" },
      { name: "granulated sugar", quantity: "1", unit: "cup", notes: "for sauce" },
      { name: "heavy cream", quantity: "1/2", unit: "cup", notes: "for sauce" },
      { name: "vanilla extract", quantity: "1", unit: "tablespoon", notes: "for sauce" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 350°F (175°C). Butter a 9x13 inch baking dish." },
      { order: 2, instruction: "Place bread cubes in the prepared baking dish. Sprinkle raisins evenly over the bread." },
      { order: 3, instruction: "In a large bowl, whisk together eggs, milk, heavy cream, granulated sugar, brown sugar, vanilla extract, cinnamon, nutmeg, and salt." },
      { order: 4, instruction: "Pour the egg mixture over the bread cubes. Press bread down gently to help it absorb the liquid." },
      { order: 5, instruction: "Let sit for 15 minutes to allow the bread to soak up the custard." },
      { order: 6, instruction: "Drizzle melted butter over the top." },
      { order: 7, instruction: "Bake for 45-50 minutes, until the pudding is set and the top is golden brown." },
      { order: 8, instruction: "While the pudding is baking, prepare the vanilla sauce: In a medium saucepan, melt 1/2 cup butter over medium heat." },
      { order: 9, instruction: "Add 1 cup sugar and stir until dissolved." },
      { order: 10, instruction: "Slowly whisk in 1/2 cup heavy cream and bring to a simmer." },
      { order: 11, instruction: "Remove from heat and stir in 1 tablespoon vanilla extract." },
      { order: 12, instruction: "Let the bread pudding cool for 10 minutes before serving." },
      { order: 13, instruction: "Serve warm, drizzled with the vanilla sauce." }
    ],
    cookingVessel: "Baking Dish",
    prepTime: 20,
    cookTime: 50,
    servings: 10,
    difficulty: "Easy",
    mealType: "Dessert",
    cuisine: "American",
    categories: ["Puddings", "Comfort Desserts"],
    dietaryCategories: ["Vegetarian"],
    tags: ["bread pudding", "custard", "raisins", "vanilla sauce"],
    imageUrl: "https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e"
  },
  {
    title: "Strawberry Shortcake",
    description: "A classic summer dessert featuring tender, buttery biscuits split and filled with juicy macerated strawberries and freshly whipped cream.",
    ingredients: [
      { name: "all-purpose flour", quantity: "2", unit: "cups" },
      { name: "granulated sugar", quantity: "1/4", unit: "cup", notes: "plus 2 tablespoons for strawberries" },
      { name: "baking powder", quantity: "1", unit: "tablespoon" },
      { name: "salt", quantity: "1/2", unit: "teaspoon" },
      { name: "unsalted butter", quantity: "1/2", unit: "cup", notes: "cold, cubed" },
      { name: "heavy cream", quantity: "3/4", unit: "cup", notes: "plus 2 tablespoons for brushing" },
      { name: "vanilla extract", quantity: "1", unit: "teaspoon", notes: "divided" },
      { name: "fresh strawberries", quantity: "2", unit: "pounds", notes: "hulled and sliced" },
      { name: "lemon juice", quantity: "1", unit: "tablespoon" },
      { name: "heavy cream", quantity: "1 1/2", unit: "cups", notes: "for whipping" },
      { name: "powdered sugar", quantity: "3", unit: "tablespoons" },
      { name: "fresh mint leaves", quantity: "2", unit: "tablespoons", notes: "for garnish, optional" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 425°F (220°C). Line a baking sheet with parchment paper." },
      { order: 2, instruction: "In a large bowl, whisk together flour, 1/4 cup sugar, baking powder, and salt." },
      { order: 3, instruction: "Using a pastry cutter or your fingers, cut in cold butter until the mixture resembles coarse crumbs." },
      { order: 4, instruction: "Stir in 3/4 cup heavy cream and 1/2 teaspoon vanilla extract until just combined. Do not overmix." },
      { order: 5, instruction: "Turn dough out onto a lightly floured surface and gently pat into a 3/4-inch thick rectangle." },
      { order: 6, instruction: "Using a 3-inch round biscuit cutter, cut out biscuits and place on the prepared baking sheet. Gather scraps, gently pat out again, and cut more biscuits." },
      { order: 7, instruction: "Brush the tops of the biscuits with the remaining 2 tablespoons heavy cream." },
      { order: 8, instruction: "Bake for 12-15 minutes, until golden brown. Transfer to a wire rack to cool." },
      { order: 9, instruction: "While biscuits are baking, combine sliced strawberries, 2 tablespoons sugar, and lemon juice in a bowl. Let sit for at least 30 minutes to macerate." },
      { order: 10, instruction: "In a chilled bowl, whip 1 1/2 cups heavy cream with powdered sugar and remaining 1/2 teaspoon vanilla extract until soft peaks form." },
      { order: 11, instruction: "To assemble: Split each biscuit horizontally. Place the bottom half on a plate, top with a generous spoonful of macerated strawberries and their juice, then a dollop of whipped cream." },
      { order: 12, instruction: "Place the top half of the biscuit on the whipped cream, add more strawberries and another dollop of whipped cream." },
      { order: 13, instruction: "Garnish with fresh mint leaves if desired." },
      { order: 14, instruction: "Serve immediately." }
    ],
    cookingVessel: "Baking Sheet",
    prepTime: 25,
    cookTime: 15,
    servings: 8,
    difficulty: "Medium",
    mealType: "Dessert",
    cuisine: "American",
    categories: ["Fruit Desserts", "Biscuit Desserts"],
    dietaryCategories: ["Vegetarian"],
    tags: ["strawberry", "shortcake", "summer dessert", "biscuits"],
    imageUrl: "https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b"
  },
  {
    title: "Peach Cobbler",
    description: "A rustic Southern dessert featuring juicy, spiced peaches topped with a sweet biscuit-like crust that's golden and crisp on top, soft and cake-like underneath.",
    ingredients: [
      { name: "fresh peaches", quantity: "8", unit: "cups", notes: "peeled, pitted, and sliced (about 8-10 peaches)" },
      { name: "granulated sugar", quantity: "1", unit: "cup", notes: "divided" },
      { name: "brown sugar", quantity: "1/4", unit: "cup", notes: "packed" },
      { name: "lemon juice", quantity: "1", unit: "tablespoon" },
      { name: "ground cinnamon", quantity: "1", unit: "teaspoon" },
      { name: "ground nutmeg", quantity: "1/4", unit: "teaspoon" },
      { name: "cornstarch", quantity: "2", unit: "tablespoons" },
      { name: "all-purpose flour", quantity: "1 1/2", unit: "cups" },
      { name: "baking powder", quantity: "2", unit: "teaspoons" },
      { name: "salt", quantity: "1/2", unit: "teaspoon" },
      { name: "unsalted butter", quantity: "1/2", unit: "cup", notes: "cold, cubed" },
      { name: "boiling water", quantity: "1/4", unit: "cup" },
      { name: "vanilla ice cream", quantity: "1", unit: "pint", notes: "for serving, optional" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 375°F (190°C). Butter a 9x13 inch baking dish." },
      { order: 2, instruction: "In a large bowl, combine sliced peaches, 1/2 cup granulated sugar, brown sugar, lemon juice, cinnamon, nutmeg, and cornstarch. Toss gently to coat peaches evenly." },
      { order: 3, instruction: "Pour peach mixture into the prepared baking dish and bake for 10 minutes." },
      { order: 4, instruction: "While peaches are baking, prepare the topping: In a medium bowl, whisk together flour, remaining 1/2 cup granulated sugar, baking powder, and salt." },
      { order: 5, instruction: "Using a pastry cutter or your fingers, cut in cold butter until the mixture resembles coarse crumbs." },
      { order: 6, instruction: "Stir in boiling water just until combined. The dough will be slightly sticky." },
      { order: 7, instruction: "Remove peaches from the oven and drop spoonfuls of the dough evenly over the hot peach mixture." },
      { order: 8, instruction: "Return to the oven and bake for 30-35 minutes, until the topping is golden brown and the peach filling is bubbly." },
      { order: 9, instruction: "Let cool for 10 minutes before serving." },
      { order: 10, instruction: "Serve warm with a scoop of vanilla ice cream if desired." }
    ],
    cookingVessel: "Baking Dish",
    prepTime: 25,
    cookTime: 45,
    servings: 8,
    difficulty: "Easy",
    mealType: "Dessert",
    cuisine: "Southern",
    categories: ["Fruit Desserts", "Cobblers"],
    dietaryCategories: ["Vegetarian"],
    tags: ["peach", "cobbler", "southern dessert", "summer dessert"],
    imageUrl: "https://images.unsplash.com/photo-1639744211487-b27096e2e7e6"
  },
  {
    title: "Chocolate Mousse",
    description: "A light and airy chocolate dessert with a silky-smooth texture and rich chocolate flavor, perfect for a sophisticated finish to any meal.",
    ingredients: [
      { name: "semi-sweet chocolate", quantity: "8", unit: "ounces", notes: "chopped" },
      { name: "unsalted butter", quantity: "3", unit: "tablespoons" },
      { name: "eggs", quantity: "4", unit: "large", notes: "separated" },
      { name: "granulated sugar", quantity: "1/4", unit: "cup" },
      { name: "heavy cream", quantity: "1", unit: "cup" },
      { name: "vanilla extract", quantity: "1", unit: "teaspoon" },
      { name: "salt", quantity: "1/8", unit: "teaspoon" },
      { name: "chocolate shavings", quantity: "2", unit: "tablespoons", notes: "for garnish" },
      { name: "fresh raspberries", quantity: "1", unit: "cup", notes: "for garnish, optional" },
      { name: "mint leaves", quantity: "2", unit: "tablespoons", notes: "for garnish, optional" }
    ],
    steps: [
      { order: 1, instruction: "In a heatproof bowl set over a pot of simmering water (double boiler), melt chocolate and butter together, stirring occasionally until smooth. Remove from heat and let cool slightly." },
      { order: 2, instruction: "In a separate bowl, whisk egg yolks until slightly thickened. Gradually add 2 tablespoons of sugar, whisking until pale and thick." },
      { order: 3, instruction: "Slowly whisk the melted chocolate mixture into the egg yolk mixture until well combined." },
      { order: 4, instruction: "In a clean bowl, beat heavy cream and vanilla extract until soft peaks form. Set aside." },
      { order: 5, instruction: "In another clean bowl, beat egg whites and salt until foamy. Gradually add the remaining 2 tablespoons of sugar and continue beating until stiff peaks form." },
      { order: 6, instruction: "Gently fold the whipped cream into the chocolate mixture until mostly combined." },
      { order: 7, instruction: "Fold in the egg whites in two additions, being careful not to deflate the mixture." },
      { order: 8, instruction: "Divide the mousse among 6 serving glasses or ramekins." },
      { order: 9, instruction: "Cover with plastic wrap and refrigerate for at least 4 hours or overnight." },
      { order: 10, instruction: "Before serving, garnish with chocolate shavings, fresh raspberries, and mint leaves if desired." }
    ],
    cookingVessel: "Mixing Bowls",
    prepTime: 25,
    cookTime: 10,
    servings: 6,
    difficulty: "Medium",
    mealType: "Dessert",
    cuisine: "French",
    categories: ["Chocolate Desserts", "Mousse"],
    dietaryCategories: ["Vegetarian", "Gluten-Free"],
    tags: ["chocolate", "mousse", "elegant dessert", "make ahead"],
    imageUrl: "https://images.unsplash.com/photo-1511715112108-9acc5793e1a3"
  },
  {
    title: "Key Lime Pie",
    description: "A refreshing dessert featuring a tangy lime filling in a graham cracker crust, topped with sweetened whipped cream for a perfect balance of sweet and tart flavors.",
    ingredients: [
      { name: "graham crackers", quantity: "1 1/2", unit: "cups", notes: "crushed into crumbs" },
      { name: "granulated sugar", quantity: "1/4", unit: "cup", notes: "for crust" },
      { name: "unsalted butter", quantity: "6", unit: "tablespoons", notes: "melted" },
      { name: "sweetened condensed milk", quantity: "2", unit: "14-ounce cans" },
      { name: "key lime juice", quantity: "3/4", unit: "cup", notes: "fresh or bottled" },
      { name: "lime zest", quantity: "1", unit: "tablespoon", notes: "plus more for garnish" },
      { name: "egg yolks", quantity: "4", unit: "large" },
      { name: "heavy cream", quantity: "1", unit: "cup" },
      { name: "powdered sugar", quantity: "2", unit: "tablespoons" },
      { name: "vanilla extract", quantity: "1/2", unit: "teaspoon" },
      { name: "lime slices", quantity: "6", unit: "", notes: "for garnish" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 350°F (175°C)." },
      { order: 2, instruction: "In a medium bowl, combine graham cracker crumbs, 1/4 cup sugar, and melted butter. Press firmly into the bottom and up the sides of a 9-inch pie dish." },
      { order: 3, instruction: "Bake crust for 8-10 minutes until lightly golden. Remove from oven and let cool." },
      { order: 4, instruction: "Reduce oven temperature to 325°F (165°C)." },
      { order: 5, instruction: "In a large bowl, whisk together sweetened condensed milk, key lime juice, lime zest, and egg yolks until well combined." },
      { order: 6, instruction: "Pour filling into the cooled crust." },
      { order: 7, instruction: "Bake for 15-17 minutes until the center is set but still slightly jiggly." },
      { order: 8, instruction: "Remove from oven and let cool completely at room temperature." },
      { order: 9, instruction: "Refrigerate for at least 3 hours or overnight." },
      { order: 10, instruction: "Before serving, whip heavy cream with powdered sugar and vanilla extract until stiff peaks form." },
      { order: 11, instruction: "Spread or pipe whipped cream over the chilled pie." },
      { order: 12, instruction: "Garnish with additional lime zest and lime slices." },
      { order: 13, instruction: "Serve chilled." }
    ],
    cookingVessel: "Pie Dish",
    prepTime: 20,
    cookTime: 25,
    servings: 8,
    difficulty: "Easy",
    mealType: "Dessert",
    cuisine: "American",
    categories: ["Pies", "Citrus Desserts"],
    dietaryCategories: ["Vegetarian"],
    tags: ["key lime", "pie", "citrus", "graham cracker crust"],
    imageUrl: "https://images.unsplash.com/photo-1519915028121-7d3463d5b1ff"
  },
  {
    title: "Panna Cotta with Berry Compote",
    description: "A silky-smooth Italian custard dessert with a delicate vanilla flavor, topped with a vibrant mixed berry compote for a perfect contrast of textures and flavors.",
    ingredients: [
      { name: "heavy cream", quantity: "2", unit: "cups" },
      { name: "whole milk", quantity: "1", unit: "cup" },
      { name: "granulated sugar", quantity: "1/2", unit: "cup", notes: "divided" },
      { name: "vanilla bean", quantity: "1", unit: "", notes: "split lengthwise and seeds scraped" },
      { name: "gelatin", quantity: "2 1/2", unit: "teaspoons", notes: "unflavored" },
      { name: "cold water", quantity: "3", unit: "tablespoons" },
      { name: "mixed berries", quantity: "3", unit: "cups", notes: "fresh or frozen (strawberries, blueberries, raspberries, blackberries)" },
      { name: "lemon juice", quantity: "1", unit: "tablespoon" },
      { name: "cornstarch", quantity: "1", unit: "teaspoon" },
      { name: "water", quantity: "1", unit: "tablespoon", notes: "for cornstarch slurry" },
      { name: "fresh mint leaves", quantity: "2", unit: "tablespoons", notes: "for garnish" }
    ],
    steps: [
      { order: 1, instruction: "In a small bowl, sprinkle gelatin over cold water and let stand for 5 minutes to soften." },
      { order: 2, instruction: "In a medium saucepan, combine heavy cream, milk, 1/4 cup sugar, vanilla bean pod, and scraped seeds. Heat over medium until it just begins to simmer, stirring occasionally to dissolve sugar." },
      { order: 3, instruction: "Remove from heat and discard vanilla bean pod." },
      { order: 4, instruction: "Add softened gelatin to the hot cream mixture and stir until completely dissolved." },
      { order: 5, instruction: "Pour mixture through a fine-mesh sieve into a large measuring cup or bowl with a pouring spout." },
      { order: 6, instruction: "Divide mixture evenly among 6 ramekins or serving glasses." },
      { order: 7, instruction: "Cover with plastic wrap and refrigerate for at least 4 hours or overnight until set." },
      { order: 8, instruction: "For the berry compote: In a medium saucepan, combine mixed berries, remaining 1/4 cup sugar, and lemon juice. Bring to a simmer over medium heat." },
      { order: 9, instruction: "Cook for 5-7 minutes until berries begin to break down and release their juices." },
      { order: 10, instruction: "In a small bowl, mix cornstarch with 1 tablespoon water to create a slurry." },
      { order: 11, instruction: "Stir cornstarch slurry into the berry mixture and cook for 1-2 minutes more until slightly thickened." },
      { order: 12, instruction: "Remove from heat and let cool completely." },
      { order: 13, instruction: "To serve: If using ramekins, run a thin knife around the edge of each panna cotta and invert onto serving plates. If using glasses, serve as is." },
      { order: 14, instruction: "Spoon berry compote over each panna cotta and garnish with fresh mint leaves." }
    ],
    cookingVessel: "Ramekins",
    prepTime: 20,
    cookTime: 15,
    servings: 6,
    difficulty: "Medium",
    mealType: "Dessert",
    cuisine: "Italian",
    categories: ["Custards", "Elegant Desserts"],
    dietaryCategories: ["Vegetarian", "Gluten-Free"],
    tags: ["panna cotta", "berry compote", "italian dessert", "make ahead"],
    imageUrl: "https://images.unsplash.com/photo-1488477181946-6428a0291777"
  },
  {
    title: "Baklava",
    description: "A rich, sweet pastry made of layers of flaky phyllo dough filled with chopped nuts and sweetened with a honey syrup infused with cinnamon and citrus.",
    ingredients: [
      { name: "phyllo dough", quantity: "1", unit: "16-ounce package", notes: "thawed according to package instructions" },
      { name: "walnuts", quantity: "1", unit: "pound", notes: "finely chopped" },
      { name: "pistachios", quantity: "1/2", unit: "cup", notes: "finely chopped" },
      { name: "granulated sugar", quantity: "1", unit: "cup", notes: "divided" },
      { name: "ground cinnamon", quantity: "1 1/2", unit: "teaspoons" },
      { name: "ground cardamom", quantity: "1/2", unit: "teaspoon" },
      { name: "unsalted butter", quantity: "1 1/2", unit: "cups", notes: "melted" },
      { name: "honey", quantity: "1", unit: "cup" },
      { name: "water", quantity: "1/2", unit: "cup" },
      { name: "lemon juice", quantity: "1", unit: "tablespoon" },
      { name: "orange zest", quantity: "1", unit: "teaspoon" },
      { name: "vanilla extract", quantity: "1", unit: "teaspoon" },
      { name: "whole cloves", quantity: "4", unit: "" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 350°F (175°C). Butter a 9x13 inch baking dish." },
      { order: 2, instruction: "In a large bowl, combine chopped walnuts, pistachios, 1/4 cup sugar, cinnamon, and cardamom. Set aside." },
      { order: 3, instruction: "Unroll phyllo dough and trim to fit the baking dish if necessary. Cover with a damp cloth to prevent drying out." },
      { order: 4, instruction: "Place 2 sheets of phyllo in the bottom of the prepared baking dish and brush generously with melted butter. Repeat this process until you have used 8 sheets." },
      { order: 5, instruction: "Sprinkle 1/3 of the nut mixture evenly over the phyllo layers." },
      { order: 6, instruction: "Add 2 more sheets of phyllo, brush with butter, and repeat until you have used 4 sheets. Sprinkle with another 1/3 of the nut mixture." },
      { order: 7, instruction: "Repeat step 6 once more." },
      { order: 8, instruction: "Top with remaining phyllo sheets, adding 2 at a time and brushing each layer with butter, until all sheets are used." },
      { order: 9, instruction: "Brush the top layer generously with butter." },
      { order: 10, instruction: "Using a sharp knife, cut the baklava into diamond or square shapes, making sure to cut all the way to the bottom of the dish." },
      { order: 11, instruction: "Bake for 45-50 minutes, until golden brown and crisp." },
      { order: 12, instruction: "While the baklava is baking, make the syrup: In a medium saucepan, combine remaining 3/4 cup sugar, honey, water, lemon juice, orange zest, vanilla extract, and cloves. Bring to a boil, then reduce heat and simmer for 10 minutes. Remove cloves and let cool slightly." },
      { order: 13, instruction: "When the baklava is done, remove from oven and immediately pour the warm syrup evenly over the hot baklava." },
      { order: 14, instruction: "Let cool completely, uncovered, at room temperature for at least 4 hours or overnight to allow the syrup to be absorbed and the flavors to meld." },
      { order: 15, instruction: "Serve at room temperature." }
    ],
    cookingVessel: "Baking Dish",
    prepTime: 40,
    cookTime: 50,
    servings: 24,
    difficulty: "Medium",
    mealType: "Dessert",
    cuisine: "Middle Eastern",
    categories: ["Pastries", "Nut Desserts"],
    dietaryCategories: ["Vegetarian"],
    tags: ["baklava", "phyllo", "honey", "nuts"],
    imageUrl: "https://images.unsplash.com/photo-1519676867240-f03562e64548"
  },
  {
    title: "Chocolate Soufflé",
    description: "A light and airy chocolate dessert that rises dramatically in the oven, with a crisp exterior and a warm, pudding-like center for an impressive finale to any special meal.",
    ingredients: [
      { name: "unsalted butter", quantity: "2", unit: "tablespoons", notes: "softened, for ramekins" },
      { name: "granulated sugar", quantity: "1/4", unit: "cup", notes: "divided, plus more for ramekins" },
      { name: "semi-sweet chocolate", quantity: "6", unit: "ounces", notes: "chopped" },
      { name: "egg yolks", quantity: "3", unit: "large" },
      { name: "vanilla extract", quantity: "1/2", unit: "teaspoon" },
      { name: "salt", quantity: "1/8", unit: "teaspoon" },
      { name: "egg whites", quantity: "5", unit: "large", notes: "at room temperature" },
      { name: "cream of tartar", quantity: "1/4", unit: "teaspoon" },
      { name: "powdered sugar", quantity: "2", unit: "tablespoons", notes: "for dusting" },
      { name: "vanilla ice cream", quantity: "1", unit: "pint", notes: "for serving, optional" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 375°F (190°C). Place a baking sheet in the oven to heat." },
      { order: 2, instruction: "Butter six 6-ounce ramekins thoroughly, then coat with granulated sugar, tapping out excess." },
      { order: 3, instruction: "In a heatproof bowl set over a pot of simmering water (double boiler), melt chocolate, stirring occasionally until smooth. Remove from heat and let cool slightly." },
      { order: 4, instruction: "In a medium bowl, whisk together egg yolks, 2 tablespoons sugar, vanilla extract, and salt until pale and thick." },
      { order: 5, instruction: "Gradually whisk the melted chocolate into the egg yolk mixture until well combined." },
      { order: 6, instruction: "In a clean bowl with clean beaters, beat egg whites and cream of tartar on medium speed until foamy." },
      { order: 7, instruction: "Gradually add the remaining 2 tablespoons sugar and continue beating on high speed until stiff, glossy peaks form." },
      { order: 8, instruction: "Gently fold 1/4 of the egg whites into the chocolate mixture to lighten it." },
      { order: 9, instruction: "Fold in the remaining egg whites in two additions, being careful not to deflate the mixture." },
      { order: 10, instruction: "Divide the batter among the prepared ramekins, filling them to about 1/4 inch from the top." },
      { order: 11, instruction: "Run your thumb around the inside edge of each ramekin to create a small channel (this helps the soufflés rise evenly)." },
      { order: 12, instruction: "Place ramekins on the preheated baking sheet and immediately reduce oven temperature to 350°F (175°C)." },
      { order: 13, instruction: "Bake for 12-14 minutes until soufflés have risen about 1-2 inches above the rims and the tops are set but centers are still slightly jiggly." },
      { order: 14, instruction: "Dust with powdered sugar and serve immediately, with a scoop of vanilla ice cream on the side if desired." }
    ],
    cookingVessel: "Ramekins",
    prepTime: 25,
    cookTime: 14,
    servings: 6,
    difficulty: "Hard",
    mealType: "Dessert",
    cuisine: "French",
    categories: ["Chocolate Desserts", "Soufflés"],
    dietaryCategories: ["Vegetarian", "Gluten-Free"],
    tags: ["soufflé", "chocolate", "elegant dessert", "special occasion"],
    imageUrl: "https://images.unsplash.com/photo-1470124182917-cc6e71b22ecc"
  },
  {
    title: "Bananas Foster",
    description: "A dramatic dessert where bananas are caramelized in a buttery brown sugar sauce, flambéed with rum, and served over vanilla ice cream for a spectacular presentation.",
    ingredients: [
      { name: "unsalted butter", quantity: "4", unit: "tablespoons" },
      { name: "brown sugar", quantity: "1/2", unit: "cup", notes: "packed" },
      { name: "ground cinnamon", quantity: "1/2", unit: "teaspoon" },
      { name: "bananas", quantity: "4", unit: "ripe", notes: "peeled and sliced lengthwise" },
      { name: "dark rum", quantity: "1/4", unit: "cup" },
      { name: "banana liqueur", quantity: "2", unit: "tablespoons", notes: "optional" },
      { name: "vanilla ice cream", quantity: "1", unit: "pint" },
      { name: "chopped walnuts", quantity: "1/4", unit: "cup", notes: "toasted, for garnish" }
    ],
    steps: [
      { order: 1, instruction: "Scoop vanilla ice cream into serving dishes and place in the freezer until ready to serve." },
      { order: 2, instruction: "In a large skillet over medium heat, melt butter." },
      { order: 3, instruction: "Add brown sugar and cinnamon, stirring until sugar dissolves, about 2-3 minutes." },
      { order: 4, instruction: "Add banana slices to the skillet and cook for 1-2 minutes on each side until they begin to soften and caramelize." },
      { order: 5, instruction: "Remove the skillet from the heat source." },
      { order: 6, instruction: "Add rum and banana liqueur (if using). Carefully ignite the mixture with a long match or lighter (stand back when doing this)." },
      { order: 7, instruction: "Allow the flames to subside, which will burn off the alcohol but leave the flavor." },
      { order: 8, instruction: "Return the skillet to low heat and cook for another minute, basting the bananas with the sauce." },
      { order: 9, instruction: "Remove ice cream from freezer and divide among serving dishes." },
      { order: 10, instruction: "Spoon the warm bananas and sauce over the ice cream." },
      { order: 11, instruction: "Garnish with toasted walnuts and serve immediately." }
    ],
    cookingVessel: "Skillet",
    prepTime: 10,
    cookTime: 10,
    servings: 4,
    difficulty: "Medium",
    mealType: "Dessert",
    cuisine: "American",
    categories: ["Flambéed Desserts", "Fruit Desserts"],
    dietaryCategories: ["Vegetarian", "Gluten-Free"],
    tags: ["bananas foster", "flambé", "rum", "ice cream"],
    imageUrl: "https://images.unsplash.com/photo-1488477304112-4944851de03d"
  },
  {
    title: "Raspberry Almond Tart",
    description: "An elegant dessert featuring a buttery almond crust filled with almond cream and topped with fresh raspberries, finished with a glossy apricot glaze.",
    ingredients: [
      { name: "all-purpose flour", quantity: "1 1/2", unit: "cups" },
      { name: "almond flour", quantity: "1/2", unit: "cup" },
      { name: "granulated sugar", quantity: "1/3", unit: "cup" },
      { name: "salt", quantity: "1/4", unit: "teaspoon" },
      { name: "unsalted butter", quantity: "10", unit: "tablespoons", notes: "cold, cubed" },
      { name: "egg yolk", quantity: "1", unit: "large" },
      { name: "ice water", quantity: "2", unit: "tablespoons" },
      { name: "almond extract", quantity: "1/2", unit: "teaspoon" },
      { name: "unsalted butter", quantity: "6", unit: "tablespoons", notes: "softened, for filling" },
      { name: "granulated sugar", quantity: "1/2", unit: "cup", notes: "for filling" },
      { name: "almond flour", quantity: "1", unit: "cup", notes: "for filling" },
      { name: "eggs", quantity: "2", unit: "large", notes: "for filling" },
      { name: "vanilla extract", quantity: "1", unit: "teaspoon", notes: "for filling" },
      { name: "almond extract", quantity: "1/4", unit: "teaspoon", notes: "for filling" },
      { name: "fresh raspberries", quantity: "2", unit: "cups" },
      { name: "apricot preserves", quantity: "1/4", unit: "cup" },
      { name: "water", quantity: "1", unit: "tablespoon" },
      { name: "sliced almonds", quantity: "1/4", unit: "cup", notes: "toasted, for garnish" },
      { name: "powdered sugar", quantity: "2", unit: "tablespoons", notes: "for dusting" }
    ],
    steps: [
      { order: 1, instruction: "For the crust: In a food processor, combine all-purpose flour, 1/2 cup almond flour, 1/3 cup sugar, and salt. Pulse to combine." },
      { order: 2, instruction: "Add cold butter cubes and pulse until mixture resembles coarse crumbs." },
      { order: 3, instruction: "In a small bowl, whisk together egg yolk, ice water, and 1/2 teaspoon almond extract. Drizzle over flour mixture and pulse just until dough begins to come together." },
      { order: 4, instruction: "Turn dough out onto a lightly floured surface, form into a disk, wrap in plastic, and refrigerate for at least 1 hour." },
      { order: 5, instruction: "Preheat oven to 375°F (190°C)." },
      { order: 6, instruction: "Roll out dough on a lightly floured surface to a 12-inch circle. Transfer to a 9-inch tart pan with a removable bottom. Press dough into the pan and trim excess. Prick the bottom with a fork." },
      { order: 7, instruction: "Line the crust with parchment paper and fill with pie weights or dried beans. Bake for 15 minutes." },
      { order: 8, instruction: "Remove weights and parchment, and bake for an additional 5-7 minutes until lightly golden. Let cool slightly." },
      { order: 9, instruction: "For the filling: In a medium bowl, beat 6 tablespoons softened butter and 1/2 cup sugar until light and fluffy." },
      { order: 10, instruction: "Beat in 1 cup almond flour, then eggs one at a time, followed by vanilla extract and 1/4 teaspoon almond extract." },
      { order: 11, instruction: "Spread almond filling evenly in the partially baked tart shell." },
      { order: 12, instruction: "Bake for 25-30 minutes until filling is set and golden brown. Let cool completely." },
      { order: 13, instruction: "Arrange fresh raspberries on top of the cooled tart." },
      { order: 14, instruction: "In a small saucepan, heat apricot preserves and water until melted and smooth. Strain if necessary." },
      { order: 15, instruction: "Brush the warm apricot glaze over the raspberries." },
      { order: 16, instruction: "Sprinkle toasted sliced almonds around the edge of the tart and dust with powdered sugar before serving." }
    ],
    cookingVessel: "Tart Pan",
    prepTime: 30,
    cookTime: 50,
    servings: 8,
    difficulty: "Medium",
    mealType: "Dessert",
    cuisine: "French",
    categories: ["Tarts", "Fruit Desserts"],
    dietaryCategories: ["Vegetarian"],
    tags: ["raspberry", "almond", "tart", "elegant dessert"],
    imageUrl: "https://images.unsplash.com/photo-1464305795204-6f5bbfc7fb81"
  },
  {
    title: "Churros with Chocolate Dipping Sauce",
    description: "Crispy on the outside, soft on the inside Spanish-style fried dough pastries, coated in cinnamon sugar and served with a rich chocolate dipping sauce.",
    ingredients: [
      { name: "water", quantity: "1", unit: "cup" },
      { name: "unsalted butter", quantity: "1/2", unit: "cup" },
      { name: "granulated sugar", quantity: "1", unit: "tablespoon", notes: "for dough" },
      { name: "salt", quantity: "1/4", unit: "teaspoon" },
      { name: "all-purpose flour", quantity: "1", unit: "cup" },
      { name: "eggs", quantity: "3", unit: "large" },
      { name: "vanilla extract", quantity: "1/2", unit: "teaspoon" },
      { name: "vegetable oil", quantity: "2", unit: "quarts", notes: "for frying" },
      { name: "granulated sugar", quantity: "1/2", unit: "cup", notes: "for coating" },
      { name: "ground cinnamon", quantity: "1", unit: "tablespoon", notes: "for coating" },
      { name: "semi-sweet chocolate", quantity: "6", unit: "ounces", notes: "chopped" },
      { name: "heavy cream", quantity: "1/2", unit: "cup" },
      { name: "cinnamon stick", quantity: "1", unit: "" },
      { name: "vanilla extract", quantity: "1/2", unit: "teaspoon", notes: "for sauce" }
    ],
    steps: [
      { order: 1, instruction: "For the chocolate sauce: In a small saucepan, heat heavy cream and cinnamon stick until it just begins to simmer. Remove from heat and let steep for 10 minutes." },
      { order: 2, instruction: "Remove cinnamon stick. Return cream to low heat and add chopped chocolate. Stir until chocolate is melted and mixture is smooth." },
      { order: 3, instruction: "Stir in 1/2 teaspoon vanilla extract. Keep warm or reheat gently before serving." },
      { order: 4, instruction: "For the churros: In a medium saucepan, combine water, butter, 1 tablespoon sugar, and salt. Bring to a boil over medium-high heat." },
      { order: 5, instruction: "Reduce heat to low and add flour all at once. Stir vigorously with a wooden spoon until the mixture forms a ball and pulls away from the sides of the pan, about 1 minute." },
      { order: 6, instruction: "Remove from heat and let cool for 5 minutes." },
      { order: 7, instruction: "Add eggs one at a time, beating well after each addition until the dough is smooth and glossy." },
      { order: 8, instruction: "Stir in 1/2 teaspoon vanilla extract." },
      { order: 9, instruction: "Transfer dough to a piping bag fitted with a large star tip." },
      { order: 10, instruction: "In a small bowl, mix 1/2 cup sugar and 1 tablespoon cinnamon. Set aside." },
      { order: 11, instruction: "Heat oil in a large, heavy pot or deep fryer to 375°F (190°C)." },
      { order: 12, instruction: "Pipe 4-inch lengths of dough directly into the hot oil, cutting the end with scissors. Work in batches of 4-5 churros at a time." },
      { order: 13, instruction: "Fry until golden brown, turning occasionally, about 2 minutes per batch." },
      { order: 14, instruction: "Remove with a slotted spoon and drain briefly on paper towels." },
      { order: 15, instruction: "While still hot, roll churros in the cinnamon-sugar mixture to coat." },
      { order: 16, instruction: "Serve warm with chocolate dipping sauce." }
    ],
    cookingVessel: "Deep Fryer",
    prepTime: 20,
    cookTime: 20,
    servings: 24,
    difficulty: "Medium",
    mealType: "Dessert",
    cuisine: "Spanish",
    categories: ["Fried Desserts", "Pastries"],
    dietaryCategories: ["Vegetarian"],
    tags: ["churros", "chocolate sauce", "fried dough", "cinnamon sugar"],
    imageUrl: "https://images.unsplash.com/photo-1624371414361-e670edf4898d"
  },
  {
    title: "Coconut Flan",
    description: "A tropical twist on the classic custard dessert, featuring rich coconut flavor and a golden caramel sauce that forms as the flan bakes and is inverted onto a serving plate.",
    ingredients: [
      { name: "granulated sugar", quantity: "1", unit: "cup", notes: "for caramel" },
      { name: "water", quantity: "1/4", unit: "cup", notes: "for caramel" },
      { name: "eggs", quantity: "5", unit: "large" },
      { name: "sweetened condensed milk", quantity: "1", unit: "14-ounce can" },
      { name: "coconut milk", quantity: "1", unit: "13.5-ounce can" },
      { name: "whole milk", quantity: "1", unit: "cup" },
      { name: "vanilla extract", quantity: "1", unit: "teaspoon" },
      { name: "coconut extract", quantity: "1/2", unit: "teaspoon" },
      { name: "salt", quantity: "1/4", unit: "teaspoon" },
      { name: "shredded coconut", quantity: "1/2", unit: "cup", notes: "toasted, for garnish" },
      { name: "fresh berries", quantity: "1", unit: "cup", notes: "for garnish, optional" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 350°F (175°C)." },
      { order: 2, instruction: "For the caramel: In a medium saucepan, combine 1 cup sugar and 1/4 cup water. Cook over medium heat, without stirring, until sugar dissolves and turns a deep amber color, about 8-10 minutes." },
      { order: 3, instruction: "Immediately pour caramel into a 9-inch round cake pan or 8-10 individual ramekins, tilting to coat the bottom evenly. Set aside to cool and harden." },
      { order: 4, instruction: "In a large bowl, whisk eggs until well beaten." },
      { order: 5, instruction: "Add sweetened condensed milk, coconut milk, whole milk, vanilla extract, coconut extract, and salt. Whisk until well combined." },
      { order: 6, instruction: "Pour mixture through a fine-mesh sieve into the caramel-lined cake pan or divide among ramekins." },
      { order: 7, instruction: "Place the cake pan or ramekins in a larger baking dish. Fill the larger dish with hot water to reach halfway up the sides of the pan or ramekins (water bath)." },
      { order: 8, instruction: "Bake for 50-60 minutes for a large flan (or 30-35 minutes for individual ramekins), until the center is just set but still slightly jiggly." },
      { order: 9, instruction: "Remove from water bath and let cool to room temperature." },
      { order: 10, instruction: "Refrigerate for at least 4 hours or overnight." },
      { order: 11, instruction: "To serve, run a thin knife around the edge of the flan. Place a serving plate with a rim over the pan and quickly invert. The flan should release easily and the caramel will flow over and around it." },
      { order: 12, instruction: "Garnish with toasted coconut and fresh berries if desired." }
    ],
    cookingVessel: "Cake Pan",
    prepTime: 20,
    cookTime: 60,
    servings: 8,
    difficulty: "Medium",
    mealType: "Dessert",
    cuisine: "Latin American",
    categories: ["Custards", "Caramel Desserts"],
    dietaryCategories: ["Vegetarian", "Gluten-Free"],
    tags: ["flan", "coconut", "caramel", "custard"],
    imageUrl: "https://images.unsplash.com/photo-1551879400-111a9087cd86"
  }
];

export default dessertRecipes;
