// Dinner Recipes for WhatAboutDinner App
// 20 detailed dinner recipes with all required fields

const dinnerRecipes = [
  {
    title: "Spaghetti Bolognese",
    description: "A classic Italian pasta dish featuring a rich and hearty meat sauce simmered with tomatoes, herbs, and aromatics, served over al dente spaghetti.",
    ingredients: [
      { name: "spaghetti", quantity: "1", unit: "pound" },
      { name: "ground beef", quantity: "1", unit: "pound" },
      { name: "onion", quantity: "1", unit: "medium", notes: "finely diced" },
      { name: "carrot", quantity: "1", unit: "medium", notes: "finely diced" },
      { name: "celery", quantity: "1", unit: "stalk", notes: "finely diced" },
      { name: "garlic", quantity: "3", unit: "cloves", notes: "minced" },
      { name: "tomato paste", quantity: "2", unit: "tablespoons" },
      { name: "crushed tomatoes", quantity: "1", unit: "28-ounce can" },
      { name: "beef broth", quantity: "1/2", unit: "cup" },
      { name: "red wine", quantity: "1/2", unit: "cup", notes: "optional" },
      { name: "dried oregano", quantity: "1", unit: "teaspoon" },
      { name: "dried basil", quantity: "1", unit: "teaspoon" },
      { name: "bay leaf", quantity: "1", unit: "" },
      { name: "salt", quantity: "1", unit: "teaspoon" },
      { name: "black pepper", quantity: "1/2", unit: "teaspoon" },
      { name: "olive oil", quantity: "2", unit: "tablespoons" },
      { name: "parmesan cheese", quantity: "1/2", unit: "cup", notes: "grated, for serving" },
      { name: "fresh basil", quantity: "2", unit: "tablespoons", notes: "chopped, for garnish" }
    ],
    steps: [
      { order: 1, instruction: "Heat olive oil in a large Dutch oven or heavy-bottomed pot over medium heat." },
      { order: 2, instruction: "Add onion, carrot, and celery. Cook until softened, about 5-7 minutes." },
      { order: 3, instruction: "Add garlic and cook for 30 seconds until fragrant." },
      { order: 4, instruction: "Increase heat to medium-high and add ground beef. Cook, breaking it up with a spoon, until browned, about 5-7 minutes." },
      { order: 5, instruction: "Add tomato paste and cook for 1-2 minutes, stirring constantly." },
      { order: 6, instruction: "If using, add red wine and simmer until reduced by half, about 2-3 minutes." },
      { order: 7, instruction: "Add crushed tomatoes, beef broth, dried oregano, dried basil, bay leaf, salt, and pepper." },
      { order: 8, instruction: "Bring to a boil, then reduce heat to low. Simmer, partially covered, for at least 30 minutes (or up to 2 hours for deeper flavor), stirring occasionally." },
      { order: 9, instruction: "Meanwhile, bring a large pot of salted water to a boil." },
      { order: 10, instruction: "Cook spaghetti according to package instructions until al dente. Drain, reserving 1/2 cup of pasta water." },
      { order: 11, instruction: "Remove bay leaf from the sauce. If sauce is too thick, add some reserved pasta water to reach desired consistency." },
      { order: 12, instruction: "Taste sauce and adjust seasoning if needed." },
      { order: 13, instruction: "Serve sauce over spaghetti, topped with grated parmesan cheese and fresh basil." }
    ],
    cookingVessel: "Dutch Oven",
    prepTime: 15,
    cookTime: 45,
    servings: 6,
    difficulty: "Medium",
    mealType: "Dinner",
    cuisine: "Italian",
    categories: ["Pasta", "Comfort Food"],
    dietaryCategories: [],
    tags: ["spaghetti", "bolognese", "pasta", "italian"],
    imageUrl: "https://images.unsplash.com/photo-1551892374-ecf8754cf8b0"
  },
  {
    title: "Vegetable Stir-Fry with Tofu",
    description: "A colorful and nutritious stir-fry featuring crispy tofu and a variety of fresh vegetables in a flavorful ginger-garlic sauce, served over steamed rice.",
    ingredients: [
      { name: "extra-firm tofu", quantity: "14", unit: "ounces", notes: "drained and pressed" },
      { name: "cornstarch", quantity: "2", unit: "tablespoons" },
      { name: "soy sauce", quantity: "3", unit: "tablespoons", notes: "divided" },
      { name: "sesame oil", quantity: "2", unit: "tablespoons", notes: "divided" },
      { name: "vegetable oil", quantity: "2", unit: "tablespoons" },
      { name: "broccoli florets", quantity: "2", unit: "cups" },
      { name: "bell peppers", quantity: "2", unit: "medium", notes: "assorted colors, sliced" },
      { name: "carrots", quantity: "2", unit: "medium", notes: "julienned" },
      { name: "snow peas", quantity: "1", unit: "cup" },
      { name: "mushrooms", quantity: "8", unit: "ounces", notes: "sliced" },
      { name: "garlic", quantity: "3", unit: "cloves", notes: "minced" },
      { name: "ginger", quantity: "1", unit: "tablespoon", notes: "minced" },
      { name: "vegetable broth", quantity: "1/4", unit: "cup" },
      { name: "rice vinegar", quantity: "1", unit: "tablespoon" },
      { name: "brown sugar", quantity: "1", unit: "tablespoon" },
      { name: "cornstarch", quantity: "1", unit: "teaspoon", notes: "for sauce" },
      { name: "water", quantity: "1", unit: "tablespoon", notes: "for sauce" },
      { name: "red pepper flakes", quantity: "1/4", unit: "teaspoon", notes: "optional" },
      { name: "green onions", quantity: "3", unit: "", notes: "sliced" },
      { name: "sesame seeds", quantity: "1", unit: "tablespoon", notes: "for garnish" },
      { name: "rice", quantity: "2", unit: "cups", notes: "cooked, for serving" }
    ],
    steps: [
      { order: 1, instruction: "Cut tofu into 1-inch cubes and place in a bowl." },
      { order: 2, instruction: "Toss tofu with 1 tablespoon soy sauce, then sprinkle with cornstarch and toss to coat evenly." },
      { order: 3, instruction: "Heat 1 tablespoon sesame oil and 1 tablespoon vegetable oil in a large wok or skillet over medium-high heat." },
      { order: 4, instruction: "Add tofu and cook, turning occasionally, until crispy and golden on all sides, about 5-7 minutes. Remove to a plate." },
      { order: 5, instruction: "In the same wok, add remaining vegetable oil. Add broccoli and carrots, stir-fry for 3 minutes." },
      { order: 6, instruction: "Add bell peppers, snow peas, and mushrooms. Stir-fry for another 2-3 minutes until vegetables are crisp-tender." },
      { order: 7, instruction: "Add garlic and ginger, stir-fry for 30 seconds until fragrant." },
      { order: 8, instruction: "In a small bowl, whisk together vegetable broth, remaining soy sauce, rice vinegar, brown sugar, 1 teaspoon cornstarch mixed with 1 tablespoon water, and red pepper flakes if using." },
      { order: 9, instruction: "Pour sauce into the wok and bring to a simmer." },
      { order: 10, instruction: "Return tofu to the wok and toss to coat with sauce and vegetables." },
      { order: 11, instruction: "Cook for 1-2 minutes until sauce thickens slightly." },
      { order: 12, instruction: "Stir in green onions and remaining sesame oil." },
      { order: 13, instruction: "Serve over cooked rice, garnished with sesame seeds." }
    ],
    cookingVessel: "Wok",
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    difficulty: "Medium",
    mealType: "Dinner",
    cuisine: "Asian",
    categories: ["Stir-Fry", "Vegetarian"],
    dietaryCategories: ["Vegetarian", "Vegan", "Dairy-Free"],
    tags: ["tofu", "stir-fry", "vegetables", "asian"],
    imageUrl: "https://images.unsplash.com/photo-1512003867696-6d5ce6835040"
  },
  {
    title: "Baked Salmon with Lemon-Dill Sauce",
    description: "Tender baked salmon fillets topped with a creamy lemon-dill sauce, served with roasted vegetables for a healthy and elegant dinner option.",
    ingredients: [
      { name: "salmon fillets", quantity: "4", unit: "6-ounce", notes: "skin-on" },
      { name: "olive oil", quantity: "2", unit: "tablespoons", notes: "divided" },
      { name: "salt", quantity: "1", unit: "teaspoon", notes: "divided" },
      { name: "black pepper", quantity: "1/2", unit: "teaspoon", notes: "divided" },
      { name: "garlic powder", quantity: "1/2", unit: "teaspoon" },
      { name: "lemon", quantity: "1", unit: "", notes: "half sliced, half juiced" },
      { name: "asparagus", quantity: "1", unit: "pound", notes: "trimmed" },
      { name: "cherry tomatoes", quantity: "1", unit: "pint" },
      { name: "Greek yogurt", quantity: "1/2", unit: "cup", notes: "plain" },
      { name: "mayonnaise", quantity: "2", unit: "tablespoons" },
      { name: "fresh dill", quantity: "2", unit: "tablespoons", notes: "chopped" },
      { name: "garlic", quantity: "1", unit: "clove", notes: "minced" },
      { name: "Dijon mustard", quantity: "1", unit: "teaspoon" },
      { name: "honey", quantity: "1", unit: "teaspoon" },
      { name: "capers", quantity: "1", unit: "tablespoon", notes: "drained and roughly chopped" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 400°F (200°C)." },
      { order: 2, instruction: "Line a large baking sheet with parchment paper or aluminum foil." },
      { order: 3, instruction: "Place salmon fillets skin-side down on one side of the baking sheet." },
      { order: 4, instruction: "Brush salmon with 1 tablespoon olive oil and season with 1/2 teaspoon salt, 1/4 teaspoon pepper, and garlic powder." },
      { order: 5, instruction: "Top each fillet with a slice of lemon." },
      { order: 6, instruction: "On the other side of the baking sheet, toss asparagus and cherry tomatoes with remaining olive oil, salt, and pepper." },
      { order: 7, instruction: "Bake for 12-15 minutes, until salmon is cooked through and flakes easily with a fork, and vegetables are tender." },
      { order: 8, instruction: "While everything is baking, make the sauce: In a small bowl, combine Greek yogurt, mayonnaise, dill, minced garlic, Dijon mustard, honey, capers, and juice from the remaining lemon half." },
      { order: 9, instruction: "Stir sauce ingredients until well combined. Season with salt and pepper to taste." },
      { order: 10, instruction: "Serve salmon fillets topped with lemon-dill sauce, alongside the roasted vegetables." }
    ],
    cookingVessel: "Baking Sheet",
    prepTime: 15,
    cookTime: 15,
    servings: 4,
    difficulty: "Easy",
    mealType: "Dinner",
    cuisine: "American",
    categories: ["Seafood", "Healthy"],
    dietaryCategories: ["Gluten-Free", "Low-Carb"],
    tags: ["salmon", "baked", "seafood", "healthy dinner"],
    imageUrl: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2"
  },
  {
    title: "Beef and Vegetable Stew",
    description: "A hearty and comforting stew featuring tender chunks of beef and a variety of vegetables simmered in a rich, flavorful broth, perfect for cold evenings.",
    ingredients: [
      { name: "beef chuck", quantity: "2", unit: "pounds", notes: "cut into 1-inch cubes" },
      { name: "salt", quantity: "1 1/2", unit: "teaspoons", notes: "divided" },
      { name: "black pepper", quantity: "1", unit: "teaspoon", notes: "divided" },
      { name: "all-purpose flour", quantity: "1/3", unit: "cup" },
      { name: "vegetable oil", quantity: "3", unit: "tablespoons", notes: "divided" },
      { name: "onion", quantity: "1", unit: "large", notes: "diced" },
      { name: "carrots", quantity: "4", unit: "medium", notes: "peeled and cut into chunks" },
      { name: "celery", quantity: "3", unit: "stalks", notes: "diced" },
      { name: "garlic", quantity: "4", unit: "cloves", notes: "minced" },
      { name: "tomato paste", quantity: "2", unit: "tablespoons" },
      { name: "red wine", quantity: "1", unit: "cup", notes: "optional" },
      { name: "beef broth", quantity: "4", unit: "cups" },
      { name: "Worcestershire sauce", quantity: "1", unit: "tablespoon" },
      { name: "bay leaves", quantity: "2", unit: "" },
      { name: "dried thyme", quantity: "1", unit: "teaspoon" },
      { name: "dried rosemary", quantity: "1", unit: "teaspoon" },
      { name: "potatoes", quantity: "1", unit: "pound", notes: "Yukon Gold, cut into chunks" },
      { name: "frozen peas", quantity: "1", unit: "cup" },
      { name: "fresh parsley", quantity: "1/4", unit: "cup", notes: "chopped, for garnish" }
    ],
    steps: [
      { order: 1, instruction: "Season beef cubes with 1 teaspoon salt and 1/2 teaspoon pepper, then toss with flour to coat." },
      { order: 2, instruction: "Heat 2 tablespoons oil in a large Dutch oven over medium-high heat." },
      { order: 3, instruction: "Working in batches, brown the beef on all sides, about 3-4 minutes per batch. Transfer to a plate." },
      { order: 4, instruction: "Add remaining oil to the pot. Add onion, carrots, and celery. Cook until softened, about 5 minutes." },
      { order: 5, instruction: "Add garlic and cook for 30 seconds until fragrant." },
      { order: 6, instruction: "Stir in tomato paste and cook for 1 minute." },
      { order: 7, instruction: "If using, add red wine and scrape up any browned bits from the bottom of the pot. Simmer for 2-3 minutes." },
      { order: 8, instruction: "Return beef to the pot and add beef broth, Worcestershire sauce, bay leaves, thyme, rosemary, remaining salt and pepper." },
      { order: 9, instruction: "Bring to a boil, then reduce heat to low. Cover and simmer for 1 hour." },
      { order: 10, instruction: "Add potatoes and continue to simmer, covered, for 30-40 minutes until beef and potatoes are tender." },
      { order: 11, instruction: "Stir in frozen peas and cook for 5 minutes more." },
      { order: 12, instruction: "Remove bay leaves and adjust seasoning if needed." },
      { order: 13, instruction: "Ladle into bowls and garnish with fresh parsley before serving." }
    ],
    cookingVessel: "Dutch Oven",
    prepTime: 25,
    cookTime: 120,
    servings: 6,
    difficulty: "Medium",
    mealType: "Dinner",
    cuisine: "American",
    categories: ["Stews", "Comfort Food"],
    dietaryCategories: ["Dairy-Free"],
    tags: ["beef", "stew", "comfort food", "winter"],
    imageUrl: "https://images.unsplash.com/photo-1608500218890-c4f9a2f2e429"
  },
  {
    title: "Chicken Parmesan",
    description: "A classic Italian-American dish featuring breaded chicken cutlets topped with marinara sauce and melted cheese, served over pasta for a satisfying dinner.",
    ingredients: [
      { name: "chicken breasts", quantity: "4", unit: "", notes: "boneless, skinless, about 2 pounds total" },
      { name: "salt", quantity: "1", unit: "teaspoon", notes: "divided" },
      { name: "black pepper", quantity: "1/2", unit: "teaspoon", notes: "divided" },
      { name: "all-purpose flour", quantity: "1/2", unit: "cup" },
      { name: "eggs", quantity: "2", unit: "large", notes: "beaten" },
      { name: "breadcrumbs", quantity: "1 1/2", unit: "cups", notes: "Italian-style" },
      { name: "parmesan cheese", quantity: "1/2", unit: "cup", notes: "grated, divided" },
      { name: "dried oregano", quantity: "1", unit: "teaspoon" },
      { name: "garlic powder", quantity: "1", unit: "teaspoon" },
      { name: "olive oil", quantity: "1/3", unit: "cup" },
      { name: "marinara sauce", quantity: "2", unit: "cups", notes: "homemade or store-bought" },
      { name: "mozzarella cheese", quantity: "8", unit: "ounces", notes: "sliced or shredded" },
      { name: "fresh basil", quantity: "1/4", unit: "cup", notes: "chopped, plus more for garnish" },
      { name: "spaghetti", quantity: "1", unit: "pound" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 425°F (220°C)." },
      { order: 2, instruction: "Place chicken breasts between sheets of plastic wrap and pound to an even 1/4-inch thickness." },
      { order: 3, instruction: "Season chicken with 1/2 teaspoon salt and 1/4 teaspoon pepper." },
      { order: 4, instruction: "Set up breading station: Place flour in one shallow dish, beaten eggs in a second dish, and combine breadcrumbs, 1/4 cup parmesan cheese, oregano, garlic powder, remaining salt and pepper in a third dish." },
      { order: 5, instruction: "Dredge each chicken breast in flour, shaking off excess, then dip in egg, and finally coat with breadcrumb mixture, pressing to adhere." },
      { order: 6, instruction: "Heat olive oil in a large oven-safe skillet over medium-high heat." },
      { order: 7, instruction: "Cook chicken until golden brown, about 2-3 minutes per side. Work in batches if needed to avoid overcrowding." },
      { order: 8, instruction: "Transfer all chicken to the skillet (if working in batches) or leave in skillet if it all fits." },
      { order: 9, instruction: "Spoon marinara sauce over each chicken breast, then top with mozzarella cheese and remaining parmesan." },
      { order: 10, instruction: "Bake in preheated oven until cheese is melted and bubbly and chicken is cooked through (internal temperature of 165°F/74°C), about 15-20 minutes." },
      { order: 11, instruction: "Meanwhile, cook spaghetti according to package instructions. Drain." },
      { order: 12, instruction: "Sprinkle baked chicken with fresh basil." },
      { order: 13, instruction: "Serve chicken parmesan over spaghetti with additional marinara sauce if desired." }
    ],
    cookingVessel: "Oven-Safe Skillet",
    prepTime: 20,
    cookTime: 30,
    servings: 4,
    difficulty: "Medium",
    mealType: "Dinner",
    cuisine: "Italian-American",
    categories: ["Chicken", "Comfort Food"],
    dietaryCategories: [],
    tags: ["chicken parmesan", "italian", "cheese", "pasta"],
    imageUrl: "https://images.unsplash.com/photo-1632778149955-e80f8ceca2e8"
  },
  {
    title: "Vegetarian Chili",
    description: "A hearty and flavorful vegetarian chili packed with beans, vegetables, and spices, perfect for a satisfying meatless dinner option.",
    ingredients: [
      { name: "olive oil", quantity: "2", unit: "tablespoons" },
      { name: "onion", quantity: "1", unit: "large", notes: "diced" },
      { name: "bell peppers", quantity: "2", unit: "medium", notes: "assorted colors, diced" },
      { name: "carrots", quantity: "2", unit: "medium", notes: "diced" },
      { name: "celery", quantity: "2", unit: "stalks", notes: "diced" },
      { name: "garlic", quantity: "4", unit: "cloves", notes: "minced" },
      { name: "jalapeño", quantity: "1", unit: "small", notes: "seeded and minced (optional)" },
      { name: "chili powder", quantity: "3", unit: "tablespoons" },
      { name: "ground cumin", quantity: "2", unit: "teaspoons" },
      { name: "dried oregano", quantity: "1", unit: "teaspoon" },
      { name: "smoked paprika", quantity: "1", unit: "teaspoon" },
      { name: "black beans", quantity: "2", unit: "15-ounce cans", notes: "drained and rinsed" },
      { name: "kidney beans", quantity: "1", unit: "15-ounce can", notes: "drained and rinsed" },
      { name: "pinto beans", quantity: "1", unit: "15-ounce can", notes: "drained and rinsed" },
      { name: "diced tomatoes", quantity: "1", unit: "28-ounce can" },
      { name: "tomato sauce", quantity: "1", unit: "15-ounce can" },
      { name: "vegetable broth", quantity: "2", unit: "cups" },
      { name: "corn kernels", quantity: "1", unit: "cup", notes: "fresh or frozen" },
      { name: "salt", quantity: "1", unit: "teaspoon", notes: "or to taste" },
      { name: "black pepper", quantity: "1/2", unit: "teaspoon" },
      { name: "brown sugar", quantity: "1", unit: "tablespoon", notes: "optional" },
      { name: "lime juice", quantity: "1", unit: "tablespoon", notes: "fresh" },
      { name: "avocado", quantity: "1", unit: "medium", notes: "diced, for serving" },
      { name: "sour cream", quantity: "1/2", unit: "cup", notes: "for serving" },
      { name: "cheddar cheese", quantity: "1", unit: "cup", notes: "shredded, for serving" },
      { name: "green onions", quantity: "3", unit: "", notes: "sliced, for serving" },
      { name: "fresh cilantro", quantity: "1/4", unit: "cup", notes: "chopped, for serving" }
    ],
    steps: [
      { order: 1, instruction: "Heat olive oil in a large Dutch oven or pot over medium heat." },
      { order: 2, instruction: "Add onion, bell peppers, carrots, and celery. Cook until softened, about 5-7 minutes." },
      { order: 3, instruction: "Add garlic and jalapeño (if using). Cook for 30 seconds until fragrant." },
      { order: 4, instruction: "Stir in chili powder, cumin, oregano, and smoked paprika. Cook for 1 minute to toast the spices." },
      { order: 5, instruction: "Add black beans, kidney beans, pinto beans, diced tomatoes, tomato sauce, and vegetable broth." },
      { order: 6, instruction: "Bring to a boil, then reduce heat to low. Simmer, partially covered, for 30 minutes, stirring occasionally." },
      { order: 7, instruction: "Add corn kernels and continue to simmer for 10 more minutes." },
      { order: 8, instruction: "Stir in salt, pepper, brown sugar (if using), and lime juice." },
      { order: 9, instruction: "Taste and adjust seasoning if needed." },
      { order: 10, instruction: "Ladle chili into bowls and serve with desired toppings: diced avocado, sour cream, shredded cheese, green onions, and cilantro." }
    ],
    cookingVessel: "Dutch Oven",
    prepTime: 20,
    cookTime: 45,
    servings: 8,
    difficulty: "Easy",
    mealType: "Dinner",
    cuisine: "American",
    categories: ["Vegetarian", "One-Pot Meals"],
    dietaryCategories: ["Vegetarian", "Vegan (without toppings)", "Gluten-Free"],
    tags: ["chili", "beans", "vegetarian", "comfort food"],
    imageUrl: "https://images.unsplash.com/photo-1564671546498-aa134e5e159a"
  },
  {
    title: "Lemon Herb Roasted Chicken",
    description: "A classic whole roasted chicken infused with bright lemon and aromatic herbs, resulting in juicy meat and crispy skin for a perfect family dinner.",
    ingredients: [
      { name: "whole chicken", quantity: "1", unit: "5-6 pound" },
      { name: "lemons", quantity: "2", unit: "", notes: "1 sliced, 1 juiced" },
      { name: "garlic", quantity: "1", unit: "head", notes: "halved crosswise" },
      { name: "fresh rosemary", quantity: "4", unit: "sprigs" },
      { name: "fresh thyme", quantity: "6", unit: "sprigs" },
      { name: "butter", quantity: "4", unit: "tablespoons", notes: "softened" },
      { name: "olive oil", quantity: "2", unit: "tablespoons" },
      { name: "salt", quantity: "1", unit: "tablespoon" },
      { name: "black pepper", quantity: "1", unit: "teaspoon" },
      { name: "garlic powder", quantity: "1", unit: "teaspoon" },
      { name: "onion", quantity: "1", unit: "medium", notes: "quartered" },
      { name: "carrots", quantity: "3", unit: "medium", notes: "cut into 2-inch pieces" },
      { name: "celery", quantity: "3", unit: "stalks", notes: "cut into 2-inch pieces" },
      { name: "chicken broth", quantity: "1", unit: "cup" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 425°F (220°C)." },
      { order: 2, instruction: "Remove giblets from chicken cavity and pat chicken dry with paper towels, inside and out." },
      { order: 3, instruction: "In a small bowl, mix softened butter with 1 tablespoon lemon juice, 1 teaspoon lemon zest, 1 teaspoon chopped rosemary, 1 teaspoon chopped thyme, garlic powder, 1 teaspoon salt, and 1/2 teaspoon pepper." },
      { order: 4, instruction: "Carefully loosen the skin over the chicken breast and thighs. Spread half of the herb butter mixture under the skin." },
      { order: 5, instruction: "Rub the outside of the chicken with olive oil and season with remaining salt and pepper." },
      { order: 6, instruction: "Stuff the cavity with lemon slices, garlic head halves, and remaining herb sprigs." },
      { order: 7, instruction: "Tie the legs together with kitchen twine and tuck the wing tips under the body." },
      { order: 8, instruction: "Place onion, carrots, and celery in the bottom of a roasting pan. Place chicken on top of vegetables, breast side up." },
      { order: 9, instruction: "Pour chicken broth into the bottom of the pan." },
      { order: 10, instruction: "Roast for 15 minutes at 425°F (220°C), then reduce temperature to 375°F (190°C)." },
      { order: 11, instruction: "Continue roasting for about 1 hour and 15 minutes, or until a meat thermometer inserted into the thickest part of the thigh registers 165°F (74°C)." },
      { order: 12, instruction: "Baste the chicken with pan juices every 30 minutes." },
      { order: 13, instruction: "Remove from oven, tent with foil, and let rest for 15 minutes before carving." },
      { order: 14, instruction: "Serve chicken with roasted vegetables and pan juices." }
    ],
    cookingVessel: "Roasting Pan",
    prepTime: 20,
    cookTime: 90,
    servings: 6,
    difficulty: "Medium",
    mealType: "Dinner",
    cuisine: "American",
    categories: ["Poultry", "Sunday Dinner"],
    dietaryCategories: ["Gluten-Free"],
    tags: ["roast chicken", "lemon", "herbs", "family dinner"],
    imageUrl: "https://images.unsplash.com/photo-1598103442097-8b74394b95c6"
  },
  {
    title: "Shrimp and Grits",
    description: "A Southern classic featuring creamy, cheesy grits topped with sautéed shrimp, bacon, and a flavorful sauce for a comforting and satisfying dinner.",
    ingredients: [
      { name: "stone-ground grits", quantity: "1", unit: "cup" },
      { name: "water", quantity: "3", unit: "cups" },
      { name: "milk", quantity: "1", unit: "cup" },
      { name: "salt", quantity: "1", unit: "teaspoon", notes: "divided" },
      { name: "butter", quantity: "4", unit: "tablespoons", notes: "divided" },
      { name: "sharp cheddar cheese", quantity: "1", unit: "cup", notes: "shredded" },
      { name: "bacon", quantity: "6", unit: "slices", notes: "diced" },
      { name: "shrimp", quantity: "1 1/2", unit: "pounds", notes: "large, peeled and deveined" },
      { name: "garlic", quantity: "3", unit: "cloves", notes: "minced" },
      { name: "green onions", quantity: "4", unit: "", notes: "sliced, whites and greens separated" },
      { name: "bell pepper", quantity: "1", unit: "medium", notes: "diced" },
      { name: "all-purpose flour", quantity: "2", unit: "tablespoons" },
      { name: "chicken broth", quantity: "1", unit: "cup" },
      { name: "lemon juice", quantity: "1", unit: "tablespoon" },
      { name: "Worcestershire sauce", quantity: "1", unit: "teaspoon" },
      { name: "hot sauce", quantity: "1/2", unit: "teaspoon", notes: "or to taste" },
      { name: "black pepper", quantity: "1/2", unit: "teaspoon" },
      { name: "cajun seasoning", quantity: "1", unit: "teaspoon", notes: "optional" },
      { name: "fresh parsley", quantity: "2", unit: "tablespoons", notes: "chopped" }
    ],
    steps: [
      { order: 1, instruction: "In a medium saucepan, bring water, milk, and 1/2 teaspoon salt to a boil." },
      { order: 2, instruction: "Slowly whisk in grits, reduce heat to low, and cover." },
      { order: 3, instruction: "Cook, stirring occasionally, for 20-25 minutes until grits are creamy and tender." },
      { order: 4, instruction: "Stir in 2 tablespoons butter and cheddar cheese until melted. Cover and keep warm." },
      { order: 5, instruction: "Meanwhile, in a large skillet, cook diced bacon over medium heat until crispy, about 5-7 minutes." },
      { order: 6, instruction: "Remove bacon with a slotted spoon and set aside, leaving the bacon fat in the skillet." },
      { order: 7, instruction: "Season shrimp with remaining salt, pepper, and cajun seasoning if using." },
      { order: 8, instruction: "Increase heat to medium-high and add shrimp to the skillet. Cook for 1-2 minutes per side until pink and just cooked through. Remove and set aside." },
      { order: 9, instruction: "Add bell pepper and white parts of green onions to the skillet. Cook until softened, about 3 minutes." },
      { order: 10, instruction: "Add garlic and cook for 30 seconds until fragrant." },
      { order: 11, instruction: "Add remaining 2 tablespoons butter to the skillet. Once melted, sprinkle in flour and cook, stirring constantly, for 1 minute." },
      { order: 12, instruction: "Gradually whisk in chicken broth, lemon juice, Worcestershire sauce, and hot sauce." },
      { order: 13, instruction: "Bring to a simmer and cook until sauce thickens slightly, about 2-3 minutes." },
      { order: 14, instruction: "Return shrimp and bacon to the skillet, toss to coat in the sauce, and heat through." },
      { order: 15, instruction: "Divide grits among serving bowls, top with shrimp mixture, and garnish with green parts of green onions and chopped parsley." }
    ],
    cookingVessel: "Skillet",
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    difficulty: "Medium",
    mealType: "Dinner",
    cuisine: "Southern",
    categories: ["Seafood", "Comfort Food"],
    dietaryCategories: [],
    tags: ["shrimp", "grits", "southern", "comfort food"],
    imageUrl: "https://images.unsplash.com/photo-1625943553852-781c6dd46faa"
  },
  {
    title: "Eggplant Parmesan",
    description: "A classic Italian vegetarian dish featuring layers of breaded and fried eggplant, marinara sauce, and melted cheese, baked until bubbly and golden.",
    ingredients: [
      { name: "eggplants", quantity: "2", unit: "large", notes: "about 2-3 pounds total" },
      { name: "salt", quantity: "2", unit: "teaspoons", notes: "divided" },
      { name: "all-purpose flour", quantity: "1", unit: "cup" },
      { name: "eggs", quantity: "3", unit: "large", notes: "beaten" },
      { name: "breadcrumbs", quantity: "2", unit: "cups", notes: "Italian-style" },
      { name: "parmesan cheese", quantity: "1", unit: "cup", notes: "grated, divided" },
      { name: "dried oregano", quantity: "1", unit: "teaspoon" },
      { name: "dried basil", quantity: "1", unit: "teaspoon" },
      { name: "garlic powder", quantity: "1", unit: "teaspoon" },
      { name: "vegetable oil", quantity: "1", unit: "cup", notes: "for frying" },
      { name: "marinara sauce", quantity: "4", unit: "cups", notes: "homemade or store-bought" },
      { name: "mozzarella cheese", quantity: "1", unit: "pound", notes: "sliced or shredded" },
      { name: "fresh basil", quantity: "1/4", unit: "cup", notes: "chopped" }
    ],
    steps: [
      { order: 1, instruction: "Slice eggplants into 1/4-inch thick rounds. Lay slices on paper towels and sprinkle with 1 teaspoon salt. Let sit for 30 minutes to draw out moisture." },
      { order: 2, instruction: "Preheat oven to 375°F (190°C)." },
      { order: 3, instruction: "Pat eggplant slices dry with paper towels." },
      { order: 4, instruction: "Set up breading station: Place flour in one shallow dish, beaten eggs in a second dish, and combine breadcrumbs, 1/2 cup parmesan cheese, oregano, basil, garlic powder, and remaining salt in a third dish." },
      { order: 5, instruction: "Dredge each eggplant slice in flour, shaking off excess, then dip in egg, and finally coat with breadcrumb mixture, pressing to adhere." },
      { order: 6, instruction: "Heat vegetable oil in a large skillet over medium-high heat." },
      { order: 7, instruction: "Working in batches, fry eggplant slices until golden brown, about 2-3 minutes per side. Transfer to paper towels to drain." },
      { order: 8, instruction: "Spread 1 cup marinara sauce in the bottom of a 9x13 inch baking dish." },
      { order: 9, instruction: "Arrange a layer of fried eggplant slices over the sauce, slightly overlapping." },
      { order: 10, instruction: "Top with 1 cup marinara sauce, 1/3 of the mozzarella cheese, and a sprinkle of parmesan." },
      { order: 11, instruction: "Repeat layers twice more, ending with cheese on top." },
      { order: 12, instruction: "Bake uncovered for 35-40 minutes until bubbly and golden brown." },
      { order: 13, instruction: "Let rest for 10 minutes before serving." },
      { order: 14, instruction: "Garnish with fresh basil before serving." }
    ],
    cookingVessel: "Baking Dish",
    prepTime: 45,
    cookTime: 60,
    servings: 8,
    difficulty: "Medium",
    mealType: "Dinner",
    cuisine: "Italian",
    categories: ["Vegetarian", "Casseroles"],
    dietaryCategories: ["Vegetarian"],
    tags: ["eggplant", "parmesan", "italian", "casserole"],
    imageUrl: "https://images.unsplash.com/photo-1629115916087-7e8c114a24ed"
  },
  {
    title: "Beef and Broccoli Stir-Fry",
    description: "A quick and flavorful Chinese-inspired dish featuring tender slices of beef and crisp broccoli in a savory sauce, served over steamed rice.",
    ingredients: [
      { name: "flank steak", quantity: "1 1/2", unit: "pounds", notes: "thinly sliced against the grain" },
      { name: "cornstarch", quantity: "2", unit: "tablespoons", notes: "divided" },
      { name: "soy sauce", quantity: "1/3", unit: "cup", notes: "divided" },
      { name: "brown sugar", quantity: "2", unit: "tablespoons" },
      { name: "beef broth", quantity: "1/2", unit: "cup" },
      { name: "oyster sauce", quantity: "2", unit: "tablespoons" },
      { name: "sesame oil", quantity: "1", unit: "tablespoon" },
      { name: "rice vinegar", quantity: "1", unit: "tablespoon" },
      { name: "garlic", quantity: "4", unit: "cloves", notes: "minced" },
      { name: "ginger", quantity: "1", unit: "tablespoon", notes: "minced" },
      { name: "vegetable oil", quantity: "3", unit: "tablespoons", notes: "divided" },
      { name: "broccoli florets", quantity: "4", unit: "cups" },
      { name: "red bell pepper", quantity: "1", unit: "medium", notes: "sliced" },
      { name: "green onions", quantity: "4", unit: "", notes: "sliced" },
      { name: "sesame seeds", quantity: "1", unit: "tablespoon", notes: "for garnish" },
      { name: "rice", quantity: "2", unit: "cups", notes: "cooked, for serving" }
    ],
    steps: [
      { order: 1, instruction: "In a medium bowl, toss sliced beef with 1 tablespoon cornstarch and 2 tablespoons soy sauce. Let marinate for 15 minutes." },
      { order: 2, instruction: "Meanwhile, in a small bowl, whisk together remaining soy sauce, brown sugar, beef broth, oyster sauce, sesame oil, rice vinegar, and remaining cornstarch. Set sauce aside." },
      { order: 3, instruction: "Heat 1 tablespoon vegetable oil in a large wok or skillet over high heat." },
      { order: 4, instruction: "Add beef in a single layer and cook without stirring for 1 minute to sear. Then stir-fry until no longer pink, about 2-3 minutes. Remove to a plate." },
      { order: 5, instruction: "Add another tablespoon of oil to the wok. Add broccoli and bell pepper, stir-fry for 3-4 minutes until crisp-tender." },
      { order: 6, instruction: "Add remaining tablespoon of oil, then add garlic and ginger. Stir-fry for 30 seconds until fragrant." },
      { order: 7, instruction: "Return beef to the wok, along with any accumulated juices." },
      { order: 8, instruction: "Pour in the sauce mixture and bring to a simmer, stirring constantly." },
      { order: 9, instruction: "Cook for 1-2 minutes until sauce thickens and coats the beef and vegetables." },
      { order: 10, instruction: "Stir in most of the green onions, reserving some for garnish." },
      { order: 11, instruction: "Serve over cooked rice, garnished with remaining green onions and sesame seeds." }
    ],
    cookingVessel: "Wok",
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    difficulty: "Medium",
    mealType: "Dinner",
    cuisine: "Chinese",
    categories: ["Stir-Fry", "Quick Dinner"],
    dietaryCategories: ["Dairy-Free"],
    tags: ["beef", "broccoli", "stir-fry", "chinese"],
    imageUrl: "https://images.unsplash.com/photo-1625944525533-473f1a3d54e7"
  },
  {
    title: "Mushroom Risotto",
    description: "A creamy Italian rice dish featuring arborio rice slowly cooked with mushrooms, white wine, and parmesan cheese for a luxurious vegetarian dinner.",
    ingredients: [
      { name: "arborio rice", quantity: "1 1/2", unit: "cups" },
      { name: "mixed mushrooms", quantity: "1", unit: "pound", notes: "cremini, shiitake, oyster, etc., sliced" },
      { name: "dried porcini mushrooms", quantity: "1/2", unit: "ounce" },
      { name: "hot water", quantity: "1", unit: "cup" },
      { name: "vegetable broth", quantity: "5", unit: "cups", notes: "warmed" },
      { name: "olive oil", quantity: "2", unit: "tablespoons" },
      { name: "butter", quantity: "4", unit: "tablespoons", notes: "divided" },
      { name: "onion", quantity: "1", unit: "medium", notes: "finely diced" },
      { name: "garlic", quantity: "3", unit: "cloves", notes: "minced" },
      { name: "dry white wine", quantity: "1/2", unit: "cup" },
      { name: "parmesan cheese", quantity: "1", unit: "cup", notes: "freshly grated" },
      { name: "fresh thyme", quantity: "2", unit: "teaspoons", notes: "chopped" },
      { name: "salt", quantity: "1", unit: "teaspoon", notes: "or to taste" },
      { name: "black pepper", quantity: "1/2", unit: "teaspoon", notes: "freshly ground" },
      { name: "fresh parsley", quantity: "2", unit: "tablespoons", notes: "chopped" }
    ],
    steps: [
      { order: 1, instruction: "Place dried porcini mushrooms in a bowl with hot water. Let soak for 20 minutes." },
      { order: 2, instruction: "Remove rehydrated mushrooms, reserving the soaking liquid. Chop the mushrooms and strain the liquid through a fine-mesh sieve lined with a coffee filter to remove any grit. Add this liquid to the vegetable broth." },
      { order: 3, instruction: "In a large, heavy-bottomed pot or Dutch oven, heat olive oil and 2 tablespoons butter over medium heat." },
      { order: 4, instruction: "Add fresh mushrooms and cook until they release their moisture and begin to brown, about 8-10 minutes. Remove half the mushrooms and set aside for garnish." },
      { order: 5, instruction: "Add onion to the pot and cook until softened, about 3-4 minutes." },
      { order: 6, instruction: "Add garlic and chopped porcini mushrooms, cook for 1 minute until fragrant." },
      { order: 7, instruction: "Add arborio rice and stir to coat with oil and butter, toasting lightly for 1-2 minutes." },
      { order: 8, instruction: "Pour in white wine and cook, stirring constantly, until absorbed, about 2 minutes." },
      { order: 9, instruction: "Add 1 cup of warm broth and chopped thyme. Cook, stirring frequently, until liquid is mostly absorbed." },
      { order: 10, instruction: "Continue adding broth 1/2 cup at a time, stirring frequently and allowing each addition to be mostly absorbed before adding more. This process will take about 18-22 minutes." },
      { order: 11, instruction: "When rice is creamy and tender but still slightly firm to the bite (al dente), remove from heat." },
      { order: 12, instruction: "Stir in remaining 2 tablespoons butter and parmesan cheese until melted." },
      { order: 13, instruction: "Season with salt and pepper to taste." },
      { order: 14, instruction: "Serve immediately, topped with reserved mushrooms and chopped parsley." }
    ],
    cookingVessel: "Dutch Oven",
    prepTime: 15,
    cookTime: 40,
    servings: 4,
    difficulty: "Medium",
    mealType: "Dinner",
    cuisine: "Italian",
    categories: ["Rice Dishes", "Vegetarian"],
    dietaryCategories: ["Vegetarian", "Gluten-Free"],
    tags: ["risotto", "mushroom", "italian", "creamy"],
    imageUrl: "https://images.unsplash.com/photo-1476124369491-e7addf5db371"
  },
  {
    title: "Grilled Lamb Chops with Mint Sauce",
    description: "Tender lamb chops marinated with herbs and garlic, grilled to perfection, and served with a fresh mint sauce for an elegant dinner option.",
    ingredients: [
      { name: "lamb chops", quantity: "8", unit: "", notes: "1-inch thick, about 2 pounds total" },
      { name: "olive oil", quantity: "3", unit: "tablespoons", notes: "divided" },
      { name: "garlic", quantity: "4", unit: "cloves", notes: "minced" },
      { name: "fresh rosemary", quantity: "2", unit: "tablespoons", notes: "chopped" },
      { name: "fresh thyme", quantity: "1", unit: "tablespoon", notes: "chopped" },
      { name: "lemon zest", quantity: "1", unit: "tablespoon" },
      { name: "salt", quantity: "1 1/2", unit: "teaspoons", notes: "divided" },
      { name: "black pepper", quantity: "1", unit: "teaspoon", notes: "divided" },
      { name: "fresh mint leaves", quantity: "1", unit: "cup", notes: "packed" },
      { name: "white wine vinegar", quantity: "1/4", unit: "cup" },
      { name: "sugar", quantity: "1", unit: "tablespoon" },
      { name: "shallot", quantity: "1", unit: "small", notes: "minced" },
      { name: "lemon juice", quantity: "1", unit: "tablespoon" }
    ],
    steps: [
      { order: 1, instruction: "In a small bowl, combine 2 tablespoons olive oil, garlic, rosemary, thyme, lemon zest, 1 teaspoon salt, and 1/2 teaspoon pepper." },
      { order: 2, instruction: "Place lamb chops in a shallow dish and rub the herb mixture all over them. Cover and refrigerate for at least 1 hour, or up to 4 hours." },
      { order: 3, instruction: "Meanwhile, make the mint sauce: In a food processor, combine mint leaves, white wine vinegar, sugar, shallot, lemon juice, remaining olive oil, 1/2 teaspoon salt, and 1/2 teaspoon pepper. Pulse until finely chopped but not pureed. Transfer to a small bowl and let sit at room temperature for flavors to meld." },
      { order: 4, instruction: "Preheat grill or grill pan to medium-high heat." },
      { order: 5, instruction: "Remove lamb chops from marinade and shake off excess. Discard remaining marinade." },
      { order: 6, instruction: "Grill lamb chops for 3-4 minutes per side for medium-rare (internal temperature of 145°F/63°C), or to desired doneness." },
      { order: 7, instruction: "Transfer to a plate and let rest for 5 minutes." },
      { order: 8, instruction: "Serve lamb chops with mint sauce on the side." }
    ],
    cookingVessel: "Grill",
    prepTime: 15,
    cookTime: 10,
    servings: 4,
    difficulty: "Medium",
    mealType: "Dinner",
    cuisine: "Mediterranean",
    categories: ["Lamb", "Grilled"],
    dietaryCategories: ["Gluten-Free", "Low-Carb"],
    tags: ["lamb chops", "mint", "grilled", "elegant dinner"],
    imageUrl: "https://images.unsplash.com/photo-1598511757337-fe2cafc31ba0"
  },
  {
    title: "Stuffed Bell Peppers",
    description: "Colorful bell peppers stuffed with a flavorful mixture of ground beef, rice, vegetables, and cheese, baked until tender for a complete and satisfying meal.",
    ingredients: [
      { name: "bell peppers", quantity: "6", unit: "large", notes: "any color, tops cut off and seeded" },
      { name: "ground beef", quantity: "1", unit: "pound", notes: "lean" },
      { name: "onion", quantity: "1", unit: "medium", notes: "diced" },
      { name: "garlic", quantity: "3", unit: "cloves", notes: "minced" },
      { name: "cooked rice", quantity: "1 1/2", unit: "cups" },
      { name: "diced tomatoes", quantity: "1", unit: "14.5-ounce can", notes: "drained" },
      { name: "tomato sauce", quantity: "1", unit: "8-ounce can", notes: "divided" },
      { name: "Worcestershire sauce", quantity: "1", unit: "tablespoon" },
      { name: "Italian seasoning", quantity: "1", unit: "tablespoon" },
      { name: "salt", quantity: "1", unit: "teaspoon" },
      { name: "black pepper", quantity: "1/2", unit: "teaspoon" },
      { name: "cheddar cheese", quantity: "1", unit: "cup", notes: "shredded, divided" },
      { name: "fresh parsley", quantity: "2", unit: "tablespoons", notes: "chopped" },
      { name: "water", quantity: "1/4", unit: "cup" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 375°F (190°C)." },
      { order: 2, instruction: "Bring a large pot of water to a boil. Add a pinch of salt and blanch the bell peppers for 3-5 minutes until slightly softened. Drain and set aside." },
      { order: 3, instruction: "In a large skillet, cook ground beef over medium heat until no longer pink, about 5-7 minutes. Drain excess fat." },
      { order: 4, instruction: "Add onion to the skillet and cook until softened, about 3-4 minutes." },
      { order: 5, instruction: "Add garlic and cook for 30 seconds until fragrant." },
      { order: 6, instruction: "Stir in cooked rice, diced tomatoes, half of the tomato sauce, Worcestershire sauce, Italian seasoning, salt, and pepper." },
      { order: 7, instruction: "Remove from heat and stir in half of the cheddar cheese and the parsley." },
      { order: 8, instruction: "Place bell peppers upright in a baking dish. Pour water into the bottom of the dish." },
      { order: 9, instruction: "Fill each pepper with the beef and rice mixture." },
      { order: 10, instruction: "Spoon remaining tomato sauce over the tops of the stuffed peppers." },
      { order: 11, instruction: "Cover the baking dish with foil and bake for 25-30 minutes." },
      { order: 12, instruction: "Remove foil, sprinkle with remaining cheddar cheese, and bake uncovered for an additional 10 minutes until cheese is melted and peppers are tender." },
      { order: 13, instruction: "Let stand for 5 minutes before serving." }
    ],
    cookingVessel: "Baking Dish",
    prepTime: 20,
    cookTime: 45,
    servings: 6,
    difficulty: "Medium",
    mealType: "Dinner",
    cuisine: "American",
    categories: ["Stuffed Vegetables", "One-Dish Meals"],
    dietaryCategories: ["Gluten-Free"],
    tags: ["stuffed peppers", "ground beef", "rice", "comfort food"],
    imageUrl: "https://images.unsplash.com/photo-1600336153113-d66c79de3e91"
  },
  {
    title: "Coconut Curry Salmon",
    description: "Tender salmon fillets simmered in a rich and aromatic coconut curry sauce with vegetables, served over rice for a flavorful and exotic dinner.",
    ingredients: [
      { name: "salmon fillets", quantity: "4", unit: "6-ounce", notes: "skin-on" },
      { name: "salt", quantity: "1", unit: "teaspoon", notes: "divided" },
      { name: "black pepper", quantity: "1/2", unit: "teaspoon", notes: "divided" },
      { name: "coconut oil", quantity: "2", unit: "tablespoons" },
      { name: "onion", quantity: "1", unit: "medium", notes: "diced" },
      { name: "bell pepper", quantity: "1", unit: "medium", notes: "diced" },
      { name: "garlic", quantity: "3", unit: "cloves", notes: "minced" },
      { name: "ginger", quantity: "1", unit: "tablespoon", notes: "minced" },
      { name: "curry powder", quantity: "2", unit: "tablespoons" },
      { name: "turmeric", quantity: "1", unit: "teaspoon" },
      { name: "coconut milk", quantity: "1", unit: "14-ounce can", notes: "full-fat" },
      { name: "fish sauce", quantity: "1", unit: "tablespoon" },
      { name: "brown sugar", quantity: "1", unit: "tablespoon" },
      { name: "lime juice", quantity: "1", unit: "tablespoon", notes: "fresh" },
      { name: "spinach", quantity: "2", unit: "cups", notes: "fresh" },
      { name: "cherry tomatoes", quantity: "1", unit: "cup", notes: "halved" },
      { name: "fresh cilantro", quantity: "1/4", unit: "cup", notes: "chopped" },
      { name: "fresh basil", quantity: "2", unit: "tablespoons", notes: "chopped" },
      { name: "lime wedges", quantity: "1", unit: "lime", notes: "cut into wedges, for serving" },
      { name: "jasmine rice", quantity: "2", unit: "cups", notes: "cooked, for serving" }
    ],
    steps: [
      { order: 1, instruction: "Season salmon fillets with 1/2 teaspoon salt and 1/4 teaspoon pepper." },
      { order: 2, instruction: "Heat 1 tablespoon coconut oil in a large skillet over medium-high heat." },
      { order: 3, instruction: "Add salmon, skin-side down, and cook for 3-4 minutes until skin is crispy." },
      { order: 4, instruction: "Flip salmon and cook for 2 minutes more. Remove to a plate (it will finish cooking in the sauce later)." },
      { order: 5, instruction: "In the same skillet, add remaining coconut oil, onion, and bell pepper. Cook until softened, about 3-4 minutes." },
      { order: 6, instruction: "Add garlic and ginger, cook for 30 seconds until fragrant." },
      { order: 7, instruction: "Stir in curry powder and turmeric, cook for 1 minute to toast the spices." },
      { order: 8, instruction: "Pour in coconut milk, fish sauce, brown sugar, and remaining salt and pepper. Bring to a simmer." },
      { order: 9, instruction: "Add cherry tomatoes and simmer for 2 minutes." },
      { order: 10, instruction: "Gently place salmon back into the skillet, spooning some sauce over the top." },
      { order: 11, instruction: "Simmer for 3-4 minutes until salmon is cooked through and flakes easily." },
      { order: 12, instruction: "Stir in spinach and cook until wilted, about 1 minute." },
      { order: 13, instruction: "Remove from heat and stir in lime juice." },
      { order: 14, instruction: "Serve over jasmine rice, garnished with cilantro, basil, and lime wedges." }
    ],
    cookingVessel: "Skillet",
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    difficulty: "Medium",
    mealType: "Dinner",
    cuisine: "Thai",
    categories: ["Seafood", "Curry"],
    dietaryCategories: ["Gluten-Free", "Dairy-Free"],
    tags: ["salmon", "coconut", "curry", "thai"],
    imageUrl: "https://images.unsplash.com/photo-1626684496076-07e23c6361ff"
  },
  {
    title: "Beef Stroganoff",
    description: "A classic Russian dish featuring tender strips of beef in a rich, creamy mushroom sauce, served over egg noodles for a comforting dinner.",
    ingredients: [
      { name: "beef sirloin", quantity: "1 1/2", unit: "pounds", notes: "cut into thin strips" },
      { name: "salt", quantity: "1", unit: "teaspoon", notes: "divided" },
      { name: "black pepper", quantity: "1/2", unit: "teaspoon", notes: "divided" },
      { name: "all-purpose flour", quantity: "2", unit: "tablespoons" },
      { name: "vegetable oil", quantity: "2", unit: "tablespoons" },
      { name: "butter", quantity: "3", unit: "tablespoons", notes: "divided" },
      { name: "onion", quantity: "1", unit: "medium", notes: "thinly sliced" },
      { name: "mushrooms", quantity: "1", unit: "pound", notes: "sliced" },
      { name: "garlic", quantity: "3", unit: "cloves", notes: "minced" },
      { name: "beef broth", quantity: "2", unit: "cups" },
      { name: "Dijon mustard", quantity: "1", unit: "tablespoon" },
      { name: "Worcestershire sauce", quantity: "1", unit: "tablespoon" },
      { name: "sour cream", quantity: "3/4", unit: "cup" },
      { name: "egg noodles", quantity: "12", unit: "ounces" },
      { name: "fresh parsley", quantity: "2", unit: "tablespoons", notes: "chopped" }
    ],
    steps: [
      { order: 1, instruction: "Season beef strips with 1/2 teaspoon salt and 1/4 teaspoon pepper, then toss with flour to coat lightly." },
      { order: 2, instruction: "Heat vegetable oil and 1 tablespoon butter in a large skillet over medium-high heat." },
      { order: 3, instruction: "Working in batches, add beef strips in a single layer and cook until browned, about 1 minute per side. Remove to a plate." },
      { order: 4, instruction: "In the same skillet, add another tablespoon of butter. Add onion and cook until softened, about 3-4 minutes." },
      { order: 5, instruction: "Add mushrooms and cook until they release their moisture and begin to brown, about 5-7 minutes." },
      { order: 6, instruction: "Add garlic and cook for 30 seconds until fragrant." },
      { order: 7, instruction: "Pour in beef broth, Dijon mustard, and Worcestershire sauce, scraping up any browned bits from the bottom of the pan." },
      { order: 8, instruction: "Bring to a simmer and cook for 5 minutes until slightly reduced." },
      { order: 9, instruction: "Meanwhile, cook egg noodles according to package instructions. Drain." },
      { order: 10, instruction: "Reduce heat to low and stir in sour cream until well combined." },
      { order: 11, instruction: "Return beef to the skillet along with any accumulated juices. Cook just until heated through, about 2-3 minutes (do not boil or the sour cream may curdle)." },
      { order: 12, instruction: "Season with remaining salt and pepper to taste." },
      { order: 13, instruction: "Stir in remaining tablespoon of butter until melted." },
      { order: 14, instruction: "Serve over cooked egg noodles, garnished with chopped parsley." }
    ],
    cookingVessel: "Skillet",
    prepTime: 15,
    cookTime: 30,
    servings: 6,
    difficulty: "Medium",
    mealType: "Dinner",
    cuisine: "Russian",
    categories: ["Beef", "Comfort Food"],
    dietaryCategories: [],
    tags: ["stroganoff", "beef", "mushrooms", "noodles"],
    imageUrl: "https://images.unsplash.com/photo-1588168333986-5078d3ae3976"
  },
  {
    title: "Vegetable Lasagna",
    description: "A hearty vegetarian lasagna layered with roasted vegetables, ricotta cheese, marinara sauce, and melted mozzarella for a satisfying meatless dinner option.",
    ingredients: [
      { name: "lasagna noodles", quantity: "12", unit: "sheets", notes: "no-boil or regular" },
      { name: "olive oil", quantity: "3", unit: "tablespoons", notes: "divided" },
      { name: "zucchini", quantity: "2", unit: "medium", notes: "diced" },
      { name: "yellow squash", quantity: "2", unit: "medium", notes: "diced" },
      { name: "bell peppers", quantity: "2", unit: "medium", notes: "assorted colors, diced" },
      { name: "mushrooms", quantity: "8", unit: "ounces", notes: "sliced" },
      { name: "onion", quantity: "1", unit: "large", notes: "diced" },
      { name: "garlic", quantity: "4", unit: "cloves", notes: "minced" },
      { name: "baby spinach", quantity: "5", unit: "ounces" },
      { name: "marinara sauce", quantity: "4", unit: "cups", notes: "homemade or store-bought" },
      { name: "ricotta cheese", quantity: "15", unit: "ounces" },
      { name: "egg", quantity: "1", unit: "large" },
      { name: "parmesan cheese", quantity: "1", unit: "cup", notes: "grated, divided" },
      { name: "mozzarella cheese", quantity: "3", unit: "cups", notes: "shredded, divided" },
      { name: "fresh basil", quantity: "1/4", unit: "cup", notes: "chopped" },
      { name: "dried oregano", quantity: "1", unit: "teaspoon" },
      { name: "salt", quantity: "1", unit: "teaspoon", notes: "divided" },
      { name: "black pepper", quantity: "1/2", unit: "teaspoon", notes: "divided" },
      { name: "red pepper flakes", quantity: "1/4", unit: "teaspoon", notes: "optional" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 400°F (200°C)." },
      { order: 2, instruction: "If using regular lasagna noodles, cook according to package instructions until al dente. Drain and lay flat on oiled baking sheets to prevent sticking. Skip this step if using no-boil noodles." },
      { order: 3, instruction: "On a large baking sheet, toss zucchini, yellow squash, bell peppers, and mushrooms with 2 tablespoons olive oil, 1/2 teaspoon salt, and 1/4 teaspoon pepper." },
      { order: 4, instruction: "Roast vegetables for 20-25 minutes until tender and lightly browned, stirring halfway through. Reduce oven temperature to 375°F (190°C)." },
      { order: 5, instruction: "Meanwhile, heat remaining olive oil in a large skillet over medium heat. Add onion and cook until softened, about 5 minutes." },
      { order: 6, instruction: "Add garlic and cook for 30 seconds until fragrant." },
      { order: 7, instruction: "Add spinach and cook until wilted, about 2 minutes. Remove from heat and let cool slightly." },
      { order: 8, instruction: "In a medium bowl, combine ricotta cheese, egg, 1/2 cup parmesan cheese, basil, oregano, remaining salt and pepper, and red pepper flakes if using. Mix well." },
      { order: 9, instruction: "Spread 1 cup marinara sauce in the bottom of a 9x13 inch baking dish." },
      { order: 10, instruction: "Arrange 3 lasagna noodles over the sauce." },
      { order: 11, instruction: "Spread 1/3 of the ricotta mixture over the noodles, followed by 1/3 of the roasted vegetables, 1/3 of the spinach mixture, 3/4 cup marinara sauce, and 3/4 cup mozzarella cheese." },
      { order: 12, instruction: "Repeat layers twice more, ending with noodles, remaining sauce, remaining mozzarella, and remaining parmesan on top." },
      { order: 13, instruction: "Cover with foil and bake for 25 minutes." },
      { order: 14, instruction: "Remove foil and bake for an additional 15-20 minutes until cheese is bubbly and golden." },
      { order: 15, instruction: "Let rest for 15 minutes before cutting and serving." }
    ],
    cookingVessel: "Baking Dish",
    prepTime: 30,
    cookTime: 70,
    servings: 8,
    difficulty: "Medium",
    mealType: "Dinner",
    cuisine: "Italian",
    categories: ["Vegetarian", "Casseroles"],
    dietaryCategories: ["Vegetarian"],
    tags: ["lasagna", "vegetable", "italian", "casserole"],
    imageUrl: "https://images.unsplash.com/photo-1574894709920-11b28e7367e3"
  },
  {
    title: "Honey Garlic Glazed Pork Chops",
    description: "Juicy pork chops seared to perfection and glazed with a sweet and savory honey garlic sauce, served with roasted vegetables for a quick and delicious dinner.",
    ingredients: [
      { name: "pork chops", quantity: "4", unit: "", notes: "bone-in, 1-inch thick" },
      { name: "salt", quantity: "1", unit: "teaspoon" },
      { name: "black pepper", quantity: "1/2", unit: "teaspoon" },
      { name: "garlic powder", quantity: "1/2", unit: "teaspoon" },
      { name: "olive oil", quantity: "2", unit: "tablespoons" },
      { name: "butter", quantity: "2", unit: "tablespoons" },
      { name: "garlic", quantity: "4", unit: "cloves", notes: "minced" },
      { name: "honey", quantity: "1/4", unit: "cup" },
      { name: "soy sauce", quantity: "2", unit: "tablespoons", notes: "low-sodium" },
      { name: "apple cider vinegar", quantity: "1", unit: "tablespoon" },
      { name: "red pepper flakes", quantity: "1/4", unit: "teaspoon", notes: "optional" },
      { name: "fresh thyme", quantity: "1", unit: "teaspoon", notes: "chopped" },
      { name: "broccoli", quantity: "1", unit: "head", notes: "cut into florets" },
      { name: "carrots", quantity: "3", unit: "medium", notes: "peeled and cut into sticks" },
      { name: "olive oil", quantity: "1", unit: "tablespoon", notes: "for vegetables" },
      { name: "salt", quantity: "1/2", unit: "teaspoon", notes: "for vegetables" },
      { name: "black pepper", quantity: "1/4", unit: "teaspoon", notes: "for vegetables" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 425°F (220°C)." },
      { order: 2, instruction: "On a baking sheet, toss broccoli and carrots with 1 tablespoon olive oil, 1/2 teaspoon salt, and 1/4 teaspoon pepper." },
      { order: 3, instruction: "Roast vegetables for 20-25 minutes until tender and lightly browned, stirring halfway through." },
      { order: 4, instruction: "Meanwhile, pat pork chops dry with paper towels and season on both sides with salt, pepper, and garlic powder." },
      { order: 5, instruction: "Heat 2 tablespoons olive oil in a large skillet over medium-high heat." },
      { order: 6, instruction: "Add pork chops and cook for 4-5 minutes per side until golden brown and internal temperature reaches 145°F (63°C). Remove to a plate and tent with foil." },
      { order: 7, instruction: "Reduce heat to medium and add butter to the same skillet." },
      { order: 8, instruction: "Once butter is melted, add garlic and cook for 30 seconds until fragrant." },
      { order: 9, instruction: "Add honey, soy sauce, apple cider vinegar, red pepper flakes (if using), and thyme. Stir to combine." },
      { order: 10, instruction: "Simmer for 2-3 minutes until sauce thickens slightly." },
      { order: 11, instruction: "Return pork chops to the skillet, turning to coat in the glaze." },
      { order: 12, instruction: "Simmer for 1-2 minutes more, spooning glaze over the pork chops." },
      { order: 13, instruction: "Serve pork chops with the honey garlic glaze drizzled on top, alongside roasted vegetables." }
    ],
    cookingVessel: "Skillet",
    prepTime: 10,
    cookTime: 30,
    servings: 4,
    difficulty: "Easy",
    mealType: "Dinner",
    cuisine: "American",
    categories: ["Pork", "Quick Dinner"],
    dietaryCategories: ["Gluten-Free (with GF soy sauce)"],
    tags: ["pork chops", "honey garlic", "glazed", "quick dinner"],
    imageUrl: "https://images.unsplash.com/photo-1432139555190-58524dae6a55"
  },
  {
    title: "Spinach and Ricotta Stuffed Shells",
    description: "Jumbo pasta shells filled with a creamy spinach and ricotta mixture, baked in marinara sauce and topped with melted cheese for a comforting vegetarian dinner.",
    ingredients: [
      { name: "jumbo pasta shells", quantity: "24", unit: "" },
      { name: "olive oil", quantity: "1", unit: "tablespoon" },
      { name: "garlic", quantity: "3", unit: "cloves", notes: "minced" },
      { name: "fresh spinach", quantity: "10", unit: "ounces", notes: "roughly chopped" },
      { name: "ricotta cheese", quantity: "15", unit: "ounces" },
      { name: "mozzarella cheese", quantity: "2", unit: "cups", notes: "shredded, divided" },
      { name: "parmesan cheese", quantity: "1/2", unit: "cup", notes: "grated, divided" },
      { name: "egg", quantity: "1", unit: "large" },
      { name: "fresh basil", quantity: "1/4", unit: "cup", notes: "chopped" },
      { name: "dried oregano", quantity: "1", unit: "teaspoon" },
      { name: "salt", quantity: "1", unit: "teaspoon" },
      { name: "black pepper", quantity: "1/2", unit: "teaspoon" },
      { name: "nutmeg", quantity: "1/8", unit: "teaspoon", notes: "freshly grated" },
      { name: "marinara sauce", quantity: "3", unit: "cups", notes: "homemade or store-bought" },
      { name: "fresh parsley", quantity: "2", unit: "tablespoons", notes: "chopped, for garnish" },
      { name: "red pepper flakes", quantity: "to taste", unit: "", notes: "optional" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 375°F (190°C)." },
      { order: 2, instruction: "Cook pasta shells according to package instructions until al dente. Drain and rinse with cold water to stop cooking. Set aside." },
      { order: 3, instruction: "Heat olive oil in a large skillet over medium heat. Add garlic and cook for 30 seconds until fragrant." },
      { order: 4, instruction: "Add spinach and cook until wilted, about 2-3 minutes. Remove from heat and let cool slightly." },
      { order: 5, instruction: "In a large bowl, combine ricotta cheese, 1 cup mozzarella cheese, 1/4 cup parmesan cheese, egg, basil, oregano, salt, pepper, and nutmeg. Mix well." },
      { order: 6, instruction: "Squeeze excess moisture from the cooked spinach and add to the ricotta mixture. Stir to combine." },
      { order: 7, instruction: "Spread 1 cup of marinara sauce in the bottom of a 9x13 inch baking dish." },
      { order: 8, instruction: "Fill each pasta shell with a generous spoonful of the spinach-ricotta mixture and arrange in the baking dish." },
      { order: 9, instruction: "Pour remaining marinara sauce over the stuffed shells." },
      { order: 10, instruction: "Sprinkle with remaining mozzarella and parmesan cheese." },
      { order: 11, instruction: "Cover with foil and bake for 25 minutes." },
      { order: 12, instruction: "Remove foil and bake for an additional 10 minutes until cheese is bubbly and golden." },
      { order: 13, instruction: "Let rest for 5 minutes before serving." },
      { order: 14, instruction: "Garnish with chopped parsley and red pepper flakes if desired." }
    ],
    cookingVessel: "Baking Dish",
    prepTime: 25,
    cookTime: 40,
    servings: 6,
    difficulty: "Medium",
    mealType: "Dinner",
    cuisine: "Italian",
    categories: ["Pasta", "Vegetarian"],
    dietaryCategories: ["Vegetarian"],
    tags: ["stuffed shells", "pasta", "spinach", "ricotta", "italian"],
    imageUrl: "https://images.unsplash.com/photo-1551892374-ecf8754cf8b0"
  },
  {
    title: "Teriyaki Glazed Salmon with Pineapple Salsa",
    description: "Tender salmon fillets glazed with homemade teriyaki sauce and topped with a fresh pineapple salsa, served with steamed rice for a tropical-inspired dinner.",
    ingredients: [
      { name: "salmon fillets", quantity: "4", unit: "6-ounce", notes: "skin-on" },
      { name: "soy sauce", quantity: "1/4", unit: "cup", notes: "low-sodium" },
      { name: "brown sugar", quantity: "3", unit: "tablespoons" },
      { name: "honey", quantity: "2", unit: "tablespoons" },
      { name: "rice vinegar", quantity: "1", unit: "tablespoon" },
      { name: "garlic", quantity: "2", unit: "cloves", notes: "minced" },
      { name: "ginger", quantity: "1", unit: "tablespoon", notes: "grated" },
      { name: "cornstarch", quantity: "1", unit: "teaspoon" },
      { name: "water", quantity: "1", unit: "tablespoon" },
      { name: "sesame oil", quantity: "1", unit: "teaspoon" },
      { name: "pineapple", quantity: "1", unit: "cup", notes: "diced" },
      { name: "red bell pepper", quantity: "1/2", unit: "medium", notes: "diced" },
      { name: "red onion", quantity: "1/4", unit: "cup", notes: "finely diced" },
      { name: "jalapeño", quantity: "1", unit: "small", notes: "seeded and minced" },
      { name: "cilantro", quantity: "2", unit: "tablespoons", notes: "chopped" },
      { name: "lime juice", quantity: "1", unit: "tablespoon", notes: "fresh" },
      { name: "salt", quantity: "1/2", unit: "teaspoon", notes: "divided" },
      { name: "black pepper", quantity: "1/4", unit: "teaspoon" },
      { name: "sesame seeds", quantity: "1", unit: "tablespoon", notes: "for garnish" },
      { name: "green onions", quantity: "2", unit: "", notes: "sliced, for garnish" },
      { name: "jasmine rice", quantity: "2", unit: "cups", notes: "cooked, for serving" }
    ],
    steps: [
      { order: 1, instruction: "Make the teriyaki sauce: In a small saucepan, combine soy sauce, brown sugar, honey, rice vinegar, garlic, and ginger. Bring to a simmer over medium heat." },
      { order: 2, instruction: "In a small bowl, mix cornstarch and water to make a slurry. Add to the saucepan and stir until sauce thickens, about 1-2 minutes. Remove from heat and stir in sesame oil." },
      { order: 3, instruction: "Make the pineapple salsa: In a medium bowl, combine pineapple, red bell pepper, red onion, jalapeño, cilantro, lime juice, 1/4 teaspoon salt, and a pinch of black pepper. Toss to combine and set aside." },
      { order: 4, instruction: "Preheat oven to 400°F (200°C). Line a baking sheet with parchment paper or aluminum foil." },
      { order: 5, instruction: "Pat salmon fillets dry with paper towels and season with remaining salt and pepper." },
      { order: 6, instruction: "Place salmon skin-side down on the prepared baking sheet." },
      { order: 7, instruction: "Brush salmon generously with half of the teriyaki sauce." },
      { order: 8, instruction: "Bake for 12-15 minutes until salmon is cooked through and flakes easily with a fork." },
      { order: 9, instruction: "During the last 2 minutes of cooking, brush salmon with more teriyaki sauce." },
      { order: 10, instruction: "Serve salmon over cooked jasmine rice, topped with pineapple salsa." },
      { order: 11, instruction: "Drizzle with remaining teriyaki sauce and garnish with sesame seeds and sliced green onions." }
    ],
    cookingVessel: "Baking Sheet",
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    difficulty: "Medium",
    mealType: "Dinner",
    cuisine: "Asian Fusion",
    categories: ["Seafood", "Healthy"],
    dietaryCategories: ["Gluten-Free (with GF soy sauce)"],
    tags: ["salmon", "teriyaki", "pineapple", "asian"],
    imageUrl: "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2"
  },
  {
    title: "Slow Cooker Pulled Pork",
    description: "Tender, juicy pulled pork cooked low and slow with a flavorful spice rub, perfect for sandwiches, tacos, or served with your favorite sides.",
    ingredients: [
      { name: "pork shoulder", quantity: "4", unit: "pounds", notes: "boneless" },
      { name: "brown sugar", quantity: "1/4", unit: "cup", notes: "packed" },
      { name: "paprika", quantity: "2", unit: "tablespoons" },
      { name: "garlic powder", quantity: "1", unit: "tablespoon" },
      { name: "onion powder", quantity: "1", unit: "tablespoon" },
      { name: "mustard powder", quantity: "1", unit: "tablespoon" },
      { name: "cumin", quantity: "2", unit: "teaspoons" },
      { name: "salt", quantity: "1", unit: "tablespoon" },
      { name: "black pepper", quantity: "1", unit: "teaspoon" },
      { name: "cayenne pepper", quantity: "1/2", unit: "teaspoon", notes: "optional" },
      { name: "onion", quantity: "1", unit: "large", notes: "sliced" },
      { name: "garlic", quantity: "4", unit: "cloves", notes: "minced" },
      { name: "chicken broth", quantity: "1", unit: "cup" },
      { name: "apple cider vinegar", quantity: "1/4", unit: "cup" },
      { name: "Worcestershire sauce", quantity: "2", unit: "tablespoons" },
      { name: "barbecue sauce", quantity: "1", unit: "cup", notes: "plus more for serving" },
      { name: "hamburger buns", quantity: "8", unit: "", notes: "for serving" },
      { name: "coleslaw", quantity: "2", unit: "cups", notes: "for serving, optional" },
      { name: "pickles", quantity: "16", unit: "slices", notes: "for serving, optional" }
    ],
    steps: [
      { order: 1, instruction: "In a small bowl, mix together brown sugar, paprika, garlic powder, onion powder, mustard powder, cumin, salt, black pepper, and cayenne pepper (if using) to create a spice rub." },
      { order: 2, instruction: "Trim excess fat from pork shoulder, if desired (leave some fat for flavor)." },
      { order: 3, instruction: "Rub the spice mixture all over the pork shoulder, pressing it into the meat." },
      { order: 4, instruction: "Place sliced onion and minced garlic in the bottom of a slow cooker." },
      { order: 5, instruction: "Place seasoned pork shoulder on top of the onions and garlic." },
      { order: 6, instruction: "In a bowl, whisk together chicken broth, apple cider vinegar, and Worcestershire sauce. Pour around the pork (not over it, to keep the rub intact)." },
      { order: 7, instruction: "Cover and cook on low for 8-10 hours, or on high for 5-6 hours, until pork is very tender and shreds easily with a fork." },
      { order: 8, instruction: "Remove pork from slow cooker and place on a cutting board. Let rest for 10 minutes." },
      { order: 9, instruction: "Using two forks, shred the pork, discarding any large pieces of fat." },
      { order: 10, instruction: "Skim excess fat from the cooking liquid in the slow cooker." },
      { order: 11, instruction: "Return shredded pork to the slow cooker and stir in barbecue sauce. Cook on low for an additional 30 minutes to allow flavors to meld." },
      { order: 12, instruction: "Serve on hamburger buns with additional barbecue sauce, coleslaw, and pickles if desired." }
    ],
    cookingVessel: "Slow Cooker",
    prepTime: 15,
    cookTime: 480,
    servings: 8,
    difficulty: "Easy",
    mealType: "Dinner",
    cuisine: "American",
    categories: ["Pork", "Slow Cooker"],
    dietaryCategories: ["Dairy-Free"],
    tags: ["pulled pork", "barbecue", "slow cooker", "sandwiches"],
    imageUrl: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9"
  },
  {
    title: "Ratatouille",
    description: "A classic French vegetable stew featuring layers of colorful vegetables baked in a rich tomato sauce, perfect as a vegetarian main course or side dish.",
    ingredients: [
      { name: "eggplant", quantity: "1", unit: "large", notes: "sliced into 1/4-inch rounds" },
      { name: "zucchini", quantity: "2", unit: "medium", notes: "sliced into 1/4-inch rounds" },
      { name: "yellow squash", quantity: "2", unit: "medium", notes: "sliced into 1/4-inch rounds" },
      { name: "roma tomatoes", quantity: "4", unit: "medium", notes: "sliced into 1/4-inch rounds" },
      { name: "olive oil", quantity: "1/4", unit: "cup", notes: "divided" },
      { name: "onion", quantity: "1", unit: "large", notes: "diced" },
      { name: "bell peppers", quantity: "2", unit: "medium", notes: "assorted colors, diced" },
      { name: "garlic", quantity: "4", unit: "cloves", notes: "minced" },
      { name: "crushed tomatoes", quantity: "1", unit: "28-ounce can" },
      { name: "fresh thyme", quantity: "2", unit: "tablespoons", notes: "chopped" },
      { name: "fresh basil", quantity: "1/4", unit: "cup", notes: "chopped, plus more for garnish" },
      { name: "bay leaf", quantity: "1", unit: "" },
      { name: "salt", quantity: "1 1/2", unit: "teaspoons", notes: "divided" },
      { name: "black pepper", quantity: "1", unit: "teaspoon", notes: "divided" },
      { name: "red pepper flakes", quantity: "1/4", unit: "teaspoon", notes: "optional" },
      { name: "parmesan cheese", quantity: "1/2", unit: "cup", notes: "grated, for serving (optional)" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 375°F (190°C)." },
      { order: 2, instruction: "Place eggplant slices on paper towels and sprinkle with 1/2 teaspoon salt. Let sit for 15 minutes to draw out moisture, then pat dry." },
      { order: 3, instruction: "Heat 2 tablespoons olive oil in a large oven-safe skillet or Dutch oven over medium heat." },
      { order: 4, instruction: "Add onion and bell peppers. Cook until softened, about 5 minutes." },
      { order: 5, instruction: "Add garlic and cook for 30 seconds until fragrant." },
      { order: 6, instruction: "Add crushed tomatoes, half of the thyme, half of the basil, bay leaf, remaining salt, half of the black pepper, and red pepper flakes if using. Simmer for 10 minutes until slightly thickened." },
      { order: 7, instruction: "Remove bay leaf and spread sauce evenly in the bottom of the skillet or transfer to a 9x13 inch baking dish." },
      { order: 8, instruction: "Arrange vegetable slices in alternating patterns (eggplant, zucchini, yellow squash, tomato) in a circular pattern from the outer edge to the center, slightly overlapping." },
      { order: 9, instruction: "Drizzle vegetables with remaining olive oil and sprinkle with remaining thyme, basil, and black pepper." },
      { order: 10, instruction: "Cover with foil and bake for 30 minutes." },
      { order: 11, instruction: "Remove foil and bake for an additional 25-30 minutes until vegetables are tender and lightly browned." },
      { order: 12, instruction: "Let cool for 10 minutes before serving." },
      { order: 13, instruction: "Garnish with additional fresh basil and grated parmesan cheese if desired." }
    ],
    cookingVessel: "Dutch Oven",
    prepTime: 30,
    cookTime: 70,
    servings: 6,
    difficulty: "Medium",
    mealType: "Dinner",
    cuisine: "French",
    categories: ["Vegetarian", "Healthy"],
    dietaryCategories: ["Vegetarian", "Vegan (without cheese)", "Gluten-Free"],
    tags: ["ratatouille", "vegetable stew", "french", "healthy"],
    imageUrl: "https://images.unsplash.com/photo-1572453800999-e8d2d1589b7c"
  },
  {
    title: "Chicken Enchiladas",
    description: "Flavorful chicken enchiladas filled with seasoned shredded chicken and cheese, topped with homemade enchilada sauce and baked until bubbly for a satisfying Mexican-inspired dinner.",
    ingredients: [
      { name: "chicken breasts", quantity: "2", unit: "pounds", notes: "boneless, skinless" },
      { name: "olive oil", quantity: "2", unit: "tablespoons" },
      { name: "onion", quantity: "1", unit: "medium", notes: "diced" },
      { name: "bell pepper", quantity: "1", unit: "medium", notes: "diced" },
      { name: "garlic", quantity: "3", unit: "cloves", notes: "minced" },
      { name: "chili powder", quantity: "2", unit: "tablespoons" },
      { name: "ground cumin", quantity: "1", unit: "tablespoon" },
      { name: "dried oregano", quantity: "1", unit: "teaspoon" },
      { name: "salt", quantity: "1 1/2", unit: "teaspoons", notes: "divided" },
      { name: "black pepper", quantity: "1/2", unit: "teaspoon" },
      { name: "tomato sauce", quantity: "1", unit: "15-ounce can" },
      { name: "chicken broth", quantity: "1", unit: "cup" },
      { name: "flour tortillas", quantity: "12", unit: "8-inch" },
      { name: "monterey jack cheese", quantity: "3", unit: "cups", notes: "shredded, divided" },
      { name: "black beans", quantity: "1", unit: "15-ounce can", notes: "drained and rinsed" },
      { name: "corn kernels", quantity: "1", unit: "cup", notes: "fresh or frozen" },
      { name: "sour cream", quantity: "1/2", unit: "cup", notes: "plus more for serving" },
      { name: "fresh cilantro", quantity: "1/4", unit: "cup", notes: "chopped, plus more for garnish" },
      { name: "green onions", quantity: "3", unit: "", notes: "sliced" },
      { name: "avocado", quantity: "1", unit: "medium", notes: "diced, for serving" },
      { name: "lime wedges", quantity: "1", unit: "lime", notes: "cut into wedges, for serving" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 375°F (190°C)." },
      { order: 2, instruction: "In a large pot, place chicken breasts and cover with water. Add 1/2 teaspoon salt. Bring to a boil, then reduce heat and simmer for 15-20 minutes until chicken is cooked through." },
      { order: 3, instruction: "Remove chicken from pot and let cool slightly. Shred using two forks." },
      { order: 4, instruction: "Meanwhile, heat olive oil in a large skillet over medium heat. Add onion and bell pepper, cook until softened, about 5 minutes." },
      { order: 5, instruction: "Add garlic and cook for 30 seconds until fragrant." },
      { order: 6, instruction: "Stir in chili powder, cumin, oregano, remaining salt, and black pepper. Cook for 1 minute to toast the spices." },
      { order: 7, instruction: "Add tomato sauce and chicken broth. Simmer for 5-7 minutes until slightly thickened." },
      { order: 8, instruction: "Remove 1 cup of the sauce and set aside for topping." },
      { order: 9, instruction: "In a large bowl, combine shredded chicken, black beans, corn, sour cream, cilantro, green onions, and 2 cups of cheese." },
      { order: 10, instruction: "Add 1/2 cup of the sauce to the chicken mixture and stir to combine." },
      { order: 11, instruction: "Spread 1/4 cup of sauce in the bottom of a 9x13 inch baking dish." },
      { order: 12, instruction: "Warm tortillas in the microwave for 30 seconds to make them more pliable." },
      { order: 13, instruction: "Fill each tortilla with about 1/3 cup of the chicken mixture. Roll up and place seam-side down in the baking dish." },
      { order: 14, instruction: "Pour the reserved sauce over the enchiladas and sprinkle with remaining cheese." },
      { order: 15, instruction: "Cover with foil and bake for 20 minutes." },
      { order: 16, instruction: "Remove foil and bake for an additional 10 minutes until cheese is bubbly and golden." },
      { order: 17, instruction: "Let cool for 5 minutes before serving." },
      { order: 18, instruction: "Serve with additional sour cream, diced avocado, chopped cilantro, and lime wedges." }
    ],
    cookingVessel: "Baking Dish",
    prepTime: 30,
    cookTime: 50,
    servings: 6,
    difficulty: "Medium",
    mealType: "Dinner",
    cuisine: "Mexican",
    categories: ["Chicken", "Casseroles"],
    dietaryCategories: [],
    tags: ["enchiladas", "mexican", "chicken", "comfort food"],
    imageUrl: "https://images.unsplash.com/photo-1534352956036-cd81e27dd615"
  }
];

export default dinnerRecipes;
