// Drink Recipes for WhatAboutDinner App
// 20 detailed drink recipes with all required fields

const drinkRecipes = [
  {
    title: "Classic Mojito",
    description: "A refreshing Cuban cocktail featuring white rum, fresh mint, lime juice, and soda water for a perfect balance of sweet, sour, and minty flavors.",
    ingredients: [
      { name: "white rum", quantity: "2", unit: "ounces" },
      { name: "fresh lime juice", quantity: "1", unit: "ounce" },
      { name: "simple syrup", quantity: "3/4", unit: "ounce", notes: "equal parts sugar and water" },
      { name: "fresh mint leaves", quantity: "8-10", unit: "leaves", notes: "plus more for garnish" },
      { name: "soda water", quantity: "2", unit: "ounces" },
      { name: "lime wedge", quantity: "1", unit: "", notes: "for garnish" },
      { name: "crushed ice", quantity: "1", unit: "cup" }
    ],
    steps: [
      { order: 1, instruction: "In a highball glass, gently muddle the mint leaves with the simple syrup to release the mint oils." },
      { order: 2, instruction: "Add the fresh lime juice and white rum to the glass." },
      { order: 3, instruction: "Fill the glass with crushed ice." },
      { order: 4, instruction: "Top with soda water and stir gently to combine." },
      { order: 5, instruction: "Garnish with additional mint leaves and a lime wedge." },
      { order: 6, instruction: "Serve immediately with a straw." }
    ],
    cookingVessel: "Highball Glass",
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    difficulty: "Easy",
    mealType: "Drink",
    cuisine: "Cuban",
    categories: ["Cocktails", "Rum Drinks"],
    dietaryCategories: ["Vegan", "Gluten-Free", "Dairy-Free"],
    tags: ["mojito", "rum", "mint", "refreshing", "summer"],
    imageUrl: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a"
  },
  {
    title: "Strawberry Basil Lemonade",
    description: "A vibrant, refreshing summer drink combining sweet strawberries, aromatic basil, and tangy lemonade for a perfect balance of flavors that's both sophisticated and family-friendly.",
    ingredients: [
      { name: "fresh strawberries", quantity: "1", unit: "cup", notes: "hulled and halved" },
      { name: "fresh basil leaves", quantity: "10", unit: "large", notes: "plus more for garnish" },
      { name: "granulated sugar", quantity: "1/2", unit: "cup" },
      { name: "water", quantity: "1", unit: "cup", notes: "for simple syrup" },
      { name: "fresh lemon juice", quantity: "1", unit: "cup", notes: "about 6-8 lemons" },
      { name: "cold water", quantity: "4", unit: "cups" },
      { name: "ice cubes", quantity: "2", unit: "cups" },
      { name: "lemon slices", quantity: "for garnish", unit: "" },
      { name: "strawberry slices", quantity: "for garnish", unit: "" }
    ],
    steps: [
      { order: 1, instruction: "In a small saucepan, combine sugar and 1 cup water. Bring to a simmer over medium heat, stirring until sugar dissolves completely. Remove from heat and let cool. This is your simple syrup." },
      { order: 2, instruction: "In a blender, combine strawberries, basil leaves, and 1/4 cup of the cooled simple syrup. Blend until smooth." },
      { order: 3, instruction: "Strain the strawberry-basil mixture through a fine-mesh sieve into a pitcher, pressing on solids to extract as much liquid as possible. Discard solids." },
      { order: 4, instruction: "Add lemon juice, remaining simple syrup, and cold water to the pitcher. Stir well to combine." },
      { order: 5, instruction: "Taste and adjust sweetness if needed by adding more simple syrup." },
      { order: 6, instruction: "Refrigerate until chilled, at least 1 hour." },
      { order: 7, instruction: "To serve, fill glasses with ice cubes and pour lemonade over ice." },
      { order: 8, instruction: "Garnish with lemon slices, strawberry slices, and fresh basil leaves." }
    ],
    cookingVessel: "Pitcher",
    prepTime: 15,
    cookTime: 5,
    servings: 6,
    difficulty: "Easy",
    mealType: "Drink",
    cuisine: "American",
    categories: ["Non-Alcoholic Drinks", "Lemonades"],
    dietaryCategories: ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free"],
    tags: ["strawberry", "basil", "lemonade", "summer", "refreshing"],
    imageUrl: "https://images.unsplash.com/photo-1497534446932-c925b458314e"
  },
  {
    title: "Spiced Chai Latte",
    description: "A warming, aromatic blend of black tea and spices simmered with milk for a comforting beverage that's perfect for cool mornings or cozy afternoons.",
    ingredients: [
      { name: "water", quantity: "2", unit: "cups" },
      { name: "black tea bags", quantity: "4", unit: "", notes: "or 4 teaspoons loose black tea" },
      { name: "cinnamon sticks", quantity: "2", unit: "" },
      { name: "whole cloves", quantity: "6", unit: "" },
      { name: "cardamom pods", quantity: "6", unit: "", notes: "lightly crushed" },
      { name: "star anise", quantity: "1", unit: "whole" },
      { name: "fresh ginger", quantity: "1", unit: "inch piece", notes: "sliced" },
      { name: "black peppercorns", quantity: "6", unit: "" },
      { name: "whole milk", quantity: "2", unit: "cups", notes: "or non-dairy alternative" },
      { name: "honey", quantity: "2", unit: "tablespoons", notes: "or to taste" },
      { name: "vanilla extract", quantity: "1/2", unit: "teaspoon", notes: "optional" },
      { name: "ground cinnamon", quantity: "for garnish", unit: "" }
    ],
    steps: [
      { order: 1, instruction: "In a medium saucepan, combine water, cinnamon sticks, cloves, cardamom pods, star anise, ginger, and peppercorns." },
      { order: 2, instruction: "Bring to a boil, then reduce heat and simmer for 10 minutes to infuse the spices." },
      { order: 3, instruction: "Add tea bags (or loose tea in an infuser), remove from heat, and let steep for 5 minutes." },
      { order: 4, instruction: "Strain the tea mixture into another saucepan, discarding the solids." },
      { order: 5, instruction: "Add milk to the spiced tea and heat over medium-low heat until hot but not boiling." },
      { order: 6, instruction: "Stir in honey and vanilla extract (if using) until dissolved." },
      { order: 7, instruction: "Taste and adjust sweetness if needed." },
      { order: 8, instruction: "Pour into mugs and sprinkle with ground cinnamon." },
      { order: 9, instruction: "Serve hot." }
    ],
    cookingVessel: "Saucepan",
    prepTime: 5,
    cookTime: 20,
    servings: 4,
    difficulty: "Easy",
    mealType: "Drink",
    cuisine: "Indian",
    categories: ["Hot Drinks", "Tea Drinks"],
    dietaryCategories: ["Vegetarian", "Gluten-Free"],
    tags: ["chai", "tea", "spiced", "warming", "comfort"],
    imageUrl: "https://images.unsplash.com/photo-1571934811356-5cc061b6821f"
  },
  {
    title: "Classic Margarita",
    description: "A perfectly balanced cocktail featuring tequila, fresh lime juice, and orange liqueur, served with a salted rim for a refreshing and timeless drink that's both tangy and smooth.",
    ingredients: [
      { name: "silver tequila", quantity: "2", unit: "ounces" },
      { name: "fresh lime juice", quantity: "1", unit: "ounce" },
      { name: "orange liqueur", quantity: "1/2", unit: "ounce", notes: "Cointreau or Triple Sec" },
      { name: "agave nectar", quantity: "1/2", unit: "ounce", notes: "or simple syrup" },
      { name: "coarse salt", quantity: "for rimming", unit: "" },
      { name: "lime wheel", quantity: "1", unit: "", notes: "for garnish" },
      { name: "ice cubes", quantity: "1", unit: "cup" }
    ],
    steps: [
      { order: 1, instruction: "Run a lime wedge around the rim of a rocks glass, then dip the rim in coarse salt to coat." },
      { order: 2, instruction: "Fill the glass with ice and set aside." },
      { order: 3, instruction: "In a cocktail shaker, combine tequila, fresh lime juice, orange liqueur, and agave nectar." },
      { order: 4, instruction: "Add ice to the shaker and shake vigorously for about 15 seconds until well-chilled." },
      { order: 5, instruction: "Strain the mixture into the prepared rocks glass." },
      { order: 6, instruction: "Garnish with a lime wheel on the rim of the glass." },
      { order: 7, instruction: "Serve immediately." }
    ],
    cookingVessel: "Cocktail Shaker",
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    difficulty: "Easy",
    mealType: "Drink",
    cuisine: "Mexican",
    categories: ["Cocktails", "Tequila Drinks"],
    dietaryCategories: ["Gluten-Free", "Vegan", "Dairy-Free"],
    tags: ["margarita", "tequila", "lime", "classic", "refreshing"],
    imageUrl: "https://images.unsplash.com/photo-1556855810-ac404aa91e85"
  },
  {
    title: "Tropical Green Smoothie",
    description: "A nutrient-packed smoothie combining leafy greens with sweet tropical fruits for a refreshing, healthy drink that's perfect for breakfast or a post-workout boost.",
    ingredients: [
      { name: "fresh spinach", quantity: "2", unit: "cups", notes: "packed" },
      { name: "frozen pineapple chunks", quantity: "1", unit: "cup" },
      { name: "frozen mango chunks", quantity: "1", unit: "cup" },
      { name: "banana", quantity: "1", unit: "medium", notes: "ripe" },
      { name: "coconut water", quantity: "1", unit: "cup" },
      { name: "Greek yogurt", quantity: "1/2", unit: "cup", notes: "plain, optional" },
      { name: "fresh ginger", quantity: "1/2", unit: "teaspoon", notes: "grated, optional" },
      { name: "chia seeds", quantity: "1", unit: "tablespoon", notes: "optional" },
      { name: "honey", quantity: "1", unit: "teaspoon", notes: "optional, to taste" },
      { name: "ice cubes", quantity: "1/2", unit: "cup", notes: "if using fresh fruit" }
    ],
    steps: [
      { order: 1, instruction: "Add spinach and coconut water to a blender. Blend until smooth and no leafy bits remain." },
      { order: 2, instruction: "Add frozen pineapple, mango, banana, and Greek yogurt (if using) to the blender." },
      { order: 3, instruction: "Add grated ginger, chia seeds, and honey (if using)." },
      { order: 4, instruction: "If using fresh fruit instead of frozen, add ice cubes." },
      { order: 5, instruction: "Blend on high speed until smooth and creamy, about 30-60 seconds." },
      { order: 6, instruction: "Taste and adjust sweetness if needed by adding more honey." },
      { order: 7, instruction: "Pour into glasses and serve immediately." }
    ],
    cookingVessel: "Blender",
    prepTime: 10,
    cookTime: 0,
    servings: 2,
    difficulty: "Easy",
    mealType: "Drink",
    cuisine: "American",
    categories: ["Smoothies", "Breakfast Drinks"],
    dietaryCategories: ["Vegetarian", "Gluten-Free"],
    tags: ["green smoothie", "tropical", "healthy", "spinach", "pineapple"],
    imageUrl: "https://images.unsplash.com/photo-1610970881699-44a5587cabec"
  },
  {
    title: "Classic Bloody Mary",
    description: "A savory, spicy cocktail featuring vodka and tomato juice, enhanced with a blend of seasonings and garnishes for a bold brunch favorite that's both a drink and an appetizer in one.",
    ingredients: [
      { name: "vodka", quantity: "2", unit: "ounces" },
      { name: "tomato juice", quantity: "4", unit: "ounces" },
      { name: "fresh lemon juice", quantity: "1/2", unit: "ounce" },
      { name: "Worcestershire sauce", quantity: "1/2", unit: "teaspoon" },
      { name: "prepared horseradish", quantity: "1/2", unit: "teaspoon", notes: "or to taste" },
      { name: "hot sauce", quantity: "3", unit: "dashes", notes: "such as Tabasco" },
      { name: "celery salt", quantity: "1/8", unit: "teaspoon" },
      { name: "black pepper", quantity: "1/8", unit: "teaspoon", notes: "freshly ground" },
      { name: "celery stalk", quantity: "1", unit: "", notes: "for garnish" },
      { name: "green olives", quantity: "3", unit: "", notes: "for garnish" },
      { name: "lemon wedge", quantity: "1", unit: "", notes: "for garnish" },
      { name: "pickle spear", quantity: "1", unit: "", notes: "for garnish, optional" },
      { name: "bacon strip", quantity: "1", unit: "", notes: "cooked crisp, for garnish, optional" },
      { name: "ice cubes", quantity: "1", unit: "cup" }
    ],
    steps: [
      { order: 1, instruction: "If desired, rim a highball glass with celery salt by rubbing a lemon wedge around the rim and dipping in celery salt." },
      { order: 2, instruction: "Fill the glass with ice cubes." },
      { order: 3, instruction: "In a mixing glass or shaker, combine vodka, tomato juice, lemon juice, Worcestershire sauce, horseradish, hot sauce, celery salt, and black pepper." },
      { order: 4, instruction: "Stir or roll between two glasses to combine (don't shake)." },
      { order: 5, instruction: "Pour the mixture into the prepared highball glass." },
      { order: 6, instruction: "Garnish with a celery stalk, green olives, lemon wedge, and optional pickle spear and bacon strip." },
      { order: 7, instruction: "Serve immediately." }
    ],
    cookingVessel: "Mixing Glass",
    prepTime: 10,
    cookTime: 0,
    servings: 1,
    difficulty: "Medium",
    mealType: "Drink",
    cuisine: "American",
    categories: ["Cocktails", "Brunch Drinks"],
    dietaryCategories: ["Gluten-Free"],
    tags: ["bloody mary", "vodka", "tomato", "spicy", "brunch"],
    imageUrl: "https://images.unsplash.com/photo-1576874240748-795e3bfc32cc"
  },
  {
    title: "Homemade Cold Brew Coffee",
    description: "A smooth, low-acid coffee concentrate made by steeping coarsely ground beans in cold water, resulting in a rich, flavorful base that can be diluted and customized to your preference.",
    ingredients: [
      { name: "coffee beans", quantity: "1", unit: "cup", notes: "coarsely ground" },
      { name: "cold water", quantity: "4", unit: "cups", notes: "filtered" },
      { name: "ice cubes", quantity: "for serving", unit: "" },
      { name: "milk or cream", quantity: "to taste", unit: "", notes: "optional" },
      { name: "simple syrup", quantity: "to taste", unit: "", notes: "optional" },
      { name: "vanilla extract", quantity: "1/4", unit: "teaspoon", notes: "optional" },
      { name: "ground cinnamon", quantity: "pinch", unit: "", notes: "optional, for garnish" }
    ],
    steps: [
      { order: 1, instruction: "In a large jar or pitcher, combine coarsely ground coffee beans and cold water. Stir gently to ensure all grounds are saturated." },
      { order: 2, instruction: "Cover and refrigerate for 12-24 hours. The longer it steeps, the stronger the coffee will be." },
      { order: 3, instruction: "After steeping, strain the coffee through a fine-mesh sieve lined with cheesecloth or a coffee filter into a clean container." },
      { order: 4, instruction: "For a clearer brew, strain a second time if desired." },
      { order: 5, instruction: "The result is a cold brew concentrate. Store in a sealed container in the refrigerator for up to 2 weeks." },
      { order: 6, instruction: "To serve, fill a glass with ice cubes." },
      { order: 7, instruction: "Dilute the cold brew concentrate with equal parts water or milk, adjusting to your preferred strength." },
      { order: 8, instruction: "Add simple syrup and/or vanilla extract if desired for sweetness." },
      { order: 9, instruction: "Stir well and garnish with a sprinkle of ground cinnamon if desired." }
    ],
    cookingVessel: "Large Jar or Pitcher",
    prepTime: 10,
    cookTime: 0,
    servings: 8,
    difficulty: "Easy",
    mealType: "Drink",
    cuisine: "American",
    categories: ["Coffee Drinks", "Cold Drinks"],
    dietaryCategories: ["Vegan", "Gluten-Free", "Dairy-Free (without milk)"],
    tags: ["cold brew", "coffee", "concentrate", "smooth", "caffeinated"],
    imageUrl: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735"
  },
  {
    title: "Fresh Watermelon Mint Cooler",
    description: "A light, hydrating beverage that captures the essence of summer with juicy watermelon and aromatic mint, perfect for hot days or outdoor gatherings.",
    ingredients: [
      { name: "watermelon", quantity: "8", unit: "cups", notes: "cubed, seeds removed" },
      { name: "fresh mint leaves", quantity: "1/4", unit: "cup", notes: "loosely packed, plus more for garnish" },
      { name: "lime juice", quantity: "1/4", unit: "cup", notes: "freshly squeezed" },
      { name: "honey", quantity: "2", unit: "tablespoons", notes: "or to taste, optional" },
      { name: "cold water", quantity: "1", unit: "cup", notes: "optional, for diluting" },
      { name: "ice cubes", quantity: "2", unit: "cups" },
      { name: "lime slices", quantity: "for garnish", unit: "" },
      { name: "watermelon wedges", quantity: "for garnish", unit: "" }
    ],
    steps: [
      { order: 1, instruction: "Place watermelon cubes in a blender and blend until smooth." },
      { order: 2, instruction: "Add mint leaves and lime juice to the blender. Blend again until mint is finely chopped and incorporated." },
      { order: 3, instruction: "If desired, add honey and blend briefly to combine." },
      { order: 4, instruction: "Strain the mixture through a fine-mesh sieve into a pitcher, pressing with a spoon to extract all the juice. Discard solids." },
      { order: 5, instruction: "If the drink is too concentrated, add cold water to dilute to your preferred consistency." },
      { order: 6, instruction: "Refrigerate until chilled, at least 1 hour." },
      { order: 7, instruction: "To serve, fill glasses with ice cubes and pour the watermelon cooler over the ice." },
      { order: 8, instruction: "Garnish with fresh mint leaves, lime slices, and small watermelon wedges." }
    ],
    cookingVessel: "Blender",
    prepTime: 15,
    cookTime: 0,
    servings: 6,
    difficulty: "Easy",
    mealType: "Drink",
    cuisine: "American",
    categories: ["Non-Alcoholic Drinks", "Fruit Drinks"],
    dietaryCategories: ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free"],
    tags: ["watermelon", "mint", "refreshing", "summer", "hydrating"],
    imageUrl: "https://images.unsplash.com/photo-1527661591475-527312dd65f5"
  },
  {
    title: "Classic Old Fashioned",
    description: "A sophisticated whiskey cocktail featuring bourbon or rye, sugar, and bitters, garnished with orange peel and a cherry for a timeless drink that highlights the spirit's complex flavors.",
    ingredients: [
      { name: "bourbon or rye whiskey", quantity: "2", unit: "ounces" },
      { name: "sugar cube", quantity: "1", unit: "", notes: "or 1/2 teaspoon granulated sugar" },
      { name: "Angostura bitters", quantity: "2-3", unit: "dashes" },
      { name: "orange peel", quantity: "1", unit: "strip" },
      { name: "maraschino cherry", quantity: "1", unit: "", notes: "optional" },
      { name: "water", quantity: "1", unit: "teaspoon" },
      { name: "large ice cube", quantity: "1", unit: "", notes: "or 2-3 regular ice cubes" }
    ],
    steps: [
      { order: 1, instruction: "Place the sugar cube in an old-fashioned glass." },
      { order: 2, instruction: "Add the Angostura bitters and a teaspoon of water to the sugar." },
      { order: 3, instruction: "Muddle until the sugar is dissolved." },
      { order: 4, instruction: "Add the large ice cube or regular ice cubes to the glass." },
      { order: 5, instruction: "Pour the whiskey over the ice." },
      { order: 6, instruction: "Gently stir for about 10 seconds to chill and dilute slightly." },
      { order: 7, instruction: "Express the oils from the orange peel by twisting it over the drink, then rub the peel around the rim of the glass." },
      { order: 8, instruction: "Drop the orange peel into the glass and add a maraschino cherry if desired." },
      { order: 9, instruction: "Serve immediately." }
    ],
    cookingVessel: "Old-Fashioned Glass",
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    difficulty: "Easy",
    mealType: "Drink",
    cuisine: "American",
    categories: ["Cocktails", "Whiskey Drinks"],
    dietaryCategories: ["Gluten-Free", "Dairy-Free", "Vegan"],
    tags: ["old fashioned", "whiskey", "bourbon", "classic", "elegant"],
    imageUrl: "https://images.unsplash.com/photo-1470337458703-46ad1756a187"
  },
  {
    title: "Homemade Ginger Turmeric Wellness Shot",
    description: "A potent, immune-boosting elixir featuring fresh ginger, turmeric, lemon, and honey for a concentrated dose of anti-inflammatory ingredients that support overall health.",
    ingredients: [
      { name: "fresh ginger", quantity: "4", unit: "ounces", notes: "peeled and roughly chopped" },
      { name: "fresh turmeric root", quantity: "2", unit: "ounces", notes: "peeled and roughly chopped" },
      { name: "lemons", quantity: "2", unit: "medium", notes: "juiced" },
      { name: "honey", quantity: "2", unit: "tablespoons", notes: "raw, or to taste" },
      { name: "black pepper", quantity: "1/8", unit: "teaspoon", notes: "freshly ground" },
      { name: "cayenne pepper", quantity: "1", unit: "pinch", notes: "optional" },
      { name: "filtered water", quantity: "1/4", unit: "cup" },
      { name: "apple", quantity: "1", unit: "small", notes: "cored and chopped, optional for sweetness" }
    ],
    steps: [
      { order: 1, instruction: "Add ginger, turmeric, lemon juice, honey, black pepper, cayenne pepper (if using), apple (if using), and water to a high-speed blender." },
      { order: 2, instruction: "Blend on high until completely smooth, about 1-2 minutes." },
      { order: 3, instruction: "Place a fine-mesh strainer over a bowl and pour the mixture through it, pressing with a spoon to extract all the liquid." },
      { order: 4, instruction: "Transfer the strained liquid to a clean jar or bottle with a tight-fitting lid." },
      { order: 5, instruction: "Store in the refrigerator for up to 5-7 days." },
      { order: 6, instruction: "To serve, pour 1-2 ounces into a small glass. For best results, drink on an empty stomach." },
      { order: 7, instruction: "Shake well before each use, as separation is natural." }
    ],
    cookingVessel: "Blender",
    prepTime: 15,
    cookTime: 0,
    servings: 8,
    difficulty: "Easy",
    mealType: "Drink",
    cuisine: "Wellness",
    categories: ["Health Drinks", "Wellness Shots"],
    dietaryCategories: ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free"],
    tags: ["ginger", "turmeric", "wellness", "immune-boosting", "anti-inflammatory"],
    imageUrl: "https://images.unsplash.com/photo-1600691746227-3250d3a3b1e5"
  },
  {
    title: "Creamy Matcha Green Tea Latte",
    description: "A soothing, antioxidant-rich beverage featuring ceremonial grade matcha powder whisked with steamed milk for a slightly sweet, earthy drink with a beautiful green hue and velvety texture.",
    ingredients: [
      { name: "ceremonial grade matcha powder", quantity: "1 1/2", unit: "teaspoons" },
      { name: "hot water", quantity: "2", unit: "tablespoons", notes: "175°F/80°C, not boiling" },
      { name: "milk", quantity: "1", unit: "cup", notes: "dairy or plant-based" },
      { name: "honey or maple syrup", quantity: "1", unit: "teaspoon", notes: "or to taste, optional" },
      { name: "vanilla extract", quantity: "1/4", unit: "teaspoon", notes: "optional" },
      { name: "matcha powder", quantity: "for dusting", unit: "", notes: "optional" }
    ],
    steps: [
      { order: 1, instruction: "Sift matcha powder into a wide mug or small bowl to remove any clumps." },
      { order: 2, instruction: "Add hot water to the matcha powder." },
      { order: 3, instruction: "Using a bamboo whisk or small regular whisk, whisk vigorously in a zigzag motion until the matcha is fully dissolved and frothy." },
      { order: 4, instruction: "In a small saucepan, heat milk until steaming but not boiling, or use a milk frother if available." },
      { order: 5, instruction: "If desired, stir honey or maple syrup and vanilla extract into the hot milk." },
      { order: 6, instruction: "Slowly pour the hot milk into the matcha mixture while stirring." },
      { order: 7, instruction: "For an extra frothy latte, use an immersion blender or transfer to a blender and blend for 10-15 seconds." },
      { order: 8, instruction: "Pour into a mug and dust with additional matcha powder if desired." },
      { order: 9, instruction: "Serve immediately." }
    ],
    cookingVessel: "Saucepan",
    prepTime: 5,
    cookTime: 5,
    servings: 1,
    difficulty: "Easy",
    mealType: "Drink",
    cuisine: "Japanese",
    categories: ["Hot Drinks", "Tea Drinks"],
    dietaryCategories: ["Vegetarian", "Gluten-Free"],
    tags: ["matcha", "green tea", "latte", "antioxidant", "calming"],
    imageUrl: "https://images.unsplash.com/photo-1536256263959-770b48d82b0a"
  },
  {
    title: "Classic Piña Colada",
    description: "A tropical, creamy cocktail blending rum, coconut cream, and pineapple juice for a sweet, vacation-worthy drink that's like sunshine in a glass.",
    ingredients: [
      { name: "white rum", quantity: "2", unit: "ounces" },
      { name: "cream of coconut", quantity: "2", unit: "ounces", notes: "not coconut milk" },
      { name: "pineapple juice", quantity: "2", unit: "ounces", notes: "fresh if possible" },
      { name: "fresh pineapple chunks", quantity: "1/4", unit: "cup", notes: "plus more for garnish" },
      { name: "ice cubes", quantity: "1 1/2", unit: "cups" },
      { name: "maraschino cherry", quantity: "1", unit: "", notes: "for garnish" },
      { name: "pineapple wedge", quantity: "1", unit: "", notes: "for garnish" }
    ],
    steps: [
      { order: 1, instruction: "Add white rum, cream of coconut, pineapple juice, pineapple chunks, and ice to a blender." },
      { order: 2, instruction: "Blend on high until smooth and creamy, about 30 seconds." },
      { order: 3, instruction: "Pour into a hurricane glass or large goblet." },
      { order: 4, instruction: "Garnish with a pineapple wedge and maraschino cherry." },
      { order: 5, instruction: "Serve immediately with a straw." }
    ],
    cookingVessel: "Blender",
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    difficulty: "Easy",
    mealType: "Drink",
    cuisine: "Puerto Rican",
    categories: ["Cocktails", "Frozen Drinks"],
    dietaryCategories: ["Gluten-Free", "Dairy-Free"],
    tags: ["piña colada", "rum", "coconut", "pineapple", "tropical"],
    imageUrl: "https://images.unsplash.com/photo-1607446045710-d5a8fd0bc07b"
  },
  {
    title: "Cucumber Mint Agua Fresca",
    description: "A light, refreshing Mexican-inspired beverage featuring cucumber, mint, and lime for a hydrating, subtly sweet drink that's perfect for hot summer days.",
    ingredients: [
      { name: "cucumber", quantity: "2", unit: "large", notes: "peeled and chopped" },
      { name: "fresh mint leaves", quantity: "1/4", unit: "cup", notes: "loosely packed, plus more for garnish" },
      { name: "lime juice", quantity: "1/4", unit: "cup", notes: "freshly squeezed" },
      { name: "granulated sugar", quantity: "1/4", unit: "cup", notes: "or to taste" },
      { name: "water", quantity: "4", unit: "cups", notes: "divided" },
      { name: "ice cubes", quantity: "2", unit: "cups" },
      { name: "lime slices", quantity: "for garnish", unit: "" },
      { name: "cucumber slices", quantity: "for garnish", unit: "" }
    ],
    steps: [
      { order: 1, instruction: "In a blender, combine chopped cucumber, mint leaves, lime juice, sugar, and 2 cups of water." },
      { order: 2, instruction: "Blend on high until smooth, about 1 minute." },
      { order: 3, instruction: "Place a fine-mesh strainer over a pitcher and pour the mixture through it, pressing with a spoon to extract all the liquid. Discard solids." },
      { order: 4, instruction: "Add the remaining 2 cups of water to the pitcher and stir to combine." },
      { order: 5, instruction: "Taste and adjust sweetness if needed by adding more sugar and stirring until dissolved." },
      { order: 6, instruction: "Refrigerate until chilled, at least 1 hour." },
      { order: 7, instruction: "To serve, fill glasses with ice cubes and pour the agua fresca over the ice." },
      { order: 8, instruction: "Garnish with fresh mint leaves, lime slices, and cucumber slices." }
    ],
    cookingVessel: "Blender",
    prepTime: 15,
    cookTime: 0,
    servings: 6,
    difficulty: "Easy",
    mealType: "Drink",
    cuisine: "Mexican",
    categories: ["Non-Alcoholic Drinks", "Agua Frescas"],
    dietaryCategories: ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free"],
    tags: ["cucumber", "mint", "refreshing", "hydrating", "summer"],
    imageUrl: "https://images.unsplash.com/photo-1622597467836-f3e6707e1fd6"
  },
  {
    title: "Homemade Masala Chai",
    description: "A fragrant, spiced Indian tea simmered with aromatic spices and milk for a warming, comforting beverage that's both soothing and invigorating.",
    ingredients: [
      { name: "water", quantity: "2", unit: "cups" },
      { name: "black tea leaves", quantity: "2", unit: "tablespoons", notes: "or 4 tea bags" },
      { name: "fresh ginger", quantity: "1", unit: "inch piece", notes: "peeled and sliced" },
      { name: "cinnamon stick", quantity: "1", unit: "" },
      { name: "green cardamom pods", quantity: "4", unit: "", notes: "lightly crushed" },
      { name: "cloves", quantity: "4", unit: "" },
      { name: "black peppercorns", quantity: "4", unit: "" },
      { name: "star anise", quantity: "1", unit: "small" },
      { name: "whole milk", quantity: "1", unit: "cup", notes: "or non-dairy alternative" },
      { name: "sugar", quantity: "2", unit: "tablespoons", notes: "or to taste" }
    ],
    steps: [
      { order: 1, instruction: "In a medium saucepan, combine water, ginger, cinnamon stick, cardamom pods, cloves, peppercorns, and star anise." },
      { order: 2, instruction: "Bring to a boil, then reduce heat and simmer for 5 minutes to infuse the spices." },
      { order: 3, instruction: "Add tea leaves or tea bags and simmer for another 2 minutes." },
      { order: 4, instruction: "Add milk and sugar, and bring back to a simmer. Do not let it boil over." },
      { order: 5, instruction: "Simmer for 2-3 minutes, stirring occasionally, until the chai reaches your desired strength and color." },
      { order: 6, instruction: "Remove from heat and strain through a fine-mesh sieve into cups or a teapot." },
      { order: 7, instruction: "Taste and adjust sweetness if needed." },
      { order: 8, instruction: "Serve hot." }
    ],
    cookingVessel: "Saucepan",
    prepTime: 5,
    cookTime: 15,
    servings: 3,
    difficulty: "Easy",
    mealType: "Drink",
    cuisine: "Indian",
    categories: ["Hot Drinks", "Tea Drinks"],
    dietaryCategories: ["Vegetarian", "Gluten-Free"],
    tags: ["chai", "tea", "spiced", "warming", "aromatic"],
    imageUrl: "https://images.unsplash.com/photo-1571934811356-5cc061b6821f"
  },
  {
    title: "Fresh Mango Lassi",
    description: "A creamy, refreshing Indian yogurt drink blended with ripe mangoes and a hint of cardamom for a sweet, tangy beverage that's both satisfying and cooling.",
    ingredients: [
      { name: "ripe mangoes", quantity: "2", unit: "large", notes: "peeled and chopped" },
      { name: "plain yogurt", quantity: "2", unit: "cups" },
      { name: "milk", quantity: "1/2", unit: "cup", notes: "optional, for thinner consistency" },
      { name: "sugar", quantity: "2", unit: "tablespoons", notes: "or to taste, depending on mango sweetness" },
      { name: "ground cardamom", quantity: "1/4", unit: "teaspoon" },
      { name: "ice cubes", quantity: "1", unit: "cup", notes: "optional" },
      { name: "mint leaves", quantity: "for garnish", unit: "", notes: "optional" },
      { name: "saffron strands", quantity: "few", unit: "", notes: "for garnish, optional" }
    ],
    steps: [
      { order: 1, instruction: "Add chopped mangoes, yogurt, milk (if using), sugar, and cardamom to a blender." },
      { order: 2, instruction: "Add ice cubes if you prefer a colder, thicker lassi." },
      { order: 3, instruction: "Blend on high until smooth and creamy, about 1 minute." },
      { order: 4, instruction: "Taste and adjust sweetness if needed by adding more sugar and blending briefly." },
      { order: 5, instruction: "Pour into glasses." },
      { order: 6, instruction: "If desired, garnish with mint leaves and a few saffron strands." },
      { order: 7, instruction: "Serve immediately or refrigerate for up to 24 hours (stir before serving if refrigerated)." }
    ],
    cookingVessel: "Blender",
    prepTime: 10,
    cookTime: 0,
    servings: 4,
    difficulty: "Easy",
    mealType: "Drink",
    cuisine: "Indian",
    categories: ["Yogurt Drinks", "Fruit Drinks"],
    dietaryCategories: ["Vegetarian", "Gluten-Free"],
    tags: ["mango", "lassi", "yogurt", "refreshing", "creamy"],
    imageUrl: "https://images.unsplash.com/photo-1626200925429-ded0cb33f0e3"
  },
  {
    title: "Classic Moscow Mule",
    description: "A refreshing cocktail featuring vodka, spicy ginger beer, and lime juice, traditionally served in a copper mug for a drink that's both zesty and cooling with a distinctive ginger kick.",
    ingredients: [
      { name: "vodka", quantity: "2", unit: "ounces" },
      { name: "fresh lime juice", quantity: "1/2", unit: "ounce" },
      { name: "ginger beer", quantity: "4", unit: "ounces", notes: "not ginger ale" },
      { name: "lime wedge", quantity: "1", unit: "", notes: "for garnish" },
      { name: "fresh mint sprig", quantity: "1", unit: "", notes: "for garnish, optional" },
      { name: "ice cubes", quantity: "1", unit: "cup" }
    ],
    steps: [
      { order: 1, instruction: "Fill a copper mug or highball glass with ice cubes." },
      { order: 2, instruction: "Add vodka and fresh lime juice to the mug." },
      { order: 3, instruction: "Top with ginger beer and stir gently to combine." },
      { order: 4, instruction: "Garnish with a lime wedge and mint sprig if using." },
      { order: 5, instruction: "Serve immediately with a straw." }
    ],
    cookingVessel: "Copper Mug",
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    difficulty: "Easy",
    mealType: "Drink",
    cuisine: "American",
    categories: ["Cocktails", "Vodka Drinks"],
    dietaryCategories: ["Gluten-Free", "Dairy-Free", "Vegan"],
    tags: ["moscow mule", "vodka", "ginger beer", "lime", "refreshing"],
    imageUrl: "https://images.unsplash.com/photo-1527661591475-527312dd65f5"
  },
  {
    title: "Homemade Lemonade",
    description: "A classic, refreshing beverage made with fresh lemon juice, sugar, and water for the perfect balance of sweet and tart that's infinitely better than store-bought versions.",
    ingredients: [
      { name: "lemons", quantity: "8-10", unit: "medium", notes: "to yield 1 1/2 cups juice" },
      { name: "granulated sugar", quantity: "1", unit: "cup" },
      { name: "water", quantity: "6", unit: "cups", notes: "divided" },
      { name: "ice cubes", quantity: "2", unit: "cups" },
      { name: "lemon slices", quantity: "for garnish", unit: "" },
      { name: "fresh mint sprigs", quantity: "for garnish", unit: "", notes: "optional" }
    ],
    steps: [
      { order: 1, instruction: "Roll lemons on the countertop, applying pressure with your palm to help release the juices." },
      { order: 2, instruction: "Cut lemons in half and juice them to yield about 1 1/2 cups of fresh lemon juice. Remove any seeds." },
      { order: 3, instruction: "In a small saucepan, combine sugar and 1 cup of water to make simple syrup. Heat over medium heat, stirring until sugar is completely dissolved. Remove from heat and let cool." },
      { order: 4, instruction: "In a large pitcher, combine the fresh lemon juice, cooled simple syrup, and remaining 5 cups of water." },
      { order: 5, instruction: "Stir well and taste. Adjust sweetness by adding more simple syrup or dilute with more water if too strong." },
      { order: 6, instruction: "Refrigerate until chilled, at least 1 hour." },
      { order: 7, instruction: "To serve, fill glasses with ice cubes and pour lemonade over ice." },
      { order: 8, instruction: "Garnish with lemon slices and mint sprigs if desired." }
    ],
    cookingVessel: "Saucepan",
    prepTime: 15,
    cookTime: 5,
    servings: 8,
    difficulty: "Easy",
    mealType: "Drink",
    cuisine: "American",
    categories: ["Non-Alcoholic Drinks", "Lemonades"],
    dietaryCategories: ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free"],
    tags: ["lemonade", "lemon", "refreshing", "summer", "classic"],
    imageUrl: "https://images.unsplash.com/photo-1621263764928-df1444c5e859"
  },
  {
    title: "Blueberry Smoothie Bowl",
    description: "A thick, creamy smoothie base topped with fresh fruits, nuts, and seeds for a nutritious, Instagram-worthy breakfast or snack that's both satisfying and beautiful.",
    ingredients: [
      { name: "frozen blueberries", quantity: "2", unit: "cups" },
      { name: "frozen banana", quantity: "1", unit: "medium", notes: "sliced" },
      { name: "Greek yogurt", quantity: "1/2", unit: "cup", notes: "plain or vanilla" },
      { name: "almond milk", quantity: "1/4", unit: "cup", notes: "or any milk of choice" },
      { name: "honey", quantity: "1", unit: "tablespoon", notes: "or maple syrup, optional" },
      { name: "fresh blueberries", quantity: "1/4", unit: "cup", notes: "for topping" },
      { name: "sliced banana", quantity: "1/2", unit: "medium", notes: "for topping" },
      { name: "granola", quantity: "1/4", unit: "cup", notes: "for topping" },
      { name: "chia seeds", quantity: "1", unit: "tablespoon", notes: "for topping" },
      { name: "sliced almonds", quantity: "1", unit: "tablespoon", notes: "for topping" },
      { name: "coconut flakes", quantity: "1", unit: "tablespoon", notes: "for topping" },
      { name: "hemp seeds", quantity: "1", unit: "teaspoon", notes: "for topping, optional" }
    ],
    steps: [
      { order: 1, instruction: "In a blender, combine frozen blueberries, frozen banana slices, Greek yogurt, almond milk, and honey or maple syrup if using." },
      { order: 2, instruction: "Blend on low speed initially, then increase to high, stopping to scrape down the sides as needed." },
      { order: 3, instruction: "Blend until smooth and creamy, but still thick enough to eat with a spoon. Add more milk if needed, but keep it thick." },
      { order: 4, instruction: "Pour the smoothie base into a bowl." },
      { order: 5, instruction: "Arrange toppings in sections or rows on top of the smoothie: fresh blueberries, sliced banana, granola, chia seeds, sliced almonds, coconut flakes, and hemp seeds if using." },
      { order: 6, instruction: "Serve immediately with a spoon." }
    ],
    cookingVessel: "Blender",
    prepTime: 10,
    cookTime: 0,
    servings: 1,
    difficulty: "Easy",
    mealType: "Drink",
    cuisine: "American",
    categories: ["Smoothie Bowls", "Breakfast Drinks"],
    dietaryCategories: ["Vegetarian", "Gluten-Free (with GF granola)"],
    tags: ["smoothie bowl", "blueberry", "breakfast", "nutritious", "Instagram-worthy"],
    imageUrl: "https://images.unsplash.com/photo-1490323948794-cc6dde6e8f5b"
  },
  {
    title: "Sparkling Elderflower Lemonade",
    description: "An elegant, effervescent beverage combining elderflower cordial with fresh lemon juice and sparkling water for a sophisticated, floral drink that's perfect for special occasions.",
    ingredients: [
      { name: "elderflower cordial or syrup", quantity: "1/4", unit: "cup" },
      { name: "fresh lemon juice", quantity: "1/4", unit: "cup" },
      { name: "sparkling water", quantity: "2", unit: "cups", notes: "chilled" },
      { name: "lemon slices", quantity: "4", unit: "", notes: "for garnish" },
      { name: "fresh mint leaves", quantity: "8", unit: "", notes: "for garnish" },
      { name: "ice cubes", quantity: "1", unit: "cup" },
      { name: "edible flowers", quantity: "for garnish", unit: "", notes: "optional" }
    ],
    steps: [
      { order: 1, instruction: "In a pitcher, combine elderflower cordial and fresh lemon juice. Stir well." },
      { order: 2, instruction: "Slowly add chilled sparkling water and stir gently to combine without losing too much carbonation." },
      { order: 3, instruction: "Fill glasses with ice cubes." },
      { order: 4, instruction: "Pour the elderflower lemonade over the ice." },
      { order: 5, instruction: "Garnish each glass with lemon slices, fresh mint leaves, and edible flowers if using." },
      { order: 6, instruction: "Serve immediately while still effervescent." }
    ],
    cookingVessel: "Pitcher",
    prepTime: 10,
    cookTime: 0,
    servings: 4,
    difficulty: "Easy",
    mealType: "Drink",
    cuisine: "European",
    categories: ["Non-Alcoholic Drinks", "Sparkling Drinks"],
    dietaryCategories: ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free"],
    tags: ["elderflower", "lemonade", "sparkling", "elegant", "refreshing"],
    imageUrl: "https://images.unsplash.com/photo-1556679343-c1c4b8e4fdce"
  },
  {
    title: "Turmeric Golden Milk",
    description: "A warming, anti-inflammatory beverage featuring turmeric, ginger, and warming spices simmered with milk for a soothing, health-promoting drink that's perfect before bedtime.",
    ingredients: [
      { name: "milk", quantity: "2", unit: "cups", notes: "dairy or plant-based" },
      { name: "ground turmeric", quantity: "1", unit: "teaspoon" },
      { name: "ground cinnamon", quantity: "1/2", unit: "teaspoon", notes: "plus more for garnish" },
      { name: "ground ginger", quantity: "1/4", unit: "teaspoon", notes: "or 1/2 teaspoon fresh grated ginger" },
      { name: "black pepper", quantity: "1", unit: "pinch", notes: "to enhance turmeric absorption" },
      { name: "honey", quantity: "1", unit: "tablespoon", notes: "or maple syrup, to taste" },
      { name: "vanilla extract", quantity: "1/4", unit: "teaspoon", notes: "optional" },
      { name: "coconut oil", quantity: "1", unit: "teaspoon", notes: "optional" }
    ],
    steps: [
      { order: 1, instruction: "In a small saucepan, combine milk, turmeric, cinnamon, ginger, and black pepper." },
      { order: 2, instruction: "Heat over medium-low heat, whisking frequently to prevent the spices from clumping." },
      { order: 3, instruction: "Bring to a gentle simmer (do not boil), then reduce heat to low and continue to simmer for 5-10 minutes to allow the flavors to meld." },
      { order: 4, instruction: "Remove from heat and stir in honey, vanilla extract (if using), and coconut oil (if using) until dissolved." },
      { order: 5, instruction: "Taste and adjust sweetness if needed." },
      { order: 6, instruction: "Pour into mugs through a fine-mesh strainer if desired for a smoother texture." },
      { order: 7, instruction: "Sprinkle with additional cinnamon for garnish." },
      { order: 8, instruction: "Serve hot." }
    ],
    cookingVessel: "Saucepan",
    prepTime: 5,
    cookTime: 10,
    servings: 2,
    difficulty: "Easy",
    mealType: "Drink",
    cuisine: "Indian",
    categories: ["Hot Drinks", "Wellness Drinks"],
    dietaryCategories: ["Vegetarian", "Gluten-Free"],
    tags: ["turmeric", "golden milk", "anti-inflammatory", "soothing", "bedtime"],
    imageUrl: "https://images.unsplash.com/photo-1578520231266-c6055fdb3ae4"
  },
  {
    title: "Classic Gin and Tonic",
    description: "A timeless, refreshing cocktail featuring gin and tonic water garnished with lime for a simple yet sophisticated drink with the perfect balance of botanical and bitter flavors.",
    ingredients: [
      { name: "gin", quantity: "2", unit: "ounces" },
      { name: "tonic water", quantity: "4", unit: "ounces", notes: "chilled" },
      { name: "lime wedge", quantity: "1", unit: "", notes: "plus more for garnish" },
      { name: "ice cubes", quantity: "1", unit: "cup" },
      { name: "cucumber slice", quantity: "for garnish", unit: "", notes: "optional" },
      { name: "juniper berries", quantity: "for garnish", unit: "", notes: "optional" }
    ],
    steps: [
      { order: 1, instruction: "Fill a highball glass or balloon glass with ice cubes." },
      { order: 2, instruction: "Pour gin over the ice." },
      { order: 3, instruction: "Squeeze a lime wedge into the glass and drop it in." },
      { order: 4, instruction: "Slowly pour in the tonic water, allowing the bubbles to rise and mix with the gin." },
      { order: 5, instruction: "Gently stir once or twice to combine." },
      { order: 6, instruction: "Garnish with an additional lime wedge and cucumber slice or juniper berries if desired." },
      { order: 7, instruction: "Serve immediately." }
    ],
    cookingVessel: "Highball Glass",
    prepTime: 5,
    cookTime: 0,
    servings: 1,
    difficulty: "Easy",
    mealType: "Drink",
    cuisine: "British",
    categories: ["Cocktails", "Gin Drinks"],
    dietaryCategories: ["Gluten-Free", "Dairy-Free", "Vegan"],
    tags: ["gin and tonic", "gin", "tonic", "classic", "refreshing"],
    imageUrl: "https://images.unsplash.com/photo-1551538827-9c037cb4f32a"
  }
];

export default drinkRecipes;
