// Lunch Recipes for WhatAboutDinner App
// 20 detailed lunch recipes with all required fields

const lunchRecipes = [
  {
    title: "Chicken Caesar Wrap",
    description: "A portable and delicious lunch option featuring grilled chicken, crisp romaine lettuce, and Caesar dressing wrapped in a tortilla, perfect for busy days.",
    ingredients: [
      { name: "chicken breast", quantity: "1", unit: "medium", notes: "grilled and sliced" },
      { name: "romaine lettuce", quantity: "2", unit: "cups", notes: "chopped" },
      { name: "parmesan cheese", quantity: "2", unit: "tablespoons", notes: "grated" },
      { name: "Caesar dressing", quantity: "2", unit: "tablespoons" },
      { name: "flour tortilla", quantity: "1", unit: "large", notes: "10-inch" },
      { name: "croutons", quantity: "1/4", unit: "cup", notes: "crushed" },
      { name: "black pepper", quantity: "1/8", unit: "teaspoon", notes: "freshly ground" }
    ],
    steps: [
      { order: 1, instruction: "In a bowl, toss the chopped romaine with Caesar dressing until well coated." },
      { order: 2, instruction: "Warm the tortilla slightly to make it more pliable." },
      { order: 3, instruction: "Lay the tortilla flat and place the dressed lettuce in the center." },
      { order: 4, instruction: "Top with sliced grilled chicken, crushed croutons, and grated parmesan." },
      { order: 5, instruction: "Season with black pepper." },
      { order: 6, instruction: "Fold in the sides of the tortilla, then roll tightly from the bottom up." },
      { order: 7, instruction: "Cut in half diagonally and serve immediately, or wrap in foil for a portable lunch." }
    ],
    cookingVessel: "Grill (for chicken)",
    prepTime: 10,
    cookTime: 0,
    servings: 1,
    difficulty: "Easy",
    mealType: "Lunch",
    cuisine: "American",
    categories: ["Wraps", "Quick & Easy"],
    dietaryCategories: [],
    tags: ["chicken", "wrap", "caesar", "lunch"],
    imageUrl: "https://images.unsplash.com/photo-1550507992-eb63ffee0847"
  },
  {
    title: "Mediterranean Quinoa Bowl",
    description: "A nutritious and colorful lunch bowl featuring protein-rich quinoa, roasted vegetables, chickpeas, and feta cheese with a lemon herb dressing.",
    ingredients: [
      { name: "quinoa", quantity: "1/2", unit: "cup", notes: "rinsed" },
      { name: "water", quantity: "1", unit: "cup" },
      { name: "bell peppers", quantity: "1", unit: "medium", notes: "assorted colors, diced" },
      { name: "zucchini", quantity: "1", unit: "small", notes: "diced" },
      { name: "red onion", quantity: "1/4", unit: "medium", notes: "diced" },
      { name: "olive oil", quantity: "2", unit: "tablespoons", notes: "divided" },
      { name: "salt", quantity: "1/2", unit: "teaspoon", notes: "divided" },
      { name: "black pepper", quantity: "1/4", unit: "teaspoon", notes: "divided" },
      { name: "chickpeas", quantity: "1/2", unit: "cup", notes: "canned, drained and rinsed" },
      { name: "lemon juice", quantity: "1", unit: "tablespoon" },
      { name: "feta cheese", quantity: "2", unit: "tablespoons", notes: "crumbled" },
      { name: "fresh parsley", quantity: "1", unit: "tablespoon", notes: "chopped" },
      { name: "fresh mint", quantity: "1", unit: "tablespoon", notes: "chopped" },
      { name: "kalamata olives", quantity: "6", unit: "", notes: "pitted and halved" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 425°F (220°C)." },
      { order: 2, instruction: "In a saucepan, combine quinoa and water. Bring to a boil, then reduce heat, cover, and simmer for 15 minutes until water is absorbed." },
      { order: 3, instruction: "On a baking sheet, toss bell peppers, zucchini, and red onion with 1 tablespoon olive oil, 1/4 teaspoon salt, and 1/8 teaspoon black pepper." },
      { order: 4, instruction: "Roast vegetables in the preheated oven for 15-20 minutes, stirring halfway through." },
      { order: 5, instruction: "Fluff the cooked quinoa with a fork and season with remaining salt and pepper." },
      { order: 6, instruction: "In a bowl, combine quinoa, roasted vegetables, and chickpeas." },
      { order: 7, instruction: "Drizzle with remaining olive oil and lemon juice, then toss to combine." },
      { order: 8, instruction: "Top with crumbled feta cheese, chopped herbs, and kalamata olives before serving." }
    ],
    cookingVessel: "Baking Sheet",
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    difficulty: "Medium",
    mealType: "Lunch",
    cuisine: "Mediterranean",
    categories: ["Bowls", "Healthy", "Meal Prep"],
    dietaryCategories: ["Vegetarian", "Gluten-Free"],
    tags: ["quinoa", "vegetable", "bowl", "healthy", "meal prep"],
    imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd"
  },
  {
    title: "Classic BLT Sandwich",
    description: "A timeless sandwich featuring crispy bacon, fresh lettuce, juicy tomatoes, and mayonnaise on toasted bread, simple yet incredibly satisfying.",
    ingredients: [
      { name: "bacon", quantity: "4", unit: "slices" },
      { name: "bread", quantity: "2", unit: "slices", notes: "white, wheat, or sourdough" },
      { name: "lettuce", quantity: "2", unit: "leaves", notes: "romaine or iceberg" },
      { name: "tomato", quantity: "1", unit: "medium", notes: "sliced" },
      { name: "mayonnaise", quantity: "1", unit: "tablespoon" },
      { name: "salt", quantity: "1/8", unit: "teaspoon" },
      { name: "black pepper", quantity: "1/8", unit: "teaspoon" }
    ],
    steps: [
      { order: 1, instruction: "Cook bacon in a skillet over medium heat until crispy, about 8-10 minutes, turning occasionally." },
      { order: 2, instruction: "Remove bacon and place on paper towels to drain excess fat." },
      { order: 3, instruction: "Toast the bread slices to desired doneness." },
      { order: 4, instruction: "Spread mayonnaise on one side of each toast slice." },
      { order: 5, instruction: "Layer lettuce leaves on one toast slice." },
      { order: 6, instruction: "Add tomato slices on top of the lettuce and season with salt and pepper." },
      { order: 7, instruction: "Place bacon strips on top of the tomatoes." },
      { order: 8, instruction: "Top with the second slice of toast, mayonnaise side down." },
      { order: 9, instruction: "Cut the sandwich diagonally and serve immediately." }
    ],
    cookingVessel: "Skillet",
    prepTime: 5,
    cookTime: 10,
    servings: 1,
    difficulty: "Easy",
    mealType: "Lunch",
    cuisine: "American",
    categories: ["Sandwiches", "Quick & Easy"],
    dietaryCategories: [],
    tags: ["bacon", "sandwich", "BLT", "classic"],
    imageUrl: "https://images.unsplash.com/photo-1619096252214-ef06c45683e3"
  },
  {
    title: "Tuna Niçoise Salad",
    description: "A classic French salad featuring seared tuna, boiled eggs, green beans, potatoes, olives, and a zesty Dijon vinaigrette for an elegant and satisfying lunch.",
    ingredients: [
      { name: "tuna steak", quantity: "6", unit: "ounces", notes: "sushi-grade" },
      { name: "olive oil", quantity: "3", unit: "tablespoons", notes: "divided" },
      { name: "salt", quantity: "1", unit: "teaspoon", notes: "divided" },
      { name: "black pepper", quantity: "1/2", unit: "teaspoon", notes: "divided" },
      { name: "baby potatoes", quantity: "6", unit: "small", notes: "halved" },
      { name: "green beans", quantity: "1", unit: "cup", notes: "trimmed" },
      { name: "eggs", quantity: "2", unit: "large" },
      { name: "mixed salad greens", quantity: "3", unit: "cups" },
      { name: "cherry tomatoes", quantity: "1/2", unit: "cup", notes: "halved" },
      { name: "kalamata olives", quantity: "1/4", unit: "cup", notes: "pitted" },
      { name: "red onion", quantity: "1/4", unit: "small", notes: "thinly sliced" },
      { name: "capers", quantity: "1", unit: "tablespoon", notes: "drained" },
      { name: "Dijon mustard", quantity: "1", unit: "teaspoon" },
      { name: "lemon juice", quantity: "2", unit: "tablespoons" },
      { name: "garlic", quantity: "1", unit: "clove", notes: "minced" },
      { name: "fresh herbs", quantity: "1", unit: "tablespoon", notes: "chopped (parsley, chives, or tarragon)" }
    ],
    steps: [
      { order: 1, instruction: "Place potatoes in a saucepan, cover with cold water, add 1/4 teaspoon salt, and bring to a boil. Cook until tender, about 10-12 minutes. Drain and let cool." },
      { order: 2, instruction: "In another saucepan, bring water to a boil and cook green beans for 3-4 minutes until crisp-tender. Transfer to an ice bath to stop cooking, then drain." },
      { order: 3, instruction: "In the same saucepan, gently lower eggs into boiling water and cook for 7 minutes for soft-boiled eggs. Transfer to an ice bath, then peel and halve." },
      { order: 4, instruction: "Season tuna steak with 1/4 teaspoon salt and 1/4 teaspoon pepper." },
      { order: 5, instruction: "Heat 1 tablespoon olive oil in a skillet over high heat. Sear tuna for 1-2 minutes per side for rare, or longer if preferred. Remove and let rest for 5 minutes, then slice." },
      { order: 6, instruction: "Make the dressing: Whisk together remaining olive oil, lemon juice, Dijon mustard, garlic, remaining salt and pepper, and herbs." },
      { order: 7, instruction: "Arrange mixed greens on a serving plate or bowl." },
      { order: 8, instruction: "Top with arranged sections of potatoes, green beans, tomatoes, olives, red onion, capers, egg halves, and sliced tuna." },
      { order: 9, instruction: "Drizzle with the prepared dressing and serve immediately." }
    ],
    cookingVessel: "Skillet and Saucepan",
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    difficulty: "Medium",
    mealType: "Lunch",
    cuisine: "French",
    categories: ["Salads", "Seafood"],
    dietaryCategories: ["Gluten-Free"],
    tags: ["tuna", "niçoise", "salad", "french"],
    imageUrl: "https://images.unsplash.com/photo-1594834749740-74b3f6764be4"
  },
  {
    title: "Spicy Black Bean Soup",
    description: "A hearty and flavorful soup made with black beans, vegetables, and warming spices, topped with fresh avocado and cilantro for a satisfying lunch.",
    ingredients: [
      { name: "black beans", quantity: "2", unit: "15-ounce cans", notes: "drained and rinsed" },
      { name: "olive oil", quantity: "2", unit: "tablespoons" },
      { name: "onion", quantity: "1", unit: "medium", notes: "diced" },
      { name: "red bell pepper", quantity: "1", unit: "medium", notes: "diced" },
      { name: "jalapeño", quantity: "1", unit: "small", notes: "seeded and minced" },
      { name: "garlic", quantity: "3", unit: "cloves", notes: "minced" },
      { name: "ground cumin", quantity: "2", unit: "teaspoons" },
      { name: "chili powder", quantity: "1", unit: "teaspoon" },
      { name: "dried oregano", quantity: "1/2", unit: "teaspoon" },
      { name: "vegetable broth", quantity: "3", unit: "cups" },
      { name: "diced tomatoes", quantity: "1", unit: "14.5-ounce can" },
      { name: "salt", quantity: "1", unit: "teaspoon" },
      { name: "black pepper", quantity: "1/2", unit: "teaspoon" },
      { name: "lime juice", quantity: "2", unit: "tablespoons" },
      { name: "avocado", quantity: "1", unit: "medium", notes: "diced, for serving" },
      { name: "fresh cilantro", quantity: "1/4", unit: "cup", notes: "chopped, for serving" },
      { name: "sour cream", quantity: "1/4", unit: "cup", notes: "for serving" },
      { name: "tortilla chips", quantity: "2", unit: "ounces", notes: "crushed, for serving" }
    ],
    steps: [
      { order: 1, instruction: "Heat olive oil in a large Dutch oven or pot over medium heat." },
      { order: 2, instruction: "Add onion, bell pepper, and jalapeño. Cook until softened, about 5 minutes." },
      { order: 3, instruction: "Add garlic, cumin, chili powder, and oregano. Cook for 1 minute until fragrant." },
      { order: 4, instruction: "Add black beans, vegetable broth, diced tomatoes, salt, and pepper. Bring to a boil." },
      { order: 5, instruction: "Reduce heat to low, cover, and simmer for 15 minutes to allow flavors to meld." },
      { order: 6, instruction: "Using an immersion blender, partially blend the soup, leaving some beans whole for texture. Alternatively, transfer about half the soup to a blender, blend until smooth, then return to the pot." },
      { order: 7, instruction: "Stir in lime juice and adjust seasoning if needed." },
      { order: 8, instruction: "Ladle soup into bowls and top with diced avocado, chopped cilantro, a dollop of sour cream, and crushed tortilla chips." }
    ],
    cookingVessel: "Dutch Oven",
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    difficulty: "Easy",
    mealType: "Lunch",
    cuisine: "Mexican",
    categories: ["Soups", "One-Pot Meals"],
    dietaryCategories: ["Vegetarian", "Gluten-Free"],
    tags: ["black bean", "soup", "spicy", "mexican"],
    imageUrl: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38"
  },
  {
    title: "Caprese Panini",
    description: "A warm Italian-inspired sandwich featuring fresh mozzarella, ripe tomatoes, basil, and balsamic glaze pressed between crusty bread for a simple yet elegant lunch.",
    ingredients: [
      { name: "ciabatta bread", quantity: "1", unit: "small loaf", notes: "or 2 ciabatta rolls" },
      { name: "fresh mozzarella", quantity: "4", unit: "ounces", notes: "sliced" },
      { name: "tomatoes", quantity: "1", unit: "large", notes: "sliced" },
      { name: "fresh basil leaves", quantity: "8", unit: "large" },
      { name: "balsamic glaze", quantity: "1", unit: "tablespoon" },
      { name: "olive oil", quantity: "1", unit: "tablespoon" },
      { name: "salt", quantity: "1/4", unit: "teaspoon" },
      { name: "black pepper", quantity: "1/8", unit: "teaspoon" },
      { name: "garlic", quantity: "1", unit: "clove", notes: "halved" }
    ],
    steps: [
      { order: 1, instruction: "Slice the ciabatta bread horizontally and open it like a book." },
      { order: 2, instruction: "Rub the cut sides of the bread with the halved garlic clove." },
      { order: 3, instruction: "Brush the outside of the bread with olive oil." },
      { order: 4, instruction: "Layer the mozzarella slices on the bottom half of the bread." },
      { order: 5, instruction: "Top with tomato slices and season with salt and pepper." },
      { order: 6, instruction: "Arrange basil leaves over the tomatoes." },
      { order: 7, instruction: "Drizzle with balsamic glaze." },
      { order: 8, instruction: "Close the sandwich with the top half of the bread." },
      { order: 9, instruction: "Heat a panini press or grill pan over medium heat." },
      { order: 10, instruction: "Place the sandwich in the press and cook until the bread is golden and crispy and the cheese is melted, about 3-5 minutes." },
      { order: 11, instruction: "If using a grill pan, place a heavy skillet on top of the sandwich to press it down, and flip halfway through cooking." },
      { order: 12, instruction: "Remove from heat, cut in half, and serve immediately." }
    ],
    cookingVessel: "Panini Press",
    prepTime: 10,
    cookTime: 5,
    servings: 2,
    difficulty: "Easy",
    mealType: "Lunch",
    cuisine: "Italian",
    categories: ["Sandwiches", "Quick & Easy"],
    dietaryCategories: ["Vegetarian"],
    tags: ["panini", "caprese", "mozzarella", "italian"],
    imageUrl: "https://images.unsplash.com/photo-1528736235302-52922df5c122"
  },
  {
    title: "Asian Chicken Lettuce Wraps",
    description: "Flavorful ground chicken cooked with Asian seasonings and vegetables, served in crisp lettuce cups for a light yet satisfying lunch option.",
    ingredients: [
      { name: "ground chicken", quantity: "1", unit: "pound" },
      { name: "vegetable oil", quantity: "1", unit: "tablespoon" },
      { name: "garlic", quantity: "3", unit: "cloves", notes: "minced" },
      { name: "ginger", quantity: "1", unit: "tablespoon", notes: "minced" },
      { name: "onion", quantity: "1", unit: "small", notes: "diced" },
      { name: "water chestnuts", quantity: "1", unit: "8-ounce can", notes: "drained and diced" },
      { name: "carrots", quantity: "1", unit: "medium", notes: "grated" },
      { name: "shiitake mushrooms", quantity: "4", unit: "ounces", notes: "diced" },
      { name: "green onions", quantity: "3", unit: "", notes: "sliced" },
      { name: "hoisin sauce", quantity: "3", unit: "tablespoons" },
      { name: "soy sauce", quantity: "2", unit: "tablespoons", notes: "low-sodium" },
      { name: "rice vinegar", quantity: "1", unit: "tablespoon" },
      { name: "sesame oil", quantity: "1", unit: "teaspoon" },
      { name: "sriracha sauce", quantity: "1", unit: "teaspoon", notes: "adjust to taste" },
      { name: "butter lettuce", quantity: "1", unit: "head", notes: "leaves separated and washed" },
      { name: "sesame seeds", quantity: "1", unit: "tablespoon", notes: "for garnish" },
      { name: "fresh cilantro", quantity: "2", unit: "tablespoons", notes: "chopped, for garnish" }
    ],
    steps: [
      { order: 1, instruction: "Heat vegetable oil in a large skillet or wok over medium-high heat." },
      { order: 2, instruction: "Add ground chicken and cook, breaking it up with a spoon, until no longer pink, about 5-6 minutes." },
      { order: 3, instruction: "Add garlic, ginger, and onion. Cook for 2 minutes until fragrant and onion begins to soften." },
      { order: 4, instruction: "Add water chestnuts, carrots, and mushrooms. Cook for 3-4 minutes until vegetables are tender." },
      { order: 5, instruction: "Stir in hoisin sauce, soy sauce, rice vinegar, sesame oil, and sriracha. Cook for 1-2 minutes until well combined and heated through." },
      { order: 6, instruction: "Remove from heat and stir in most of the green onions, reserving some for garnish." },
      { order: 7, instruction: "Arrange lettuce leaves on a serving platter." },
      { order: 8, instruction: "Spoon the chicken mixture into the lettuce cups." },
      { order: 9, instruction: "Garnish with remaining green onions, sesame seeds, and cilantro." },
      { order: 10, instruction: "Serve immediately, allowing everyone to assemble their own wraps." }
    ],
    cookingVessel: "Wok",
    prepTime: 15,
    cookTime: 15,
    servings: 4,
    difficulty: "Medium",
    mealType: "Lunch",
    cuisine: "Asian",
    categories: ["Wraps", "Protein-Rich"],
    dietaryCategories: ["Dairy-Free"],
    tags: ["lettuce wraps", "chicken", "asian", "light lunch"],
    imageUrl: "https://images.unsplash.com/photo-1506280754576-f6fa8a873550"
  },
  {
    title: "Roasted Vegetable and Hummus Wrap",
    description: "A hearty vegetarian wrap filled with roasted vegetables, creamy hummus, and fresh greens, perfect for a nutritious and satisfying plant-based lunch.",
    ingredients: [
      { name: "zucchini", quantity: "1", unit: "medium", notes: "sliced into half-moons" },
      { name: "bell peppers", quantity: "2", unit: "medium", notes: "assorted colors, sliced" },
      { name: "red onion", quantity: "1/2", unit: "medium", notes: "sliced" },
      { name: "eggplant", quantity: "1/2", unit: "small", notes: "sliced" },
      { name: "olive oil", quantity: "2", unit: "tablespoons" },
      { name: "salt", quantity: "1/2", unit: "teaspoon" },
      { name: "black pepper", quantity: "1/4", unit: "teaspoon" },
      { name: "garlic powder", quantity: "1/2", unit: "teaspoon" },
      { name: "dried oregano", quantity: "1/2", unit: "teaspoon" },
      { name: "hummus", quantity: "1/2", unit: "cup" },
      { name: "whole wheat tortillas", quantity: "4", unit: "large", notes: "10-inch" },
      { name: "baby spinach", quantity: "2", unit: "cups" },
      { name: "feta cheese", quantity: "1/4", unit: "cup", notes: "crumbled, optional" },
      { name: "kalamata olives", quantity: "1/4", unit: "cup", notes: "pitted and sliced, optional" },
      { name: "lemon juice", quantity: "1", unit: "tablespoon" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 425°F (220°C)." },
      { order: 2, instruction: "On a large baking sheet, toss zucchini, bell peppers, red onion, and eggplant with olive oil, salt, black pepper, garlic powder, and oregano." },
      { order: 3, instruction: "Spread vegetables in a single layer and roast for 20-25 minutes, stirring halfway through, until tender and lightly browned." },
      { order: 4, instruction: "Remove from oven and drizzle with lemon juice while still warm." },
      { order: 5, instruction: "Warm the tortillas slightly to make them more pliable." },
      { order: 6, instruction: "Spread 2 tablespoons of hummus on each tortilla, leaving a border around the edge." },
      { order: 7, instruction: "Divide the spinach among the tortillas." },
      { order: 8, instruction: "Top with roasted vegetables, and if using, sprinkle with feta cheese and olives." },
      { order: 9, instruction: "Fold in the sides of each tortilla, then roll up tightly from the bottom." },
      { order: 10, instruction: "Cut each wrap in half diagonally and serve immediately, or wrap in foil for a portable lunch." }
    ],
    cookingVessel: "Baking Sheet",
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    difficulty: "Easy",
    mealType: "Lunch",
    cuisine: "Mediterranean",
    categories: ["Wraps", "Vegetarian"],
    dietaryCategories: ["Vegetarian", "Vegan (without feta)"],
    tags: ["wrap", "roasted vegetables", "hummus", "plant-based"],
    imageUrl: "https://images.unsplash.com/photo-1540420773420-3366772f4999"
  },
  {
    title: "Lentil and Vegetable Soup",
    description: "A hearty and nutritious soup packed with lentils, vegetables, and aromatic herbs, perfect for a warming and satisfying lunch on cooler days.",
    ingredients: [
      { name: "olive oil", quantity: "2", unit: "tablespoons" },
      { name: "onion", quantity: "1", unit: "large", notes: "diced" },
      { name: "carrots", quantity: "2", unit: "medium", notes: "diced" },
      { name: "celery", quantity: "2", unit: "stalks", notes: "diced" },
      { name: "garlic", quantity: "3", unit: "cloves", notes: "minced" },
      { name: "dried green or brown lentils", quantity: "1", unit: "cup", notes: "rinsed and picked over" },
      { name: "diced tomatoes", quantity: "1", unit: "14.5-ounce can" },
      { name: "vegetable broth", quantity: "6", unit: "cups" },
      { name: "bay leaf", quantity: "1", unit: "" },
      { name: "dried thyme", quantity: "1", unit: "teaspoon" },
      { name: "ground cumin", quantity: "1", unit: "teaspoon" },
      { name: "smoked paprika", quantity: "1/2", unit: "teaspoon" },
      { name: "salt", quantity: "1", unit: "teaspoon" },
      { name: "black pepper", quantity: "1/2", unit: "teaspoon" },
      { name: "spinach", quantity: "3", unit: "cups", notes: "fresh, roughly chopped" },
      { name: "lemon juice", quantity: "2", unit: "tablespoons" },
      { name: "fresh parsley", quantity: "1/4", unit: "cup", notes: "chopped, for garnish" }
    ],
    steps: [
      { order: 1, instruction: "Heat olive oil in a large Dutch oven or pot over medium heat." },
      { order: 2, instruction: "Add onion, carrots, and celery. Cook until softened, about 5-7 minutes." },
      { order: 3, instruction: "Add garlic and cook for 1 minute until fragrant." },
      { order: 4, instruction: "Stir in lentils, diced tomatoes, vegetable broth, bay leaf, thyme, cumin, smoked paprika, salt, and pepper." },
      { order: 5, instruction: "Bring to a boil, then reduce heat to low. Cover and simmer for 25-30 minutes, until lentils are tender." },
      { order: 6, instruction: "Remove bay leaf." },
      { order: 7, instruction: "Stir in spinach and cook for 2-3 minutes until wilted." },
      { order: 8, instruction: "Stir in lemon juice and adjust seasoning if needed." },
      { order: 9, instruction: "Ladle soup into bowls and garnish with fresh parsley." },
      { order: 10, instruction: "Serve hot with crusty bread if desired." }
    ],
    cookingVessel: "Dutch Oven",
    prepTime: 15,
    cookTime: 35,
    servings: 6,
    difficulty: "Easy",
    mealType: "Lunch",
    cuisine: "Mediterranean",
    categories: ["Soups", "One-Pot Meals"],
    dietaryCategories: ["Vegetarian", "Vegan", "Gluten-Free"],
    tags: ["lentil", "soup", "healthy", "plant-based"],
    imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554"
  },
  {
    title: "Grilled Chicken and Avocado Club Sandwich",
    description: "A hearty triple-decker sandwich featuring grilled chicken breast, crispy bacon, fresh avocado, and all the classic club sandwich fixings.",
    ingredients: [
      { name: "chicken breast", quantity: "1", unit: "large", notes: "boneless, skinless" },
      { name: "olive oil", quantity: "1", unit: "tablespoon" },
      { name: "salt", quantity: "1/2", unit: "teaspoon", notes: "divided" },
      { name: "black pepper", quantity: "1/4", unit: "teaspoon", notes: "divided" },
      { name: "garlic powder", quantity: "1/4", unit: "teaspoon" },
      { name: "bread", quantity: "3", unit: "slices", notes: "white, wheat, or sourdough" },
      { name: "mayonnaise", quantity: "2", unit: "tablespoons" },
      { name: "Dijon mustard", quantity: "1", unit: "teaspoon" },
      { name: "bacon", quantity: "3", unit: "slices", notes: "cooked until crispy" },
      { name: "avocado", quantity: "1/2", unit: "medium", notes: "sliced" },
      { name: "tomato", quantity: "1", unit: "medium", notes: "sliced" },
      { name: "lettuce", quantity: "2", unit: "leaves", notes: "romaine or green leaf" },
      { name: "red onion", quantity: "2", unit: "thin slices", notes: "optional" }
    ],
    steps: [
      { order: 1, instruction: "Season chicken breast with olive oil, 1/4 teaspoon salt, 1/8 teaspoon pepper, and garlic powder." },
      { order: 2, instruction: "Heat a grill pan over medium-high heat. Grill chicken for 5-7 minutes per side, until internal temperature reaches 165°F (74°C)." },
      { order: 3, instruction: "Remove chicken from grill and let rest for 5 minutes, then slice thinly." },
      { order: 4, instruction: "Toast all three bread slices until golden brown." },
      { order: 5, instruction: "In a small bowl, mix mayonnaise and Dijon mustard." },
      { order: 6, instruction: "Spread the mayo-mustard mixture on one side of each bread slice." },
      { order: 7, instruction: "On the first bread slice, layer lettuce, tomato slices, and season with remaining salt and pepper." },
      { order: 8, instruction: "Top with sliced chicken and red onion (if using)." },
      { order: 9, instruction: "Place the second bread slice on top, mayo side up." },
      { order: 10, instruction: "On the second bread slice, layer more lettuce, bacon strips, and avocado slices." },
      { order: 11, instruction: "Top with the third bread slice, mayo side down." },
      { order: 12, instruction: "Secure the sandwich with toothpicks and cut into quarters diagonally." },
      { order: 13, instruction: "Serve immediately." }
    ],
    cookingVessel: "Grill Pan",
    prepTime: 15,
    cookTime: 15,
    servings: 1,
    difficulty: "Medium",
    mealType: "Lunch",
    cuisine: "American",
    categories: ["Sandwiches", "Protein-Rich"],
    dietaryCategories: [],
    tags: ["club sandwich", "chicken", "avocado", "bacon"],
    imageUrl: "https://images.unsplash.com/photo-1550507992-eb63ffee0847"
  },
  {
    title: "Falafel Pita with Tahini Sauce",
    description: "Crispy homemade falafel patties stuffed in warm pita bread with fresh vegetables and creamy tahini sauce for an authentic Middle Eastern lunch.",
    ingredients: [
      { name: "dried chickpeas", quantity: "1", unit: "cup", notes: "soaked overnight, not canned" },
      { name: "onion", quantity: "1/2", unit: "medium", notes: "roughly chopped" },
      { name: "garlic", quantity: "3", unit: "cloves" },
      { name: "fresh parsley", quantity: "1/2", unit: "cup", notes: "packed" },
      { name: "fresh cilantro", quantity: "1/2", unit: "cup", notes: "packed" },
      { name: "ground cumin", quantity: "1", unit: "teaspoon" },
      { name: "ground coriander", quantity: "1", unit: "teaspoon" },
      { name: "salt", quantity: "1", unit: "teaspoon" },
      { name: "baking powder", quantity: "1/2", unit: "teaspoon" },
      { name: "flour", quantity: "2", unit: "tablespoons", notes: "all-purpose or chickpea" },
      { name: "vegetable oil", quantity: "3", unit: "cups", notes: "for frying" },
      { name: "tahini", quantity: "1/4", unit: "cup" },
      { name: "lemon juice", quantity: "2", unit: "tablespoons" },
      { name: "water", quantity: "2", unit: "tablespoons", notes: "or more as needed" },
      { name: "garlic", quantity: "1", unit: "clove", notes: "minced, for sauce" },
      { name: "pita bread", quantity: "4", unit: "pockets" },
      { name: "tomatoes", quantity: "2", unit: "medium", notes: "diced" },
      { name: "cucumber", quantity: "1", unit: "medium", notes: "diced" },
      { name: "red onion", quantity: "1/4", unit: "medium", notes: "thinly sliced" },
      { name: "lettuce", quantity: "2", unit: "cups", notes: "shredded" }
    ],
    steps: [
      { order: 1, instruction: "Drain soaked chickpeas and pat dry with paper towels." },
      { order: 2, instruction: "In a food processor, combine chickpeas, onion, garlic, parsley, cilantro, cumin, coriander, and salt." },
      { order: 3, instruction: "Pulse until mixture is finely minced but not pureed, scraping down sides as needed." },
      { order: 4, instruction: "Transfer mixture to a bowl and add baking powder and flour. Mix well and refrigerate for 30 minutes." },
      { order: 5, instruction: "Form mixture into 16 small patties, about 1 1/2 inches in diameter." },
      { order: 6, instruction: "Heat oil in a deep pot or Dutch oven to 350°F (175°C)." },
      { order: 7, instruction: "Fry falafel in batches, turning occasionally, until deep golden brown and crispy, about 3-4 minutes." },
      { order: 8, instruction: "Remove with a slotted spoon and drain on paper towels." },
      { order: 9, instruction: "Make tahini sauce: Whisk together tahini, lemon juice, water, minced garlic, and a pinch of salt until smooth. Add more water if needed to reach desired consistency." },
      { order: 10, instruction: "Warm pita bread in the oven or on a dry skillet." },
      { order: 11, instruction: "Cut the top quarter off each pita to create a pocket." },
      { order: 12, instruction: "Fill each pita with lettuce, tomatoes, cucumber, and red onion." },
      { order: 13, instruction: "Add 4 falafel patties to each pita and drizzle generously with tahini sauce." },
      { order: 14, instruction: "Serve immediately." }
    ],
    cookingVessel: "Dutch Oven",
    prepTime: 45,
    cookTime: 15,
    servings: 4,
    difficulty: "Medium",
    mealType: "Lunch",
    cuisine: "Middle Eastern",
    categories: ["Sandwiches", "Vegetarian"],
    dietaryCategories: ["Vegetarian", "Vegan", "Dairy-Free"],
    tags: ["falafel", "pita", "chickpeas", "middle eastern"],
    imageUrl: "https://images.unsplash.com/photo-1593001872095-7d5b3868dd20"
  },
  {
    title: "Pesto Pasta Salad with Grilled Vegetables",
    description: "A vibrant pasta salad featuring al dente pasta, homemade basil pesto, and colorful grilled vegetables, perfect for a make-ahead lunch option.",
    ingredients: [
      { name: "pasta", quantity: "8", unit: "ounces", notes: "fusilli, farfalle, or penne" },
      { name: "zucchini", quantity: "1", unit: "medium", notes: "sliced lengthwise" },
      { name: "yellow squash", quantity: "1", unit: "medium", notes: "sliced lengthwise" },
      { name: "red bell pepper", quantity: "1", unit: "large", notes: "quartered and seeded" },
      { name: "red onion", quantity: "1/2", unit: "medium", notes: "cut into thick slices" },
      { name: "olive oil", quantity: "2", unit: "tablespoons", notes: "for grilling vegetables" },
      { name: "salt", quantity: "1", unit: "teaspoon", notes: "divided" },
      { name: "black pepper", quantity: "1/2", unit: "teaspoon", notes: "divided" },
      { name: "fresh basil leaves", quantity: "2", unit: "cups", notes: "packed" },
      { name: "pine nuts", quantity: "1/3", unit: "cup", notes: "plus 2 tablespoons for garnish" },
      { name: "garlic", quantity: "2", unit: "cloves" },
      { name: "parmesan cheese", quantity: "1/2", unit: "cup", notes: "grated" },
      { name: "lemon juice", quantity: "1", unit: "tablespoon" },
      { name: "olive oil", quantity: "1/3", unit: "cup", notes: "for pesto" },
      { name: "cherry tomatoes", quantity: "1", unit: "cup", notes: "halved" },
      { name: "fresh mozzarella", quantity: "4", unit: "ounces", notes: "pearl size or diced" },
      { name: "baby spinach", quantity: "2", unit: "cups", notes: "optional" }
    ],
    steps: [
      { order: 1, instruction: "Cook pasta according to package instructions until al dente. Drain, rinse with cold water, and set aside." },
      { order: 2, instruction: "Preheat grill or grill pan to medium-high heat." },
      { order: 3, instruction: "Brush zucchini, yellow squash, bell pepper, and red onion with olive oil and season with 1/2 teaspoon salt and 1/4 teaspoon black pepper." },
      { order: 4, instruction: "Grill vegetables until tender and lightly charred, about 3-4 minutes per side." },
      { order: 5, instruction: "Remove from grill and let cool slightly, then chop into bite-sized pieces." },
      { order: 6, instruction: "Make the pesto: In a food processor, combine basil, 1/3 cup pine nuts, garlic, parmesan cheese, lemon juice, remaining salt and pepper. Pulse until coarsely chopped." },
      { order: 7, instruction: "With the processor running, slowly add 1/3 cup olive oil until smooth." },
      { order: 8, instruction: "In a large bowl, combine cooked pasta, grilled vegetables, cherry tomatoes, and fresh mozzarella." },
      { order: 9, instruction: "Add pesto and toss gently to coat. If using spinach, fold it in now." },
      { order: 10, instruction: "Garnish with remaining pine nuts." },
      { order: 11, instruction: "Serve at room temperature or chilled." }
    ],
    cookingVessel: "Grill Pan",
    prepTime: 20,
    cookTime: 20,
    servings: 6,
    difficulty: "Medium",
    mealType: "Lunch",
    cuisine: "Italian",
    categories: ["Pasta", "Salads", "Make-Ahead"],
    dietaryCategories: ["Vegetarian"],
    tags: ["pasta salad", "pesto", "grilled vegetables", "italian"],
    imageUrl: "https://images.unsplash.com/photo-1473093295043-cdd812d0e601"
  },
  {
    title: "Chicken and Wild Rice Soup",
    description: "A comforting and hearty soup featuring tender chicken, nutty wild rice, and vegetables in a creamy broth, perfect for a satisfying lunch on chilly days.",
    ingredients: [
      { name: "chicken breasts", quantity: "1", unit: "pound", notes: "boneless, skinless" },
      { name: "olive oil", quantity: "2", unit: "tablespoons" },
      { name: "onion", quantity: "1", unit: "medium", notes: "diced" },
      { name: "carrots", quantity: "2", unit: "medium", notes: "diced" },
      { name: "celery", quantity: "2", unit: "stalks", notes: "diced" },
      { name: "garlic", quantity: "3", unit: "cloves", notes: "minced" },
      { name: "wild rice blend", quantity: "1", unit: "cup" },
      { name: "chicken broth", quantity: "6", unit: "cups" },
      { name: "dried thyme", quantity: "1", unit: "teaspoon" },
      { name: "dried rosemary", quantity: "1/2", unit: "teaspoon", notes: "crushed" },
      { name: "bay leaf", quantity: "1", unit: "" },
      { name: "salt", quantity: "1", unit: "teaspoon" },
      { name: "black pepper", quantity: "1/2", unit: "teaspoon" },
      { name: "butter", quantity: "4", unit: "tablespoons" },
      { name: "all-purpose flour", quantity: "1/4", unit: "cup" },
      { name: "milk", quantity: "2", unit: "cups" },
      { name: "heavy cream", quantity: "1/2", unit: "cup" },
      { name: "fresh parsley", quantity: "2", unit: "tablespoons", notes: "chopped, for garnish" }
    ],
    steps: [
      { order: 1, instruction: "In a large Dutch oven or pot, heat olive oil over medium heat." },
      { order: 2, instruction: "Add chicken breasts and cook for 5-6 minutes per side until golden and cooked through. Remove and set aside." },
      { order: 3, instruction: "In the same pot, add onion, carrots, and celery. Cook until softened, about 5 minutes." },
      { order: 4, instruction: "Add garlic and cook for 30 seconds until fragrant." },
      { order: 5, instruction: "Add wild rice, chicken broth, thyme, rosemary, bay leaf, salt, and pepper. Bring to a boil." },
      { order: 6, instruction: "Reduce heat to low, cover, and simmer for 45 minutes, or until rice is tender." },
      { order: 7, instruction: "Meanwhile, shred the cooked chicken." },
      { order: 8, instruction: "In a separate saucepan, melt butter over medium heat. Whisk in flour and cook for 1 minute." },
      { order: 9, instruction: "Gradually whisk in milk and cream. Cook, stirring constantly, until thickened, about 5 minutes." },
      { order: 10, instruction: "Remove bay leaf from the soup pot." },
      { order: 11, instruction: "Add the shredded chicken and the cream mixture to the soup pot. Stir to combine." },
      { order: 12, instruction: "Simmer for an additional 10 minutes, stirring occasionally." },
      { order: 13, instruction: "Adjust seasoning if needed." },
      { order: 14, instruction: "Ladle into bowls and garnish with fresh parsley before serving." }
    ],
    cookingVessel: "Dutch Oven",
    prepTime: 15,
    cookTime: 75,
    servings: 6,
    difficulty: "Medium",
    mealType: "Lunch",
    cuisine: "American",
    categories: ["Soups", "Comfort Food"],
    dietaryCategories: [],
    tags: ["chicken soup", "wild rice", "creamy", "comfort food"],
    imageUrl: "https://images.unsplash.com/photo-1547592166-23ac45744acd"
  },
  {
    title: "Greek Chickpea Salad",
    description: "A protein-packed Mediterranean salad featuring chickpeas, fresh vegetables, feta cheese, and olives tossed in a zesty lemon herb dressing.",
    ingredients: [
      { name: "chickpeas", quantity: "2", unit: "15-ounce cans", notes: "drained and rinsed" },
      { name: "cucumber", quantity: "1", unit: "medium", notes: "diced" },
      { name: "cherry tomatoes", quantity: "1", unit: "pint", notes: "halved" },
      { name: "red bell pepper", quantity: "1", unit: "medium", notes: "diced" },
      { name: "red onion", quantity: "1/2", unit: "small", notes: "thinly sliced" },
      { name: "kalamata olives", quantity: "1/2", unit: "cup", notes: "pitted and halved" },
      { name: "feta cheese", quantity: "4", unit: "ounces", notes: "crumbled" },
      { name: "fresh parsley", quantity: "1/4", unit: "cup", notes: "chopped" },
      { name: "fresh mint", quantity: "2", unit: "tablespoons", notes: "chopped" },
      { name: "olive oil", quantity: "1/4", unit: "cup", notes: "extra virgin" },
      { name: "lemon juice", quantity: "3", unit: "tablespoons", notes: "fresh" },
      { name: "garlic", quantity: "1", unit: "clove", notes: "minced" },
      { name: "dried oregano", quantity: "1", unit: "teaspoon" },
      { name: "Dijon mustard", quantity: "1", unit: "teaspoon" },
      { name: "salt", quantity: "1/2", unit: "teaspoon" },
      { name: "black pepper", quantity: "1/4", unit: "teaspoon" }
    ],
    steps: [
      { order: 1, instruction: "In a large bowl, combine chickpeas, cucumber, cherry tomatoes, bell pepper, red onion, olives, feta cheese, parsley, and mint." },
      { order: 2, instruction: "In a small bowl or jar, whisk together olive oil, lemon juice, garlic, oregano, Dijon mustard, salt, and pepper." },
      { order: 3, instruction: "Pour the dressing over the salad and toss gently to combine." },
      { order: 4, instruction: "Let the salad sit for at least 10 minutes before serving to allow flavors to meld." },
      { order: 5, instruction: "Serve chilled or at room temperature." },
      { order: 6, instruction: "This salad can be stored in the refrigerator for up to 3 days." }
    ],
    cookingVessel: "Mixing Bowl",
    prepTime: 20,
    cookTime: 0,
    servings: 6,
    difficulty: "Easy",
    mealType: "Lunch",
    cuisine: "Greek",
    categories: ["Salads", "No-Cook", "Make-Ahead"],
    dietaryCategories: ["Vegetarian", "Gluten-Free"],
    tags: ["chickpea", "greek", "salad", "mediterranean"],
    imageUrl: "https://images.unsplash.com/photo-1529059997568-3d847b1154f0"
  },
  {
    title: "Turkey and Cranberry Sandwich",
    description: "A delicious sandwich featuring roasted turkey, tangy cranberry sauce, and creamy brie cheese on artisan bread, perfect for using holiday leftovers or any time of year.",
    ingredients: [
      { name: "artisan bread", quantity: "4", unit: "slices", notes: "such as sourdough or multigrain" },
      { name: "roasted turkey", quantity: "8", unit: "ounces", notes: "thinly sliced" },
      { name: "cranberry sauce", quantity: "4", unit: "tablespoons" },
      { name: "brie cheese", quantity: "4", unit: "ounces", notes: "sliced" },
      { name: "arugula", quantity: "1", unit: "cup", notes: "loosely packed" },
      { name: "Dijon mustard", quantity: "2", unit: "teaspoons", notes: "optional" },
      { name: "mayonnaise", quantity: "2", unit: "tablespoons", notes: "optional" },
      { name: "butter", quantity: "2", unit: "tablespoons", notes: "softened" },
      { name: "salt", quantity: "1/8", unit: "teaspoon" },
      { name: "black pepper", quantity: "1/8", unit: "teaspoon" }
    ],
    steps: [
      { order: 1, instruction: "Spread butter on one side of each bread slice." },
      { order: 2, instruction: "On the non-buttered side of two bread slices, spread mayonnaise (if using)." },
      { order: 3, instruction: "On the non-buttered side of the other two bread slices, spread Dijon mustard (if using) and cranberry sauce." },
      { order: 4, instruction: "Layer the turkey slices on the mayonnaise-spread bread." },
      { order: 5, instruction: "Season turkey with salt and pepper." },
      { order: 6, instruction: "Add brie cheese slices on top of the turkey." },
      { order: 7, instruction: "Top with arugula." },
      { order: 8, instruction: "Close the sandwiches with the cranberry sauce-spread bread slices, buttered sides facing out." },
      { order: 9, instruction: "Heat a skillet or griddle over medium heat." },
      { order: 10, instruction: "Cook sandwiches for 3-4 minutes per side until golden brown and cheese is melted." },
      { order: 11, instruction: "Remove from heat, cut in half, and serve immediately." }
    ],
    cookingVessel: "Skillet",
    prepTime: 10,
    cookTime: 8,
    servings: 2,
    difficulty: "Easy",
    mealType: "Lunch",
    cuisine: "American",
    categories: ["Sandwiches", "Leftovers"],
    dietaryCategories: [],
    tags: ["turkey", "cranberry", "sandwich", "holiday"],
    imageUrl: "https://images.unsplash.com/photo-1509722747041-616f39b57569"
  },
  {
    title: "Quinoa Stuffed Bell Peppers",
    description: "Colorful bell peppers stuffed with a flavorful mixture of quinoa, black beans, corn, and spices, topped with melted cheese for a nutritious and satisfying lunch.",
    ingredients: [
      { name: "bell peppers", quantity: "4", unit: "large", notes: "any color, halved lengthwise and seeded" },
      { name: "quinoa", quantity: "1", unit: "cup", notes: "rinsed" },
      { name: "water", quantity: "2", unit: "cups" },
      { name: "olive oil", quantity: "1", unit: "tablespoon" },
      { name: "onion", quantity: "1", unit: "medium", notes: "diced" },
      { name: "garlic", quantity: "2", unit: "cloves", notes: "minced" },
      { name: "black beans", quantity: "1", unit: "15-ounce can", notes: "drained and rinsed" },
      { name: "corn kernels", quantity: "1", unit: "cup", notes: "fresh or frozen" },
      { name: "diced tomatoes", quantity: "1", unit: "14.5-ounce can", notes: "drained" },
      { name: "chili powder", quantity: "1", unit: "tablespoon" },
      { name: "ground cumin", quantity: "1", unit: "teaspoon" },
      { name: "smoked paprika", quantity: "1/2", unit: "teaspoon" },
      { name: "salt", quantity: "1", unit: "teaspoon" },
      { name: "black pepper", quantity: "1/2", unit: "teaspoon" },
      { name: "lime juice", quantity: "1", unit: "tablespoon" },
      { name: "fresh cilantro", quantity: "1/4", unit: "cup", notes: "chopped, plus more for garnish" },
      { name: "cheddar cheese", quantity: "1", unit: "cup", notes: "shredded" },
      { name: "avocado", quantity: "1", unit: "medium", notes: "diced, for serving" },
      { name: "sour cream", quantity: "1/4", unit: "cup", notes: "for serving" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 375°F (190°C)." },
      { order: 2, instruction: "In a saucepan, combine quinoa and water. Bring to a boil, then reduce heat, cover, and simmer for 15 minutes until water is absorbed. Fluff with a fork." },
      { order: 3, instruction: "Place bell pepper halves cut-side up in a 9x13 inch baking dish. Drizzle with a little olive oil and sprinkle with salt. Bake for 15 minutes to soften slightly." },
      { order: 4, instruction: "Meanwhile, heat olive oil in a large skillet over medium heat. Add onion and cook until softened, about 5 minutes." },
      { order: 5, instruction: "Add garlic and cook for 30 seconds until fragrant." },
      { order: 6, instruction: "Stir in black beans, corn, diced tomatoes, chili powder, cumin, smoked paprika, salt, and pepper. Cook for 5 minutes." },
      { order: 7, instruction: "Remove from heat and stir in cooked quinoa, lime juice, and cilantro." },
      { order: 8, instruction: "Fill each bell pepper half with the quinoa mixture." },
      { order: 9, instruction: "Sprinkle shredded cheese over the top of each stuffed pepper." },
      { order: 10, instruction: "Cover the baking dish with foil and bake for 25 minutes." },
      { order: 11, instruction: "Remove foil and bake for an additional 5-10 minutes until cheese is bubbly and peppers are tender." },
      { order: 12, instruction: "Serve hot, topped with diced avocado, a dollop of sour cream, and additional cilantro." }
    ],
    cookingVessel: "Baking Dish",
    prepTime: 20,
    cookTime: 55,
    servings: 4,
    difficulty: "Medium",
    mealType: "Lunch",
    cuisine: "Mexican",
    categories: ["Stuffed Vegetables", "Make-Ahead"],
    dietaryCategories: ["Vegetarian", "Gluten-Free"],
    tags: ["quinoa", "stuffed peppers", "mexican", "healthy"],
    imageUrl: "https://images.unsplash.com/photo-1564834744159-ff0ea41ba4b9"
  },
  {
    title: "Shrimp and Avocado Ceviche",
    description: "A refreshing Latin American dish featuring citrus-marinated shrimp, creamy avocado, and fresh vegetables, perfect for a light and flavorful lunch.",
    ingredients: [
      { name: "shrimp", quantity: "1", unit: "pound", notes: "medium, peeled and deveined" },
      { name: "lime juice", quantity: "1/2", unit: "cup", notes: "fresh, about 4-5 limes" },
      { name: "lemon juice", quantity: "1/4", unit: "cup", notes: "fresh, about 1-2 lemons" },
      { name: "red onion", quantity: "1/2", unit: "medium", notes: "finely diced" },
      { name: "cucumber", quantity: "1", unit: "medium", notes: "seeded and diced" },
      { name: "roma tomatoes", quantity: "2", unit: "medium", notes: "seeded and diced" },
      { name: "jalapeño", quantity: "1", unit: "small", notes: "seeded and minced" },
      { name: "avocado", quantity: "1", unit: "large", notes: "diced" },
      { name: "fresh cilantro", quantity: "1/3", unit: "cup", notes: "chopped" },
      { name: "garlic", quantity: "2", unit: "cloves", notes: "minced" },
      { name: "salt", quantity: "1", unit: "teaspoon" },
      { name: "black pepper", quantity: "1/4", unit: "teaspoon" },
      { name: "olive oil", quantity: "1", unit: "tablespoon", notes: "extra virgin" },
      { name: "hot sauce", quantity: "to taste", unit: "", notes: "optional" },
      { name: "tortilla chips", quantity: "for serving", unit: "" }
    ],
    steps: [
      { order: 1, instruction: "Bring a large pot of salted water to a boil. Add shrimp and cook just until pink and opaque, about 2-3 minutes." },
      { order: 2, instruction: "Immediately transfer shrimp to an ice bath to stop the cooking process." },
      { order: 3, instruction: "Once cooled, drain shrimp and chop into 1/2-inch pieces." },
      { order: 4, instruction: "In a large glass or ceramic bowl, combine chopped shrimp, lime juice, and lemon juice. Stir to coat shrimp completely." },
      { order: 5, instruction: "Cover and refrigerate for 30 minutes to 1 hour to allow the citrus to \"cook\" the shrimp further." },
      { order: 6, instruction: "Add red onion, cucumber, tomatoes, jalapeño, garlic, salt, and pepper to the shrimp mixture. Stir to combine." },
      { order: 7, instruction: "Refrigerate for another 30 minutes to allow flavors to meld." },
      { order: 8, instruction: "Just before serving, gently fold in diced avocado, chopped cilantro, and olive oil." },
      { order: 9, instruction: "Taste and adjust seasoning if needed. Add hot sauce if desired." },
      { order: 10, instruction: "Serve chilled with tortilla chips on the side." }
    ],
    cookingVessel: "Saucepan",
    prepTime: 20,
    cookTime: 3,
    servings: 4,
    difficulty: "Medium",
    mealType: "Lunch",
    cuisine: "Latin American",
    categories: ["Seafood", "No-Cook"],
    dietaryCategories: ["Gluten-Free", "Dairy-Free"],
    tags: ["ceviche", "shrimp", "avocado", "citrus", "light lunch"],
    imageUrl: "https://images.unsplash.com/photo-1604259597308-5321e8e4789c"
  },
  {
    title: "Mushroom and Barley Soup",
    description: "A hearty and earthy soup featuring a variety of mushrooms, nutty barley, and aromatic herbs, perfect for a warming and satisfying lunch.",
    ingredients: [
      { name: "dried porcini mushrooms", quantity: "1/2", unit: "ounce" },
      { name: "hot water", quantity: "1", unit: "cup" },
      { name: "olive oil", quantity: "2", unit: "tablespoons" },
      { name: "onion", quantity: "1", unit: "medium", notes: "diced" },
      { name: "carrots", quantity: "2", unit: "medium", notes: "diced" },
      { name: "celery", quantity: "2", unit: "stalks", notes: "diced" },
      { name: "garlic", quantity: "3", unit: "cloves", notes: "minced" },
      { name: "fresh mushrooms", quantity: "1", unit: "pound", notes: "mixed varieties (cremini, shiitake, button), sliced" },
      { name: "thyme", quantity: "2", unit: "teaspoons", notes: "fresh, chopped" },
      { name: "rosemary", quantity: "1", unit: "teaspoon", notes: "fresh, chopped" },
      { name: "pearl barley", quantity: "3/4", unit: "cup", notes: "rinsed" },
      { name: "vegetable broth", quantity: "6", unit: "cups" },
      { name: "bay leaf", quantity: "1", unit: "" },
      { name: "soy sauce", quantity: "1", unit: "tablespoon" },
      { name: "salt", quantity: "1", unit: "teaspoon", notes: "or to taste" },
      { name: "black pepper", quantity: "1/2", unit: "teaspoon" },
      { name: "fresh parsley", quantity: "1/4", unit: "cup", notes: "chopped, for garnish" },
      { name: "lemon juice", quantity: "1", unit: "tablespoon", notes: "fresh" }
    ],
    steps: [
      { order: 1, instruction: "Place dried porcini mushrooms in a bowl and cover with hot water. Let soak for 20 minutes." },
      { order: 2, instruction: "Remove rehydrated mushrooms, reserving the soaking liquid. Chop the mushrooms and strain the liquid through a fine-mesh sieve lined with a coffee filter or paper towel to remove any grit." },
      { order: 3, instruction: "Heat olive oil in a large Dutch oven or pot over medium heat." },
      { order: 4, instruction: "Add onion, carrots, and celery. Cook until softened, about 5-7 minutes." },
      { order: 5, instruction: "Add garlic and cook for 30 seconds until fragrant." },
      { order: 6, instruction: "Increase heat to medium-high and add fresh mushrooms. Cook until they release their moisture and begin to brown, about 8-10 minutes." },
      { order: 7, instruction: "Add thyme and rosemary, cook for 1 minute." },
      { order: 8, instruction: "Add barley, vegetable broth, reserved mushroom soaking liquid, chopped porcini mushrooms, bay leaf, soy sauce, salt, and pepper." },
      { order: 9, instruction: "Bring to a boil, then reduce heat to low. Cover and simmer for 45-50 minutes, until barley is tender." },
      { order: 10, instruction: "Remove bay leaf." },
      { order: 11, instruction: "Stir in lemon juice and adjust seasoning if needed." },
      { order: 12, instruction: "Ladle into bowls and garnish with fresh parsley before serving." }
    ],
    cookingVessel: "Dutch Oven",
    prepTime: 30,
    cookTime: 60,
    servings: 6,
    difficulty: "Medium",
    mealType: "Lunch",
    cuisine: "European",
    categories: ["Soups", "One-Pot Meals"],
    dietaryCategories: ["Vegetarian", "Vegan", "Dairy-Free"],
    tags: ["mushroom", "barley", "soup", "hearty"],
    imageUrl: "https://images.unsplash.com/photo-1603105037880-880cd4edfb0d"
  },
  {
    title: "Vietnamese Banh Mi Sandwich",
    description: "A flavorful Vietnamese sandwich featuring marinated pork, pickled vegetables, fresh herbs, and spicy mayo on a crusty baguette for an international lunch option.",
    ingredients: [
      { name: "pork tenderloin", quantity: "1", unit: "pound" },
      { name: "fish sauce", quantity: "2", unit: "tablespoons" },
      { name: "soy sauce", quantity: "1", unit: "tablespoon" },
      { name: "honey", quantity: "1", unit: "tablespoon" },
      { name: "garlic", quantity: "3", unit: "cloves", notes: "minced" },
      { name: "lemongrass", quantity: "1", unit: "stalk", notes: "minced (white part only)" },
      { name: "vegetable oil", quantity: "1", unit: "tablespoon" },
      { name: "carrots", quantity: "2", unit: "medium", notes: "julienned" },
      { name: "daikon radish", quantity: "1/2", unit: "medium", notes: "julienned" },
      { name: "rice vinegar", quantity: "1/2", unit: "cup" },
      { name: "sugar", quantity: "2", unit: "tablespoons" },
      { name: "salt", quantity: "1", unit: "teaspoon", notes: "divided" },
      { name: "mayonnaise", quantity: "1/4", unit: "cup" },
      { name: "sriracha sauce", quantity: "1", unit: "tablespoon", notes: "adjust to taste" },
      { name: "baguette", quantity: "1", unit: "24-inch", notes: "or 4 individual baguettes" },
      { name: "cucumber", quantity: "1", unit: "medium", notes: "thinly sliced lengthwise" },
      { name: "jalapeño", quantity: "1", unit: "medium", notes: "thinly sliced" },
      { name: "fresh cilantro", quantity: "1", unit: "cup", notes: "leaves and tender stems" },
      { name: "fresh mint", quantity: "1/2", unit: "cup", notes: "leaves" }
    ],
    steps: [
      { order: 1, instruction: "In a bowl, combine fish sauce, soy sauce, honey, garlic, and lemongrass to make the marinade." },
      { order: 2, instruction: "Place pork tenderloin in a resealable plastic bag and pour marinade over it. Seal bag and refrigerate for at least 2 hours, preferably overnight." },
      { order: 3, instruction: "Make the pickled vegetables: In a bowl, combine carrots, daikon, rice vinegar, sugar, and 1/2 teaspoon salt. Let sit for at least 30 minutes, stirring occasionally." },
      { order: 4, instruction: "Preheat oven to 400°F (200°C)." },
      { order: 5, instruction: "Remove pork from marinade and pat dry. Heat vegetable oil in an oven-safe skillet over high heat." },
      { order: 6, instruction: "Sear pork on all sides until browned, about 2-3 minutes per side." },
      { order: 7, instruction: "Transfer skillet to oven and roast until pork reaches an internal temperature of 145°F (63°C), about 15-20 minutes." },
      { order: 8, instruction: "Let pork rest for 10 minutes, then thinly slice." },
      { order: 9, instruction: "Make the spicy mayo: In a small bowl, mix mayonnaise, sriracha, and remaining 1/2 teaspoon salt." },
      { order: 10, instruction: "Cut baguette into 4 equal portions and split each piece horizontally, leaving one edge intact." },
      { order: 11, instruction: "Toast baguette pieces lightly if desired." },
      { order: 12, instruction: "Spread spicy mayo on both sides of each baguette piece." },
      { order: 13, instruction: "Layer sliced pork, drained pickled vegetables, cucumber slices, jalapeño slices, cilantro, and mint leaves on each sandwich." },
      { order: 14, instruction: "Serve immediately." }
    ],
    cookingVessel: "Oven-Safe Skillet",
    prepTime: 30,
    cookTime: 25,
    servings: 4,
    difficulty: "Medium",
    mealType: "Lunch",
    cuisine: "Vietnamese",
    categories: ["Sandwiches", "International"],
    dietaryCategories: ["Dairy-Free"],
    tags: ["banh mi", "vietnamese", "sandwich", "pork"],
    imageUrl: "https://images.unsplash.com/photo-1600454309261-3dc9b7597637"
  },
  {
    title: "Spinach and Feta Quiche",
    description: "A classic French-inspired quiche featuring a flaky crust filled with a creamy mixture of spinach, feta cheese, and eggs, perfect for a sophisticated lunch.",
    ingredients: [
      { name: "pie crust", quantity: "1", unit: "9-inch", notes: "store-bought or homemade" },
      { name: "olive oil", quantity: "1", unit: "tablespoon" },
      { name: "onion", quantity: "1", unit: "medium", notes: "diced" },
      { name: "garlic", quantity: "2", unit: "cloves", notes: "minced" },
      { name: "fresh spinach", quantity: "10", unit: "ounces", notes: "roughly chopped" },
      { name: "eggs", quantity: "4", unit: "large" },
      { name: "heavy cream", quantity: "1", unit: "cup" },
      { name: "milk", quantity: "1/2", unit: "cup" },
      { name: "feta cheese", quantity: "6", unit: "ounces", notes: "crumbled" },
      { name: "dried dill", quantity: "1", unit: "teaspoon" },
      { name: "nutmeg", quantity: "1/8", unit: "teaspoon", notes: "freshly grated" },
      { name: "salt", quantity: "1/2", unit: "teaspoon" },
      { name: "black pepper", quantity: "1/4", unit: "teaspoon" },
      { name: "cherry tomatoes", quantity: "1/2", unit: "cup", notes: "halved, for topping" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 375°F (190°C)." },
      { order: 2, instruction: "Place pie crust in a 9-inch pie dish or quiche pan. Prick the bottom with a fork several times." },
      { order: 3, instruction: "Line the crust with parchment paper and fill with pie weights or dried beans." },
      { order: 4, instruction: "Blind bake the crust for 15 minutes. Remove weights and parchment, and bake for an additional 5 minutes until lightly golden." },
      { order: 5, instruction: "Meanwhile, heat olive oil in a large skillet over medium heat." },
      { order: 6, instruction: "Add onion and cook until softened, about 5 minutes." },
      { order: 7, instruction: "Add garlic and cook for 30 seconds until fragrant." },
      { order: 8, instruction: "Add spinach in batches, stirring until wilted, about 2-3 minutes total." },
      { order: 9, instruction: "Remove from heat and let cool slightly." },
      { order: 10, instruction: "In a large bowl, whisk together eggs, heavy cream, milk, salt, pepper, dill, and nutmeg." },
      { order: 11, instruction: "Squeeze excess moisture from the spinach mixture and spread it evenly over the bottom of the par-baked crust." },
      { order: 12, instruction: "Sprinkle crumbled feta cheese over the spinach." },
      { order: 13, instruction: "Pour the egg mixture over the spinach and feta." },
      { order: 14, instruction: "Arrange halved cherry tomatoes on top, cut side up." },
      { order: 15, instruction: "Bake for 35-40 minutes until the center is set and the top is golden brown." },
      { order: 16, instruction: "Let cool for 10 minutes before slicing and serving." }
    ],
    cookingVessel: "Pie Dish",
    prepTime: 20,
    cookTime: 55,
    servings: 6,
    difficulty: "Medium",
    mealType: "Lunch",
    cuisine: "French",
    categories: ["Egg Dishes", "Make-Ahead"],
    dietaryCategories: ["Vegetarian"],
    tags: ["quiche", "spinach", "feta", "french"],
    imageUrl: "https://images.unsplash.com/photo-1535980156496-32138e4f5e84"
  },
  {
    title: "Beef and Barley Stew",
    description: "A hearty and comforting stew featuring tender beef, nutty barley, and root vegetables simmered in a rich broth, perfect for a satisfying cold-weather lunch.",
    ingredients: [
      { name: "beef chuck", quantity: "1 1/2", unit: "pounds", notes: "cut into 1-inch cubes" },
      { name: "salt", quantity: "1 1/2", unit: "teaspoons", notes: "divided" },
      { name: "black pepper", quantity: "1", unit: "teaspoon", notes: "divided" },
      { name: "all-purpose flour", quantity: "3", unit: "tablespoons" },
      { name: "vegetable oil", quantity: "2", unit: "tablespoons" },
      { name: "onion", quantity: "1", unit: "large", notes: "diced" },
      { name: "carrots", quantity: "3", unit: "medium", notes: "diced" },
      { name: "celery", quantity: "2", unit: "stalks", notes: "diced" },
      { name: "garlic", quantity: "3", unit: "cloves", notes: "minced" },
      { name: "tomato paste", quantity: "2", unit: "tablespoons" },
      { name: "red wine", quantity: "1/2", unit: "cup", notes: "optional" },
      { name: "beef broth", quantity: "6", unit: "cups" },
      { name: "bay leaves", quantity: "2", unit: "" },
      { name: "dried thyme", quantity: "1", unit: "teaspoon" },
      { name: "pearl barley", quantity: "3/4", unit: "cup", notes: "rinsed" },
      { name: "potatoes", quantity: "2", unit: "medium", notes: "peeled and diced" },
      { name: "parsnips", quantity: "2", unit: "medium", notes: "peeled and diced" },
      { name: "Worcestershire sauce", quantity: "1", unit: "tablespoon" },
      { name: "fresh parsley", quantity: "1/4", unit: "cup", notes: "chopped, for garnish" }
    ],
    steps: [
      { order: 1, instruction: "Season beef cubes with 1 teaspoon salt and 1/2 teaspoon pepper, then toss with flour to coat." },
      { order: 2, instruction: "Heat vegetable oil in a large Dutch oven over medium-high heat." },
      { order: 3, instruction: "Working in batches, brown the beef on all sides, about 3-4 minutes per batch. Transfer to a plate." },
      { order: 4, instruction: "In the same pot, add onion, carrots, and celery. Cook until softened, about 5 minutes." },
      { order: 5, instruction: "Add garlic and cook for 30 seconds until fragrant." },
      { order: 6, instruction: "Stir in tomato paste and cook for 1 minute." },
      { order: 7, instruction: "If using, add red wine and scrape up any browned bits from the bottom of the pot. Simmer for 2 minutes." },
      { order: 8, instruction: "Return beef to the pot and add beef broth, bay leaves, thyme, remaining salt and pepper." },
      { order: 9, instruction: "Bring to a boil, then reduce heat to low. Cover and simmer for 1 hour." },
      { order: 10, instruction: "Add barley, potatoes, and parsnips. Cover and simmer for an additional 45 minutes, until beef and barley are tender." },
      { order: 11, instruction: "Stir in Worcestershire sauce." },
      { order: 12, instruction: "Remove bay leaves and adjust seasoning if needed." },
      { order: 13, instruction: "Ladle into bowls and garnish with fresh parsley before serving." }
    ],
    cookingVessel: "Dutch Oven",
    prepTime: 25,
    cookTime: 120,
    servings: 6,
    difficulty: "Medium",
    mealType: "Lunch",
    cuisine: "American",
    categories: ["Stews", "Comfort Food"],
    dietaryCategories: ["Dairy-Free"],
    tags: ["beef", "barley", "stew", "hearty"],
    imageUrl: "https://images.unsplash.com/photo-1608500218890-c4f9a2f2e429"
  },
  {
    title: "Waldorf Chicken Salad",
    description: "A classic American salad featuring tender chicken, crisp apples, grapes, celery, and walnuts in a creamy dressing, served on a bed of lettuce or as a sandwich filling.",
    ingredients: [
      { name: "chicken breast", quantity: "2", unit: "pounds", notes: "cooked and diced" },
      { name: "celery", quantity: "3", unit: "stalks", notes: "diced" },
      { name: "apples", quantity: "2", unit: "medium", notes: "cored and diced (Honeycrisp or Granny Smith)" },
      { name: "red grapes", quantity: "1", unit: "cup", notes: "halved" },
      { name: "walnuts", quantity: "1/2", unit: "cup", notes: "toasted and chopped" },
      { name: "mayonnaise", quantity: "3/4", unit: "cup" },
      { name: "Greek yogurt", quantity: "1/4", unit: "cup", notes: "plain" },
      { name: "lemon juice", quantity: "1", unit: "tablespoon" },
      { name: "Dijon mustard", quantity: "1", unit: "teaspoon" },
      { name: "honey", quantity: "1", unit: "teaspoon" },
      { name: "salt", quantity: "1/2", unit: "teaspoon" },
      { name: "black pepper", quantity: "1/4", unit: "teaspoon" },
      { name: "dried tarragon", quantity: "1/2", unit: "teaspoon", notes: "optional" },
      { name: "lettuce leaves", quantity: "8", unit: "large", notes: "for serving" },
      { name: "croissants", quantity: "4", unit: "", notes: "split, for serving as sandwiches (optional)" }
    ],
    steps: [
      { order: 1, instruction: "In a large bowl, combine diced chicken, celery, apples, grapes, and walnuts." },
      { order: 2, instruction: "In a separate bowl, whisk together mayonnaise, Greek yogurt, lemon juice, Dijon mustard, honey, salt, pepper, and tarragon (if using)." },
      { order: 3, instruction: "Pour the dressing over the chicken mixture and toss gently to coat evenly." },
      { order: 4, instruction: "Cover and refrigerate for at least 30 minutes to allow flavors to meld." },
      { order: 5, instruction: "Serve chilled on a bed of lettuce leaves or as a filling in split croissants." }
    ],
    cookingVessel: "Mixing Bowl",
    prepTime: 20,
    cookTime: 0,
    servings: 4,
    difficulty: "Easy",
    mealType: "Lunch",
    cuisine: "American",
    categories: ["Salads", "Make-Ahead"],
    dietaryCategories: ["Gluten-Free (without croissant)"],
    tags: ["chicken salad", "waldorf", "apples", "grapes"],
    imageUrl: "https://images.unsplash.com/photo-1512852939750-1305098529bf"
  }
];

export default lunchRecipes;
