// Other Recipes for WhatAboutDinner App
// 20 detailed recipes for the "Other" category with all required fields

const otherRecipes = [
  {
    title: "Homemade Granola",
    description: "A customizable, crunchy blend of oats, nuts, seeds, and dried fruits baked with honey and spices for a versatile breakfast topping or snack that's far superior to store-bought versions.",
    ingredients: [
      { name: "old-fashioned rolled oats", quantity: "4", unit: "cups" },
      { name: "mixed nuts", quantity: "1 1/2", unit: "cups", notes: "almonds, pecans, walnuts, roughly chopped" },
      { name: "sunflower seeds", quantity: "1/2", unit: "cup" },
      { name: "pumpkin seeds", quantity: "1/2", unit: "cup" },
      { name: "unsweetened coconut flakes", quantity: "1", unit: "cup" },
      { name: "ground cinnamon", quantity: "2", unit: "teaspoons" },
      { name: "salt", quantity: "1/2", unit: "teaspoon" },
      { name: "coconut oil", quantity: "1/2", unit: "cup", notes: "melted" },
      { name: "honey", quantity: "1/2", unit: "cup" },
      { name: "maple syrup", quantity: "1/4", unit: "cup" },
      { name: "vanilla extract", quantity: "2", unit: "teaspoons" },
      { name: "dried fruits", quantity: "1 1/2", unit: "cups", notes: "cranberries, raisins, chopped apricots, etc." }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 300°F (150°C). Line two large baking sheets with parchment paper." },
      { order: 2, instruction: "In a large bowl, combine oats, nuts, seeds, coconut flakes, cinnamon, and salt." },
      { order: 3, instruction: "In a separate bowl, whisk together melted coconut oil, honey, maple syrup, and vanilla extract." },
      { order: 4, instruction: "Pour the wet ingredients over the dry ingredients and stir until everything is well coated." },
      { order: 5, instruction: "Spread the mixture evenly onto the prepared baking sheets." },
      { order: 6, instruction: "Bake for 40-45 minutes, stirring every 15 minutes, until the granola is golden brown." },
      { order: 7, instruction: "Remove from oven and let cool completely on the baking sheets. The granola will crisp up as it cools." },
      { order: 8, instruction: "Once cooled, add dried fruits and mix well." },
      { order: 9, instruction: "Store in airtight containers at room temperature for up to 2 weeks or in the freezer for up to 3 months." }
    ],
    cookingVessel: "Baking Sheet",
    prepTime: 15,
    cookTime: 45,
    servings: 12,
    difficulty: "Easy",
    mealType: "Other",
    cuisine: "American",
    categories: ["Breakfast Foods", "Homemade Basics"],
    dietaryCategories: ["Vegetarian", "Gluten-Free (with GF oats)", "Dairy-Free"],
    tags: ["granola", "oats", "nuts", "breakfast", "meal prep"],
    imageUrl: "https://images.unsplash.com/photo-1517093157656-b9eccef91cb1"
  },
  {
    title: "Homemade Almond Butter",
    description: "Smooth, creamy nut butter made from roasted almonds for a fresh, preservative-free alternative to store-bought versions that's perfect for spreading, baking, or adding to smoothies.",
    ingredients: [
      { name: "raw almonds", quantity: "3", unit: "cups" },
      { name: "salt", quantity: "1/4", unit: "teaspoon", notes: "optional" },
      { name: "honey or maple syrup", quantity: "1", unit: "tablespoon", notes: "optional" },
      { name: "cinnamon", quantity: "1/2", unit: "teaspoon", notes: "optional" },
      { name: "vanilla extract", quantity: "1/2", unit: "teaspoon", notes: "optional" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 350°F (175°C). Spread almonds in a single layer on a baking sheet." },
      { order: 2, instruction: "Roast almonds for 10-12 minutes, stirring once halfway through, until fragrant and slightly darkened. Be careful not to burn them." },
      { order: 3, instruction: "Let the almonds cool for 5-10 minutes. They should still be warm but not hot." },
      { order: 4, instruction: "Transfer the warm almonds to a food processor or high-powered blender." },
      { order: 5, instruction: "Process the almonds, scraping down the sides as needed. Be patient, as this process takes time." },
      { order: 6, instruction: "The almonds will go through several stages: first a flour-like consistency, then clumpy, then a thick paste, and finally a smooth, creamy butter (about 10-15 minutes total)." },
      { order: 7, instruction: "Once the almond butter is smooth and creamy, add salt and any optional ingredients (honey, cinnamon, vanilla) if desired." },
      { order: 8, instruction: "Process for another minute to incorporate add-ins." },
      { order: 9, instruction: "Transfer to a clean jar with a tight-fitting lid." },
      { order: 10, instruction: "Store at room temperature for up to 2 weeks, or in the refrigerator for up to 1 month." }
    ],
    cookingVessel: "Food Processor",
    prepTime: 5,
    cookTime: 25,
    servings: 24,
    difficulty: "Medium",
    mealType: "Other",
    cuisine: "American",
    categories: ["Nut Butters", "Homemade Basics"],
    dietaryCategories: ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free"],
    tags: ["almond butter", "nuts", "homemade", "preservative-free", "natural"],
    imageUrl: "https://images.unsplash.com/photo-1612224099291-d1a0b93c1c2e"
  },
  {
    title: "Homemade Vegetable Stock",
    description: "A flavorful, aromatic base for soups, stews, and risottos made from simmered vegetables and herbs that adds depth and richness to countless recipes while reducing food waste.",
    ingredients: [
      { name: "onions", quantity: "2", unit: "large", notes: "roughly chopped" },
      { name: "carrots", quantity: "3", unit: "medium", notes: "roughly chopped" },
      { name: "celery stalks", quantity: "4", unit: "", notes: "roughly chopped" },
      { name: "garlic", quantity: "4", unit: "cloves", notes: "smashed" },
      { name: "leek", quantity: "1", unit: "medium", notes: "white and light green parts, chopped" },
      { name: "mushroom stems", quantity: "1", unit: "cup", notes: "optional" },
      { name: "parsley stems", quantity: "1/2", unit: "cup" },
      { name: "thyme sprigs", quantity: "4", unit: "" },
      { name: "bay leaves", quantity: "2", unit: "" },
      { name: "black peppercorns", quantity: "1", unit: "teaspoon" },
      { name: "vegetable scraps", quantity: "2", unit: "cups", notes: "optional: clean peels, ends, stems" },
      { name: "water", quantity: "12", unit: "cups" },
      { name: "salt", quantity: "1", unit: "teaspoon", notes: "optional" }
    ],
    steps: [
      { order: 1, instruction: "In a large stockpot, combine all ingredients except salt." },
      { order: 2, instruction: "Bring to a boil over high heat, then reduce heat to maintain a gentle simmer." },
      { order: 3, instruction: "Partially cover the pot and simmer for 1-1.5 hours, occasionally skimming any foam that rises to the surface." },
      { order: 4, instruction: "The longer it simmers, the more flavorful it will become, but avoid going beyond 2 hours as the vegetables can begin to break down too much." },
      { order: 5, instruction: "Remove from heat and let cool slightly." },
      { order: 6, instruction: "Strain the stock through a fine-mesh sieve into a large bowl or container, pressing gently on the solids to extract as much liquid as possible." },
      { order: 7, instruction: "Discard the solids." },
      { order: 8, instruction: "If desired, add salt to taste." },
      { order: 9, instruction: "Let cool completely before transferring to storage containers." },
      { order: 10, instruction: "Refrigerate for up to 5 days or freeze in portions for up to 3 months." }
    ],
    cookingVessel: "Stockpot",
    prepTime: 20,
    cookTime: 90,
    servings: 10,
    difficulty: "Easy",
    mealType: "Other",
    cuisine: "Universal",
    categories: ["Stocks and Broths", "Homemade Basics"],
    dietaryCategories: ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free"],
    tags: ["vegetable stock", "soup base", "homemade", "food waste reduction", "freezer friendly"],
    imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554"
  },
  {
    title: "Homemade Pickled Red Onions",
    description: "Quick-pickled red onions with a perfect balance of tangy, sweet, and aromatic flavors that add bright color and zesty crunch to tacos, salads, sandwiches, and more.",
    ingredients: [
      { name: "red onions", quantity: "2", unit: "medium", notes: "thinly sliced" },
      { name: "apple cider vinegar", quantity: "1", unit: "cup" },
      { name: "water", quantity: "1/2", unit: "cup" },
      { name: "granulated sugar", quantity: "3", unit: "tablespoons" },
      { name: "kosher salt", quantity: "1 1/2", unit: "teaspoons" },
      { name: "garlic cloves", quantity: "2", unit: "", notes: "lightly smashed" },
      { name: "black peppercorns", quantity: "1", unit: "teaspoon" },
      { name: "red pepper flakes", quantity: "1/4", unit: "teaspoon", notes: "optional" },
      { name: "bay leaf", quantity: "1", unit: "" },
      { name: "whole cloves", quantity: "3", unit: "", notes: "optional" }
    ],
    steps: [
      { order: 1, instruction: "Place sliced red onions in a clean glass jar or container that has a tight-fitting lid." },
      { order: 2, instruction: "Add garlic cloves, black peppercorns, red pepper flakes (if using), bay leaf, and cloves (if using) to the jar." },
      { order: 3, instruction: "In a small saucepan, combine apple cider vinegar, water, sugar, and salt." },
      { order: 4, instruction: "Bring the mixture to a simmer over medium heat, stirring until sugar and salt are completely dissolved." },
      { order: 5, instruction: "Carefully pour the hot brine over the onions in the jar, making sure all onions are submerged." },
      { order: 6, instruction: "Let the jar cool to room temperature, about 30 minutes." },
      { order: 7, instruction: "Secure the lid and refrigerate for at least 1 hour before using, though they're best after 24 hours." },
      { order: 8, instruction: "Pickled onions will keep in the refrigerator for up to 2 weeks." }
    ],
    cookingVessel: "Saucepan",
    prepTime: 10,
    cookTime: 5,
    servings: 16,
    difficulty: "Easy",
    mealType: "Other",
    cuisine: "Mexican-Inspired",
    categories: ["Pickles and Preserves", "Condiments"],
    dietaryCategories: ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free"],
    tags: ["pickled onions", "condiment", "quick pickle", "taco topping", "no canning required"],
    imageUrl: "https://images.unsplash.com/photo-1593030103066-0093718efeb9"
  },
  {
    title: "Homemade Ghee (Clarified Butter)",
    description: "Pure butterfat with milk solids removed for a high-smoke-point cooking fat with a rich, nutty flavor that's shelf-stable and suitable for those with mild lactose sensitivities.",
    ingredients: [
      { name: "unsalted butter", quantity: "1", unit: "pound", notes: "preferably grass-fed" }
    ],
    steps: [
      { order: 1, instruction: "Cut butter into cubes and place in a heavy-bottomed saucepan or Dutch oven." },
      { order: 2, instruction: "Melt the butter over medium-low heat." },
      { order: 3, instruction: "Once melted, reduce heat to low and let the butter simmer gently." },
      { order: 4, instruction: "As it simmers, the butter will separate into three layers: foam on top, clear golden liquid in the middle, and milk solids at the bottom." },
      { order: 5, instruction: "Allow it to simmer undisturbed for about 15-20 minutes. The milk solids at the bottom will begin to brown, and the liquid will become clear and golden." },
      { order: 6, instruction: "When the milk solids are golden brown and the liquid is clear with a pleasant nutty aroma, remove from heat." },
      { order: 7, instruction: "Let cool slightly for 2-3 minutes." },
      { order: 8, instruction: "Line a fine-mesh strainer with several layers of cheesecloth and place over a clean, dry glass jar." },
      { order: 9, instruction: "Carefully pour the ghee through the strainer, leaving the browned milk solids behind." },
      { order: 10, instruction: "Let cool completely before securing the lid." },
      { order: 11, instruction: "Store at room temperature for up to 3 months, or in the refrigerator for up to 1 year." }
    ],
    cookingVessel: "Heavy-Bottomed Saucepan",
    prepTime: 5,
    cookTime: 25,
    servings: 32,
    difficulty: "Medium",
    mealType: "Other",
    cuisine: "Indian",
    categories: ["Cooking Fats", "Homemade Basics"],
    dietaryCategories: ["Gluten-Free", "Low-Lactose"],
    tags: ["ghee", "clarified butter", "cooking fat", "high smoke point", "shelf-stable"],
    imageUrl: "https://images.unsplash.com/photo-1631213637991-55a5c0c19c5c"
  },
  {
    title: "Homemade Taco Seasoning",
    description: "A preservative-free blend of spices and herbs that delivers authentic Mexican-inspired flavor for tacos, fajitas, and more, allowing you to control the heat level and avoid additives.",
    ingredients: [
      { name: "chili powder", quantity: "1/4", unit: "cup" },
      { name: "ground cumin", quantity: "2", unit: "tablespoons" },
      { name: "paprika", quantity: "1", unit: "tablespoon" },
      { name: "garlic powder", quantity: "1", unit: "tablespoon" },
      { name: "onion powder", quantity: "1", unit: "tablespoon" },
      { name: "dried oregano", quantity: "2", unit: "teaspoons" },
      { name: "salt", quantity: "2", unit: "teaspoons" },
      { name: "black pepper", quantity: "2", unit: "teaspoons" },
      { name: "cayenne pepper", quantity: "1/2", unit: "teaspoon", notes: "adjust to taste" },
      { name: "crushed red pepper flakes", quantity: "1/2", unit: "teaspoon", notes: "optional" },
      { name: "cornstarch", quantity: "1", unit: "tablespoon", notes: "optional, for thickening" }
    ],
    steps: [
      { order: 1, instruction: "In a small bowl, combine all ingredients." },
      { order: 2, instruction: "Whisk thoroughly to ensure even distribution of all spices." },
      { order: 3, instruction: "Transfer to an airtight container or spice jar." },
      { order: 4, instruction: "Store in a cool, dry place for up to 6 months." },
      { order: 5, instruction: "To use: Add 2-3 tablespoons of seasoning per pound of meat or plant-based protein." },
      { order: 6, instruction: "If the original recipe calls for water, add about 2/3 cup water with the seasoning." }
    ],
    cookingVessel: "Mixing Bowl",
    prepTime: 10,
    cookTime: 0,
    servings: 24,
    difficulty: "Easy",
    mealType: "Other",
    cuisine: "Mexican-Inspired",
    categories: ["Spice Blends", "Homemade Basics"],
    dietaryCategories: ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free"],
    tags: ["taco seasoning", "spice blend", "preservative-free", "customizable", "pantry staple"],
    imageUrl: "https://images.unsplash.com/photo-1564844536308-50b114a1d946"
  },
  {
    title: "Homemade Vanilla Extract",
    description: "A pure, aromatic extract made by steeping vanilla beans in alcohol for a superior flavoring agent in baking that makes an excellent gift and saves money over store-bought versions.",
    ingredients: [
      { name: "vanilla beans", quantity: "5-6", unit: "", notes: "Grade B, split lengthwise" },
      { name: "vodka", quantity: "1", unit: "cup", notes: "at least 80 proof" },
      { name: "glass bottle", quantity: "1", unit: "8-ounce", notes: "dark-colored with tight-fitting lid" }
    ],
    steps: [
      { order: 1, instruction: "Using a sharp knife, split each vanilla bean lengthwise, leaving about 1/2 inch connected at each end." },
      { order: 2, instruction: "Place the split vanilla beans in a clean glass bottle." },
      { order: 3, instruction: "Pour vodka over the beans, making sure they are completely submerged." },
      { order: 4, instruction: "Secure the lid tightly." },
      { order: 5, instruction: "Store the bottle in a cool, dark place for at least 8 weeks, preferably 3-6 months for the best flavor." },
      { order: 6, instruction: "Shake the bottle once a week to agitate the mixture." },
      { order: 7, instruction: "After the initial steeping period, you can begin using the extract while continuing to let it age." },
      { order: 8, instruction: "As you use the extract, you can top it off with more vodka to maintain the level. The beans will continue to infuse the alcohol." },
      { order: 9, instruction: "The extract will keep indefinitely as long as the beans remain covered with alcohol." }
    ],
    cookingVessel: "Glass Bottle",
    prepTime: 15,
    cookTime: 0,
    servings: 48,
    difficulty: "Easy",
    mealType: "Other",
    cuisine: "Universal",
    categories: ["Extracts", "Homemade Basics"],
    dietaryCategories: ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free"],
    tags: ["vanilla extract", "baking essential", "homemade gift", "long-term project", "money-saving"],
    imageUrl: "https://images.unsplash.com/photo-1621886292650-520f76c747d6"
  },
  {
    title: "Homemade Croutons",
    description: "Crispy, flavorful bread cubes seasoned with herbs and garlic that elevate salads and soups while reducing food waste by transforming stale bread into a delicious topping.",
    ingredients: [
      { name: "day-old bread", quantity: "1", unit: "loaf", notes: "about 8 cups cubed" },
      { name: "olive oil", quantity: "1/3", unit: "cup" },
      { name: "garlic powder", quantity: "1", unit: "teaspoon" },
      { name: "dried Italian herbs", quantity: "2", unit: "teaspoons", notes: "or mix of oregano, basil, thyme" },
      { name: "salt", quantity: "1", unit: "teaspoon" },
      { name: "black pepper", quantity: "1/2", unit: "teaspoon" },
      { name: "grated parmesan cheese", quantity: "2", unit: "tablespoons", notes: "optional" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 375°F (190°C). Line a large baking sheet with parchment paper." },
      { order: 2, instruction: "Cut bread into 3/4-inch cubes and place in a large bowl." },
      { order: 3, instruction: "In a small bowl, whisk together olive oil, garlic powder, dried herbs, salt, and pepper." },
      { order: 4, instruction: "Pour the oil mixture over the bread cubes and toss until all cubes are evenly coated." },
      { order: 5, instruction: "If using parmesan cheese, sprinkle it over the bread cubes and toss again." },
      { order: 6, instruction: "Spread the bread cubes in a single layer on the prepared baking sheet." },
      { order: 7, instruction: "Bake for 10-15 minutes, stirring halfway through, until the croutons are golden brown and crisp." },
      { order: 8, instruction: "Remove from oven and let cool completely on the baking sheet." },
      { order: 9, instruction: "Store in an airtight container at room temperature for up to 2 weeks." }
    ],
    cookingVessel: "Baking Sheet",
    prepTime: 10,
    cookTime: 15,
    servings: 8,
    difficulty: "Easy",
    mealType: "Other",
    cuisine: "Universal",
    categories: ["Salad Toppings", "Homemade Basics"],
    dietaryCategories: ["Vegetarian", "Dairy-Free (without cheese)"],
    tags: ["croutons", "bread", "salad topping", "food waste reduction", "soup topping"],
    imageUrl: "https://images.unsplash.com/photo-1604908176997-125f7c9a1600"
  },
  {
    title: "Homemade Tzatziki Sauce",
    description: "A cool, creamy Greek yogurt sauce with cucumber, garlic, and herbs that's perfect for serving with grilled meats, vegetables, pita bread, or as a refreshing dip.",
    ingredients: [
      { name: "Greek yogurt", quantity: "2", unit: "cups", notes: "full-fat" },
      { name: "cucumber", quantity: "1", unit: "medium", notes: "English or Persian preferred" },
      { name: "garlic", quantity: "3", unit: "cloves", notes: "minced" },
      { name: "fresh dill", quantity: "2", unit: "tablespoons", notes: "chopped" },
      { name: "fresh mint", quantity: "1", unit: "tablespoon", notes: "chopped, optional" },
      { name: "lemon juice", quantity: "2", unit: "tablespoons", notes: "fresh" },
      { name: "extra virgin olive oil", quantity: "1", unit: "tablespoon" },
      { name: "salt", quantity: "1/2", unit: "teaspoon", notes: "or to taste" },
      { name: "black pepper", quantity: "1/4", unit: "teaspoon", notes: "freshly ground" }
    ],
    steps: [
      { order: 1, instruction: "Peel the cucumber if desired (English or Persian cucumbers can be left unpeeled). Cut in half lengthwise and scoop out the seeds with a spoon." },
      { order: 2, instruction: "Grate the cucumber using the large holes of a box grater." },
      { order: 3, instruction: "Place the grated cucumber in a clean kitchen towel or several layers of cheesecloth. Squeeze firmly to remove as much liquid as possible." },
      { order: 4, instruction: "In a medium bowl, combine the Greek yogurt, drained cucumber, minced garlic, dill, mint (if using), lemon juice, olive oil, salt, and pepper." },
      { order: 5, instruction: "Stir well to combine all ingredients." },
      { order: 6, instruction: "Cover and refrigerate for at least 2 hours, preferably overnight, to allow the flavors to meld." },
      { order: 7, instruction: "Taste and adjust seasonings before serving." },
      { order: 8, instruction: "Serve chilled, drizzled with additional olive oil if desired." },
      { order: 9, instruction: "Store in an airtight container in the refrigerator for up to 4 days." }
    ],
    cookingVessel: "Mixing Bowl",
    prepTime: 20,
    cookTime: 0,
    servings: 8,
    difficulty: "Easy",
    mealType: "Other",
    cuisine: "Greek",
    categories: ["Sauces and Dips", "Condiments"],
    dietaryCategories: ["Vegetarian", "Gluten-Free", "Low-Carb"],
    tags: ["tzatziki", "yogurt sauce", "cucumber", "Greek", "dip"],
    imageUrl: "https://images.unsplash.com/photo-1594312180721-3b5217cfc65f"
  },
  {
    title: "Homemade Pesto Sauce",
    description: "A vibrant, herbaceous sauce made with fresh basil, pine nuts, garlic, Parmesan, and olive oil that's perfect for pasta, sandwiches, or as a flavor-packed addition to soups and proteins.",
    ingredients: [
      { name: "fresh basil leaves", quantity: "2", unit: "cups", notes: "packed" },
      { name: "pine nuts", quantity: "1/3", unit: "cup", notes: "toasted" },
      { name: "garlic", quantity: "3", unit: "cloves" },
      { name: "Parmesan cheese", quantity: "1/2", unit: "cup", notes: "freshly grated" },
      { name: "extra virgin olive oil", quantity: "1/2", unit: "cup" },
      { name: "lemon juice", quantity: "1", unit: "tablespoon", notes: "fresh" },
      { name: "salt", quantity: "1/2", unit: "teaspoon", notes: "or to taste" },
      { name: "black pepper", quantity: "1/4", unit: "teaspoon", notes: "freshly ground" }
    ],
    steps: [
      { order: 1, instruction: "In a dry skillet over medium heat, toast the pine nuts until lightly golden and fragrant, about 3-5 minutes, stirring frequently to prevent burning. Let cool." },
      { order: 2, instruction: "In a food processor, combine basil leaves, cooled toasted pine nuts, and garlic. Pulse until coarsely chopped." },
      { order: 3, instruction: "Add the grated Parmesan cheese, salt, and pepper. Pulse to combine." },
      { order: 4, instruction: "With the food processor running, slowly drizzle in the olive oil until the mixture is smooth and well combined." },
      { order: 5, instruction: "Add the lemon juice and pulse a few more times to incorporate." },
      { order: 6, instruction: "Taste and adjust seasonings as needed." },
      { order: 7, instruction: "Transfer to a jar or airtight container." },
      { order: 8, instruction: "If not using immediately, pour a thin layer of olive oil on top to prevent discoloration." },
      { order: 9, instruction: "Store in the refrigerator for up to 1 week, or freeze in ice cube trays for up to 3 months." }
    ],
    cookingVessel: "Food Processor",
    prepTime: 15,
    cookTime: 5,
    servings: 8,
    difficulty: "Easy",
    mealType: "Other",
    cuisine: "Italian",
    categories: ["Sauces", "Homemade Basics"],
    dietaryCategories: ["Vegetarian", "Gluten-Free"],
    tags: ["pesto", "basil", "sauce", "Italian", "versatile"],
    imageUrl: "https://images.unsplash.com/photo-1564844536308-50b114a1d946"
  },
  {
    title: "Homemade Chicken Stock",
    description: "A rich, flavorful cooking base made by simmering chicken bones with vegetables and herbs for a versatile kitchen staple that enhances soups, sauces, and countless other dishes.",
    ingredients: [
      { name: "chicken bones", quantity: "3-4", unit: "pounds", notes: "from roasted chicken or raw chicken parts" },
      { name: "onions", quantity: "2", unit: "medium", notes: "quartered, skin on" },
      { name: "carrots", quantity: "3", unit: "medium", notes: "roughly chopped" },
      { name: "celery stalks", quantity: "3", unit: "", notes: "roughly chopped" },
      { name: "garlic", quantity: "4", unit: "cloves", notes: "smashed" },
      { name: "bay leaves", quantity: "2", unit: "" },
      { name: "fresh thyme sprigs", quantity: "6", unit: "" },
      { name: "fresh parsley stems", quantity: "1/2", unit: "cup" },
      { name: "whole black peppercorns", quantity: "1", unit: "tablespoon" },
      { name: "cold water", quantity: "12", unit: "cups", notes: "or enough to cover ingredients" },
      { name: "apple cider vinegar", quantity: "1", unit: "tablespoon", notes: "helps extract minerals from bones" },
      { name: "salt", quantity: "to taste", unit: "", notes: "optional" }
    ],
    steps: [
      { order: 1, instruction: "If using raw chicken parts, consider roasting them in a 400°F (200°C) oven for 30-40 minutes until browned for deeper flavor." },
      { order: 2, instruction: "In a large stockpot, combine chicken bones, onions, carrots, celery, garlic, bay leaves, thyme, parsley stems, and peppercorns." },
      { order: 3, instruction: "Add cold water to cover the ingredients by about 1 inch." },
      { order: 4, instruction: "Add apple cider vinegar and let sit for 30 minutes (this helps extract nutrients from the bones)." },
      { order: 5, instruction: "Bring to a gentle boil over medium-high heat, then immediately reduce to a low simmer." },
      { order: 6, instruction: "Skim off any foam or impurities that rise to the surface during the first 30 minutes of simmering." },
      { order: 7, instruction: "Partially cover the pot and simmer gently for 4-6 hours (or up to 24 hours for bone broth). The longer it simmers, the more flavorful it will be." },
      { order: 8, instruction: "Strain the stock through a fine-mesh sieve into a large bowl or container, discarding solids." },
      { order: 9, instruction: "Let cool slightly, then refrigerate overnight." },
      { order: 10, instruction: "Once chilled, skim off any solidified fat from the surface if desired." },
      { order: 11, instruction: "Season with salt to taste if using immediately, or leave unsalted for more versatile use in recipes." },
      { order: 12, instruction: "Portion and store in the refrigerator for up to 5 days, or freeze for up to 3 months." }
    ],
    cookingVessel: "Stockpot",
    prepTime: 20,
    cookTime: 360,
    servings: 12,
    difficulty: "Medium",
    mealType: "Other",
    cuisine: "Universal",
    categories: ["Stocks and Broths", "Homemade Basics"],
    dietaryCategories: ["Gluten-Free", "Dairy-Free"],
    tags: ["chicken stock", "bone broth", "soup base", "freezer friendly", "kitchen staple"],
    imageUrl: "https://images.unsplash.com/photo-1547592180-85f173990554"
  },
  {
    title: "Homemade Hummus",
    description: "A creamy, protein-rich dip made from chickpeas, tahini, lemon, and garlic that's perfect for snacking with vegetables or pita, spreading on sandwiches, or as part of a mezze platter.",
    ingredients: [
      { name: "canned chickpeas", quantity: "1", unit: "15-ounce can", notes: "drained and rinsed" },
      { name: "tahini", quantity: "1/4", unit: "cup", notes: "well stirred" },
      { name: "fresh lemon juice", quantity: "3", unit: "tablespoons" },
      { name: "garlic", quantity: "2", unit: "cloves", notes: "minced" },
      { name: "extra virgin olive oil", quantity: "2", unit: "tablespoons", notes: "plus more for serving" },
      { name: "ground cumin", quantity: "1/2", unit: "teaspoon" },
      { name: "salt", quantity: "1/2", unit: "teaspoon", notes: "or to taste" },
      { name: "ice water", quantity: "2-3", unit: "tablespoons" },
      { name: "paprika", quantity: "for garnish", unit: "" },
      { name: "chopped fresh parsley", quantity: "for garnish", unit: "" }
    ],
    steps: [
      { order: 1, instruction: "For smoother hummus, remove the skins from the chickpeas by gently pinching each one (optional but recommended)." },
      { order: 2, instruction: "In a food processor, combine chickpeas, tahini, lemon juice, garlic, olive oil, cumin, and salt." },
      { order: 3, instruction: "Process until smooth, about 1-2 minutes, stopping to scrape down the sides as needed." },
      { order: 4, instruction: "With the food processor running, slowly add ice water through the feed tube until the hummus reaches your desired consistency." },
      { order: 5, instruction: "Taste and adjust seasonings, adding more salt or lemon juice if needed." },
      { order: 6, instruction: "Transfer to a serving bowl and use the back of a spoon to create a shallow well in the center." },
      { order: 7, instruction: "Drizzle with additional olive oil and sprinkle with paprika and chopped parsley." },
      { order: 8, instruction: "Serve with pita bread, pita chips, or fresh vegetables." },
      { order: 9, instruction: "Store in an airtight container in the refrigerator for up to 1 week." }
    ],
    cookingVessel: "Food Processor",
    prepTime: 15,
    cookTime: 0,
    servings: 6,
    difficulty: "Easy",
    mealType: "Other",
    cuisine: "Middle Eastern",
    categories: ["Dips", "Spreads"],
    dietaryCategories: ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free"],
    tags: ["hummus", "chickpeas", "dip", "protein", "mezze"],
    imageUrl: "https://images.unsplash.com/photo-1577805947697-89e18249d767"
  },
  {
    title: "Homemade Salsa",
    description: "A vibrant, chunky mixture of fresh tomatoes, onions, peppers, and herbs that delivers bright, zesty flavor perfect for dipping chips, topping tacos, or enhancing grilled meats and fish.",
    ingredients: [
      { name: "ripe tomatoes", quantity: "6", unit: "medium", notes: "diced" },
      { name: "red onion", quantity: "1/2", unit: "medium", notes: "finely diced" },
      { name: "jalapeño peppers", quantity: "1-2", unit: "", notes: "seeded and minced" },
      { name: "garlic", quantity: "2", unit: "cloves", notes: "minced" },
      { name: "fresh cilantro", quantity: "1/2", unit: "cup", notes: "chopped" },
      { name: "fresh lime juice", quantity: "2", unit: "tablespoons" },
      { name: "ground cumin", quantity: "1/2", unit: "teaspoon" },
      { name: "salt", quantity: "1/2", unit: "teaspoon", notes: "or to taste" },
      { name: "black pepper", quantity: "1/4", unit: "teaspoon", notes: "freshly ground" },
      { name: "sugar", quantity: "1/4", unit: "teaspoon", notes: "optional, to balance acidity" }
    ],
    steps: [
      { order: 1, instruction: "In a medium bowl, combine diced tomatoes, red onion, jalapeños, garlic, and cilantro." },
      { order: 2, instruction: "Add lime juice, cumin, salt, black pepper, and sugar (if using)." },
      { order: 3, instruction: "Stir gently to combine all ingredients." },
      { order: 4, instruction: "For a smoother salsa, pulse a portion or all of the mixture in a food processor or blender to your desired consistency." },
      { order: 5, instruction: "Taste and adjust seasonings as needed, adding more salt, lime juice, or jalapeño for heat." },
      { order: 6, instruction: "Let sit for at least 30 minutes before serving to allow flavors to meld." },
      { order: 7, instruction: "For best flavor, refrigerate for 2-4 hours before serving." },
      { order: 8, instruction: "Store in an airtight container in the refrigerator for up to 5 days." }
    ],
    cookingVessel: "Mixing Bowl",
    prepTime: 20,
    cookTime: 0,
    servings: 8,
    difficulty: "Easy",
    mealType: "Other",
    cuisine: "Mexican",
    categories: ["Dips", "Condiments"],
    dietaryCategories: ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free"],
    tags: ["salsa", "tomato", "fresh", "dip", "Mexican"],
    imageUrl: "https://images.unsplash.com/photo-1600335895229-6e75511892c8"
  },
  {
    title: "Homemade Mayonnaise",
    description: "A silky, rich condiment made from oil, egg yolks, and acid that's far superior to store-bought versions with a fresh flavor that elevates sandwiches, salads, and sauces.",
    ingredients: [
      { name: "egg yolks", quantity: "2", unit: "large", notes: "at room temperature" },
      { name: "Dijon mustard", quantity: "1", unit: "teaspoon" },
      { name: "white wine vinegar or lemon juice", quantity: "2", unit: "teaspoons" },
      { name: "salt", quantity: "1/2", unit: "teaspoon" },
      { name: "neutral oil", quantity: "1", unit: "cup", notes: "such as canola or grapeseed" },
      { name: "extra virgin olive oil", quantity: "1/4", unit: "cup", notes: "optional, for flavor" }
    ],
    steps: [
      { order: 1, instruction: "In a medium bowl, whisk together egg yolks, Dijon mustard, vinegar or lemon juice, and salt until well combined." },
      { order: 2, instruction: "Combine the neutral oil and olive oil (if using) in a measuring cup with a pour spout." },
      { order: 3, instruction: "While whisking constantly, add a few drops of oil to the egg mixture. Continue whisking until completely incorporated." },
      { order: 4, instruction: "Very slowly, in a thin stream, add more oil while whisking vigorously. The mixture will begin to thicken and emulsify." },
      { order: 5, instruction: "Continue adding oil in a slow, steady stream while whisking until all oil is incorporated and the mayonnaise is thick and glossy." },
      { order: 6, instruction: "If the mayonnaise becomes too thick, add a few drops of water to thin it slightly." },
      { order: 7, instruction: "Taste and adjust seasoning with additional salt or acid if needed." },
      { order: 8, instruction: "Transfer to a jar or airtight container and refrigerate for at least 30 minutes before using." },
      { order: 9, instruction: "Store in the refrigerator for up to 1 week." }
    ],
    cookingVessel: "Mixing Bowl",
    prepTime: 15,
    cookTime: 0,
    servings: 16,
    difficulty: "Medium",
    mealType: "Other",
    cuisine: "French",
    categories: ["Condiments", "Homemade Basics"],
    dietaryCategories: ["Vegetarian", "Gluten-Free", "Dairy-Free"],
    tags: ["mayonnaise", "condiment", "emulsion", "egg-based", "sandwich spread"],
    imageUrl: "https://images.unsplash.com/photo-1585907291096-715e7fc8c5c4"
  },
  {
    title: "Homemade Kimchi",
    description: "A traditional Korean fermented cabbage dish with a complex flavor profile that's spicy, tangy, and umami-rich, perfect as a side dish or ingredient in countless recipes.",
    ingredients: [
      { name: "napa cabbage", quantity: "1", unit: "medium head", notes: "about 2 pounds" },
      { name: "kosher salt", quantity: "1/4", unit: "cup" },
      { name: "water", quantity: "2", unit: "quarts", notes: "filtered" },
      { name: "daikon radish", quantity: "8", unit: "ounces", notes: "peeled and cut into matchsticks" },
      { name: "carrots", quantity: "2", unit: "medium", notes: "peeled and cut into matchsticks" },
      { name: "green onions", quantity: "6", unit: "", notes: "cut into 1-inch pieces" },
      { name: "garlic", quantity: "6", unit: "cloves", notes: "minced" },
      { name: "fresh ginger", quantity: "2", unit: "tablespoons", notes: "grated" },
      { name: "Korean red pepper flakes (gochugaru)", quantity: "1/4", unit: "cup", notes: "adjust to taste" },
      { name: "fish sauce", quantity: "2", unit: "tablespoons", notes: "or soy sauce for vegan version" },
      { name: "granulated sugar", quantity: "1", unit: "tablespoon" },
      { name: "rice flour", quantity: "2", unit: "tablespoons", notes: "optional, for thicker paste" },
      { name: "water", quantity: "1/4", unit: "cup", notes: "for rice flour paste if using" }
    ],
    steps: [
      { order: 1, instruction: "Cut the napa cabbage in half lengthwise, then cut each half into quarters. Remove the core." },
      { order: 2, instruction: "In a large bowl, dissolve 1/4 cup kosher salt in 2 quarts of water to make a brine." },
      { order: 3, instruction: "Submerge the cabbage in the brine, weighing it down with a plate if necessary. Let soak for 1-2 hours." },
      { order: 4, instruction: "Rinse the cabbage thoroughly under cold water, 3 times. Drain well and pat dry." },
      { order: 5, instruction: "If using rice flour paste: In a small saucepan, whisk rice flour with 1/4 cup water. Heat over medium, stirring constantly until it thickens to a paste. Let cool completely." },
      { order: 6, instruction: "In a large bowl, combine garlic, ginger, Korean red pepper flakes, fish sauce, sugar, and rice flour paste (if using) to make the kimchi paste." },
      { order: 7, instruction: "Add daikon, carrots, and green onions to the kimchi paste and mix well." },
      { order: 8, instruction: "Using gloves, rub the kimchi paste all over each cabbage leaf, getting between all the layers." },
      { order: 9, instruction: "Pack the kimchi into a clean glass jar with a tight-fitting lid, pressing down to remove air pockets." },
      { order: 10, instruction: "Leave about 1 inch of space at the top of the jar as the kimchi will expand as it ferments." },
      { order: 11, instruction: "Seal the jar and let it sit at room temperature for 1-5 days, depending on the ambient temperature and desired sourness. The warmer it is, the faster it will ferment." },
      { order: 12, instruction: "Check the kimchi daily, pressing down to keep it submerged in its juices. You may want to place the jar on a plate to catch any overflow." },
      { order: 13, instruction: "When it reaches your desired level of fermentation (bubbles will appear and it will smell sour), transfer to the refrigerator." },
      { order: 14, instruction: "Kimchi will continue to ferment slowly in the refrigerator and can be kept for several months, with the flavor developing over time." }
    ],
    cookingVessel: "Glass Jar",
    prepTime: 30,
    cookTime: 0,
    servings: 16,
    difficulty: "Medium",
    mealType: "Other",
    cuisine: "Korean",
    categories: ["Fermented Foods", "Condiments"],
    dietaryCategories: ["Gluten-Free", "Dairy-Free", "Vegan (with soy sauce)"],
    tags: ["kimchi", "fermented", "cabbage", "Korean", "probiotic"],
    imageUrl: "https://images.unsplash.com/photo-1583224964978-2e827ef39d97"
  },
  {
    title: "Homemade Pasta Dough",
    description: "A simple, versatile dough made with flour and eggs that can be rolled and cut into various pasta shapes for a fresh, tender texture that's incomparable to dried pasta.",
    ingredients: [
      { name: "all-purpose flour", quantity: "2", unit: "cups", notes: "plus more for dusting" },
      { name: "eggs", quantity: "3", unit: "large" },
      { name: "egg yolks", quantity: "2", unit: "large" },
      { name: "olive oil", quantity: "1", unit: "tablespoon" },
      { name: "salt", quantity: "1/2", unit: "teaspoon" },
      { name: "water", quantity: "1-2", unit: "tablespoons", notes: "if needed" }
    ],
    steps: [
      { order: 1, instruction: "On a clean work surface, create a mound with the flour. Make a well in the center." },
      { order: 2, instruction: "Crack the eggs and egg yolks into the well. Add olive oil and salt." },
      { order: 3, instruction: "Using a fork, beat the eggs, gradually incorporating flour from the inner edges of the well." },
      { order: 4, instruction: "Once the dough becomes too thick to mix with a fork, use your hands to incorporate the remaining flour." },
      { order: 5, instruction: "If the dough seems too dry, add water, 1 teaspoon at a time. If too sticky, add more flour." },
      { order: 6, instruction: "Knead the dough for 8-10 minutes until smooth and elastic. The dough should spring back when poked." },
      { order: 7, instruction: "Form the dough into a ball, wrap tightly in plastic wrap, and let rest at room temperature for at least 30 minutes (or up to 2 hours)." },
      { order: 8, instruction: "After resting, divide the dough into 4 equal portions. Work with one portion at a time, keeping the others wrapped." },
      { order: 9, instruction: "Flatten the dough portion slightly and dust with flour. Pass through a pasta machine at the widest setting." },
      { order: 10, instruction: "Fold the dough in thirds, like a letter, and pass through the machine again. Repeat this process 3-4 times to develop the gluten." },
      { order: 11, instruction: "Gradually reduce the settings on the pasta machine, passing the dough through once at each setting until desired thickness is reached." },
      { order: 12, instruction: "Cut the pasta sheets into your desired shape (fettuccine, tagliatelle, etc.) or use for filled pasta like ravioli." },
      { order: 13, instruction: "Cook fresh pasta in salted boiling water for 1-3 minutes, depending on thickness, until al dente." },
      { order: 14, instruction: "Alternatively, let the pasta dry completely before storing in an airtight container for up to 2 weeks." }
    ],
    cookingVessel: "Work Surface",
    prepTime: 20,
    cookTime: 0,
    servings: 4,
    difficulty: "Medium",
    mealType: "Other",
    cuisine: "Italian",
    categories: ["Pasta", "Homemade Basics"],
    dietaryCategories: ["Vegetarian"],
    tags: ["pasta dough", "homemade pasta", "Italian", "from scratch", "versatile"],
    imageUrl: "https://images.unsplash.com/photo-1556760544-74068565f05c"
  },
  {
    title: "Homemade Garam Masala",
    description: "A fragrant, warming Indian spice blend featuring toasted and ground whole spices that adds depth and complexity to countless dishes from curries to roasted vegetables.",
    ingredients: [
      { name: "coriander seeds", quantity: "3", unit: "tablespoons" },
      { name: "cumin seeds", quantity: "2", unit: "tablespoons" },
      { name: "cardamom pods", quantity: "1", unit: "tablespoon", notes: "green, seeds removed from pods" },
      { name: "black peppercorns", quantity: "2", unit: "teaspoons" },
      { name: "cloves", quantity: "1", unit: "teaspoon" },
      { name: "cinnamon stick", quantity: "1", unit: "3-inch piece", notes: "broken into pieces" },
      { name: "bay leaves", quantity: "2", unit: "", notes: "dried" },
      { name: "star anise", quantity: "1", unit: "whole" },
      { name: "nutmeg", quantity: "1/2", unit: "teaspoon", notes: "freshly grated" },
      { name: "mace", quantity: "1/4", unit: "teaspoon", notes: "optional" }
    ],
    steps: [
      { order: 1, instruction: "In a dry skillet over medium heat, add all whole spices (coriander seeds, cumin seeds, cardamom seeds, black peppercorns, cloves, cinnamon pieces, bay leaves, and star anise)." },
      { order: 2, instruction: "Toast the spices, stirring frequently, until they become fragrant and slightly darker in color, about 3-5 minutes. Be careful not to burn them." },
      { order: 3, instruction: "Remove from heat and let cool completely." },
      { order: 4, instruction: "Transfer the cooled toasted spices to a spice grinder or clean coffee grinder." },
      { order: 5, instruction: "Add the freshly grated nutmeg and mace (if using)." },
      { order: 6, instruction: "Grind to a fine powder, working in batches if necessary." },
      { order: 7, instruction: "Sift the ground spices through a fine-mesh sieve to remove any larger pieces." },
      { order: 8, instruction: "Transfer to an airtight container or spice jar." },
      { order: 9, instruction: "Store in a cool, dark place for up to 3 months for optimal flavor, or up to 6 months total." }
    ],
    cookingVessel: "Skillet",
    prepTime: 10,
    cookTime: 5,
    servings: 24,
    difficulty: "Easy",
    mealType: "Other",
    cuisine: "Indian",
    categories: ["Spice Blends", "Homemade Basics"],
    dietaryCategories: ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free"],
    tags: ["garam masala", "spice blend", "Indian", "aromatic", "curry"],
    imageUrl: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d"
  },
  {
    title: "Homemade Ricotta Cheese",
    description: "A fresh, creamy cheese made by heating milk and acid that's perfect for lasagna, stuffed pasta, toast, or desserts, with a delicate flavor that's far superior to store-bought versions.",
    ingredients: [
      { name: "whole milk", quantity: "1", unit: "gallon", notes: "not ultra-pasteurized" },
      { name: "heavy cream", quantity: "1", unit: "cup", notes: "optional, for richness" },
      { name: "salt", quantity: "1", unit: "teaspoon" },
      { name: "lemon juice", quantity: "1/3", unit: "cup", notes: "freshly squeezed" },
      { name: "white vinegar", quantity: "1/4", unit: "cup", notes: "as an alternative to lemon juice" }
    ],
    steps: [
      { order: 1, instruction: "Line a large colander with a double layer of cheesecloth and place it over a large bowl." },
      { order: 2, instruction: "In a large, heavy-bottomed pot, combine milk, heavy cream (if using), and salt." },
      { order: 3, instruction: "Heat the mixture over medium heat, stirring occasionally to prevent scorching." },
      { order: 4, instruction: "Insert a candy or digital thermometer and heat until the mixture reaches 185°F (85°C)." },
      { order: 5, instruction: "Remove from heat and stir in lemon juice or vinegar. Stir gently for 1-2 minutes. The mixture should begin to curdle immediately." },
      { order: 6, instruction: "Let the mixture sit undisturbed for 10 minutes to allow the curds to fully separate from the whey." },
      { order: 7, instruction: "Carefully pour the mixture into the cheesecloth-lined colander. The curds will collect in the cheesecloth and the whey will drain into the bowl." },
      { order: 8, instruction: "For a creamier ricotta, drain for about 20-30 minutes. For a firmer texture, drain for 1-2 hours." },
      { order: 9, instruction: "Transfer the ricotta to an airtight container. It can be used immediately or refrigerated for up to 5 days." },
      { order: 10, instruction: "The leftover whey can be saved for other uses, such as bread making or as a liquid in smoothies." }
    ],
    cookingVessel: "Heavy-Bottomed Pot",
    prepTime: 10,
    cookTime: 30,
    servings: 16,
    difficulty: "Medium",
    mealType: "Other",
    cuisine: "Italian",
    categories: ["Cheese", "Homemade Basics"],
    dietaryCategories: ["Vegetarian", "Gluten-Free"],
    tags: ["ricotta", "cheese", "homemade", "fresh", "versatile"],
    imageUrl: "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d"
  },
  {
    title: "Homemade Preserved Lemons",
    description: "Salt-cured lemons that develop a unique, intense flavor and soft texture over time, adding bright, complex notes to Moroccan tagines, salads, dressings, and countless other dishes.",
    ingredients: [
      { name: "lemons", quantity: "8-10", unit: "", notes: "organic, scrubbed clean" },
      { name: "kosher salt", quantity: "1/2", unit: "cup", notes: "plus more as needed" },
      { name: "fresh lemon juice", quantity: "1/2", unit: "cup", notes: "as needed" },
      { name: "bay leaves", quantity: "2", unit: "", notes: "optional" },
      { name: "cinnamon stick", quantity: "1", unit: "", notes: "optional" },
      { name: "black peppercorns", quantity: "1", unit: "tablespoon", notes: "optional" },
      { name: "coriander seeds", quantity: "1", unit: "tablespoon", notes: "optional" },
      { name: "cloves", quantity: "4", unit: "", notes: "optional" }
    ],
    steps: [
      { order: 1, instruction: "Sterilize a large glass jar with a tight-fitting lid by washing with hot, soapy water and rinsing thoroughly, or running through a dishwasher cycle." },
      { order: 2, instruction: "Cut off any stems from the lemons and trim about 1/4 inch from each end." },
      { order: 3, instruction: "Stand each lemon on end and make two deep cuts downward to form an X, cutting almost but not completely through (about 3/4 of the way down)." },
      { order: 4, instruction: "Open each lemon slightly and pack the cuts generously with kosher salt, using about 1-2 tablespoons per lemon." },
      { order: 5, instruction: "Place about 2 tablespoons of salt in the bottom of the sterilized jar." },
      { order: 6, instruction: "Pack the salted lemons into the jar, pressing down firmly to release some juice. Add any optional spices between layers if using." },
      { order: 7, instruction: "Continue layering lemons and pressing down until the jar is nearly full." },
      { order: 8, instruction: "If needed, add enough fresh lemon juice to completely cover the lemons." },
      { order: 9, instruction: "Seal the jar tightly and let it sit at room temperature for 3-4 days, turning the jar upside down occasionally to distribute the salt and juice." },
      { order: 10, instruction: "After the initial period, transfer the jar to the refrigerator and let cure for at least 3-4 weeks before using. The longer they cure, the more developed the flavor will be." },
      { order: 11, instruction: "To use, remove a preserved lemon from the jar, rinse under cold water to remove excess salt if desired, and separate the peel from the flesh." },
      { order: 12, instruction: "The peel is most commonly used in recipes, finely chopped or sliced, though the flesh can also be used in some applications." },
      { order: 13, instruction: "Preserved lemons will keep in the refrigerator for up to 1 year." }
    ],
    cookingVessel: "Glass Jar",
    prepTime: 30,
    cookTime: 0,
    servings: 24,
    difficulty: "Easy",
    mealType: "Other",
    cuisine: "Moroccan",
    categories: ["Preserves", "Condiments"],
    dietaryCategories: ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free"],
    tags: ["preserved lemons", "Moroccan", "condiment", "fermented", "long-term project"],
    imageUrl: "https://images.unsplash.com/photo-1587049352851-8d4e89133924"
  },
  {
    title: "Homemade Kombucha",
    description: "A fermented, lightly effervescent tea drink with probiotic benefits that can be flavored in countless ways for a refreshing, tangy beverage that's both healthy and cost-effective to make at home.",
    ingredients: [
      { name: "filtered water", quantity: "14", unit: "cups", notes: "divided" },
      { name: "granulated sugar", quantity: "1", unit: "cup" },
      { name: "black or green tea bags", quantity: "8", unit: "", notes: "or 2 tablespoons loose leaf tea" },
      { name: "SCOBY", quantity: "1", unit: "", notes: "symbiotic culture of bacteria and yeast" },
      { name: "starter tea", quantity: "2", unit: "cups", notes: "from previous batch or store-bought unpasteurized, unflavored kombucha" },
      { name: "fruit juice", quantity: "to taste", unit: "", notes: "optional, for flavoring" },
      { name: "fresh fruit", quantity: "to taste", unit: "", notes: "optional, for flavoring" },
      { name: "herbs", quantity: "to taste", unit: "", notes: "optional, for flavoring" },
      { name: "glass brewing vessel", quantity: "1", unit: "1-gallon", notes: "wide-mouth jar" },
      { name: "tightly woven cloth", quantity: "1", unit: "", notes: "or coffee filter" },
      { name: "rubber band", quantity: "1", unit: "large" },
      { name: "glass bottles", quantity: "6-8", unit: "", notes: "with tight-fitting lids for second fermentation" }
    ],
    steps: [
      { order: 1, instruction: "Bring 4 cups of water to a boil in a large pot." },
      { order: 2, instruction: "Remove from heat and add sugar, stirring until completely dissolved." },
      { order: 3, instruction: "Add tea bags or loose tea and steep for 15-20 minutes." },
      { order: 4, instruction: "Remove tea bags or strain out loose tea leaves." },
      { order: 5, instruction: "Add remaining 10 cups of room temperature water to cool the tea mixture." },
      { order: 6, instruction: "Check that the tea has cooled to room temperature (68-85°F). Hot tea will kill the SCOBY." },
      { order: 7, instruction: "Pour the cooled sweet tea into a clean glass brewing vessel." },
      { order: 8, instruction: "Add the starter tea, which helps create an acidic environment that protects against harmful bacteria during the initial fermentation." },
      { order: 9, instruction: "With clean hands, gently place the SCOBY on top of the liquid. It may float, sink, or hover in the middle—all are normal." },
      { order: 10, instruction: "Cover the jar with a tightly woven cloth or coffee filter and secure with a rubber band. This allows the mixture to breathe while keeping out contaminants." },
      { order: 11, instruction: "Place the jar in a warm, dark place away from direct sunlight, with good air circulation. Ideal temperature is 75-85°F." },
      { order: 12, instruction: "Allow to ferment for 7-14 days, depending on your taste preference and ambient temperature. Warmer temperatures speed up fermentation." },
      { order: 13, instruction: "After 7 days, start tasting the kombucha daily using a straw. It should be tangy and slightly sweet. The longer it ferments, the more vinegar-like it becomes." },
      { order: 14, instruction: "When it reaches your desired flavor, prepare for bottling. Reserve 2 cups of the kombucha as starter tea for your next batch." },
      { order: 15, instruction: "For a second fermentation (optional): Fill glass bottles with kombucha, leaving 1-2 inches of headspace. Add any desired flavorings like fruit juice or herbs." },
      { order: 16, instruction: "Seal bottles tightly and let sit at room temperature for 1-3 days to build carbonation." },
      { order: 17, instruction: "Refrigerate bottles to slow fermentation and carbonation. Always open bottles carefully as pressure can build up." },
      { order: 18, instruction: "Start a new batch with the reserved SCOBY and starter tea." }
    ],
    cookingVessel: "Glass Brewing Vessel",
    prepTime: 30,
    cookTime: 0,
    servings: 16,
    difficulty: "Medium",
    mealType: "Other",
    cuisine: "Global",
    categories: ["Fermented Drinks", "Probiotic Foods"],
    dietaryCategories: ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free"],
    tags: ["kombucha", "fermented", "probiotic", "tea", "homemade"],
    imageUrl: "https://images.unsplash.com/photo-1595983239571-3c50ee7bdf30"
  },
  {
    title: "Homemade Sourdough Starter",
    description: "A living culture of wild yeast and beneficial bacteria that serves as a natural leavening agent for bread, pancakes, and other baked goods, imparting complex flavor and improved digestibility.",
    ingredients: [
      { name: "all-purpose flour or bread flour", quantity: "5", unit: "cups", notes: "total, over several days" },
      { name: "whole wheat flour", quantity: "1", unit: "cup", notes: "for initial feeding" },
      { name: "filtered water", quantity: "6", unit: "cups", notes: "total, room temperature, over several days" },
      { name: "glass jar", quantity: "1", unit: "quart-sized", notes: "with loose-fitting lid or cloth cover" }
    ],
    steps: [
      { order: 1, instruction: "Day 1: In a clean glass jar, combine 1/2 cup whole wheat flour (which contains more natural yeast than all-purpose) and 1/2 cup room temperature filtered water. Stir vigorously until smooth." },
      { order: 2, instruction: "Cover the jar with a cloth or loose-fitting lid to allow air circulation while keeping contaminants out." },
      { order: 3, instruction: "Place the jar in a warm spot in your kitchen (70-75°F is ideal). Mark the level of the mixture on the jar with a rubber band or marker." },
      { order: 4, instruction: "Day 2: You may or may not see activity. Regardless, discard half of the mixture (about 1/2 cup)." },
      { order: 5, instruction: "Add 1/2 cup all-purpose flour and 1/2 cup room temperature filtered water. Stir vigorously until smooth." },
      { order: 6, instruction: "Cover and return to the warm spot. Mark the new level." },
      { order: 7, instruction: "Day 3: Repeat the process from Day 2. You might start to see some bubbles and detect a slightly sour smell." },
      { order: 8, instruction: "Day 4: Repeat the process from Day 2. The mixture should be showing more signs of life with increased bubbling and a stronger smell." },
      { order: 9, instruction: "Day 5: Repeat the process from Day 2. By now, the starter should be quite active, doubling in volume within 4-8 hours after feeding." },
      { order: 10, instruction: "Days 6-7: Continue the daily feeding process. The starter should have a pleasant, yeasty smell and be reliably doubling in size between feedings." },
      { order: 11, instruction: "Once your starter consistently doubles in size within 4-8 hours of feeding and has a pleasant, yeasty aroma, it's ready to use in baking." },
      { order: 12, instruction: "To maintain your starter: Feed it once a day if kept at room temperature, or once a week if refrigerated." },
      { order: 13, instruction: "For room temperature maintenance: Discard all but 1/4 cup starter, then feed with 1/2 cup flour and 1/2 cup water." },
      { order: 14, instruction: "For refrigerator maintenance: Feed as above, let sit at room temperature for 2 hours, then refrigerate. Before using, remove from refrigerator, feed, and let activate for 8-12 hours." }
    ],
    cookingVessel: "Glass Jar",
    prepTime: 10,
    cookTime: 0,
    servings: 16,
    difficulty: "Medium",
    mealType: "Other",
    cuisine: "Universal",
    categories: ["Fermented Foods", "Baking Basics"],
    dietaryCategories: ["Vegetarian", "Vegan", "Dairy-Free"],
    tags: ["sourdough", "starter", "fermented", "bread", "natural leavening"],
    imageUrl: "https://images.unsplash.com/photo-1585478259715-876a6a81fc08"
  }
];

export default otherRecipes;
