// Snack Recipes for WhatAboutDinner App
// 20 detailed snack recipes with all required fields

const snackRecipes = [
  {
    title: "Homemade Trail Mix",
    description: "A customizable blend of nuts, seeds, dried fruits, and chocolate for a satisfying, energy-boosting snack that's perfect for on-the-go or between meals.",
    ingredients: [
      { name: "almonds", quantity: "1", unit: "cup", notes: "raw or roasted" },
      { name: "cashews", quantity: "1", unit: "cup", notes: "raw or roasted" },
      { name: "walnuts", quantity: "1/2", unit: "cup", notes: "halves and pieces" },
      { name: "pumpkin seeds", quantity: "1/2", unit: "cup", notes: "shelled" },
      { name: "sunflower seeds", quantity: "1/4", unit: "cup", notes: "shelled" },
      { name: "dried cranberries", quantity: "1/2", unit: "cup" },
      { name: "dried apricots", quantity: "1/2", unit: "cup", notes: "chopped" },
      { name: "banana chips", quantity: "1/2", unit: "cup" },
      { name: "dark chocolate chips", quantity: "1/3", unit: "cup" },
      { name: "coconut flakes", quantity: "1/4", unit: "cup", notes: "unsweetened" },
      { name: "sea salt", quantity: "1/2", unit: "teaspoon", notes: "optional" },
      { name: "cinnamon", quantity: "1/2", unit: "teaspoon", notes: "optional" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 350°F (175°C) if using raw nuts and seeds." },
      { order: 2, instruction: "Spread raw nuts and seeds on a baking sheet in a single layer." },
      { order: 3, instruction: "Toast in the oven for 8-10 minutes, stirring halfway through, until lightly golden and fragrant. Let cool completely. (Skip this step if using pre-roasted nuts.)" },
      { order: 4, instruction: "In a large bowl, combine cooled toasted nuts and seeds with dried cranberries, chopped apricots, banana chips, chocolate chips, and coconut flakes." },
      { order: 5, instruction: "If using, sprinkle with sea salt and cinnamon, then toss to combine." },
      { order: 6, instruction: "Store in an airtight container at room temperature for up to 2 weeks, or in the refrigerator for up to 1 month." }
    ],
    cookingVessel: "Baking Sheet",
    prepTime: 10,
    cookTime: 10,
    servings: 12,
    difficulty: "Easy",
    mealType: "Snack",
    cuisine: "American",
    categories: ["Nuts and Seeds", "Energy Snacks"],
    dietaryCategories: ["Vegetarian", "Gluten-Free", "Dairy-Free (without chocolate)"],
    tags: ["trail mix", "nuts", "dried fruit", "energy", "portable"],
    imageUrl: "https://images.unsplash.com/photo-1599599810769-bcde5a160d32"
  },
  {
    title: "Avocado Toast with Everything Bagel Seasoning",
    description: "Creamy mashed avocado spread on toasted bread and topped with zesty everything bagel seasoning for a quick, nutritious, and satisfying snack.",
    ingredients: [
      { name: "ripe avocado", quantity: "1", unit: "large" },
      { name: "bread", quantity: "2", unit: "slices", notes: "sourdough, whole grain, or your preference" },
      { name: "lemon juice", quantity: "1", unit: "teaspoon", notes: "fresh" },
      { name: "everything bagel seasoning", quantity: "1", unit: "tablespoon" },
      { name: "red pepper flakes", quantity: "1/4", unit: "teaspoon", notes: "optional" },
      { name: "salt", quantity: "1/8", unit: "teaspoon", notes: "to taste" },
      { name: "black pepper", quantity: "1/8", unit: "teaspoon", notes: "to taste" },
      { name: "extra virgin olive oil", quantity: "1", unit: "teaspoon", notes: "for drizzling" },
      { name: "microgreens", quantity: "1/4", unit: "cup", notes: "optional, for garnish" }
    ],
    steps: [
      { order: 1, instruction: "Toast the bread slices to your desired level of crispness." },
      { order: 2, instruction: "Cut the avocado in half, remove the pit, and scoop the flesh into a small bowl." },
      { order: 3, instruction: "Add lemon juice, salt, and pepper to the avocado. Mash with a fork to your preferred consistency (chunky or smooth)." },
      { order: 4, instruction: "Spread the mashed avocado evenly over the toasted bread slices." },
      { order: 5, instruction: "Sprinkle everything bagel seasoning over the avocado." },
      { order: 6, instruction: "Add red pepper flakes if desired for some heat." },
      { order: 7, instruction: "Drizzle with a small amount of olive oil." },
      { order: 8, instruction: "Top with microgreens if using." },
      { order: 9, instruction: "Serve immediately." }
    ],
    cookingVessel: "Toaster",
    prepTime: 5,
    cookTime: 2,
    servings: 2,
    difficulty: "Easy",
    mealType: "Snack",
    cuisine: "American",
    categories: ["Toast", "Healthy Snacks"],
    dietaryCategories: ["Vegetarian", "Vegan", "Dairy-Free"],
    tags: ["avocado", "toast", "quick", "healthy", "plant-based"],
    imageUrl: "https://images.unsplash.com/photo-1588137378633-dea1336ce1e2"
  },
  {
    title: "Crispy Roasted Chickpeas",
    description: "Crunchy, seasoned chickpeas roasted to perfection for a protein-packed, fiber-rich snack that satisfies savory cravings without the guilt.",
    ingredients: [
      { name: "canned chickpeas", quantity: "2", unit: "15-ounce cans", notes: "drained and rinsed" },
      { name: "olive oil", quantity: "2", unit: "tablespoons" },
      { name: "garlic powder", quantity: "1", unit: "teaspoon" },
      { name: "ground cumin", quantity: "1", unit: "teaspoon" },
      { name: "smoked paprika", quantity: "1", unit: "teaspoon" },
      { name: "salt", quantity: "1", unit: "teaspoon" },
      { name: "black pepper", quantity: "1/4", unit: "teaspoon" },
      { name: "cayenne pepper", quantity: "1/8", unit: "teaspoon", notes: "optional, for heat" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 400°F (200°C). Line a large baking sheet with parchment paper." },
      { order: 2, instruction: "Drain and rinse the chickpeas. Place them on a clean kitchen towel or paper towels and pat dry thoroughly. Remove any loose skins." },
      { order: 3, instruction: "Transfer dried chickpeas to a large bowl. Add olive oil and toss to coat evenly." },
      { order: 4, instruction: "In a small bowl, mix together garlic powder, cumin, smoked paprika, salt, black pepper, and cayenne pepper (if using)." },
      { order: 5, instruction: "Sprinkle the spice mixture over the chickpeas and toss until evenly coated." },
      { order: 6, instruction: "Spread the chickpeas in a single layer on the prepared baking sheet." },
      { order: 7, instruction: "Roast for 20-30 minutes, shaking the pan halfway through, until chickpeas are golden brown and crispy." },
      { order: 8, instruction: "Remove from oven and let cool completely on the baking sheet. They will become crispier as they cool." },
      { order: 9, instruction: "Store in an airtight container at room temperature for up to 3-4 days." }
    ],
    cookingVessel: "Baking Sheet",
    prepTime: 10,
    cookTime: 30,
    servings: 6,
    difficulty: "Easy",
    mealType: "Snack",
    cuisine: "Mediterranean",
    categories: ["Roasted Snacks", "Legumes"],
    dietaryCategories: ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free"],
    tags: ["chickpeas", "roasted", "crunchy", "protein", "healthy"],
    imageUrl: "https://images.unsplash.com/photo-1649252726777-e53c4e11836b"
  },
  {
    title: "Greek Yogurt Parfait",
    description: "Layers of creamy Greek yogurt, crunchy granola, and fresh berries create a balanced snack that's both satisfying and nutritious, with protein, fiber, and antioxidants.",
    ingredients: [
      { name: "Greek yogurt", quantity: "2", unit: "cups", notes: "plain or vanilla" },
      { name: "honey", quantity: "2", unit: "tablespoons", notes: "or maple syrup" },
      { name: "granola", quantity: "1", unit: "cup" },
      { name: "fresh strawberries", quantity: "1", unit: "cup", notes: "sliced" },
      { name: "fresh blueberries", quantity: "1/2", unit: "cup" },
      { name: "banana", quantity: "1", unit: "medium", notes: "sliced" },
      { name: "chia seeds", quantity: "1", unit: "tablespoon", notes: "optional" },
      { name: "chopped nuts", quantity: "2", unit: "tablespoons", notes: "optional" },
      { name: "ground cinnamon", quantity: "1/4", unit: "teaspoon", notes: "optional" }
    ],
    steps: [
      { order: 1, instruction: "If using plain Greek yogurt, stir in honey or maple syrup to sweeten to taste." },
      { order: 2, instruction: "In two serving glasses or bowls, begin layering by adding 1/4 cup of Greek yogurt to the bottom of each." },
      { order: 3, instruction: "Add a layer of granola (about 2 tablespoons) over the yogurt." },
      { order: 4, instruction: "Add a layer of mixed berries and banana slices." },
      { order: 5, instruction: "Repeat the layers: yogurt, granola, and fruit." },
      { order: 6, instruction: "Top with a final layer of yogurt." },
      { order: 7, instruction: "Sprinkle with remaining granola, chia seeds, and chopped nuts if using." },
      { order: 8, instruction: "Dust with cinnamon if desired." },
      { order: 9, instruction: "Serve immediately, or refrigerate for up to 2 hours (note that the granola will soften over time)." }
    ],
    cookingVessel: "Serving Glasses",
    prepTime: 10,
    cookTime: 0,
    servings: 2,
    difficulty: "Easy",
    mealType: "Snack",
    cuisine: "American",
    categories: ["Yogurt Snacks", "Parfaits"],
    dietaryCategories: ["Vegetarian", "Gluten-Free (with GF granola)"],
    tags: ["yogurt", "parfait", "berries", "protein", "no-cook"],
    imageUrl: "https://images.unsplash.com/photo-1488477181946-6428a0291777"
  },
  {
    title: "Homemade Hummus with Vegetable Sticks",
    description: "Smooth, creamy homemade hummus served with crisp vegetable sticks for a nutritious, protein-rich snack that's perfect for dipping and satisfying hunger between meals.",
    ingredients: [
      { name: "canned chickpeas", quantity: "1", unit: "15-ounce can", notes: "drained and rinsed" },
      { name: "tahini", quantity: "1/4", unit: "cup" },
      { name: "lemon juice", quantity: "3", unit: "tablespoons", notes: "fresh" },
      { name: "garlic", quantity: "2", unit: "cloves", notes: "minced" },
      { name: "olive oil", quantity: "2", unit: "tablespoons", notes: "plus more for drizzling" },
      { name: "ground cumin", quantity: "1/2", unit: "teaspoon" },
      { name: "salt", quantity: "1/2", unit: "teaspoon", notes: "or to taste" },
      { name: "ice water", quantity: "2", unit: "tablespoons" },
      { name: "paprika", quantity: "1/4", unit: "teaspoon", notes: "for garnish" },
      { name: "fresh parsley", quantity: "1", unit: "tablespoon", notes: "chopped, for garnish" },
      { name: "carrot sticks", quantity: "1", unit: "cup" },
      { name: "cucumber sticks", quantity: "1", unit: "cup" },
      { name: "bell pepper strips", quantity: "1", unit: "cup", notes: "assorted colors" },
      { name: "celery sticks", quantity: "1", unit: "cup" }
    ],
    steps: [
      { order: 1, instruction: "In a food processor, combine chickpeas, tahini, lemon juice, garlic, olive oil, cumin, and salt." },
      { order: 2, instruction: "Process until smooth, about 1-2 minutes, stopping to scrape down the sides as needed." },
      { order: 3, instruction: "With the food processor running, slowly add ice water through the feed tube until the hummus reaches your desired consistency." },
      { order: 4, instruction: "Taste and adjust seasonings if needed, adding more salt or lemon juice as desired." },
      { order: 5, instruction: "Transfer hummus to a serving bowl. Using the back of a spoon, create a shallow well in the center." },
      { order: 6, instruction: "Drizzle with additional olive oil and sprinkle with paprika and chopped parsley." },
      { order: 7, instruction: "Arrange carrot sticks, cucumber sticks, bell pepper strips, and celery sticks on a platter around the hummus bowl." },
      { order: 8, instruction: "Serve immediately, or refrigerate hummus in an airtight container for up to 5 days." }
    ],
    cookingVessel: "Food Processor",
    prepTime: 15,
    cookTime: 0,
    servings: 4,
    difficulty: "Easy",
    mealType: "Snack",
    cuisine: "Middle Eastern",
    categories: ["Dips", "Vegetable Snacks"],
    dietaryCategories: ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free"],
    tags: ["hummus", "chickpeas", "dip", "vegetables", "healthy"],
    imageUrl: "https://images.unsplash.com/photo-1637949385162-10de67f64f53"
  },
  {
    title: "Baked Sweet Potato Chips",
    description: "Thin slices of sweet potato baked until crispy and seasoned to perfection for a healthier alternative to store-bought potato chips that still satisfies crunchy cravings.",
    ingredients: [
      { name: "sweet potatoes", quantity: "2", unit: "medium", notes: "scrubbed clean" },
      { name: "olive oil", quantity: "2", unit: "tablespoons" },
      { name: "salt", quantity: "1", unit: "teaspoon" },
      { name: "garlic powder", quantity: "1/2", unit: "teaspoon", notes: "optional" },
      { name: "paprika", quantity: "1/2", unit: "teaspoon", notes: "optional" },
      { name: "black pepper", quantity: "1/4", unit: "teaspoon", notes: "optional" },
      { name: "fresh rosemary", quantity: "1", unit: "teaspoon", notes: "finely chopped, optional" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 250°F (120°C). Line two large baking sheets with parchment paper." },
      { order: 2, instruction: "Using a mandoline slicer or very sharp knife, slice sweet potatoes into very thin rounds, about 1/16-inch thick." },
      { order: 3, instruction: "Place sweet potato slices in a large bowl. Add olive oil and toss to coat evenly." },
      { order: 4, instruction: "In a small bowl, mix together salt, garlic powder, paprika, black pepper, and rosemary (if using)." },
      { order: 5, instruction: "Sprinkle the seasoning mixture over the oiled sweet potato slices and toss to distribute evenly." },
      { order: 6, instruction: "Arrange the slices in a single layer on the prepared baking sheets, making sure they don't overlap." },
      { order: 7, instruction: "Bake for 1 hour, then flip the chips over." },
      { order: 8, instruction: "Continue baking for another 30-45 minutes, checking frequently to prevent burning, until chips are crisp and edges start to curl slightly." },
      { order: 9, instruction: "Remove from oven and let cool completely on the baking sheets. They will crisp up further as they cool." },
      { order: 10, instruction: "Store in an airtight container at room temperature for up to 3 days." }
    ],
    cookingVessel: "Baking Sheet",
    prepTime: 15,
    cookTime: 105,
    servings: 4,
    difficulty: "Medium",
    mealType: "Snack",
    cuisine: "American",
    categories: ["Chips", "Baked Snacks"],
    dietaryCategories: ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free"],
    tags: ["sweet potato", "chips", "baked", "healthy", "crunchy"],
    imageUrl: "https://images.unsplash.com/photo-1599490659213-e2b9527bd087"
  },
  {
    title: "Caprese Skewers",
    description: "Bite-sized skewers featuring fresh mozzarella, cherry tomatoes, and basil drizzled with balsamic glaze for an elegant, no-cook snack that's perfect for entertaining or a quick protein boost.",
    ingredients: [
      { name: "cherry tomatoes", quantity: "1", unit: "pint" },
      { name: "fresh mozzarella pearls", quantity: "8", unit: "ounces", notes: "or mozzarella ball cut into 1-inch cubes" },
      { name: "fresh basil leaves", quantity: "1", unit: "bunch", notes: "large leaves torn in half" },
      { name: "extra virgin olive oil", quantity: "2", unit: "tablespoons" },
      { name: "balsamic glaze", quantity: "2", unit: "tablespoons", notes: "store-bought or homemade" },
      { name: "salt", quantity: "1/4", unit: "teaspoon", notes: "flaky sea salt preferred" },
      { name: "black pepper", quantity: "1/4", unit: "teaspoon", notes: "freshly ground" },
      { name: "wooden skewers", quantity: "24", unit: "small", notes: "4-6 inches long" }
    ],
    steps: [
      { order: 1, instruction: "If using wooden skewers, soak in water for 10 minutes to prevent splintering." },
      { order: 2, instruction: "Wash and dry cherry tomatoes and basil leaves." },
      { order: 3, instruction: "Thread the ingredients onto each skewer in this order: cherry tomato, basil leaf (folded if large), mozzarella ball, basil leaf (folded if large), cherry tomato." },
      { order: 4, instruction: "Arrange the prepared skewers on a serving platter." },
      { order: 5, instruction: "Drizzle with extra virgin olive oil and balsamic glaze." },
      { order: 6, instruction: "Sprinkle with salt and freshly ground black pepper." },
      { order: 7, instruction: "Serve immediately, or refrigerate for up to 2 hours before serving." }
    ],
    cookingVessel: "None",
    prepTime: 15,
    cookTime: 0,
    servings: 8,
    difficulty: "Easy",
    mealType: "Snack",
    cuisine: "Italian",
    categories: ["Skewers", "No-Cook Snacks"],
    dietaryCategories: ["Vegetarian", "Gluten-Free"],
    tags: ["caprese", "mozzarella", "tomato", "basil", "appetizer"],
    imageUrl: "https://images.unsplash.com/photo-1625944228741-cf30983ecb91"
  },
  {
    title: "Energy Balls",
    description: "No-bake, nutrient-dense bites made with oats, nut butter, honey, and mix-ins for a portable energy boost that satisfies sweet cravings while providing sustained energy.",
    ingredients: [
      { name: "old-fashioned oats", quantity: "1", unit: "cup" },
      { name: "natural peanut butter", quantity: "1/2", unit: "cup", notes: "or almond butter" },
      { name: "honey", quantity: "1/3", unit: "cup", notes: "or maple syrup for vegan option" },
      { name: "ground flaxseed", quantity: "2", unit: "tablespoons" },
      { name: "chia seeds", quantity: "2", unit: "tablespoons" },
      { name: "mini chocolate chips", quantity: "1/3", unit: "cup", notes: "dark or semi-sweet" },
      { name: "vanilla extract", quantity: "1", unit: "teaspoon" },
      { name: "ground cinnamon", quantity: "1/2", unit: "teaspoon" },
      { name: "salt", quantity: "1/8", unit: "teaspoon" },
      { name: "shredded coconut", quantity: "1/4", unit: "cup", notes: "unsweetened, optional" },
      { name: "dried cranberries", quantity: "1/4", unit: "cup", notes: "optional" }
    ],
    steps: [
      { order: 1, instruction: "In a large bowl, combine oats, peanut butter, honey, ground flaxseed, chia seeds, chocolate chips, vanilla extract, cinnamon, and salt." },
      { order: 2, instruction: "If using, add shredded coconut and dried cranberries." },
      { order: 3, instruction: "Stir until all ingredients are well combined. If the mixture seems too dry, add a bit more peanut butter or honey. If too wet, add more oats." },
      { order: 4, instruction: "Cover the bowl and refrigerate for 30 minutes to make the mixture easier to handle." },
      { order: 5, instruction: "Using a tablespoon or cookie scoop, portion out the mixture and roll between your palms to form 1-inch balls." },
      { order: 6, instruction: "Store in an airtight container in the refrigerator for up to 1 week, or in the freezer for up to 3 months." }
    ],
    cookingVessel: "Mixing Bowl",
    prepTime: 15,
    cookTime: 0,
    servings: 20,
    difficulty: "Easy",
    mealType: "Snack",
    cuisine: "American",
    categories: ["Energy Bites", "No-Bake Snacks"],
    dietaryCategories: ["Vegetarian", "Gluten-Free (with GF oats)"],
    tags: ["energy balls", "protein", "no-bake", "portable", "oats"],
    imageUrl: "https://images.unsplash.com/photo-1490567674331-72de84996c6c"
  },
  {
    title: "Stuffed Dates with Nut Butter and Sea Salt",
    description: "Sweet, chewy dates filled with creamy nut butter and sprinkled with flaky sea salt for a simple yet decadent snack that balances sweet and savory flavors.",
    ingredients: [
      { name: "Medjool dates", quantity: "12", unit: "large" },
      { name: "almond butter", quantity: "1/4", unit: "cup", notes: "or peanut butter, cashew butter" },
      { name: "flaky sea salt", quantity: "1/2", unit: "teaspoon" },
      { name: "dark chocolate", quantity: "2", unit: "ounces", notes: "melted, optional" },
      { name: "chopped pistachios", quantity: "2", unit: "tablespoons", notes: "optional" }
    ],
    steps: [
      { order: 1, instruction: "Using a small knife, make a lengthwise slit in each date and remove the pit." },
      { order: 2, instruction: "Fill each date with about 1 teaspoon of nut butter." },
      { order: 3, instruction: "Arrange the stuffed dates on a serving plate." },
      { order: 4, instruction: "Sprinkle each date with a small pinch of flaky sea salt." },
      { order: 5, instruction: "If using, drizzle with melted dark chocolate and sprinkle with chopped pistachios." },
      { order: 6, instruction: "If chocolate is added, allow it to set in the refrigerator for about 10 minutes." },
      { order: 7, instruction: "Serve immediately, or store in an airtight container in the refrigerator for up to 5 days." }
    ],
    cookingVessel: "None",
    prepTime: 10,
    cookTime: 0,
    servings: 12,
    difficulty: "Easy",
    mealType: "Snack",
    cuisine: "Middle Eastern",
    categories: ["Fruit Snacks", "Sweet Treats"],
    dietaryCategories: ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free"],
    tags: ["dates", "nut butter", "sweet and salty", "no-cook", "natural sweetness"],
    imageUrl: "https://images.unsplash.com/photo-1581400151483-511ae375bd6e"
  },
  {
    title: "Edamame with Sea Salt",
    description: "Steamed young soybeans in the pod, lightly seasoned with sea salt for a protein-rich, fiber-filled snack that's both satisfying and nutritious.",
    ingredients: [
      { name: "frozen edamame in pods", quantity: "1", unit: "pound" },
      { name: "water", quantity: "4", unit: "cups" },
      { name: "sea salt", quantity: "1", unit: "tablespoon", notes: "divided" },
      { name: "lemon wedges", quantity: "1", unit: "lemon", notes: "cut into wedges, optional" },
      { name: "togarashi seasoning", quantity: "1", unit: "teaspoon", notes: "Japanese seven-spice blend, optional" }
    ],
    steps: [
      { order: 1, instruction: "Bring water and 1 teaspoon of sea salt to a boil in a medium saucepan." },
      { order: 2, instruction: "Add the frozen edamame pods and return to a boil." },
      { order: 3, instruction: "Reduce heat to medium and simmer for 5 minutes, or until edamame is tender but still firm." },
      { order: 4, instruction: "Drain the edamame in a colander and rinse under cold water to stop the cooking process." },
      { order: 5, instruction: "Pat dry with paper towels and transfer to a serving bowl." },
      { order: 6, instruction: "Sprinkle with remaining sea salt and toss to coat." },
      { order: 7, instruction: "If using, sprinkle with togarashi seasoning for a spicy kick." },
      { order: 8, instruction: "Serve warm or at room temperature with lemon wedges on the side if desired." },
      { order: 9, instruction: "To eat, squeeze the pods between your teeth to extract the beans, discarding the pods." }
    ],
    cookingVessel: "Saucepan",
    prepTime: 5,
    cookTime: 5,
    servings: 4,
    difficulty: "Easy",
    mealType: "Snack",
    cuisine: "Japanese",
    categories: ["Legume Snacks", "Steamed Snacks"],
    dietaryCategories: ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free"],
    tags: ["edamame", "soybeans", "protein", "japanese", "simple"],
    imageUrl: "https://images.unsplash.com/photo-1564894809611-1742fc40ed80"
  },
  {
    title: "Apple Slices with Honey-Cinnamon Yogurt Dip",
    description: "Crisp apple slices served with a creamy, honey-sweetened yogurt dip spiced with cinnamon for a refreshing, nutritious snack that satisfies sweet cravings.",
    ingredients: [
      { name: "apples", quantity: "2", unit: "medium", notes: "any variety, cored and sliced" },
      { name: "lemon juice", quantity: "1", unit: "tablespoon", notes: "to prevent browning" },
      { name: "Greek yogurt", quantity: "1", unit: "cup", notes: "plain" },
      { name: "honey", quantity: "2", unit: "tablespoons" },
      { name: "ground cinnamon", quantity: "1/2", unit: "teaspoon" },
      { name: "vanilla extract", quantity: "1/4", unit: "teaspoon" },
      { name: "salt", quantity: "1", unit: "pinch" },
      { name: "chopped walnuts", quantity: "2", unit: "tablespoons", notes: "optional, for garnish" }
    ],
    steps: [
      { order: 1, instruction: "Core and slice the apples into wedges or rounds." },
      { order: 2, instruction: "Toss apple slices with lemon juice to prevent browning." },
      { order: 3, instruction: "In a small bowl, combine Greek yogurt, honey, cinnamon, vanilla extract, and salt. Stir until well mixed." },
      { order: 4, instruction: "If using, sprinkle chopped walnuts on top of the yogurt dip." },
      { order: 5, instruction: "Arrange apple slices on a plate or in a bowl with the yogurt dip in the center." },
      { order: 6, instruction: "Serve immediately, or store the dip and apples separately in the refrigerator for up to 3 days." }
    ],
    cookingVessel: "None",
    prepTime: 10,
    cookTime: 0,
    servings: 2,
    difficulty: "Easy",
    mealType: "Snack",
    cuisine: "American",
    categories: ["Fruit Snacks", "Dips"],
    dietaryCategories: ["Vegetarian", "Gluten-Free"],
    tags: ["apple", "yogurt", "dip", "healthy", "quick"],
    imageUrl: "https://images.unsplash.com/photo-1568909344668-6f14a07b56a0"
  },
  {
    title: "Homemade Beef Jerky",
    description: "Lean beef strips marinated in a savory blend of spices and slowly dried for a protein-packed, portable snack with deep flavor and satisfying chew.",
    ingredients: [
      { name: "beef eye of round", quantity: "2", unit: "pounds", notes: "trimmed of all visible fat" },
      { name: "soy sauce", quantity: "1/2", unit: "cup", notes: "low sodium" },
      { name: "Worcestershire sauce", quantity: "1/4", unit: "cup" },
      { name: "liquid smoke", quantity: "1", unit: "teaspoon", notes: "hickory flavor" },
      { name: "brown sugar", quantity: "3", unit: "tablespoons" },
      { name: "garlic powder", quantity: "2", unit: "teaspoons" },
      { name: "onion powder", quantity: "2", unit: "teaspoons" },
      { name: "black pepper", quantity: "1", unit: "tablespoon", notes: "freshly ground" },
      { name: "red pepper flakes", quantity: "1", unit: "teaspoon", notes: "optional, for heat" },
      { name: "smoked paprika", quantity: "1", unit: "teaspoon" }
    ],
    steps: [
      { order: 1, instruction: "Freeze the beef for about 1-2 hours until firm but not completely frozen, which makes it easier to slice thinly." },
      { order: 2, instruction: "Using a sharp knife, slice the beef against the grain into 1/8 to 1/4-inch thick strips." },
      { order: 3, instruction: "In a large bowl or ziplock bag, combine soy sauce, Worcestershire sauce, liquid smoke, brown sugar, garlic powder, onion powder, black pepper, red pepper flakes (if using), and smoked paprika." },
      { order: 4, instruction: "Add the beef strips to the marinade, making sure each piece is coated. Cover or seal and refrigerate for at least 6 hours or overnight, turning occasionally." },
      { order: 5, instruction: "Preheat oven to 175°F (80°C) or the lowest setting. Line baking sheets with aluminum foil and place wire racks on top." },
      { order: 6, instruction: "Remove beef from marinade and pat dry with paper towels." },
      { order: 7, instruction: "Arrange beef strips in a single layer on the wire racks, making sure they don't touch." },
      { order: 8, instruction: "Bake for 3-4 hours, rotating the baking sheets and flipping the jerky halfway through, until the jerky is dry but still slightly pliable." },
      { order: 9, instruction: "Let cool completely before storing in an airtight container. Properly dried jerky will keep at room temperature for 1-2 weeks, or refrigerated for up to 3 months." }
    ],
    cookingVessel: "Oven with Wire Racks",
    prepTime: 30,
    cookTime: 240,
    servings: 16,
    difficulty: "Medium",
    mealType: "Snack",
    cuisine: "American",
    categories: ["Meat Snacks", "Dried Snacks"],
    dietaryCategories: ["Dairy-Free", "Gluten-Free (with GF soy sauce)"],
    tags: ["jerky", "beef", "protein", "portable", "low-carb"],
    imageUrl: "https://images.unsplash.com/photo-1626073398072-1d7991af7b7e"
  },
  {
    title: "Cucumber Rounds with Herbed Cream Cheese",
    description: "Fresh cucumber slices topped with herb-infused cream cheese for a light, refreshing snack that's perfect for warm days or when you want something crisp and satisfying.",
    ingredients: [
      { name: "English cucumber", quantity: "1", unit: "large" },
      { name: "cream cheese", quantity: "8", unit: "ounces", notes: "softened" },
      { name: "fresh dill", quantity: "2", unit: "tablespoons", notes: "chopped" },
      { name: "fresh chives", quantity: "2", unit: "tablespoons", notes: "chopped" },
      { name: "lemon zest", quantity: "1", unit: "teaspoon" },
      { name: "lemon juice", quantity: "1", unit: "teaspoon" },
      { name: "garlic", quantity: "1", unit: "clove", notes: "minced" },
      { name: "salt", quantity: "1/4", unit: "teaspoon" },
      { name: "black pepper", quantity: "1/8", unit: "teaspoon" },
      { name: "cherry tomatoes", quantity: "6", unit: "", notes: "halved, for garnish" },
      { name: "microgreens", quantity: "1/4", unit: "cup", notes: "for garnish, optional" }
    ],
    steps: [
      { order: 1, instruction: "Wash and slice the cucumber into 1/4-inch thick rounds. If desired, use a vegetable peeler to create decorative stripes on the cucumber skin before slicing." },
      { order: 2, instruction: "Place cucumber rounds on paper towels to remove excess moisture." },
      { order: 3, instruction: "In a medium bowl, combine softened cream cheese, chopped dill, chopped chives, lemon zest, lemon juice, minced garlic, salt, and pepper. Mix until well combined." },
      { order: 4, instruction: "Transfer the herbed cream cheese to a piping bag fitted with a star tip, or use a small spoon." },
      { order: 5, instruction: "Arrange cucumber rounds on a serving platter." },
      { order: 6, instruction: "Pipe or spoon about 1 teaspoon of the herbed cream cheese onto each cucumber round." },
      { order: 7, instruction: "Garnish with halved cherry tomatoes and microgreens if using." },
      { order: 8, instruction: "Serve immediately, or refrigerate for up to 2 hours before serving." }
    ],
    cookingVessel: "None",
    prepTime: 15,
    cookTime: 0,
    servings: 6,
    difficulty: "Easy",
    mealType: "Snack",
    cuisine: "American",
    categories: ["Vegetable Snacks", "Canapes"],
    dietaryCategories: ["Vegetarian", "Gluten-Free", "Low-Carb"],
    tags: ["cucumber", "cream cheese", "fresh", "light", "herbs"],
    imageUrl: "https://images.unsplash.com/photo-1533070738812-2ffd5c3bfa12"
  },
  {
    title: "Baked Kale Chips",
    description: "Crispy, nutrient-packed kale leaves baked with olive oil and seasonings for a light, crunchy snack that's a healthier alternative to traditional potato chips.",
    ingredients: [
      { name: "kale", quantity: "1", unit: "bunch", notes: "stems removed, torn into bite-sized pieces" },
      { name: "olive oil", quantity: "1", unit: "tablespoon" },
      { name: "salt", quantity: "1/2", unit: "teaspoon" },
      { name: "garlic powder", quantity: "1/4", unit: "teaspoon", notes: "optional" },
      { name: "nutritional yeast", quantity: "1", unit: "tablespoon", notes: "optional, for cheesy flavor" },
      { name: "red pepper flakes", quantity: "1/8", unit: "teaspoon", notes: "optional, for heat" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 300°F (150°C). Line two large baking sheets with parchment paper." },
      { order: 2, instruction: "Wash kale leaves thoroughly and dry completely using a salad spinner or paper towels. Any moisture left will create steam and prevent the kale from getting crispy." },
      { order: 3, instruction: "Remove the tough stems and tear the leaves into bite-sized pieces." },
      { order: 4, instruction: "Place kale pieces in a large bowl and drizzle with olive oil." },
      { order: 5, instruction: "Using your hands, massage the oil into the kale for 2-3 minutes until all pieces are lightly coated and the kale begins to soften slightly." },
      { order: 6, instruction: "Sprinkle with salt, garlic powder, nutritional yeast, and red pepper flakes (if using). Toss to distribute evenly." },
      { order: 7, instruction: "Arrange kale in a single layer on the prepared baking sheets, making sure pieces don't overlap." },
      { order: 8, instruction: "Bake for 15-20 minutes, rotating the pans halfway through, until the edges are slightly browned but not burnt." },
      { order: 9, instruction: "Let cool completely on the baking sheets. The chips will crisp up further as they cool." },
      { order: 10, instruction: "Store in an airtight container at room temperature for up to 3 days." }
    ],
    cookingVessel: "Baking Sheet",
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    difficulty: "Easy",
    mealType: "Snack",
    cuisine: "American",
    categories: ["Vegetable Chips", "Baked Snacks"],
    dietaryCategories: ["Vegetarian", "Vegan", "Gluten-Free", "Dairy-Free", "Low-Carb"],
    tags: ["kale", "chips", "healthy", "crispy", "superfood"],
    imageUrl: "https://images.unsplash.com/photo-1527324688151-0e627063f2b1"
  },
  {
    title: "Deviled Eggs",
    description: "Classic deviled eggs featuring creamy, seasoned egg yolk filling piped into halved egg whites for a protein-rich, satisfying snack that's perfect for gatherings or meal prep.",
    ingredients: [
      { name: "eggs", quantity: "6", unit: "large" },
      { name: "mayonnaise", quantity: "3", unit: "tablespoons" },
      { name: "Dijon mustard", quantity: "1", unit: "teaspoon" },
      { name: "white vinegar", quantity: "1", unit: "teaspoon" },
      { name: "salt", quantity: "1/4", unit: "teaspoon" },
      { name: "black pepper", quantity: "1/8", unit: "teaspoon" },
      { name: "paprika", quantity: "1/2", unit: "teaspoon", notes: "plus more for garnish" },
      { name: "fresh chives", quantity: "1", unit: "tablespoon", notes: "finely chopped, plus more for garnish" },
      { name: "pickle relish", quantity: "1", unit: "teaspoon", notes: "optional" }
    ],
    steps: [
      { order: 1, instruction: "Place eggs in a single layer in a saucepan and cover with water by 1 inch." },
      { order: 2, instruction: "Bring to a boil over medium-high heat. Once boiling, remove from heat, cover, and let sit for 12 minutes." },
      { order: 3, instruction: "Transfer eggs to an ice bath and let cool for 5 minutes." },
      { order: 4, instruction: "Peel eggs and cut in half lengthwise." },
      { order: 5, instruction: "Carefully remove yolks and place them in a medium bowl." },
      { order: 6, instruction: "Arrange the egg white halves on a serving platter." },
      { order: 7, instruction: "Mash the yolks with a fork until smooth." },
      { order: 8, instruction: "Add mayonnaise, Dijon mustard, white vinegar, salt, pepper, paprika, chopped chives, and pickle relish (if using). Mix until creamy and well combined." },
      { order: 9, instruction: "Transfer the yolk mixture to a piping bag fitted with a star tip, or use a small spoon." },
      { order: 10, instruction: "Pipe or spoon the filling into the egg white halves." },
      { order: 11, instruction: "Sprinkle with additional paprika and garnish with extra chives." },
      { order: 12, instruction: "Refrigerate until ready to serve, up to 24 hours." }
    ],
    cookingVessel: "Saucepan",
    prepTime: 15,
    cookTime: 12,
    servings: 12,
    difficulty: "Easy",
    mealType: "Snack",
    cuisine: "American",
    categories: ["Egg Snacks", "Protein Snacks"],
    dietaryCategories: ["Vegetarian", "Gluten-Free", "Low-Carb"],
    tags: ["deviled eggs", "protein", "classic", "party food", "meal prep"],
    imageUrl: "https://images.unsplash.com/photo-1635436338433-63923e3d2a1e"
  },
  {
    title: "Roasted Chickpea and Vegetable Snack Jars",
    description: "Portable jars layered with roasted chickpeas, fresh vegetables, and a flavorful dip for a balanced, nutrient-dense snack that's perfect for meal prep or on-the-go eating.",
    ingredients: [
      { name: "canned chickpeas", quantity: "1", unit: "15-ounce can", notes: "drained, rinsed, and patted dry" },
      { name: "olive oil", quantity: "1", unit: "tablespoon" },
      { name: "ground cumin", quantity: "1/2", unit: "teaspoon" },
      { name: "smoked paprika", quantity: "1/2", unit: "teaspoon" },
      { name: "salt", quantity: "1/4", unit: "teaspoon" },
      { name: "black pepper", quantity: "1/8", unit: "teaspoon" },
      { name: "hummus", quantity: "1", unit: "cup", notes: "store-bought or homemade" },
      { name: "cherry tomatoes", quantity: "1", unit: "cup", notes: "halved" },
      { name: "cucumber", quantity: "1", unit: "medium", notes: "diced" },
      { name: "bell pepper", quantity: "1", unit: "medium", notes: "diced" },
      { name: "carrot", quantity: "1", unit: "large", notes: "peeled and cut into sticks" },
      { name: "feta cheese", quantity: "1/2", unit: "cup", notes: "crumbled, optional" },
      { name: "fresh parsley", quantity: "2", unit: "tablespoons", notes: "chopped" },
      { name: "lemon wedges", quantity: "4", unit: "", notes: "for serving" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 400°F (200°C). Line a baking sheet with parchment paper." },
      { order: 2, instruction: "In a bowl, toss chickpeas with olive oil, cumin, smoked paprika, salt, and pepper until evenly coated." },
      { order: 3, instruction: "Spread chickpeas in a single layer on the prepared baking sheet." },
      { order: 4, instruction: "Roast for 20-25 minutes, shaking the pan halfway through, until chickpeas are golden and crispy. Let cool completely." },
      { order: 5, instruction: "Prepare 4 mason jars or food storage containers." },
      { order: 6, instruction: "Divide hummus among the jars, spreading it on the bottom." },
      { order: 7, instruction: "Layer vegetables on top of the hummus: bell pepper, cucumber, cherry tomatoes, and carrot sticks." },
      { order: 8, instruction: "Top with roasted chickpeas and crumbled feta cheese (if using)." },
      { order: 9, instruction: "Sprinkle with fresh parsley." },
      { order: 10, instruction: "Seal jars and refrigerate until ready to eat, up to 3 days." },
      { order: 11, instruction: "Serve with lemon wedges for squeezing over the top just before eating." }
    ],
    cookingVessel: "Baking Sheet",
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    difficulty: "Easy",
    mealType: "Snack",
    cuisine: "Mediterranean",
    categories: ["Meal Prep Snacks", "Jar Snacks"],
    dietaryCategories: ["Vegetarian", "Gluten-Free"],
    tags: ["chickpeas", "vegetables", "portable", "meal prep", "balanced"],
    imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd"
  },
  {
    title: "Homemade Granola Bars",
    description: "Chewy, customizable granola bars packed with oats, nuts, seeds, and dried fruit, bound together with honey and nut butter for a portable, energy-boosting snack.",
    ingredients: [
      { name: "old-fashioned oats", quantity: "2 1/2", unit: "cups" },
      { name: "chopped nuts", quantity: "1", unit: "cup", notes: "almonds, walnuts, or pecans" },
      { name: "sunflower seeds", quantity: "1/2", unit: "cup" },
      { name: "ground flaxseed", quantity: "1/4", unit: "cup" },
      { name: "ground cinnamon", quantity: "1", unit: "teaspoon" },
      { name: "salt", quantity: "1/2", unit: "teaspoon" },
      { name: "honey", quantity: "1/2", unit: "cup" },
      { name: "almond butter", quantity: "1/2", unit: "cup", notes: "or peanut butter" },
      { name: "vanilla extract", quantity: "1", unit: "teaspoon" },
      { name: "dried cranberries", quantity: "1/2", unit: "cup" },
      { name: "dried apricots", quantity: "1/2", unit: "cup", notes: "chopped" },
      { name: "mini chocolate chips", quantity: "1/3", unit: "cup", notes: "optional" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 350°F (175°C). Line a 9x13 inch baking dish with parchment paper, leaving an overhang on the sides." },
      { order: 2, instruction: "Spread oats and nuts on a baking sheet and toast in the oven for 10-12 minutes, stirring halfway through, until lightly golden. Let cool slightly." },
      { order: 3, instruction: "In a large bowl, combine toasted oats and nuts, sunflower seeds, ground flaxseed, cinnamon, and salt." },
      { order: 4, instruction: "In a small saucepan over medium heat, combine honey and almond butter. Stir until melted and smooth." },
      { order: 5, instruction: "Remove from heat and stir in vanilla extract." },
      { order: 6, instruction: "Pour the honey mixture over the oat mixture and stir until well combined and evenly coated." },
      { order: 7, instruction: "Fold in dried cranberries and chopped apricots." },
      { order: 8, instruction: "If using chocolate chips, let the mixture cool for about 5 minutes before folding them in to prevent melting." },
      { order: 9, instruction: "Press the mixture firmly into the prepared baking dish, using the back of a spatula or your hands (slightly dampened to prevent sticking)." },
      { order: 10, instruction: "Refrigerate for at least 2 hours or overnight until firm." },
      { order: 11, instruction: "Using the parchment paper overhang, lift the bars out of the dish and place on a cutting board." },
      { order: 12, instruction: "With a sharp knife, cut into 16 bars." },
      { order: 13, instruction: "Store in an airtight container, separated by parchment paper, at room temperature for up to 1 week, or in the refrigerator for up to 2 weeks." }
    ],
    cookingVessel: "Baking Dish",
    prepTime: 20,
    cookTime: 12,
    servings: 16,
    difficulty: "Medium",
    mealType: "Snack",
    cuisine: "American",
    categories: ["Granola Bars", "Energy Snacks"],
    dietaryCategories: ["Vegetarian", "Gluten-Free (with GF oats)"],
    tags: ["granola bars", "oats", "nuts", "dried fruit", "portable"],
    imageUrl: "https://images.unsplash.com/photo-1590080875515-8a3a8dc5735e"
  },
  {
    title: "Smoked Salmon Cucumber Rounds",
    description: "Elegant cucumber slices topped with cream cheese, smoked salmon, and fresh dill for a sophisticated, protein-rich snack that's perfect for entertaining or a special treat.",
    ingredients: [
      { name: "English cucumber", quantity: "1", unit: "large" },
      { name: "cream cheese", quantity: "4", unit: "ounces", notes: "softened" },
      { name: "lemon juice", quantity: "1", unit: "teaspoon" },
      { name: "lemon zest", quantity: "1/2", unit: "teaspoon" },
      { name: "fresh dill", quantity: "1", unit: "tablespoon", notes: "chopped, plus more for garnish" },
      { name: "smoked salmon", quantity: "4", unit: "ounces", notes: "thinly sliced" },
      { name: "capers", quantity: "1", unit: "tablespoon", notes: "drained" },
      { name: "red onion", quantity: "2", unit: "tablespoons", notes: "finely diced" },
      { name: "black pepper", quantity: "1/4", unit: "teaspoon", notes: "freshly ground" }
    ],
    steps: [
      { order: 1, instruction: "Wash and slice the cucumber into 1/4-inch thick rounds." },
      { order: 2, instruction: "Place cucumber rounds on paper towels to remove excess moisture." },
      { order: 3, instruction: "In a small bowl, mix together softened cream cheese, lemon juice, lemon zest, and chopped dill until well combined." },
      { order: 4, instruction: "Arrange cucumber rounds on a serving platter." },
      { order: 5, instruction: "Spread or pipe about 1 teaspoon of the cream cheese mixture onto each cucumber round." },
      { order: 6, instruction: "Top each with a small piece of smoked salmon, folded or rolled for presentation." },
      { order: 7, instruction: "Sprinkle with capers and diced red onion." },
      { order: 8, instruction: "Season with freshly ground black pepper." },
      { order: 9, instruction: "Garnish with additional fresh dill sprigs." },
      { order: 10, instruction: "Serve immediately, or refrigerate for up to 1 hour before serving." }
    ],
    cookingVessel: "None",
    prepTime: 15,
    cookTime: 0,
    servings: 4,
    difficulty: "Easy",
    mealType: "Snack",
    cuisine: "Scandinavian",
    categories: ["Seafood Snacks", "Canapes"],
    dietaryCategories: ["Gluten-Free", "Low-Carb"],
    tags: ["smoked salmon", "cucumber", "cream cheese", "elegant", "protein"],
    imageUrl: "https://images.unsplash.com/photo-1485963631004-f2f00b1d6606"
  },
  {
    title: "Spiced Roasted Nuts",
    description: "A warm, aromatic blend of mixed nuts roasted with sweet and savory spices for a protein-rich, satisfying snack that's perfect for entertaining or everyday snacking.",
    ingredients: [
      { name: "mixed nuts", quantity: "3", unit: "cups", notes: "raw, unsalted (almonds, walnuts, pecans, cashews)" },
      { name: "egg white", quantity: "1", unit: "large" },
      { name: "water", quantity: "1", unit: "tablespoon" },
      { name: "granulated sugar", quantity: "1/4", unit: "cup" },
      { name: "brown sugar", quantity: "2", unit: "tablespoons", notes: "packed" },
      { name: "ground cinnamon", quantity: "1 1/2", unit: "teaspoons" },
      { name: "ground cumin", quantity: "1", unit: "teaspoon" },
      { name: "smoked paprika", quantity: "1", unit: "teaspoon" },
      { name: "cayenne pepper", quantity: "1/4", unit: "teaspoon", notes: "adjust to taste" },
      { name: "salt", quantity: "1", unit: "teaspoon" },
      { name: "fresh rosemary", quantity: "1", unit: "tablespoon", notes: "finely chopped" }
    ],
    steps: [
      { order: 1, instruction: "Preheat oven to 300°F (150°C). Line a baking sheet with parchment paper." },
      { order: 2, instruction: "In a large bowl, whisk egg white and water until frothy but not stiff." },
      { order: 3, instruction: "Add nuts to the egg white mixture and toss until all nuts are well coated." },
      { order: 4, instruction: "In a small bowl, combine granulated sugar, brown sugar, cinnamon, cumin, smoked paprika, cayenne pepper, salt, and chopped rosemary." },
      { order: 5, instruction: "Sprinkle the spice mixture over the nuts and toss until evenly coated." },
      { order: 6, instruction: "Spread the nuts in a single layer on the prepared baking sheet." },
      { order: 7, instruction: "Bake for 30-35 minutes, stirring every 10 minutes, until nuts are fragrant and golden brown." },
      { order: 8, instruction: "Remove from oven and let cool completely on the baking sheet, stirring occasionally as they cool to prevent sticking." },
      { order: 9, instruction: "Once completely cooled, break apart any clusters and store in an airtight container at room temperature for up to 2 weeks." }
    ],
    cookingVessel: "Baking Sheet",
    prepTime: 10,
    cookTime: 35,
    servings: 12,
    difficulty: "Easy",
    mealType: "Snack",
    cuisine: "American",
    categories: ["Roasted Nuts", "Spiced Snacks"],
    dietaryCategories: ["Vegetarian", "Gluten-Free", "Dairy-Free"],
    tags: ["nuts", "spiced", "roasted", "protein", "party snack"],
    imageUrl: "https://images.unsplash.com/photo-1536591465196-9b2a6ab6b847"
  },
  {
    title: "Mini Caprese Skewers",
    description: "Bite-sized skewers featuring fresh mozzarella, cherry tomatoes, and basil drizzled with balsamic glaze for an elegant, no-cook snack that's perfect for entertaining or a quick protein boost.",
    ingredients: [
      { name: "cherry tomatoes", quantity: "1", unit: "pint" },
      { name: "fresh mozzarella pearls", quantity: "8", unit: "ounces", notes: "or mozzarella ball cut into 1-inch cubes" },
      { name: "fresh basil leaves", quantity: "1", unit: "bunch", notes: "large leaves torn in half" },
      { name: "extra virgin olive oil", quantity: "2", unit: "tablespoons" },
      { name: "balsamic glaze", quantity: "2", unit: "tablespoons", notes: "store-bought or homemade" },
      { name: "salt", quantity: "1/4", unit: "teaspoon", notes: "flaky sea salt preferred" },
      { name: "black pepper", quantity: "1/4", unit: "teaspoon", notes: "freshly ground" },
      { name: "wooden skewers", quantity: "24", unit: "small", notes: "4-6 inches long" }
    ],
    steps: [
      { order: 1, instruction: "If using wooden skewers, soak in water for 10 minutes to prevent splintering." },
      { order: 2, instruction: "Wash and dry cherry tomatoes and basil leaves." },
      { order: 3, instruction: "Thread the ingredients onto each skewer in this order: cherry tomato, basil leaf (folded if large), mozzarella ball, basil leaf (folded if large), cherry tomato." },
      { order: 4, instruction: "Arrange the prepared skewers on a serving platter." },
      { order: 5, instruction: "Drizzle with extra virgin olive oil and balsamic glaze." },
      { order: 6, instruction: "Sprinkle with salt and freshly ground black pepper." },
      { order: 7, instruction: "Serve immediately, or refrigerate for up to 2 hours before serving." }
    ],
    cookingVessel: "None",
    prepTime: 15,
    cookTime: 0,
    servings: 8,
    difficulty: "Easy",
    mealType: "Snack",
    cuisine: "Italian",
    categories: ["Skewers", "No-Cook Snacks"],
    dietaryCategories: ["Vegetarian", "Gluten-Free"],
    tags: ["caprese", "mozzarella", "tomato", "basil", "appetizer"],
    imageUrl: "https://images.unsplash.com/photo-1625944228741-cf30983ecb91"
  },
  {
    title: "Peanut Butter Banana Rice Cakes",
    description: "Crispy rice cakes topped with creamy peanut butter, banana slices, and optional toppings for a quick, satisfying snack that combines complex carbs, protein, and natural sweetness.",
    ingredients: [
      { name: "rice cakes", quantity: "4", unit: "plain or lightly salted" },
      { name: "natural peanut butter", quantity: "4", unit: "tablespoons" },
      { name: "banana", quantity: "1", unit: "medium", notes: "sliced" },
      { name: "honey", quantity: "2", unit: "teaspoons", notes: "optional" },
      { name: "ground cinnamon", quantity: "1/4", unit: "teaspoon", notes: "optional" },
      { name: "chia seeds", quantity: "1", unit: "teaspoon", notes: "optional" },
      { name: "dark chocolate chips", quantity: "1", unit: "tablespoon", notes: "optional" }
    ],
    steps: [
      { order: 1, instruction: "Spread 1 tablespoon of peanut butter evenly over each rice cake." },
      { order: 2, instruction: "Arrange banana slices on top of the peanut butter." },
      { order: 3, instruction: "If using, drizzle with honey." },
      { order: 4, instruction: "If using, sprinkle with cinnamon, chia seeds, and/or chocolate chips." },
      { order: 5, instruction: "Serve immediately." }
    ],
    cookingVessel: "None",
    prepTime: 5,
    cookTime: 0,
    servings: 4,
    difficulty: "Easy",
    mealType: "Snack",
    cuisine: "American",
    categories: ["Rice Cakes", "No-Cook Snacks"],
    dietaryCategories: ["Vegetarian", "Gluten-Free", "Dairy-Free"],
    tags: ["peanut butter", "banana", "rice cake", "quick", "simple"],
    imageUrl: "https://images.unsplash.com/photo-1541519481457-763224276691"
  }
];

export default snackRecipes;
